### ISSUE TITLE
memory leak when ES is crashing loopback and fluentd is retring to push buffered log

### ISSUE THREAD

**Issue by mchtech** [uken/fluent-plugin-elasticsearch#1051]
#### Problem

After upgrade fluentd from 1.15.2 to 1.17.0, fluentd (es output) encountered memory reclaim issue in complex fault scenarios.
memory is not released when ES status is crashloopback and fluentd is retring to push buffered log.

#### Steps to replicate

- env prepare
  - start elastic cluster, nginx proxy for elastic, fluentd with ES output (fluentd ES outputs to nginx ip, nginx reserve-proxy to ES cluster)
- fault simulation
  - a. config nginx to return 502 and reload nginx. (or stop nginx)
  - b. wait fluentd to generate at least 2 buffer files (buffer.b..., buffer.qaaa, bufer.qbbb...)
  - c. quickly revert step "a" and tail nginx log
  - d. when fluentd begin to retry pushing buffered log (see nginx _bulk http 200 log): redo step "a"
  - e. fluentd begin to output lots of error logs (for each log entry) and the memory of fluentd (v1.17.0) keeps increasing until OOM or container restart (liveness-probe: healthcheck failed), but old-version fluentd works well.

##### main nginx(openresty) config
<details>
<pre>
server {
    listen 80;

    server_name _;

    set $xforwaredfor $remote_addr;
    proxy_set_header Host $http_host;
    proxy_set_header X-Forwarded-For $xforwaredfor;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $connection_upgrade;

    proxy_http_version 1.1;
    proxy_connect_timeout 5s;
    proxy_send_timeout 30s;
    proxy_read_timeout 30s;

    proxy_buffers 64 8k;
    client_max_body_size 100m;

    location / {
        access_by_lua_block {
            ---ngx.sleep(math.random(14.5,16));
            ---ngx.exit(502);
        }
	proxy_pass http://127.0.0.1:9200;
    }

    location /_bulk {
        access_by_lua_block {
        ---    ngx.sleep(math.random(14.5,18))
        ---    ngx.exit(502);
        }
        proxy_pass http://127.0.0.1:9200;
    }
}
</pre>
</details>

##### fluentd config
<details>
<pre>
&lt;ROOT&gt;
  &lt;label @FLUENT_LOG&gt;
    &lt;match **&gt;
      @type null
      @id ignore_fluent_logs
    &lt;/match&gt;
  &lt;/label&gt;
  &lt;source&gt;
    @type gc_stat
    tag "gc.stat"
  &lt;/source&gt;
  &lt;match gc.stat&gt;
    @type stdout
  &lt;/match&gt;
  &lt;source&gt;
    @type tail
    @id fluentd_test_log
    @label @SOURCE
    path "/path/to/request.log"
    pos_file "/path/to/request.log.pos"
    tag "fluentd_test_log"
    read_from_head true
    follow_inodes true
    emit_unmatched_lines true
    &lt;parse&gt;
      @type "none"
      unmatched_lines true
    &lt;/parse&gt;
  &lt;/source&gt;
  &lt;label @SOURCE&gt;
    &lt;filter **&gt;
      @type record_transformer
      &lt;record&gt;
        _cluster xx
        _tag ${tag}
        _hostname fluentd-test-xxxx
      &lt;/record&gt;
    &lt;/filter&gt;
    &lt;filter fluentd_test_log&gt;
      @type grep
      &lt;exclude&gt;
        key "message"
        pattern /api1/
      &lt;/exclude&gt;
    &lt;/filter&gt;
    &lt;filter fluentd_test_log&gt;
      @type grep
      &lt;exclude&gt;
        key "message"
        pattern /api2/
      &lt;/exclude&gt;
    &lt;/filter&gt;
    &lt;match **&gt;
      @type relabel
      @label @DISPATCH
    &lt;/match&gt;
  &lt;/label&gt;
  &lt;label @DISPATCH&gt;
    &lt;filter **&gt;
      @type prometheus
      &lt;metric&gt;
        name fluentd_input_status_num_records_total
        type counter
        desc The total number of incoming records
        &lt;labels&gt;
          tag ${tag}
          hostname ${hostname}
        &lt;/labels&gt;
      &lt;/metric&gt;
    &lt;/filter&gt;
    &lt;match fluentd_test_log&gt;
      @type relabel
      @label @OUTPUT__fluentd_test_log
    &lt;/match&gt;
  &lt;/label&gt;
  &lt;label @OUTPUT__fluentd_test_log&gt;
    &lt;filter **&gt;
      @type elasticsearch_genid
      hash_id_key "_hash"
    &lt;/filter&gt;
    &lt;match **&gt;
      @type copy
      &lt;store&gt;
        @type "elasticsearch"
        hosts "nginx:80"
        path ""
        user "elastic"
        password xxxxxx
        index_name "fluentd-test"
        include_timestamp true
        request_timeout 15s
        bulk_message_request_threshold 20MB
        write_operation "create"
        id_key "_hash"
        remove_keys "_hash"
        &lt;buffer&gt;
          @type "file"
          path "/var/log/fluent/buf/elasticsearch/fluentd_test_log"
          path_suffix ".buf"
          total_limit_size 64GB
          flush_interval 5s
          flush_at_shutdown true
          retry_forever false
          retry_timeout 8h
          retry_max_times 486
          retry_max_interval 60s
        &lt;/buffer&gt;
      &lt;/store&gt;
    &lt;/match&gt;
  &lt;/label&gt;
  &lt;source&gt;
    @type prometheus
    @id in_prometheus
    bind "0.0.0.0"
    port 24231
    metrics_path "/metrics"
  &lt;/source&gt;
  &lt;source&gt;
    @type prometheus_monitor
    @id in_prometheus_monitor
  &lt;/source&gt;
  &lt;source&gt;
    @type prometheus_output_monitor
    @id in_prometheus_output_monitor
  &lt;/source&gt;
&lt;/ROOT&gt;
</pre>
</details>

##### error logs
<details>
<pre>
# flood output (v1.17.0 + v1.15.2)
2024-10-09 20:10:41 +0800 [warn]: #0 dump an error event: error_class=Fluent::Plugin::ElasticsearchOutput::RecoverableRequestFailure error="could not push logs to Elasticsearch cluster ({:host=>\"10.x.x.x\", :port=>80, :scheme=>\"http\", :user=>\"elastic\", :password=>\"obfuscated\", :path=>\"\"}): Connection refused - connect(2) for 10.x.x.x:80 (Errno::ECONNREFUSED)" location="/fluentd/vendor/bundle/ruby/3.2.0/gems/fluent-plugin-elasticsearch-5.2.5/lib/fluent/plugin/out_elasticsearch.rb:1146:in `rescue in send_bulk'" tag="fluentd_test_log" time=2024-10-09 19:46:42.084289025 +0800 record={"message"=>"a long log text", "_cluster"=>"yyy", "_tag"=>"fluentd_test_log", "_hostname"=>"fluentd-test-6ddddf5c6-gdxmw", "_node_ip"=>"10.y.y.y", "_pool_name"=>"xxx_fluentd-test-yyy", "@timestamp"=>"2024-10-09T19:46:42.084289025+08:00"}
2024-10-09 20:10:41 +0800 [warn]: #0 dump an error event: error_class=Fluent::Plugin::ElasticsearchOutput::RecoverableRequestFailure error="could not push logs to Elasticsearch cluster ({:host=>\"10.x.x.x\", :port=>80, :scheme=>\"http\", :user=>\"elastic\", :password=>\"obfuscated\", :path=>\"\"}): Connection refused - connect(2) for 10.x.x.x:80 (Errno::ECONNREFUSED)" location="/fluentd/vendor/bundle/ruby/3.2.0/gems/fluent-plugin-elasticsearch-5.2.5/lib/fluent/plugin/out_elasticsearch.rb:1146:in `rescue in send_bulk'" tag="fluentd_test_log" time=2024-10-09 19:46:42.085269889 +0800 record={"message"=>"2024-10-09 19:46:42.085119371+08:00", "_cluster"=>"yyy", "_tag"=>"fluentd_test_log", "_hostname"=>"fluentd-test-6ddddf5c6-gdxmw", "_node_ip"=>"10.y.y.y", "_pool_name"=>"xxx_fluentd-test-yyy", "@timestamp"=>"2024-10-09T19:46:42.085269889+08:00"}
2024-10-09 20:10:41 +0800 [warn]: #0 dump an error event: error_class=Fluent::Plugin::ElasticsearchOutput::RecoverableRequestFailure error="could not push logs to Elasticsearch cluster ({:host=>\"10.x.x.x\", :port=>80, :scheme=>\"http\", :user=>\"elastic\", :password=>\"obfuscated\", :path=>\"\"}): Connection refused - connect(2) for 10.x.x.x:80 (Errno::ECONNREFUSED)" location="/fluentd/vendor/bundle/ruby/3.2.0/gems/fluent-plugin-elasticsearch-5.2.5/lib/fluent/plugin/out_elasticsearch.rb:1146:in `rescue in send_bulk'" tag="fluentd_test_log" time=2024-10-09 19:46:42.086607166 +0800 record={"message"=>"a long log text", "_cluster"=>"yyy", "_tag"=>"fluentd_test_log", "_hostname"=>"fluentd-test-6ddddf5c6-gdxmw", "_node_ip"=>"10.y.y.y", "_pool_name"=>"xxx_fluentd-test-yyy", "@timestamp"=>"2024-10-09T19:46:42.086607166+08:00"}
2024-10-09 20:10:41 +0800 [warn]: #0 dump an error event: error_class=Fluent::Plugin::ElasticsearchOutput::RecoverableRequestFailure error="could not push logs to Elasticsearch cluster ({:host=>\"10.x.x.x\", :port=>80, :scheme=>\"http\", :user=>\"elastic\", :password=>\"obfuscated\", :path=>\"\"}): Connection refused - connect(2) for 10.x.x.x:80 (Errno::ECONNREFUSED)" location="/fluentd/vendor/bundle/ruby/3.2.0/gems/fluent-plugin-elasticsearch-5.2.5/lib/fluent/plugin/out_elasticsearch.rb:1146:in `rescue in send_bulk'" tag="fluentd_test_log" time=2024-10-09 19:46:42.087835513 +0800 ^C2024-10-09 20:10:41 +0800 [warn]: #0 dump an error event: error_class=Fluent::Plugin::ElasticsearchOutput::RecoverableRequestFailure error="could not push logs to Elasticsearch cluster ({:host=>\"10.x.x.x\", :port=>80, :scheme=>\"http\", :user=>\"elastic\", :password=>\"obfuscated\", :path=>\"\"}): Connection refused - connect(2) for 10.x.x.x:80 (Errno::ECONNREFUSED)" location="/fluentd/vendor/bundle/ruby/3.2.0/gems/fluent-plugin-elasticsearch-5.2.5/lib/fluent/plugin/out_elasticsearch.rb:1146:in `rescue in send_bulk'" tag="fluentd_test_log" time=2024-10-09 19:46:42.089250369 +0800 record={"message"=>"a long log text", "_cluster"=>"yyy", "_tag"=>"fluentd_test_log", "_hostname"=>"fluentd-test-6ddddf5c6-gdxmw", "_node_ip"=>"10.y.y.y", "_pool_name"=>"xxx_fluentd-test-yyy", "@timestamp"=>"2024-10-09T19:46:42.089250369+08:00"}
2024-10-09 20:10:41 +0800 [warn]: #0 dump an error event: error_class=Fluent::Plugin::ElasticsearchOutput::RecoverableRequestFailure error="could not push logs to Elasticsearch cluster ({:host=>\"10.x.x.x\", :port=>80, :scheme=>\"http\", :user=>\"elastic\", :password=>\"obfuscated\", :path=>\"\"}): Connection refused - connect(2) for 10.x.x.x:80 (Errno::ECONNREFUSED)" location="/fluentd/vendor/bundle/ruby/3.2.0/gems/fluent-plugin-elasticsearch-5.2.5/lib/fluent/plugin/out_elasticsearch.rb:1146:in `rescue in send_bulk'" tag="fluentd_test_log" time=2024-10-09 19:46:42.090581442 +0800 record={"message"=>"2024-10-09 19:46:42.090401205+08:00", "_cluster"=>"yyy", "_tag"=>"fluentd_test_log", "_hostname"=>"fluentd-test-6ddddf5c6-gdxmw", "_node_ip"=>"10.y.y.y", "_pool_name"=>"xxx_fluentd-test-yyy", "@timestamp"=>"2024-10-09T19:46:42.090581442+08:00"}
</pre>
</details>

##### log generator
```bash
while true;do date --rfc-3339=ns >> request.log; cat data.txt >> request.log; done &
```

#### Expected Behavior or What you need to ask

Why

#### Using Fluentd and ES plugin versions

* OS version: `almalinux 9.4`
* Bare Metal or within Docker or Kubernetes or others: `k8s 1.26`
* Fluentd version: `fluentd 1.17.0 & fluentd 1.15.2`
* ES plugin version:
```
# 1.15.2
elasticsearch (7.17.1)
elasticsearch-api (7.17.1)
elasticsearch-transport (7.17.1)
elasticsearch-xpack (7.17.1)
fluent-plugin-elasticsearch (5.1.5)
```
```
# 1.17.0
elasticsearch (7.17.11)
elasticsearch-api (7.17.11)
elasticsearch-transport (7.17.11)
elasticsearch-xpack (7.17.11)
fluent-plugin-elasticsearch (5.2.5)
```

* ES version: `7.17.6`
* Pod resource: `requests 256Mi, limits 512Mi`

#### monitor
- simulation env
![pic1](https://github.com/user-attachments/assets/e00b731b-f9b0-4a17-83b8-279f0386268e)
![pic2](https://github.com/user-attachments/assets/a12925be-0ed7-4959-8810-e9c190cb0815)
- prod cluster
![prod](https://github.com/user-attachments/assets/2c401a7a-966a-4602-b9e8-d0f1a93ea98b)

**Comment by cosmo0920** [comment]
Tagging for @kenhys or @daipom.

**Comment by kenhys** [comment]
elasticsearch related gem version is not unified.
It makes hard to dig into the actual problem.
Could you help to simplify the reproducible step?

(I mean what component actually causes it? Does hit Fluentd's edge case? or fluent-plugin-elasticsearch issue? or ....)

**Comment by daipom** [comment]
@mchtech 
Thanks for your report!
Sorry for our late response.

As @kenhys says, we need more info to investigate this issue.

* Is this issue reproducible in the following env?
  * fluentd v1.15.2 and fluent-plugin-elasticsearch v5.2.5
  * I want to clarify whether it depends on the version of Fluentd or the version of the plugin.
* Could `Steps to replicate` be simpler?
  * Does that mean that the memory will grow if Fluentd keeps failing to send data?
  * Otherwise, is there a requirement to repeat the successes and failures of the output?

**Comment by Watson1978** [comment]
I've tried to reproduce, but I haven't been able to reproduce the problem.
What happens if you used same versions of the plugins ?

**Comment by mchtech** [comment]
I will supplement some information this week.

**Comment by mchtech** [comment]
@kenhys @daipom @Watson1978 

After multiple simplified  tests with single variable change, this issue seems to be related to `failed chunks discards` feature with elasticsearch plugin. There is no such problem for fluentd with kafka plugin.

|           |   retry_forever = false, retry_timeout 5m  |  retry_forever = true |
|-------| ----------------------------------------| ---------------------|
| es      |  memory keeps growing                             | ok
| kafka | ok                                                                 | ok

### simplified steps that can reproduce issue quickly
 - setup env: 
   - start: nginx --proxy_pass to--> elasticsearch
   - prepare 100KB data.txt
 - start fluentd with [config](https://github.com/uken/fluent-plugin-elasticsearch/issues/1051#issue-2575840141)
```
        <buffer>
....
          retry_forever false
          retry_timeout 5m # <-- memory keeps growing after nginx stop 5min
....
        </buffer>
```
 - write log:
```bash
while true; do sleep 1; cat data.log | tee -a /path/to/pod1/logs/request.log  /path/to/pod2/logs/request.log >/dev/null;  done &
```
 - wait 2min and stop nginx
 - watch memory monitor for 10min

### test1 (elasticsearch)
 - v1.15.2-debian-elasticsearch7-1.0 with elasticsearch plugin `v5.2.5` and `v5.1.5`
 -  retry_forever = false
 -  retry_timeout 5m

![Image](https://github.com/user-attachments/assets/575da77a-9137-46b7-8bc7-b974cc556146)

### test2 (elasticsearch)
 - v1.15.2-debian-elasticsearch7-1.0 with elasticsearch plugin `v5.2.5` and `v5.1.5`
 -  retry_forever = true

![Image](https://github.com/user-attachments/assets/74201677-315a-4cb3-9a17-35f4d29486d2)

### test3 (kafka)
 - v1.15.2-debian-kafka2-1.0, v1.17.0-debian-kafka2-1.5, v1.18.0-debian-kafka2-1.4
 -  retry_forever = false
 -  retry_timeout 5m

![Image](https://github.com/user-attachments/assets/79d6c8d6-0247-4d43-a56a-5ab7f2431a15)

**Comment by Watson1978** [comment]
Can you reproduce your issue without nginx?
And can you simplify the your fluentd config to reproduce ?

**Comment by mchtech** [comment]
> Can you reproduce your issue without nginx? And can you simplify the your fluentd config to reproduce ?

ok. simplified fluentd config:

```conf
  <label @FLUENT_LOG>
    <match **>
      @type null
      @id ignore_fluent_logs
    </match>
  </label>
  <source>
    @type tail
    @id fluentd_test_log
    @label @SOURCE
    path "/path/to/request.log"
    pos_file "/path/to/request.log.pos"
    tag "fluentd_test_log"
    read_from_head true
    follow_inodes true
    emit_unmatched_lines true
    <parse>
      @type "none"
      unmatched_lines true
    </parse>
  </source>
  <label @SOURCE>
    <filter **>
      @type record_transformer
      <record>
        _tag ${tag}
      </record>
    </filter>
    <match **>
      @type relabel
      @label @DISPATCH
    </match>
  </label>
  <label @DISPATCH>
    <match fluentd_test_log>
      @type relabel
      @label @OUTPUT__fluentd_test_log
    </match>
  </label>
  <label @OUTPUT__fluentd_test_log>
    <filter **>
      @type elasticsearch_genid
      hash_id_key "_hash"
    </filter>
    <match **>
      @type copy
      <store>
        @type "elasticsearch"
        hosts "xx.xx.xx.xx:9200"
        path ""
        user "elastic"
        password xxxxxx
        index_name "fluentd-test"
        include_timestamp true
        request_timeout 15s
        bulk_message_request_threshold 20MB
        write_operation "create"
        id_key "_hash"
        remove_keys "_hash"
        <buffer>
          @type "file"
          path "/var/log/fluent/buf/elasticsearch/fluentd_test_log"
          path_suffix ".buf"
          total_limit_size 64GB
          flush_interval 5s
          flush_at_shutdown true
          retry_forever false
          retry_timeout 5m
          retry_max_times 486
          retry_max_interval 60s
        </buffer>
      </store>
    </match>
  </label>
```

**Comment by Watson1978** [comment]
I created a docker environment to reproduce in https://github.com/Watson1978/test-fluentd-elasticsearch

![Image](https://github.com/user-attachments/assets/8ff7fe6d-c967-4f43-9d55-bbc4f26e5bf4)

However, v1.15 and v1.17 has similar memory usage...
Is there something I'm doing wrong?

**Comment by mchtech** [comment]
> I created a docker environment to reproduce in https://github.com/Watson1978/test-fluentd-elasticsearch
> 
> However, v1.15 and v1.17 has similar memory usage... Is there something I'm doing wrong?


@Watson1978  It seems to be related to the number of buffered data entries.

I create a PR: https://github.com/Watson1978/test-fluentd-elasticsearch/pull/1 to reproduce this.

I suggest observing metrics for about an hour after stopping ES.


![Image](https://github.com/user-attachments/assets/849a2108-e0bb-404e-8fbe-736c76cb33c7)

**Comment by Watson1978** [comment]
It seems that memory usage is related to the version of fluent-plugin-elasticsearch.

fluent-plugin-elasticsearch 5.1.5 | fluent-plugin-elasticsearch 5.2.5
-- | --
<img src="https://github.com/user-attachments/assets/d7d2fbcb-527b-4e5d-8882-ef2483584252" /> | <img src="https://github.com/user-attachments/assets/dd094059-86fa-4378-b196-9ef456038f49" />

**Comment by Watson1978** [comment]
I measured the memory usage with follwing pattern.

* Fluentd 1.15 + fluent-plugin-elasticsearch 5.1.5
* Fluentd 1.15 + fluent-plugin-elasticsearch 5.2.0
* Fluentd 1.15 + fluent-plugin-elasticsearch 5.2.1
* Fluentd 1.15 + fluent-plugin-elasticsearch 5.2.2
* Fluentd 1.15 + fluent-plugin-elasticsearch 5.2.3
* Fluentd 1.15 + fluent-plugin-elasticsearch 5.2.4
* Fluentd 1.15 + fluent-plugin-elasticsearch 5.2.5

![Image](https://github.com/user-attachments/assets/faa28f6a-e43a-4aec-943a-de86c4db2814)

Seems 5.2.4 and 5.2.5 have same memory usage.
Looks like the increase in memory usage started in 5.2.3.

**Comment by Watson1978** [comment]
If it cannot connect to Elasticsearch, `Faraday::ConnectionFailed` exception will occur when sending data with `send_bulk` method.
The message to be sent is large, so the message is cleared during normal processing after sent.

https://github.com/uken/fluent-plugin-elasticsearch/blob/58ef41ba27c813daee0ba0d37f479e922a40e236/lib/fluent/plugin/out_elasticsearch.rb#L883-L892

https://github.com/uken/fluent-plugin-elasticsearch/blob/58ef41ba27c813daee0ba0d37f479e922a40e236/lib/fluent/plugin/out_elasticsearch.rb#L908-L913

This clear process is not performed when an exception occurs in `send_bulk`.

It seems that the message we tried to send with `send_bulk` is large and cannot be cleared,
it will increase memory usage.

**Comment by daipom** [comment]
@Watson1978  Thanks for investigating this!

It looks like this issue has been occurring since v5.2.3.

* https://github.com/uken/fluent-plugin-elasticsearch/compare/v5.2.2...v5.2.3#diff-cf75cdd038558996eefb3a1e148524c313f9094460b38022d003bf7d1878233aR830

Looks like `unpackedMsgArr` is the cause of this memory shortage.
That variable was added between v5.2.2 and v5.2.3.
If `clear` is not called, it could be very large.

So, #1065 appears to be effective.
