### ISSUE TITLE
object mapping for [fluentd] tried to parse field [context] as object, but got EOF

### ISSUE THREAD

**Issue by Seraf** [uken/fluent-plugin-elasticsearch#113]
Hello everyone,

I have a strange behavior (I'm using 0.9.0 but have the same problem with 0.8.0). I don't know if it's related to the plugin or not. When I send a particular message, elasticsearch complains about a EOF. I don't know where ES can see this EOF ...
I'm stuck as I can't store these important logs. Any idea please ?

Here is my elasticsearch log :
```
[2015-06-22 17:30:25,597][DEBUG][action.bulk              ] [SUPPORT-LOG-i-3c0e13d8-search] [logstash-2015.06.22][0] failed to execute bulk item (index) index {[logstash-2015.06.22][fluentd][AU4b5FMilsvY52DHpdBN], source[{"message":"Creates new command with params","context":{"class":"Youpi\\Kernel\\Driver\\AbstractDeviceDriver","method":"perform","command":"132","params":"[\"15\"]","message_tracking_number":"not_found","mac":"XXXXXXXXXXXX","routing_key":"rich.gw.api.cmd","user_uid":"not_found"},"level":"DEBUG","level_name":"DEBUG","channel":"Youpi\\Kernel\\Driver\\Box\\YoupiBoxDriver","datetime":{"date":"2015-06-22 15:30:18.884065","timezone_type":3,"timezone":"UTC"},"extra":[],"formatted":"{\"message\":\"Creates new command with params\",\"context\":{\"class\":\"Youpi\\\\Kernel\\\\Driver\\\\AbstractDeviceDriver\",\"method\":\"perform\",\"command\":\"132\",\"params\":\"[\\\"15\\\"]\",\"message_tracking_number\":\"not_found\",\"mac\":\"6C0B84102154\",\"routing_key\":\"rich.gw.api.cmd\",\"user_uid\":\"not_found\"},\"level\":100,\"level_name\":\"DEBUG\",\"channel\":\"Youpi\\\\Kernel\\\\Driver\\\\Box\\\\YoupiBoxDriver\",\"datetime\":{\"date\":\"2015-06-22 15:30:18.884065\",\"timezone_type\":3,\"timezone\":\"UTC\"},\"extra\":[]}\n","hostname":"CONSUMERS-EU-PREPROD-i-0b7921a1","_key":"youpi.eu.preprod.consumers.app.consumers.preprod","@timestamp":"2015-06-22T17:30:18+02:00"}]}
org.elasticsearch.index.mapper.MapperParsingException: object mapping for [fluentd] tried to parse field [context] as object, but got EOF, has a concrete value been provided to it?
	at org.elasticsearch.index.mapper.object.ObjectMapper.parse(ObjectMapper.java:495)
	at org.elasticsearch.index.mapper.DocumentMapper.parse(DocumentMapper.java:544)
	at org.elasticsearch.index.mapper.DocumentMapper.parse(DocumentMapper.java:493)
	at org.elasticsearch.index.shard.IndexShard.prepareCreate(IndexShard.java:453)
	at org.elasticsearch.action.bulk.TransportShardBulkAction.shardIndexOperation(TransportShardBulkAction.java:432)
	at org.elasticsearch.action.bulk.TransportShardBulkAction.shardOperationOnPrimary(TransportShardBulkAction.java:149)
	at org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$AsyncShardOperationAction.performOnPrimary(TransportShardReplicationOperationAction.java:515)
	at org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$AsyncShardOperationAction$1.run(TransportShardReplicationOperationAction.java:422)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

Thanks !

**Comment by diclophis** [comment]
@Seraf what did you find out about this issue?

**Comment by Seraf** [comment]
Hello, I didn't use fluentd anymore, I gave up. Sorry

**Comment by diclophis** [comment]
Thanks
