### ISSUE TITLE
Fix allowed characters in keys

### ISSUE THREAD

**Issue by superdump** [uken/fluent-plugin-elasticsearch#145]
I am using the fluentd docker log driver and configuring it to add a bunch of labels that are applied to the container by swarm and others using reverse domain notation as used and recommended by docker.

I am also using fluentd with this fluentd elasticsearch plugin. Unfortunately, elasticsearch does not like the '.' characters in the keys, so I get output like this:

```
[2016-01-12 08:12:05,215][DEBUG][action.bulk              ] [Punchout] [logstash-2016.01.12][3] failed to execute bulk item (index) index {[logstash-2016.01.12][fluentd][AVI05FLyAO15xpkHnohx], source[{"com.example.site.applicationid":"logs","com.example.site.componentid":"kibana","container_id":"6b0e7cb8db11024bf712f0c56e29774d49b67cfaa5ca823bbf03569312b30245","container_name":"/elated_williams","source":"stdout","log":"Some log text","com.docker.swarm.id":"db0a0774ccdc4c131d1f69848b6390a55691f42a397f6fff7deb97f8d0ba293b","@timestamp":"2016-01-12T08:11:26+00:00"}]}
MapperParsingException[Field name [com.docker.swarm.id] cannot contain '.']
    at org.elasticsearch.index.mapper.object.ObjectMapper$TypeParser.parseProperties(ObjectMapper.java:278)
    at org.elasticsearch.index.mapper.object.ObjectMapper$TypeParser.parseObjectOrDocumentTypeProperties(ObjectMapper.java:223)
    at org.elasticsearch.index.mapper.object.RootObjectMapper$TypeParser.parse(RootObjectMapper.java:139)
    at org.elasticsearch.index.mapper.DocumentMapperParser.parse(DocumentMapperParser.java:140)
    at org.elasticsearch.index.mapper.DocumentMapperParser.parseCompressed(DocumentMapperParser.java:121)
    at org.elasticsearch.index.mapper.MapperService.parse(MapperService.java:391)
    at org.elasticsearch.cluster.metadata.MetaDataMappingService$2.execute(MetaDataMappingService.java:386)
    at org.elasticsearch.cluster.service.InternalClusterService$UpdateTask.run(InternalClusterService.java:388)
    at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:231)
    at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:194)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

Would it be possible to re-write the keys in the plugin to ensure that they are elasticsearch-compatible? I tried to find some clear documentation of what characters are allowed in keys. I'll post here if I find anything useful.

**Comment by pitr** [comment]
Looks like Elasticsearch 2.0 introduced this limitation - https://www.elastic.co/guide/en/elasticsearch/reference/2.0/breaking_20_mapping_changes.html#_field_names_may_not_contain_dots

Converting dotted keys to a hash (ie `{"com.docker.swarm.id":"db0a"} => {"com": {"docker":{"swarm":{"id":"db0a"}}}}` sounds like a good filter plugin. Unfortunately I couldn't find anything in plugin list - http://www.fluentd.org/plugins#filter BUT seems like it would be easy to create such plugin. There's a plugin that sort of does the reverse of what you want - https://github.com/winebarrel/fluent-plugin-filter-object-flatten which could be used as a starting point. If you do end up creating this plugin, ping us and we'll link to it from README, in case anyone else encounters this problem.

**Comment by superdump** [comment]
https://github.com/winebarrel/fluent-plugin-filter-record-map#example2 <---
this works. Specifically:

<filter docker.**>
  @type record_map
  map1 record.each {|k, v| new_record[k.gsub(/\./, '_')] = v }
</filter>

**Comment by pitr** [comment]
ah, an even simpler alternative

**Comment by gtrevg** [comment]
Just for reference, I wrote this a long while back which would handle the conversion:  https://github.com/gtrevg/fluent-plugin-dotted-keys
