### ISSUE TITLE
error="no implicit conversion of nil into String" on kubernetes

### ISSUE THREAD

**Issue by vichargrave** [uken/fluent-plugin-elasticsearch#183]
### Problem

I'm running fluentd as a secure log forwarder to elasticsearch 2.3.3. The logs are shipped to the forwarder by another fluentd instance.  I'm running the fluentd log shipper, fluentd log forwarder (the component having the problem), and the Elasticsearch cluster in containers on Google Container Engine with Kubernetes.

When I run the fluentd forwarder with the fluent-plugin-elasticsearch forwarding in elasticsearch_dynamic mode, data will be indexed into Elasticsearch for a couple of minutes then will stop.  When I check the fluentd forwarder container logs I get this:
```
2016-07-27 19:04:06 +0000 [info]: Connection opened to Elasticsearch cluster => {:host=>"elasticsearch", :port=>9200, :scheme=>"http"}
2016-07-27 19:04:11 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2016-07-27 19:04:12 +0000 error_class="TypeError" error="no implicit conversion of nil into String" plugin_id="object:15e34d0"
  2016-07-27 19:04:11 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-elasticsearch-1.5.0/lib/fluent/plugin/out_elasticsearch_dynamic.rb:223:in `sub!'
  2016-07-27 19:04:11 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-elasticsearch-1.5.0/lib/fluent/plugin/out_elasticsearch_dynamic.rb:223:in `expand_param'
  2016-07-27 19:04:11 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-elasticsearch-1.5.0/lib/fluent/plugin/out_elasticsearch_dynamic.rb:124:in `block (2 levels) in write'
  2016-07-27 19:04:11 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-elasticsearch-1.5.0/lib/fluent/plugin/out_elasticsearch_dynamic.rb:119:in `each'
  2016-07-27 19:04:11 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-elasticsearch-1.5.0/lib/fluent/plugin/out_elasticsearch_dynamic.rb:119:in `block in write'
  2016-07-27 19:04:11 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/lib/fluent/plugin/buf_memory.rb:67:in `feed_each'
  2016-07-27 19:04:11 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/lib/fluent/plugin/buf_memory.rb:67:in `msgpack_each'
  2016-07-27 19:04:11 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-elasticsearch-1.5.0/lib/fluent/plugin/out_elasticsearch_dynamic.rb:115:in `write'
  2016-07-27 19:04:11 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/lib/fluent/buffer.rb:354:in `write_chunk'
  2016-07-27 19:04:11 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/lib/fluent/buffer.rb:333:in `pop'
  2016-07-27 19:04:11 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/lib/fluent/output.rb:338:in `try_flush'
  2016-07-27 19:04:11 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/lib/fluent/output.rb:149:in `run'
2016-07-27 19:04:12 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2016-07-27 19:04:14 +0000 error_class="TypeError" error="no implicit conversion of nil into String" plugin_id="object:15e34d0"
  2016-07-27 19:04:12 +0000 [warn]: suppressed same stacktrace
2016-07-27 19:04:14 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2016-07-27 19:04:19 +0000 error_class="TypeError" error="no implicit conversion of nil into String" plugin_id="object:15e34d0"
  2016-07-27 19:04:14 +0000 [warn]: suppressed same stacktrace
2016-07-27 19:04:19 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2016-07-27 19:04:27 +0000 error_class="TypeError" error="no implicit conversion of nil into String" plugin_id="object:15e34d0"
  2016-07-27 19:04:19 +0000 [warn]: suppressed same stacktrace
2016-07-27 19:04:27 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2016-07-27 19:04:42 +0000 error_class="TypeError" error="no implicit conversion of nil into String" plugin_id="object:15e34d0"
  2016-07-27 19:04:27 +0000 [warn]: suppressed same stacktrace
2016-07-27 19:04:42 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2016-07-27 19:05:17 +0000 error_class="TypeError" error="no implicit conversion of nil into String" plugin_id="object:15e34d0"
  2016-07-27 19:04:42 +0000 [warn]: suppressed same stacktrace
2016-07-27 19:05:17 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2016-07-27 19:06:21 +0000 error_class="TypeError" error="no implicit conversion of nil into String" plugin_id="object:15e34d0"
  2016-07-27 19:05:17 +0000 [warn]: suppressed same stacktrace
2016-07-27 19:06:21 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2016-07-27 19:08:21 +0000 error_class="TypeError" error="no implicit conversion of nil into String" plugin_id="object:15e34d0"
  2016-07-27 19:06:21 +0000 [warn]: suppressed same stacktrace
```
## Config
```
<match **>
  type copy
  <store>
    type elasticsearch_dynamic
    host elasticsearch
    port 9200
    logstash_format true
    logstash_dateformat %Y-%m-%d
    logstash_prefix my-logs-${record['my_idx_id']}
    type_name logs
    flush_interval 5s
  </store>
</match>
```
NOTE: This does not seem to be a problem when I use regular ```type elasticsearch```.  It seems to be a problem with ```type elasticsearch_dynamic```.

**Comment by pitr** [comment]
can you post example log?

**Comment by vichargrave** [comment]
I did under the problem description section.

**Comment by pitr** [comment]
Ah, I meant an example of a log that you are trying to send through fluentd

**Comment by vichargrave** [comment]
Here is a set of container logs from one of the cluster nodes:
```
{"log":"I0727 21:16:07.890169       1 nanny_lib.go:102] The expected resources are {Limits:map[cpu:{i:{value:0 scale:0} d:{Dec:0xc8202e0f00} s: Format:Dec
imalSI} memory:{i:{value:0 scale:0} d:{Dec:0xc8202e1380} s: Format:BinarySI}] Requests:map[cpu:{i:{value:0 scale:0} d:{Dec:0xc8202e0f00} s: Format:Decimal
SI} memory:{i:{value:0 scale:0} d:{Dec:0xc8202e1380} s: Format:BinarySI}]}\n","stream":"stderr","time":"2016-07-27T21:16:07.890240063Z"}
{"log":"I0727 21:16:07.890289       1 nanny_lib.go:106] Resources are within the expected limits.\n","stream":"stderr","time":"2016-07-27T21:16:07.8903068
8Z"}
{"log":"I0727 21:16:17.895791       1 nanny_lib.go:90] The number of nodes is 5\n","stream":"stderr","time":"2016-07-27T21:16:17.895888915Z"}
{"log":"I0727 21:16:17.899123       1 nanny_lib.go:98] The container resources are {Limits:map[cpu:{i:{value:88 scale:-3} d:{Dec:\u003cnil\u003e} s:88m Fo
rmat:DecimalSI} memory:{i:{value:213909504 scale:0} d:{Dec:\u003cnil\u003e} s:204Mi Format:BinarySI}] Requests:map[cpu:{i:{value:88 scale:-3} d:{Dec:\u003
cnil\u003e} s:88m Format:DecimalSI} memory:{i:{value:213909504 scale:0} d:{Dec:\u003cnil\u003e} s:204Mi Format:BinarySI}]}\n","stream":"stderr","time":"20
16-07-27T21:16:17.899205186Z"}
{"log":"I0727 21:16:17.899315       1 nanny_lib.go:102] The expected resources are {Limits:map[memory:{i:{value:0 scale:0} d:{Dec:0xc8201baae0} s: Format:
BinarySI} cpu:{i:{value:0 scale:0} d:{Dec:0xc820010c60} s: Format:DecimalSI}] Requests:map[cpu:{i:{value:0 scale:0} d:{Dec:0xc820010c60} s: Format:Decimal
SI} memory:{i:{value:0 scale:0} d:{Dec:0xc8201baae0} s: Format:BinarySI}]}\n","stream":"stderr","time":"2016-07-27T21:16:17.899380268Z"}
{"log":"I0727 21:16:17.899427       1 nanny_lib.go:106] Resources are within the expected limits.\n","stream":"stderr","time":"2016-07-27T21:16:17.8994436
83Z"}
{"log":"I0727 21:16:27.906048       1 nanny_lib.go:90] The number of nodes is 5\n","stream":"stderr","time":"2016-07-27T21:16:27.906171625Z"}
{"log":"I0727 21:16:27.909593       1 nanny_lib.go:98] The container resources are {Limits:map[cpu:{i:{value:88 scale:-3} d:{Dec:\u003cnil\u003e} s:88m Fo
rmat:DecimalSI} memory:{i:{value:213909504 scale:0} d:{Dec:\u003cnil\u003e} s:204Mi Format:BinarySI}] Requests:map[memory:{i:{value:213909504 scale:0} d:{
Dec:\u003cnil\u003e} s:204Mi Format:BinarySI} cpu:{i:{value:88 scale:-3} d:{Dec:\u003cnil\u003e} s:88m Format:DecimalSI}]}\n","stream":"stderr","time":"20
16-07-27T21:16:27.909700776Z"}
{"log":"I0727 21:16:27.909844       1 nanny_lib.go:102] The expected resources are {Limits:map[cpu:{i:{value:0 scale:0} d:{Dec:0xc8201f2b40} s: Format:Dec
imalSI} memory:{i:{value:0 scale:0} d:{Dec:0xc8201f2fc0} s: Format:BinarySI}] Requests:map[cpu:{i:{value:0 scale:0} d:{Dec:0xc8201f2b40} s: Format:Decimal
SI} memory:{i:{value:0 scale:0} d:{Dec:0xc8201f2fc0} s: Format:BinarySI}]}\n","stream":"stderr","time":"2016-07-27T21:16:27.909889481Z"}
{"log":"I0727 21:16:27.909940       1 nanny_lib.go:106] Resources are within the expected limits.\n","stream":"stderr","time":"2016-07-27T21:16:27.9099585
64Z"}
{"log":"Starting HTTP server on port 9090\n","stream":"stdout","time":"2016-07-27T18:56:11.675024998Z"}
{"log":"Creating API server client for https://10.99.240.1:443\n","stream":"stdout","time":"2016-07-27T18:56:11.676031504Z"}
{"log":"Error while initializing connection to Kubernetes apiserver. This most likely means that the cluster is misconfigured (e.g., it has invalid apiser
ver certificates or service accounts configuration) or the --apiserver-host param points to a server that does not exist. Reason: Get https://10.99.240.1:
443/version: dial tcp 10.99.240.1:443: i/o timeout\n","stream":"stdout","time":"2016-07-27T18:56:41.677211578Z"}
{"log":"Starting HTTP server on port 9090\n","stream":"stdout","time":"2016-07-27T18:56:42.907599449Z"}
{"log":"Creating API server client for https://10.99.240.1:443\n","stream":"stdout","time":"2016-07-27T18:56:42.912113468Z"}
{"log":"Successful initial request to the apiserver, version: v1.3.2\n","stream":"stdout","time":"2016-07-27T18:56:42.949268846Z"}
{"log":"Creating in-cluster Heapster client\n","stream":"stdout","time":"2016-07-27T18:56:42.949345445Z"}
```

**Comment by vichargrave** [comment]
Just to verify, when I set the log forwarding back to ```type elasticsearch```, I don't have this problem, so it is definitely related to ```type elasticsearch_dynamic```.  Here is the forwarding config I tried:
```
<match **>
#  type stdout
  type copy
  <store>
    type elasticsearch
    host elasticsearch
    port 9200
    logstash_format true
    logstash_dateformat %Y-%m-%d
    logstash_prefix my-logs
    type_name logs
    flush_interval 5s
  </store>
</match>
```

**Comment by vichargrave** [comment]
Any thoughts on this issue?

**Comment by pitr** [comment]
I see in the config you have `logstash_prefix my-logs-${record['my_idx_id']}`, but I see no `my_idx_id` field in your container logs

**Comment by vichargrave** [comment]
Yeah I was just sanitizing the stuff I sent to you.

**Comment by vichargrave** [comment]
The problem seems to pop here in the out_elasticsearch_dynamic.rb code:

    chunk.msgpack_each do |tag, time, record|
      next unless record.is_a? Hash

I'm starting to look at the chunk by outputting if to stdout with chunk.to_yaml to try to see what it going on.  If you can suggest other debugging methods and give them a try.

**Comment by vichargrave** [comment]
Any suggestions for how to debug this?

**Comment by pitr** [comment]
according to logs you posted originally, it seems that the code tries to eval a nil on line 223. I suggest starting with printing `param` and seeing where nil is coming from

**Comment by vichargrave** [comment]
Have you been able to reproduce this error?

**Comment by vichargrave** [comment]
I added the two ```puts``` line to the beginning of ```expand_param``` to print out the ```param``` in out_elasticsearch_dynamic.rb:
```
  def expand_param(param, tag, time, record)
    # check for '${ ... }'
    #   yes => `eval`
    #   no  => return param
    inner = param.clone
    puts "***** param  *****"
    puts inner.to_yaml 
    return param if (param =~ /\${.+}/).nil?
```
Here is an example of the output I get when there is the nil error:
```
***** param  *****
***** param  *****
--- gsk-logs-${record['gsk_customer_id']}
...
2016-08-11 18:15:03 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2016-08-11 18:15:04 +0000 error_class="TypeError" error="no impl\
icit conversion of nil into String" plugin_id="object:ca8b90"
  2016-08-11 18:15:03 +0000 [warn]: suppressed same stacktrace
```
There is nothing printed in between the two ```***** param *****``` lines which I assume is the nil, but I can't tell what is nil.  Any suggestions?

**Comment by vichargrave** [comment]
It's not clear to me what is going on here.  The dynamic fields seemed to parse properly.  I'm hopeful you have some other suggestions.

**Comment by pitr** [comment]
so this confirms that the issue is with records missing `gsk_customer_id` field, as that's the last thing printed before nil error. You should either make sure every record has `gsk_customer_id` field OR do something like `gsk-logs-${record['gsk_customer_id'] || 'unknown'}`

**Comment by vichargrave** [comment]
Since I'm sending the gsk_customer_id in record_transformer filter, I'm expecting the fluentd forwarder to insert this every time.  Are you saying that this may be an issue with the forwarder, which in my case is the secure_forward plugin?
