### ISSUE TITLE
error_class="Elasticsearch::Transport::Transport::Errors::ServiceUnavailable" error="[503] "

### ISSUE THREAD

**Issue by bwnyasse** [uken/fluent-plugin-elasticsearch#186]
I apologise in advance if I'm posting this to the wrong repo. I'm running into an issue using the plugin with Docker using [elasticsearch 2.3.5](https://hub.docker.com/r/library/elasticsearch/tags/)

Here is my Dockerfile :

<pre>
FROM fluent/fluentd:v0.12.26

MAINTAINER bwnyasse

USER root
ARG proxy
ENV http_proxy ${proxy}
ENV https_proxy ${proxy}
ENV no_proxy=localhost,127.0.0.1,0.0.0.0

RUN gem install fluent-plugin-elasticsearch && \
    gem install fluent-plugin-parser

COPY fluent.conf /fluentd/etc/
EXPOSE 24284

CMD exec fluentd -c /fluentd/etc/$FLUENTD_CONF -p /fluentd/plugins $FLUENTD_OPT
</pre>

and my fluent.conf
<pre>
<code>
&lt;source&gt;
   @type forward
 &lt;/source&gt;

&lt;match unparse.nginx1.docker.**&gt;
  type parser
  format nginx
  remove_prefix unparse
  key_name log
  reserve_data yes
&lt;/match&gt;

&lt;match nginx1.docker.**&gt;
  type elasticsearch
  host elasticsearch
  port 9200
  type_name fluentd
  logstash_format true
  logstash_prefix nginx1
  flush_interval 5s
&lt;/match&gt;
</code>
</pre>

And I'm getting the following error

<pre>
2016-08-05 11:18:14 +0000 [info]: listening fluent socket on 0.0.0.0:24224
2016-08-05 11:19:04 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2016-08-05 11:19:05 +0000 error_class="Elasticsearch::Transport::Transport::Errors::ServiceUnavailable" error="[503] " plugin_id="object:2abd2599728c"
  2016-08-05 11:19:04 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/elasticsearch-transport-2.0.0/lib/elasticsearch/transport/transport/base.rb:201:in `__raise_transport_error'
  2016-08-05 11:19:04 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/elasticsearch-transport-2.0.0/lib/elasticsearch/transport/transport/base.rb:312:in `perform_request'
  2016-08-05 11:19:04 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/elasticsearch-transport-2.0.0/lib/elasticsearch/transport/transport/http/faraday.rb:20:in `perform_request'
  2016-08-05 11:19:04 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/elasticsearch-transport-2.0.0/lib/elasticsearch/transport/client.rb:128:in `perform_request'
  2016-08-05 11:19:04 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/elasticsearch-api-2.0.0/lib/elasticsearch/api/actions/ping.rb:20:in `ping'
  2016-08-05 11:19:04 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/fluent-plugin-elasticsearch-1.5.0/lib/fluent/plugin/out_elasticsearch.rb:122:in `client'
  2016-08-05 11:19:04 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/fluent-plugin-elasticsearch-1.5.0/lib/fluent/plugin/out_elasticsearch.rb:279:in `rescue in send'
  2016-08-05 11:19:04 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/fluent-plugin-elasticsearch-1.5.0/lib/fluent/plugin/out_elasticsearch.rb:277:in `send'
  2016-08-05 11:19:04 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/fluent-plugin-elasticsearch-1.5.0/lib/fluent/plugin/out_elasticsearch.rb:271:in `write'
  2016-08-05 11:19:04 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.26/lib/fluent/buffer.rb:354:in `write_chunk'
  2016-08-05 11:19:04 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.26/lib/fluent/buffer.rb:333:in `pop'
  2016-08-05 11:19:04 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.26/lib/fluent/output.rb:338:in `try_flush'
  2016-08-05 11:19:04 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.26/lib/fluent/output.rb:149:in `run'
2016-08-05 11:19:05 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2016-08-05 11:19:07 +0000 error_class="Elasticsearch::Transport::Transport::Errors::ServiceUnavailable" error="[503] " plugin_id="object:2abd2599728c"
  2016-08-05 11:19:05 +0000 [warn]: suppressed same stacktrace
</pre>

is it possible that it's a bug or am I doing something wrong ?

**Comment by bwnyasse** [comment]
It was a bad proxy configuration in my architecture. 
Everything is ok.
