### ISSUE TITLE
NoMethodError error="undefined method `to_msgpack' 

### ISSUE THREAD

**Issue by sallespro** [uken/fluent-plugin-elasticsearch#188]
#### Problem(s)

2016-08-11 21:49:35 +0000 [warn]: emit transaction failed: error_class=NoMethodError error="undefined method `to_msgpack' for BSON::ObjectId('572a626be5f72f000600000c'):BSON::ObjectId" tag="ast13-ast-1"
  2016-08-11 21:49:35 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/fluent-plugin-elasticsearch-1.5.0/lib/fluent/plugin/out_elasticsearch.rb:174:in `to_msgpack'
  2016-08-11 21:49:35 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/fluent-plugin-elasticsearch-1.5.0/lib/fluent/plugin/out_elasticsearch.rb:174:in `format'

#### Steps to replicate

```
  <source>
    type mongo_tail
    url mongodb://mongodb/grid_server
    collection container_logs
    tag_key name
    time_key created_at
    id_store_collection container_logs_tail
  </source>
  <match **>
    type elasticsearch
    logstash_format true
    host elasticsearchhost.example
    port 9200
    index_name fluentd
    type_name fluentd
    include_tag_key true
  </match>
```

**Comment by repeatedly** [comment]
This is bug of fluent-plugin-mongo.
Maintainers can close this issue.
