### ISSUE TITLE
Fluentd dummy -> AWS ES fails unless fluentd running verbose

### ISSUE THREAD

**Issue by mpackard-tracelink** [uken/fluent-plugin-elasticsearch#207]
#### Problem

Hello,

I'm running fluentd with the dummy input set to generate data and sending output to an AWS ES cluster. When running fluentd normally, no dummy output is sent to ES. Running fluentd in verbose mode does, however.

fluentd: 0.14.6
fluent-plugin-elasticsearch: 1.7.0
ruby: 2.2.2p95
platform: CentOS 7 x86_64
fluentd.conf:

```
# Load generation input
<source>
  @type dummy
  tag input.dummy
  dummy {"key":"value"}
  rate 1000
  auto_increment_key dummy.counter
</source>

# Include Elasticsearch friendly timestamps on all messages
<filter **>
  @type elasticsearch_timestamp_check
</filter>

# Elasticsearch output
<match **>
  @type elasticsearch
  host <AWS_ES_Endpoint>
  port 80
  index_name foo.index
  type_name foo.type
  flush_interval 60
</match>
```
Regards,
Matthew Packard
...
#### Steps to replicate

```
$ fluentd -c fluentd.conf
2016-10-25 17:12:39 +0000 [info]: Connection opened to Elasticsearch cluster => {:host=>"<AWS_ES_Endpoint>", :port=>80, :scheme=>"http"}
2016-10-25 17:13:11 +0000 [warn]: Could not push logs to Elasticsearch, resetting connection and trying again. read timeout reached
2016-10-25 17:13:13 +0000 [info]: Connection opened to Elasticsearch cluster => {:host=>"<AWS_ES_Endpoint>", :port=>80, :scheme=>"http"}
2016-10-25 17:13:45 +0000 [warn]: Could not push logs to Elasticsearch, resetting connection and trying again. read timeout reached
2016-10-25 17:13:45 +0000 [info]: Connection opened to Elasticsearch cluster => {:host=>"<AWS_ES_Endpoint>", :port=>80, :scheme=>"http"}
2016-10-25 17:14:17 +0000 [warn]: failed to flush the buffer. plugin_id="object:9880f0" retry_time=0 next_retry=2016-10-25 17:14:18 +0000 chunk="53fb39a0223fa5996f535e5adb41b961" error_class=Fluent::ElasticsearchOutput::ConnectionFailure error="Could not push logs to Elasticsearch after 2 retries. read timeout reached"
2016-10-25 17:14:17 +0000 [warn]: /usr/local/rvm/gems/ruby-2.2.2/gems/fluent-plugin-elasticsearch-1.7.0/lib/fluent/plugin/out_elasticsearch.rb:343:in `rescue in send'
2016-10-25 17:14:17 +0000 [warn]: /usr/local/rvm/gems/ruby-2.2.2/gems/fluent-plugin-elasticsearch-1.7.0/lib/fluent/plugin/out_elasticsearch.rb:333:in `send'
2016-10-25 17:14:17 +0000 [warn]: /usr/local/rvm/gems/ruby-2.2.2/gems/fluent-plugin-elasticsearch-1.7.0/lib/fluent/plugin/out_elasticsearch.rb:318:in `write'
2016-10-25 17:14:17 +0000 [warn]: /usr/local/rvm/gems/ruby-2.2.2/gems/fluentd-0.14.6/lib/fluent/compat/output.rb:127:in `write'
2016-10-25 17:14:17 +0000 [warn]: /usr/local/rvm/gems/ruby-2.2.2/gems/fluentd-0.14.6/lib/fluent/plugin/output.rb:828:in `try_flush'
2016-10-25 17:14:17 +0000 [warn]: /usr/local/rvm/gems/ruby-2.2.2/gems/fluentd-0.14.6/lib/fluent/plugin/output.rb:1015:in `flush_thread_run'
2016-10-25 17:14:17 +0000 [warn]: /usr/local/rvm/gems/ruby-2.2.2/gems/fluentd-0.14.6/lib/fluent/plugin/output.rb:380:in `block (2 levels) in start'
2016-10-25 17:14:17 +0000 [warn]: /usr/local/rvm/gems/ruby-2.2.2/gems/fluentd-0.14.6/lib/fluent/plugin_helper/thread.rb:66:in `block in thread_create'

<no incrementing document count in ES>

vs.

$ fluentd -vvv -c fluentd.conf
2016-10-25 17:17:18 +0000 [debug]: plugin/buffer.rb:114:start: buffer started instance=9965440 stage_size=0 queue_size=0
2016-10-25 17:17:18 +0000 [debug]: plugin/filter_elasticsearch_timestamp_check.rb:30:filter: Timestamp added: 2016-10-25T17:17:18+0000
2016-10-25 17:17:18 +0000 [debug]: plugin/output.rb:954:enqueue_thread_run: enqueue_thread actually running
2016-10-25 17:17:18 +0000 [debug]: plugin/buffer.rb:343:enqueue_all: enqueueing all chunks in buffer instance=9965440
2016-10-25 17:17:18 +0000 [trace]: plugin/buffer.rb:168:add_metadata: adding metadata instance=9965440 metadata=#<struct Fluent::Plugin::Buffer::Metadata timekey=nil, tag=nil, variables=nil>
2016-10-25 17:17:18 +0000 [trace]: plugin/buffer.rb:191:write: writing events into buffer instance=9965440 metadata_size=1
2016-10-25 17:17:18 +0000 [debug]: plugin/filter_elasticsearch_timestamp_check.rb:30:filter: Timestamp added: 2016-10-25T17:17:18+0000
2016-10-25 17:17:18 +0000 [trace]: plugin/buffer.rb:168:add_metadata: adding metadata instance=9965440 metadata=#<struct Fluent::Plugin::Buffer::Metadata timekey=nil, tag=nil, variables=nil>
2016-10-25 17:17:18 +0000 [trace]: plugin/buffer.rb:191:write: writing events into buffer instance=9965440 metadata_size=1
2016-10-25 17:17:18 +0000 [debug]: plugin/filter_elasticsearch_timestamp_check.rb:30:filter: Timestamp added: 2016-10-25T17:17:18+0000
2016-10-25 17:17:18 +0000 [trace]: plugin/buffer.rb:168:add_metadata: adding metadata instance=9965440 metadata=#<struct Fluent::Plugin::Buffer::Metadata timekey=nil, tag=nil, variables=nil>
2016-10-25 17:17:18 +0000 [trace]: plugin/buffer.rb:191:write: writing events into buffer instance=9965440 metadata_size=1
2016-10-25 17:17:18 +0000 [debug]: plugin/filter_elasticsearch_timestamp_check.rb:30:filter: Timestamp added: 2016-10-25T17:17:18+0000
2016-10-25 17:17:18 +0000 [trace]: plugin/buffer.rb:168:add_metadata: adding metadata instance=9965440 metadata=#<struct Fluent::Plugin::Buffer::Metadata timekey=nil, tag=nil, variables=nil>
2016-10-25 17:17:18 +0000 [trace]: plugin/buffer.rb:191:write: writing events into buffer instance=9965440 metadata_size=1

<steadily incrementing document count in ES>
```

**Comment by pitr** [comment]
Can't replicate, non-verbose is working fine, just takes a minute to push logs

```
# fluentd --config config
2016-10-25 10:38:00 -0700 [info]: reading config file path="config"
2016-10-25 10:38:00 -0700 [info]: starting fluentd-0.14.2
2016-10-25 10:38:00 -0700 [info]: reading config file path="config"
2016-10-25 10:38:00 -0700 [info]: starting fluentd-0.14.2 without supervision
2016-10-25 10:38:00 -0700 [info]: gem 'fluentd' version '0.14.2'
2016-10-25 10:38:00 -0700 [info]: gem 'fluent-plugin-elasticsearch' version '1.8.0'
2016-10-25 10:38:00 -0700 [info]: gem 'fluent-plugin-elasticsearch-timestamp-check' version '0.1.2'
2016-10-25 10:38:00 -0700 [info]: adding filter pattern="**" type="elasticsearch_timestamp_check"
2016-10-25 10:38:00 -0700 [info]: adding match pattern="**" type="elasticsearch"
2016-10-25 10:38:00 -0700 [info]: adding source type="dummy"
2016-10-25 10:38:00 -0700 [warn]: both of Plugin @id and path for <storage> are not specified. Using on-memory store.
2016-10-25 10:38:00 -0700 [info]: using configuration file: <ROOT>
  <source>
    @type dummy
    tag "input.dummy"
    dummy {"key":"value"}
    rate 1000
    auto_increment_key "dummy.counter"
  </source>
  <filter **>
    @type elasticsearch_timestamp_check
  </filter>
  <match **>
    @type elasticsearch
    host "localhost"
    port 9200
    index_name "foo.index"
    type_name "foo.type"
    flush_interval 60
    <buffer>
      flush_mode interval
      retry_type exponential_backoff
      flush_interval 60
    </buffer>
  </match>
</ROOT>
2016-10-25 10:38:59 -0700 [info]: Connection opened to Elasticsearch cluster => {:host=>"localhost", :port=>9200, :scheme=>"http"}
```

**Comment by mpackard-tracelink** [comment]
Out of curiosity, what version of ES are you running locally? AWS is configured to use 2.3 at present.

I just tried updating the fluent-plugin-elasticsearch to 1.8.0 and saw the same behavior against AWS ES.

**Comment by pitr** [comment]
I am running 1.4.2. This plugin does not support ES 2.x, and neither does [fluent-plugin-aws-elasticsearch-service](atomita/fluent-plugin-aws-elasticsearch-service#19)

**Comment by pitr** [comment]
PR is welcomed, if you want to add support

**Comment by mpackard-tracelink** [comment]
Thanks for the info, Pitr. Is 2.X or even 5.0 support planned in the near future?

**Comment by pitr** [comment]
I'm not working on it, but if anyone contributes, I'll gladly review
