### ISSUE TITLE
ES Transport forgets username and password [401]

### ISSUE THREAD

**Issue by se-m** [uken/fluent-plugin-elasticsearch#208]
elasticsearch:2.4 + shield
gem 'fluent-plugin-elasticsearch' version '1.7.0'
gem 'fluent-plugin-parser' version '0.6.1'
gem 'fluent-plugin-record-reformer' version '0.8.2'
gem 'fluent-plugin-rewrite-tag-filter' version '1.5.5'
gem 'fluentd' version '0.12.24'

Elastic and fluentd in dockers

I don't know how is this possible, but i faced with this behavior.
All sevices are set and all working. But periodically fluentd stops send data to es at all. Fluentd configuration reload solves the problem as long as it does not happen again. In the beginning, I did not notice this problem. Period was 4-5 days when i noticed it. But I get this error every day now.  The PC is not very powerfull and when fluentd failing to flush it's ok, but 401 error is beyond my understanding.

fluentd  log:
```
2016-10-26 14:20:01 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2016-10-26 14:20:02 +0000 
            error_class="Elasticsearch::Transport::Transport::Errors::Unauthorized" error="[401] 
            {\"error\":
              {\"root_cause\":[
                {\"type\":\"security_exception\",\"reason\":\"missing authentication token for REST request [/_bulk]\",\"header\":{\"WWW-Authenticate\":\"Basic realm=\\\"shield\\\" charset=\\\"UTF-8\\\"\"}}
              ]
             ,\"type\":\"security_exception\"
             ,\"reason\":\"missing authentication token for REST request [/_bulk]\"
             ,\"header\":{\"WWW-Authenticate\":\"Basic realm=\\\"shield\\\" charset=\\\"UTF-8\\\"\"}}
             ,\"status\":401}" plugin_id="object:2ac356475ca4"
             
  2016-10-26 14:20:01 +0000 [warn]: /home/fluent/.gem/ruby/2.2.0/gems/elasticsearch-transport-1.0.18/lib/elasticsearch/transport/transport/base.rb:201:in `__raise_transport_error'
  2016-10-26 14:20:01 +0000 [warn]: /home/fluent/.gem/ruby/2.2.0/gems/elasticsearch-transport-1.0.18/lib/elasticsearch/transport/transport/base.rb:312:in `perform_request'
  2016-10-26 14:20:01 +0000 [warn]: /home/fluent/.gem/ruby/2.2.0/gems/elasticsearch-transport-1.0.18/lib/elasticsearch/transport/transport/http/faraday.rb:20:in `perform_request'
  2016-10-26 14:20:01 +0000 [warn]: /home/fluent/.gem/ruby/2.2.0/gems/elasticsearch-transport-1.0.18/lib/elasticsearch/transport/client.rb:128:in `perform_request'
  2016-10-26 14:20:01 +0000 [warn]: /home/fluent/.gem/ruby/2.2.0/gems/elasticsearch-api-1.0.18/lib/elasticsearch/api/actions/bulk.rb:90:in `bulk'
  2016-10-26 14:20:01 +0000 [warn]: /home/fluent/.gem/ruby/2.2.0/gems/fluent-plugin-elasticsearch-1.7.0/lib/fluent/plugin/out_elasticsearch.rb:334:in `send'
  2016-10-26 14:20:01 +0000 [warn]: /home/fluent/.gem/ruby/2.2.0/gems/fluent-plugin-elasticsearch-1.7.0/lib/fluent/plugin/out_elasticsearch.rb:318:in `write'
  2016-10-26 14:20:01 +0000 [warn]: /usr/lib/ruby/gems/2.2.0/gems/fluentd-0.12.24/lib/fluent/buffer.rb:354:in `write_chunk'
  2016-10-26 14:20:01 +0000 [warn]: /usr/lib/ruby/gems/2.2.0/gems/fluentd-0.12.24/lib/fluent/buffer.rb:333:in `pop'
  2016-10-26 14:20:01 +0000 [warn]: /usr/lib/ruby/gems/2.2.0/gems/fluentd-0.12.24/lib/fluent/output.rb:338:in `try_flush'
  2016-10-26 14:20:01 +0000 [warn]: /usr/lib/ruby/gems/2.2.0/gems/fluentd-0.12.24/lib/fluent/output.rb:149:in `run'
  2016-10-26 14:20:01 +0000 fluent.warn: {"next_retry":"2016-10-26 14:20:02 +0000","error_class":"Elasticsearch::Transport::Transport::Errors::Unauthorized","error":"[401] {\"error\":{\"root_cause\":[{\"type\":\"security_exception\",\"reason\":\"missing authentication token for REST request [/_bulk]\",\"header\":{\"WWW-Authenticate\":\"Basic realm=\\\"shield\\\" charset=\\\"UTF-8\\\"\"}}],\"type\":\"security_exception\",\"reason\":\"missing authentication token for REST request [/_bulk]\",\"header\":{\"WWW-Authenticate\":\"Basic realm=\\\"shield\\\" charset=\\\"UTF-8\\\"\"}},\"status\":401}","plugin_id":"object:2ac356475ca4","message":"temporarily failed to flush the buffer. next_retry=2016-10-26 14:20:02 +0000 error_class=\"Elasticsearch::Transport::Transport::Errors::Unauthorized\" error=\"[401] {\\\"error\\\":{\\\"root_cause\\\":[{\\\"type\\\":\\\"security_exception\\\",\\\"reason\\\":\\\"missing authentication token for REST request [/_bulk]\\\",\\\"header\\\":{\\\"WWW-Authenticate\\\":\\\"Basic realm=\\\\\\\"shield\\\\\\\" charset=\\\\\\\"UTF-8\\\\\\\"\\\"}}],\\\"type\\\":\\\"security_exception\\\",\\\"reason\\\":\\\"missing authentication token for REST request [/_bulk]\\\",\\\"header\\\":{\\\"WWW-Authenticate\\\":\\\"Basic realm=\\\\\\\"shield\\\\\\\" charset=\\\\\\\"UTF-8\\\\\\\"\\\"}},\\\"status\\\":401}\" plugin_id=\"object:2ac356475ca4\""}
  2016-10-26 14:20:02 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2016-10-26 14:20:04 +0000 error_class="Elasticsearch::Transport::Transport::Errors::Unauthorized" error="[401] {\"error\":{\"root_cause\":[{\"type\":\"security_exception\",\"reason\":\"missing authentication token for REST request [/_bulk]\",\"header\":{\"WWW-Authenticate\":\"Basic realm=\\\"shield\\\" charset=\\\"UTF-8\\\"\"}}],\"type\":\"security_exception\",\"reason\":\"missing authentication token for REST request [/_bulk]\",\"header\":{\"WWW-Authenticate\":\"Basic realm=\\\"shield\\\" charset=\\\"UTF-8\\\"\"}},\"status\":401}" plugin_id="object:2ac356475ca4"
  2016-10-26 14:20:02 +0000 [warn]: suppressed same stacktrace
  2016-10-26 14:20:02 +0000 fluent.warn: {"next_retry":"2016-10-26 14:20:04 +0000","error_class":"Elasticsearch::Transport::Transport::Errors::Unauthorized","error":"[401] {\"error\":{\"root_cause\":[{\"type\":\"security_exception\",\"reason\":\"missing authentication token for REST request [/_bulk]\",\"header\":{\"WWW-Authenticate\":\"Basic realm=\\\"shield\\\" charset=\\\"UTF-8\\\"\"}}],\"type\":\"security_exception\",\"reason\":\"missing authentication token for REST request [/_bulk]\",\"header\":{\"WWW-Authenticate\":\"Basic realm=\\\"shield\\\" charset=\\\"UTF-8\\\"\"}},\"status\":401}","plugin_id":"object:2ac356475ca4","message":"temporarily failed to flush the buffer. next_retry=2016-10-26 14:20:04 +0000 error_class=\"Elasticsearch::Transport::Transport::Errors::Unauthorized\" error=\"[401] {\\\"error\\\":{\\\"root_cause\\\":[{\\\"type\\\":\\\"security_exception\\\",\\\"reason\\\":\\\"missing authentication token for REST request [/_bulk]\\\",\\\"header\\\":{\\\"WWW-Authenticate\\\":\\\"Basic realm=\\\\\\\"shield\\\\\\\" charset=\\\\\\\"UTF-8\\\\\\\"\\\"}}],\\\"type\\\":\\\"security_exception\\\",\\\"reason\\\":\\\"missing authentication token for REST request [/_bulk]\\\",\\\"header\\\":{\\\"WWW-Authenticate\\\":\\\"Basic realm=\\\\\\\"shield\\\\\\\" charset=\\\\\\\"UTF-8\\\\\\\"\\\"}},\\\"status\\\":401}\" plugin_id=\"object:2ac356475ca4\""}
```

**Comment by se-m** [comment]
My output config
```
#all xxxx to elastic
<match xxxx.**>
  @type copy
  <store>
    @type elasticsearch
    host elasticsearch
    port 9200
    target_index_key target_index
    target_type_key target_type
    include_tag_key true
    tag_key  fluent_tag
    flush_interval 5s
    template_name xxxx
    template_file /templates/xxxx
    user "#{ENV['USERNAME']}"
    password "#{ENV['PASSWORD']}"
  </store>
  <store>
    @type stdout
  </store>
</match>
```

**Comment by pitr** [comment]
ES 2.x is not supported. PR is welcomed

**Comment by se-m** [comment]
@pitr 
Once question was closed, I have applied a patch to try resolve this issue. 
Do I need to create a new issue for discussion or you open this?

**Comment by turbotankist** [comment]
@se-m 
Hello!
How did you resolve it?
I have the same problem every two days and I need to restart containers.

**Comment by se-m** [comment]
@turbotankist
Did you enable `reconnect_on_error` option in config?

I did not have time to check my patch on production, because I had problems with the license for shield.
So I removed it, and I had to switch all to this configuration:
fluent-docker and elasticsearch-docker are connected to the same internal docker network and fluent interacts with es without auth. For external connection I protect my elasticsearch-docker with proxy (nginx-docker).

For example, when I start kibana I need to enter login-password once for nginx, and then it works without problems at all.

**Comment by dev-e** [comment]
Please reopen, because I have the same issue on ES 5.6.3. 'fluent-plugin-elasticsearch' version '1.10.0'
fluentd user have cluster permission "monitor" and index premissions "write" and "create_index".

**Comment by cosmo0920** [comment]
Is there any suspicious output in elasticsearch side?

**Comment by dev-e** [comment]
I dont'like this one:
`[2017-10-11T07:38:25,979][ERROR][o.e.x.s.a.e.NativeUsersStore] [_HAUaHL] failed to retrieve user [fluentd]`

**Comment by dev-e** [comment]
Today the same story:

2017-10-12 **09:39:10** +0000 [info]: following tail of /var/log/containers/selenium-hub-test-4pkcr_test_selenium-hub-test-da86647e47ef1257858846c6ac733406258f46203b24ac57c9e47aaf45fc451b.log
2017-10-12 **14:12:06** +0000 [warn]: temporarily failed to flush the buffer. next_retry=2017-10-12 14:12:07 +0000 error_class="Elasticsearch::Transport::Transport::Errors::Unauthorized" error="[401] {\"error\":{\"root_cause\":[{\"type\":\"security_exception\",\"reason\":\"missing authentication token for REST request [/_bulk]\",\"header\":{\"WWW-Authenticate\":\"Basic realm=\\\"security\\\" charset=\\\"UTF-8\\\"\"}}],\"type\":\"security_exception\",\"reason\":\"missing authentication token for REST request [/_bulk]\",\"header\":{\"WWW-Authenticate\":\"Basic realm=\\\"security\\\" charset=\\\"UTF-8\\\"\"}},\"status\":401}" plugin_id="object:352afedc74"

2017-10-12 14:12:06 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/elasticsearch-transport-5.0.4/lib/elasticsearch/transport/transport/base.rb:202:in `__raise_transport_error'

2017-10-12 14:12:06 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/elasticsearch-transport-5.0.4/lib/elasticsearch/transport/transport/base.rb:319:in `perform_request'

2017-10-12 14:12:06 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/elasticsearch-transport-5.0.4/lib/elasticsearch/transport/transport/http/faraday.rb:20:in `perform_request'

2017-10-12 14:12:06 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/elasticsearch-transport-5.0.4/lib/elasticsearch/transport/client.rb:131:in `perform_request'

2017-10-12 14:12:06 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/elasticsearch-api-5.0.4/lib/elasticsearch/api/actions/bulk.rb:95:in `bulk'

2017-10-12 14:12:06 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/fluent-plugin-elasticsearch-1.10.0/lib/fluent/plugin/out_elasticsearch.rb:362:in `send_bulk'

2017-10-12 14:12:06 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/fluent-plugin-elasticsearch-1.10.0/lib/fluent/plugin/out_elasticsearch.rb:348:in `write_objects'

2017-10-12 14:12:06 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.33/lib/fluent/output.rb:490:in `write'

2017-10-12 14:12:06 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.33/lib/fluent/buffer.rb:354:in `write_chunk'

2017-10-12 14:12:06 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.33/lib/fluent/buffer.rb:333:in `pop'

2017-10-12 14:12:06 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.33/lib/fluent/output.rb:342:in `try_flush'

2017-10-12 14:12:06 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.33/lib/fluent/output.rb:149:in `run'

No relevant output on ES side.
