### ISSUE TITLE
error with td-agent and elasticsearch 5

### ISSUE THREAD

**Issue by heiqs** [uken/fluent-plugin-elasticsearch#209]
After updating elastic search from 2.4 to 5, we get following error from td-agent log files: 

```
2016-11-03 08:48:07 +0100 [warn]: suppressed same stacktrace
2016-11-03 08:48:16 +0100 [warn]: failed to flush the buffer. plugin_id="object:3ffcd3628490" retry_time=5 next_retry=2016-11-03 08:48:34 +0100 chunk="54060c61f6bca5ca6e93d330622f2aca" error_class=MultiJson::ParseError error="Yajl::ParseError"
  2016-11-03 08:48:16 +0100 [warn]: suppressed same stacktrace
2016-11-03 08:48:34 +0100 [warn]: failed to flush the buffer. plugin_id="object:3ffcd3628490" retry_time=6 next_retry=2016-11-03 08:49:02 +0100 chunk="54060c61f6bca5ca6e93d330622f2aca" error_class=MultiJson::ParseError error="Yajl::ParseError"
  2016-11-03 08:48:34 +0100 [warn]: suppressed same stacktrace
2016-11-03 08:49:02 +0100 [warn]: failed to flush the buffer. plugin_id="object:3ffcd3628490" retry_time=7 next_retry=2016-11-03 08:50:09 +0100 chunk="54060c61f6bca5ca6e93d330622f2aca" error_class=MultiJson::ParseError error="Yajl::ParseError"
  2016-11-03 08:49:02 +0100 [warn]: suppressed same stacktrace
2016-11-03 08:50:09 +0100 [warn]: failed to flush the buffer. plugin_id="object:3ffcd3628490" retry_time=8 next_retry=2016-11-03 08:52:11 +0100 chunk="54060c61f6bca5ca6e93d330622f2aca" error_class=MultiJson::ParseError error="Yajl::ParseError"
  2016-11-03 08:50:09 +0100 [warn]: suppressed same stacktrace
```
This is my td-agent configuration file:

```
<source>
  @type forward
  port 4000
  bind 192.168.2.71
</source>

<match **>
  @type elasticsearch
  host localhost
  port 9200
  logstash_format true
  #flush_interval 5
  flush_interval 10s
</match>
```

Our system: we have clients which send log messages to our server where elastic search and fluent-plugin-elasticsearch are installed there. 

Could anybody help us to fix this issue?
Thanks

**Comment by elmalto** [comment]
I ran into a similar issue and it seems it was a dependency issue. I am using the ubuntu package and removed td-agent + deleted /opt/td-agent (important!) to get rid of the embedded dependencies and then reinstalled td-agent and my dependencies. I think dependencies of plugins were not updated properly (there probably is a better way to force update all dependencies, but I don't know ruby)

**Comment by andyevans** [comment]
@heiqs what was the solution to this one? I am seeing the same when i upgrade to Elasticsearch 5.0

**Comment by essa** [comment]
I met same problem and resolved it by re-installing fluentd from scrach.

```bash
$ sudo service td-agent stop
$ sudo apt-get purge td-agent
$ sudo rm -rf /opt/td-agent/
$ curl -L https://toolbelt.treasuredata.com/sh/install-ubuntu-trusty-td-agent2.sh | sudo sh
$ sudo /opt/td-agent/embedded/bin/gem install fluent-plugin-elasticsearch
```

**Comment by xingxing9688** [comment]
I have encountered this problem, how do you solve it? 

Starting fluentd agent ...
2017-08-02 07:32:07 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2017-08-02 07:32:09 +0000 error_class="MultiJson::ParseError" error="Yajl::ParseError" plugin_id="object:19f8944"
  2017-08-02 07:32:07 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/multi_json-1.11.0/lib/multi_json/adapter.rb:19:in `load'
  2017-08-02 07:32:07 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/multi_json-1.11.0/lib/multi_json.rb:119:in `load'
  2017-08-02 07:32:07 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/elasticsearch-transport-1.0.13/lib/elasticsearch/transport/transport/serializer/multi_json.rb:24:in `load'
  2017-08-02 07:32:07 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/elasticsearch-transport-1.0.13/lib/elasticsearch/transport/transport/base.rb:231:in `perform_request'
  2017-08-02 07:32:07 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/elasticsearch-transport-1.0.13/lib/elasticsearch/transport/transport/http/faraday.rb:20:in `perform_request'
  2017-08-02 07:32:07 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/elasticsearch-transport-1.0.13/lib/elasticsearch/transport/client.rb:119:in `perform_request'
  2017-08-02 07:32:07 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/elasticsearch-api-1.0.13/lib/elasticsearch/api/actions/ping.rb:20:in `block in ping'
  2017-08-02 07:32:07 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/elasticsearch-api-1.0.13/lib/elasticsearch/api/utils.rb:191:in `__rescue_from_not_found'
  2017-08-02 07:32:07 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/elasticsearch-api-1.0.13/lib/elasticsearch/api/actions/ping.rb:19:in `ping'
  2017-08-02 07:32:07 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-elasticsearch-1.0.0/lib/fluent/plugin/out_elasticsearch.rb:64:in `client'
  2017-08-02 07:32:07 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-elasticsearch-1.0.0/lib/fluent/plugin/out_elasticsearch.rb:171:in `rescue in send'
  2017-08-02 07:32:07 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-elasticsearch-1.0.0/lib/fluent/plugin/out_elasticsearch.rb:169:in `send'
  2017-08-02 07:32:07 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-elasticsearch-1.0.0/lib/fluent/plugin/out_elasticsearch.rb:163:in `write'
  2017-08-02 07:32:07 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.12/lib/fluent/buffer.rb:325:in `write_chunk'
  2017-08-02 07:32:07 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.12/lib/fluent/buffer.rb:304:in `pop'
  2017-08-02 07:32:07 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.12/lib/fluent/output.rb:321:in `try_flush'
  2017-08-02 07:32:07 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.12/lib/fluent/output.rb:140:in `run'
2017-08-02 07:32:09 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2017-08-02 07:32:10 +0000 error_class="MultiJson::ParseError" error="Yajl::ParseError" plugin_id="object:19f8944"  2017-08-02 07:32:09 +0000 [warn]: suppressed same stacktrace
2017-08-02 07:32:10 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2017-08-02 07:32:15 +0000 error_class="MultiJson::ParseError" error="Yajl::ParseError" plugin_id="object:19f8944"  2017-08-02 07:32:10 +0000 [warn]: suppressed same stacktrace
2017-08-02 07:32:15 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2017-08-02 07:32:22 +0000 error_class="MultiJson::ParseError" error="Yajl::ParseError" plugin_id="object:19f8944"  2017-08-02 07:32:15 +0000 [warn]: suppressed same stacktrace
2017-08-02 07:32:22 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2017-08-02 07:32:40 +0000 error_class="MultiJson::ParseError" error="Yajl::ParseError" plugin_id="object:19f8944"  2017-08-02 07:32:22 +0000 [warn]: suppressed same stacktrace
2017-08-02 07:32:40 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2017-08-02 07:33:08 +0000 error_class="MultiJson::ParseError" error="Yajl::ParseError" plugin_id="object:19f8944"  2017-08-02 07:32:40 +0000 [warn]: suppressed same stacktrace
2017-08-02 07:33:09 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2017-08-02 07:34:17 +0000 error_class="MultiJson::ParseError" error="Yajl::ParseError" plugin_id="object:19f8944"  2017-08-02 07:33:09 +0000 [warn]: suppressed same stacktrace
2017-08-02 07:34:17 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2017-08-02 07:36:35 +0000 error_class="MultiJson::ParseError" error="Yajl::ParseError" plugin_id="object:19f8944"  2017-08-02 07:34:17 +0000 [warn]: suppressed same stacktrace
2017-08-02 07:36:35 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2017-08-02 07:40:39 +0000 error_class="MultiJson::ParseError" error="Yajl::ParseError" plugin_id="object:19f8944"  2017-08-02 07:36:35 +0000 [warn]: suppressed same stacktrace
root@fluentd-elk-mrxoc:/tmp# tail -f  fluentd-stdout---supervisor-YA4Zxb.log 
2017-08-02 07:32:40 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2017-08-02 07:33:08 +0000 error_class="MultiJson::ParseError" error="Yajl::ParseError" plugin_id="object:19f8944"
  2017-08-02 07:32:40 +0000 [warn]: suppressed same stacktrace
2017-08-02 07:33:09 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2017-08-02 07:34:17 +0000 error_class="MultiJson::ParseError" error="Yajl::ParseError" plugin_id="object:19f8944"
  2017-08-02 07:33:09 +0000 [warn]: suppressed same stacktrace
2017-08-02 07:34:17 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2017-08-02 07:36:35 +0000 error_class="MultiJson::ParseError" error="Yajl::ParseError" plugin_id="object:19f8944"
  2017-08-02 07:34:17 +0000 [warn]: suppressed same stacktrace
2017-08-02 07:36:35 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2017-08-02 07:40:39 +0000 error_class="MultiJson::ParseError" error="Yajl::ParseError" plugin_id="object:19f8944"
  2017-08-02 07:36:35 +0000 [warn]: suppressed same stacktrace
2017-08-02 07:40:39 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2017-08-02 07:45:39 +0000 error_class="MultiJson::ParseError" error="Yajl::ParseError" plugin_id="object:19f8944"
  2017-08-02 07:40:39 +0000 [warn]: suppressed same stacktrace




2017-08-02 07:45:39 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2017-08-02 07:50:39 +0000 error_class="MultiJson::ParseError" error="Yajl::ParseError" plugin_id="object:19f8944"
  2017-08-02 07:45:39 +0000 [warn]: suppressed same stacktrace

**Comment by andyevans** [comment]
It has been a while but from memory it was a problem either with:
1. Trying to use fluentd with AWS Elasticsearch, or
2. The version of Elasticsearch not being supported  by the fluentd version

_____________________________

**Comment by xingxing9688** [comment]
2017-08-03 02:37:42 +0000 [error]: config error file="/etc/td-agent/td-agent.conf" error="Unknown output plugin 'record_reformer'. Run 'gem search -rd fluent-plugin' to find plugins"
2017-08-03 02:37:42 +0000 [warn]: process died within 1 second. exit.

**Comment by ngocson2vn** [comment]
Recently I have encountered this problem too. I've followed @essa's suggestion and it works very well.
```
$ sudo service td-agent stop
$ sudo apt-get purge td-agent
$ sudo rm -rf /opt/td-agent/
$ curl -L https://toolbelt.treasuredata.com/sh/install-ubuntu-trusty-td-agent2.sh | sudo sh
```
