### ISSUE TITLE
temporarily failed to flush the buffer, Yajl::ParseError

### ISSUE THREAD

**Issue by liujiawinds** [uken/fluent-plugin-elasticsearch#218]
It seems to be a parsing error.  btw, I run this td-agent in a kubernetes cluster.

**Trace**

```
2016-12-01 02:12:19 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2016-12-01 02:14:31 +0000 error_class="MultiJson::ParseError" error="Yajl::ParseError" plugin_id="object:14cc948"
  2016-12-01 02:12:19 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/multi_json-1.10.1/lib/multi_json/adapter.rb:19:in `load'
  2016-12-01 02:12:19 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/multi_json-1.10.1/lib/multi_json.rb:119:in `load'
  2016-12-01 02:12:19 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/elasticsearch-transport-1.0.6/lib/elasticsearch/transport/transport/serializer/multi_json.rb:24:in `load'
  2016-12-01 02:12:19 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/elasticsearch-transport-1.0.6/lib/elasticsearch/transport/transport/base.rb:227:in `perform_request'
  2016-12-01 02:12:19 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/elasticsearch-transport-1.0.6/lib/elasticsearch/transport/transport/http/faraday.rb:20:in `perform_request'
  2016-12-01 02:12:19 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/elasticsearch-transport-1.0.6/lib/elasticsearch/transport/client.rb:111:in `perform_request'
  2016-12-01 02:12:19 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/elasticsearch-api-1.0.6/lib/elasticsearch/api/actions/ping.rb:19:in `ping'
  2016-12-01 02:12:19 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-elasticsearch-0.7.0/lib/fluent/plugin/out_elasticsearch.rb:62:in `client'
  2016-12-01 02:12:19 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-elasticsearch-0.7.0/lib/fluent/plugin/out_elasticsearch.rb:168:in `send'
  2016-12-01 02:12:19 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-elasticsearch-0.7.0/lib/fluent/plugin/out_elasticsearch.rb:161:in `write'
  2016-12-01 02:12:19 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.10.58/lib/fluent/buffer.rb:300:in `write_chunk'
  2016-12-01 02:12:19 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.10.58/lib/fluent/buffer.rb:280:in `pop'
  2016-12-01 02:12:19 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.10.58/lib/fluent/output.rb:315:in `try_flush'
  2016-12-01 02:12:19 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.10.58/lib/fluent/output.rb:136:in `run'
```

**config**

```
<source>
  type tail
  format json
  time_key time
  path /var/lib/docker/containers/*/*-json.log
  pos_file /var/lib/docker/containers/containers.log.pos
  time_format %Y-%m-%dT%H:%M:%S
  tag docker.container.*
</source>

<match docker.container.**>
   type elasticsearch
   include_tag_key true
   host elasticsearch-logging
   port 9200
   logstash_format true
   flush_interval 5s
   # Never wait longer than 5 minutes between retries.
   max_retry_wait 300
   # Disable the limit on the number of retries (retry forever).
   disable_retry_limit
</match>

<source>
  type tail
  format none
  path /var/log/messages
  pos_file /var/log/messages.pos
  tag serviceoutput
</source>

<match serviceoutput>
   type elasticsearch
   include_tag_key true
   host elasticsearch-logging
   port 9200
   logstash_format true
   flush_interval 5s
   # Never wait longer than 5 minutes between retries.
   max_retry_wait 300
   # Disable the limit on the number of retries (retry forever).
   disable_retry_limit
</match>

```

**version** 

```
td-agent:0.10.58
fluent-plugin-elasticsearch:0.7.0
elasticsearch:5.0.1
```

**Comment by pitr** [comment]
Looks like the issue is with parsing ElasticSearch response ([see code here](https://github.com/elastic/elasticsearch-ruby/blob/v1.0.6/elasticsearch-transport/lib/elasticsearch/transport/transport/base.rb#L227)). I suggest trying to call elasticsearch from the server that is running td-agent and verifying that the response is valid json

**Comment by liujiawinds** [comment]
I solved this problem by upgrading fluent-plugin-elasticsearch.

now my version :
```
fluentd: 0.12.29
fluent-plugin-elasticsearch: 1.5.0
elasticsearch: 5.0.1
kibana: 5.0.1
```
