### ISSUE TITLE
Parameter 'path' has timestamp placeholders, but chunk key 'time' is not configured

### ISSUE THREAD

**Issue by sampointer** [uken/fluent-plugin-elasticsearch#221]
## Problem
With fluentd 0.14.9 and the latest version of this plugin configuring `@type file` as a `<secondary>` output throws the error `Parameter 'path' has timestamp placeholders, but chunk key 'time' is not configured`.

Using another output plugin as the secondary (such as `@type stdout`) does not show this error.

0.14.9 was the release that made sub-second timestamps the default (our reason for upgrading) and I've got a suspicion that it is related to this issue, specifically: https://github.com/uken/fluent-plugin-elasticsearch/blob/master/lib/fluent/plugin/out_elasticsearch.rb#L114

A stack trace from the point that exception is raised is:

```
From: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.9/lib/fluent/plugin/output.rb @ line 575 Fluent::Plugin::Output::PlaceholderValidator#validate_time!:
    566: def validate_time!
    567:   sec = @argument[:sec]
    568:   title = @argument[:title]
    569:   example = @argument[:example]
    570:   timekey = @argument[:timekey]
    571:   if !sec && timekey
    572:     raise Fluent::ConfigError, "Parameter '#{name}' doesn't have timestamp placeholders for timekey #{timekey.to_i}"
    573:   end
    574:   if sec && !timekey
 => 575:     binding.pry
    576:     raise Fluent::ConfigError, "Parameter '#{name}' has timestamp placeholders, but chunk key 'time' is not configured"
    577:   end
    578:   if sec && timekey && timekey < sec
    579:     raise Fluent::ConfigError, "Parameter '#{@name}' doesn't have timestamp placeholder for #{title}('#{example}') for timekey #{timekey.to_i}"
    580:   end
    581: end
[1] pry(#<Fluent::Plugin::Output::PlaceholderValidator>)*   pry-backtrace
Backtrace:
--
/opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.9/lib/fluent/plugin/output.rb:575:in `validate_time!'
/opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.9/lib/fluent/plugin/output.rb:560:in `validate!'
/opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.9/lib/fluent/plugin/output.rb:510:in `block in placeholder_validate!'
/opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.9/lib/fluent/plugin/output.rb:509:in `each'
/opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.9/lib/fluent/plugin/output.rb:509:in `placeholder_validate!'
/opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.9/lib/fluent/plugin/out_file.rb:118:in `configure'
/opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.9/lib/fluent/plugin/output.rb:322:in `configure'
/opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.9/lib/fluent/plugin_helper/inject.rb:95:in `configure'
/opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.9/lib/fluent/plugin_helper/event_emitter.rb:73:in `configure'
/opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.9/lib/fluent/compat/output.rb:482:in `configure'
/opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-elasticsearch-1.9.0/lib/fluent/plugin/out_elasticsearch.rb:71:in `configure'
/opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.9/lib/fluent/plugin/multi_output.rb:73:in `block in configure'
/opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.9/lib/fluent/plugin/multi_output.rb:62:in `each'
/opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.9/lib/fluent/plugin/multi_output.rb:62:in `configure'
/opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.9/lib/fluent/agent.rb:127:in `add_match'
/opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.9/lib/fluent/agent.rb:70:in `block in configure'
/opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.9/lib/fluent/agent.rb:63:in `each'
/opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.9/lib/fluent/agent.rb:63:in `configure'
/opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.9/lib/fluent/root_agent.rb:86:in `configure'
/opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.9/lib/fluent/engine.rb:119:in `configure'
/opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.9/lib/fluent/engine.rb:93:in `run_configure'
/opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.9/lib/fluent/supervisor.rb:693:in `run_configure'
/opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.9/lib/fluent/supervisor.rb:453:in `block in run_worker'
/opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.9/lib/fluent/supervisor.rb:626:in `call'
/opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.9/lib/fluent/supervisor.rb:626:in `main_process'
/opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.9/lib/fluent/supervisor.rb:449:in `run_worker'
/opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.9/lib/fluent/command/fluentd.rb:288:in `<top (required)>'
/opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:69:in `require'
/opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:69:in `require'
/opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.9/bin/fluentd:5:in `<top (required)>'
/opt/td-agent/embedded/bin/fluentd:23:in `load'
/opt/td-agent/embedded/bin/fluentd:23:in `<main>'
[1] pry(#<Fluent::Plugin::Output::PlaceholderValidator>)* 
```
`sec` contains `86400` and `timekey` is `nil`.

Here is our configuration and installed gems:

### Gems
```
addressable (2.5.0)
aws-sdk (2.2.14)
aws-sdk-core (2.2.14)
elasticsearch-api (1.0.18)
elasticsearch-transport (1.0.18)
excon (0.54.0)
faraday (0.10.0)
faraday_middleware-aws-signers-v4 (0.1.1)
fluent-logger (0.6.1)
fluent-mixin-config-placeholders (0.4.0)
fluent-mixin-plaintextformatter (0.2.6)
fluent-plugin-aws-elasticsearch-service (0.1.4)
fluent-plugin-cloudwatch-logs (0.3.3)
fluent-plugin-elasticsearch (1.9.0)
fluent-plugin-mongo (0.7.12)
fluent-plugin-rewrite-tag-filter (1.5.4)
fluent-plugin-s3 (0.6.5)
fluent-plugin-scribe (0.10.14)
fluent-plugin-secure-forward (0.4.3)
fluent-plugin-statsd (1.0.3)
fluent-plugin-td (0.10.28)
fluent-plugin-td-monitoring (0.2.2)
fluent-plugin-webhdfs (0.4.1)
fluentd (0.14.9)
hirb (0.7.3)
http_parser.rb (0.6.0)
httpclient (2.7.1)
io-console (0.4.3)
ipaddress (0.8.3)
jmespath (1.3.1)
json (1.8.1)
ltsv (0.1.0)
mini_portile2 (2.1.0)
minitest (4.7.5)
mixlib-cli (1.7.0)
mixlib-config (2.2.4)
mixlib-log (1.7.1)
mixlib-shellout (2.2.7)
mongo (1.12.5)
msgpack (1.0.2, 0.7.6, 0.5.11)
multi_json (1.12.1)
multipart-post (2.0.0)
nokogiri (1.6.8.1)
ohai (6.20.0)
oj (2.14.4)
parallel (0.6.5)
proxifier (1.0.3)
psych (2.0.5)
public_suffix (2.0.4)
rake (10.1.0)
rdoc (4.1.0)
resolve-hostname (0.0.4)
ruby-progressbar (1.7.5)
rubyzip (1.1.7)
serverengine (2.0.4)
sigdump (0.2.3)
statsd-ruby (1.3.0)
string-scrub (0.0.5)
strptime (0.1.8)
systemu (2.5.2)
td (0.13.2)
td-client (0.8.78)
td-logger (0.3.26)
test-unit (2.1.8.0)
thread_safe (0.3.5)
thrift (0.8.0)
tzinfo (1.2.2)
tzinfo-data (1.2016.1)
uuidtools (2.1.5)
webhdfs (0.7.4)
yajl-ruby (1.2.1)
zip-zip (0.3)
```
### Configuration
```
# Sources
# This source ingests the local system logs
<source>
  @type tail
  path /var/log/syslog
  pos_file /var/spool/td-agent/syslog.pos
  tag locallogs
  format /^(?<time>[^\s]+) (?<facility>\w+)\.(?<priority>\w+) (?<hostname>[^\s]+) (?<process>[^:]+): *(?<message>.*)$/

  # Support ms time resolution
  time_format %Y-%m-%dT%H:%M:%S.%L%z
  keep_time_key true
</source>

# This source receives logs from remote client fluentd installations:
# the primary manner in which logs are ingested into the service
<source>
  @type secure_forward
  self_hostname REDACTED
  shared_key REDACTED

  secure true
  cert_path /etc/td-agent/ssl_cert.pem
  private_key_path /etc/td-agent/ssl_key.pem
  private_key_passphrase

  # Support ms time resolution
  time_as_integer false
</source>

# These optional sources fetch logs from Cloudwatch.
# It requires appropriate IAM configuration.

# This source is present so that it can be used to
# ingest the files from /var/spool/td-agent/overflow
#
# The simplest way to do this is to execute:
#
#   cat failed.log._* | nc localhost 24224
#
# and then to remove the files. Running this command
# twice will lead to a duplication of entries in the
# index.
#
# http://docs.fluentd.org/articles/in_forward
<source>
  @type forward
  port 24224
  bind 127.0.0.1
</source>

# Filters
<filter locallogs>
  @type record_transformer
  <record>
    statsd_type increment
    statsd_key syslog.${facility}.${priority}
  </record>
  <record>
    ident_product REDACTED
    ident_environment REDACTED
    ident_role REDACTED
    ident_hostname REDACTED
    host_ident REACTED
  </record>
</filter>

# For cloudwatch logs the tag includes the
# log stream prefix, like this:
#  cloudwatch.2016/11/15/[8]3f7fd61b30134354b5d3c85115a47f99
#
# Therefore, below we match on cloudwatch.*
<filter cloudwatch.*>
  @type record_transformer
  <record>
    statsd_type increment
    statsd_key cloudwatch
  </record>
</filter>


# Matched outputs
<match **>
  type copy

  <store>
    @type statsd
    host localhost
    port 8125
    flush_interval 1s
  </store>


  <store>
    @type "aws-elasticsearch-service"
    logstash_format true
    include_tag_key true
    tag_key "@log_name"

    # Implement this fix:
    # https://discuss.elastic.co/t/elasitcsearch-ruby-raises-cannot-get-new-connection-from-pool-error/36252/9
    reload_connections false

    # We'd like to gain the .raw fields mapping, like logstash:
    # http://stackoverflow.com/questions/33979226/where-do-raw-fields-come-from-when-using-logstash-with-elasticsearch-output
    #
    # This is so that we can do visualizations on non-analyzed fields.
    #
    # Further reading:
    #
    # https://github.com/uken/fluent-plugin-elasticsearch/pull/194
    # https://github.com/uken/fluent-plugin-elasticsearch/issues/33
    template_name "logstash"
    template_file "/etc/td-agent/elasticsearch-template-es2x.json"

    # Implement this fix:
    # https://github.com/fluent/fluentd/issues/607
    request_timeout 10

    # Support ms time resolution
    time_key 'time'
    time_as_integer false

    # AWS Elasticsearch has a 10M maximum request size.
    # Fluentd serializes messages sent to the Elasticsearch
    # output plugin with msgpack.
    #
    # A small subset of benchmarked messages were shown to
    # compress to between 85 and 66% of their original size.
    #
    # Therefore the buffer_chunk_limit below assumes that
    # msgpack will never be more than 50% efficient.
    buffer_type "file"
    buffer_path "/var/spool/td-agent/"
    buffer_chunk_limit 5m    # AWS ES Service max request size is 10m
    buffer_queue_limit 17800 # 5m chunk with a 90G spool volume, plus headroom
    flush_interval 5s
    retry_limit 2            # Write to secondary quickly

    <endpoint>
      url https://REDACTED.us-west-1.es.amazonaws.com
      region us-west-1
    </endpoint>

    <secondary>
      @type file
      path /var/spool/td-agent/overflow/failed.
    </secondary>

  </store>
```

**Comment by repeatedly** [comment]
Does this happen with v0.14.10?

**Comment by sampointer** [comment]
I have this working with v0.14.11. However, due to the changes in 0.14 the `<secondary>` mechanism does not seems to work. I'll discuss this in another issue.

**Comment by sampointer** [comment]
Discussion of secondary mechanism: https://github.com/uken/fluent-plugin-elasticsearch/issues/235

**Comment by sampointer** [comment]
With the master branch that will become 0.14.13 we have this working with the above configuration, albeit using `secondary_file` as the secondary plugin.
