### ISSUE TITLE
Cannot get new connection from pool.

### ISSUE THREAD

**Issue by zerthimon** [uken/fluent-plugin-elasticsearch#237]
I'm having a problem with sending logs to elastic.
The logging stops with error after a while until fluentd restarted:
```
2017-01-26 12:49:34 +0000 [info]: listening fluent socket on 0.0.0.0:24224
2017-01-26 12:49:40 +0000 [info]: Connection opened to Elasticsearch cluster => {:host=>"138.201.19.49", :port=>9200, :scheme=>"http"}
2017-01-26 12:49:40 +0000 fluent.info: {"message":"Connection opened to Elasticsearch cluster => {:host=>\"138.201.19.49\", :port=>9200, :scheme=>\"http\"}"}
2017-01-26 12:49:40 +0000 [warn]: no patterns matched tag="fluent.info"
2017-02-01 03:16:54 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2017-02-01 03:16:55 +0000 error_class="Elasticsearch::Transport::Transport::Error" error="Cannot get new connection from pool." plugin_id="output_docker1"
  2017-02-01 03:16:54 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/elasticsearch-transport-1.0.18/lib/elasticsearch/transport/transport/base.rb:249:in `perform_request'
  2017-02-01 03:16:54 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/elasticsearch-transport-1.0.18/lib/elasticsearch/transport/transport/http/faraday.rb:20:in `perform_request'
  2017-02-01 03:16:54 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/elasticsearch-transport-1.0.18/lib/elasticsearch/transport/client.rb:128:in `perform_request'
  2017-02-01 03:16:54 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/elasticsearch-api-1.0.18/lib/elasticsearch/api/actions/bulk.rb:90:in `bulk'
  2017-02-01 03:16:54 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/fluent-plugin-elasticsearch-1.8.0/lib/fluent/plugin/out_elasticsearch.rb:338:in `send_bulk'
  2017-02-01 03:16:54 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/fluent-plugin-elasticsearch-1.8.0/lib/fluent/plugin/out_elasticsearch.rb:322:in `write'
  2017-02-01 03:16:54 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.29/lib/fluent/buffer.rb:354:in `write_chunk'
  2017-02-01 03:16:54 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.29/lib/fluent/buffer.rb:333:in `pop'
  2017-02-01 03:16:54 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.29/lib/fluent/output.rb:338:in `try_flush'
  2017-02-01 03:16:54 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.29/lib/fluent/output.rb:149:in `run'
2017-02-01 03:16:54 +0000 fluent.warn: {"next_retry":"2017-02-01 03:16:55 +0000","error_class":"Elasticsearch::Transport::Transport::Error","error":"Cannot get new connection from pool.","plugin_id":"output_docker1","message":"temporarily failed to flush the buffer. next_retry=2017-02-01 03:16:55 +0000 error_class=\"Elasticsearch::Transport::Transport::Error\" error=\"Cannot get new connection from pool.\" plugin_id=\"output_docker1\""}
```
Is this a problem with fluentd itself or elasticsearch plugin or one of the gems ?
Can the following parameters improve the situation ?
```
request_timeout
reconnect_on_error
reload_on_failure
```

**Comment by zerthimon** [comment]
reconnect_on_error true helped - I don't have to restart fluent anymore.
However, it's still looks that there is a bug in connection pool code somewhere....

```
2017-02-05 04:23:12 +0000 fluent.warn: {"next_retry":"2017-02-05 04:23:13 +0000","error_class":"Elasticsearch::Transport::Transport::Error","error":"Cannot get new connection from pool.","plugin_id":"output_docker1","message":"temporarily failed to flush the buffer. next_retry=2017-02-05 04:23:13 +0000 error_class=\"Elasticsearch::Transport::Transport::Error\" error=\"Cannot get new connection from pool.\" plugin_id=\"output_docker1\""}
2017-02-05 04:23:12 +0000 [warn]: no patterns matched tag="fluent.warn"
2017-02-05 04:23:13 +0000 [info]: Connection opened to Elasticsearch cluster => {:host=>"138.201.19.49", :port=>9200, :scheme=>"http"}
2017-02-05 04:23:13 +0000 [warn]: retry succeeded. plugin_id="output_docker1"
2017-02-05 04:23:13 +0000 fluent.info: {"message":"Connection opened to Elasticsearch cluster => {:host=>\"138.201.19.49\", :port=>9200, :scheme=>\"http\"}"}
2017-02-05 04:23:13 +0000 fluent.warn: {"plugin_id":"output_docker1","message":"retry succeeded. plugin_id=\"output_docker1\""}
2017-02-05 18:16:39 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2017-02-05 18:16:40 +0000 error_class="Elasticsearch::Transport::Transport::Error" error="Cannot get new connection from pool." plugin_id="output_docker1"
  2017-02-05 18:16:39 +0000 [warn]: suppressed same stacktrace
2017-02-05 18:16:39 +0000 fluent.warn: {"next_retry":"2017-02-05 18:16:40 +0000","error_class":"Elasticsearch::Transport::Transport::Error","error":"Cannot get new connection from pool.","plugin_id":"output_docker1","message":"temporarily failed to flush the buffer. next_retry=2017-02-05 18:16:40 +0000 error_class=\"Elasticsearch::Transport::Transport::Error\" error=\"Cannot get new connection from pool.\" plugin_id=\"output_docker1\""}
2017-02-05 18:16:40 +0000 [info]: Connection opened to Elasticsearch cluster => {:host=>"138.201.19.49", :port=>9200, :scheme=>"http"}
2017-02-05 18:16:40 +0000 [warn]: retry succeeded. plugin_id="output_docker1"
2017-02-05 18:16:40 +0000 fluent.info: {"message":"Connection opened to Elasticsearch cluster => {:host=>\"138.201.19.49\", :port=>9200, :scheme=>\"http\"}"}
2017-02-05 18:16:40 +0000 fluent.warn: {"plugin_id":"output_docker1","message":"retry succeeded. plugin_id=\"output_docker1\""}
2017-02-06 08:10:14 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2017-02-06 08:10:15 +0000 error_class="Elasticsearch::Transport::Transport::Error" error="Cannot get new connection from pool." plugin_id="output_docker1"
  2017-02-06 08:10:14 +0000 [warn]: suppressed same stacktrace
2017-02-06 08:10:14 +0000 fluent.warn: {"next_retry":"2017-02-06 08:10:15 +0000","error_class":"Elasticsearch::Transport::Transport::Error","error":"Cannot get new connection from pool.","plugin_id":"output_docker1","message":"temporarily failed to flush the buffer. next_retry=2017-02-06 08:10:15 +0000 error_class=\"Elasticsearch::Transport::Transport::Error\" error=\"Cannot get new connection from pool.\" plugin_id=\"output_docker1\""}
2017-02-06 08:10:15 +0000 [info]: Connection opened to Elasticsearch cluster => {:host=>"138.201.19.49", :port=>9200, :scheme=>"http"}
2017-02-06 08:10:15 +0000 [warn]: retry succeeded. plugin_id="output_docker1"
2017-02-06 08:10:15 +0000 fluent.info: {"message":"Connection opened to Elasticsearch cluster => {:host=>\"138.201.19.49\", :port=>9200, :scheme=>\"http\"}"}
2017-02-06 08:10:15 +0000 fluent.warn: {"plugin_id":"output_docker1","message":"retry succeeded. plugin_id=\"output_docker1\""}
2017-02-06 08:10:15 +0000 [warn]: no patterns matched tag="fluent.warn"
```

**Comment by cemo** [comment]
We hit the same error. 

```2017-05-11 22:12:49 +0000 [info]: Connection opened to Elasticsearch cluster => {:host=>"elasticsearch-logging", :port=>9200, :scheme=>"http"}
2017-05-12 04:51:12 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2017-05-12 04:51:13 +0000 error_class="Elasticsearch::Transport::Transport::Error" error="Cannot get new connection from po
ol." plugin_id="object:3fb8c8415954"
  2017-05-12 04:51:12 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/elasticsearch-transport-1.0.18/lib/elasticsearch/transport/transport/base.rb:249:in `perform_request'
  2017-05-12 04:51:12 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/elasticsearch-transport-1.0.18/lib/elasticsearch/transport/transport/http/faraday.rb:20:in `perform_request'
  2017-05-12 04:51:12 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/elasticsearch-transport-1.0.18/lib/elasticsearch/transport/client.rb:128:in `perform_request'
  2017-05-12 04:51:12 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/elasticsearch-api-1.0.18/lib/elasticsearch/api/actions/bulk.rb:90:in `bulk'
  2017-05-12 04:51:12 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-elasticsearch-1.9.2/lib/fluent/plugin/out_elasticsearch.rb:353:in `send_bulk'
  2017-05-12 04:51:12 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-elasticsearch-1.9.2/lib/fluent/plugin/out_elasticsearch.rb:339:in `write_objects'
  2017-05-12 04:51:12 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.31/lib/fluent/output.rb:490:in `write'
  2017-05-12 04:51:12 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.31/lib/fluent/buffer.rb:354:in `write_chunk'
  2017-05-12 04:51:12 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.31/lib/fluent/buffer.rb:333:in `pop'
  2017-05-12 04:51:12 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.31/lib/fluent/output.rb:342:in `try_flush'
  2017-05-12 04:51:12 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.31/lib/fluent/output.rb:149:in `run'
2017-05-12 04:51:13 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2017-05-12 04:51:14 +0000 error_class="Elasticsearch::Transport::Transport::Error" error="Cannot get new connection from po
ol." plugin_id="object:3fb8c8415954"
```

**Comment by monotone** [comment]
look this, https://discuss.elastic.co/t/elasitcsearch-ruby-raises-cannot-get-new-connection-from-pool-error/36252/3    . it seems add `resurrect_after` will fix it.

**Comment by cosmo0920** [comment]
It seems that `reconnect_on_error true` should be helpful: https://github.com/uken/fluent-plugin-elasticsearch/issues/237#issuecomment-277650421
