### ISSUE TITLE
plugin is throwing error when trying to configure it with index template

### ISSUE THREAD

**Issue by paragradke** [uken/fluent-plugin-elasticsearch#242]
#### Problem

When I am trying to configure a elasticsearch index template. I am getting this error.

```log
2017-02-14 09:11:12 +0000 [warn]: 'ack_timeout_ms' parameter is deprecated. Use second unit 'ack_timeout' instead
2017-02-14 09:11:12 +0000 [info]: Connection opened to Elasticsearch cluster => {:host=>"elasticsearch", :port=>9200, :scheme=>"https"}
**2017-02-14 09:11:12 +0000 [error]: unexpected error error="If you specify a template_name you must specify a valid template file (checked '/home/fluent/index_template_sc.json')!"**
  2017-02-14 09:11:12 +0000 [error]: /usr/lib/ruby/gems/2.3.0/gems/fluent-plugin-elasticsearch-1.9.2/lib/fluent/plugin/elasticsearch_index_template.rb:5:in `get_template'
  2017-02-14 09:11:12 +0000 [error]: /usr/lib/ruby/gems/2.3.0/gems/fluent-plugin-elasticsearch-1.9.2/lib/fluent/plugin/elasticsearch_index_template.rb:24:in `template_install' 
```

####  example config

```aconf
# ...
  <store ignore_error>
    type elasticsearch
    host elasticsearch
    port 9200
    scheme https
    ssl_verify false
    logstash_format true
    logstash_prefix sc_business_event
    utc_index false
    template_name sc_business_event_template
    template_file /home/fluent/index_template_sc.json
    flush_interval 5s
    request_timeout 30s
    reconnect_on_error true
  </store>
# ...
</match>

<match **>
  @type stdout
</match>`
```

As per the code block 

```ruby
    if !File.exists?(template_file)
      raise "If you specify a template_name you must specify a valid template file (checked '#{template_file}')!"
    end
# …
```

it raise this error when it's not able to locate template file.The file is there and the file path is correct and the owner is also fluentd user

```bash
>~ $ ls
index_template_re.json  index_template_sc.json
~ $ pwd
/home/fluent
~ $ ls -la
total 16
drwxr-sr-x    2 fluent   fluent         107 Feb 14 09:06 .
drwxr-xr-x    3 root     root            20 Jan 31 04:26 ..
-rw-------    1 fluent   fluent          14 Feb 14 09:06 .ash_history
-rw-r--r--    1 fluent   fluent          34 Jan 31 04:26 .gemrc
-rw-r--r--    1 root     root          1703 Feb 14 09:03 index_template_re.json
-rw-r--r--    1 root     root          1694 Feb 14 09:03  index_template_sc.json
~ $ ls /home/fluent/index_template_re.json
/home/fluent/index_template_re.json
```

**Comment by cosmo0920** [comment]
Could you try ES plugin 2.4.0 or 1.11.0?
Your log does not have enough error messages.

**Comment by cosmo0920** [comment]
From error message, it seems that you specify invalid template.
I'm closing this issue due to no response.

**Comment by ncepuwanghui** [comment]
![image](https://user-images.githubusercontent.com/6895399/75608416-2bd79180-5b3a-11ea-89bf-021ef64577fd.png)
As shown in the FIG, the name ` index_template_sc.json` has an extra space.
