### ISSUE TITLE
Fluentd seems to crash when sending a template to an unavailable ES cluster

### ISSUE THREAD

**Issue by FlorentGuillin** [uken/fluent-plugin-elasticsearch#243]
#### Problem

I am using FluentD to send data on a free trial of Elastic Cloud and it seems that FluentD can crash during a template creation when the cluster is unavailable (due to the limit of the trial cluster config and the amount of data that I am sending). I let my fluentd config to help you identify if it's the effect of it or if it's an unknown bug (missing recover/error handling?)

#### Steps to replicate

Logs: 

```
2017-02-20 16:05:48 +0000 [info]: starting fluentd-0.12.31
2017-02-20 16:05:48 +0000 [info]: gem 'fluent-mixin-config-placeholders' version '0.4.0'
2017-02-20 16:05:48 +0000 [info]: gem 'fluent-mixin-plaintextformatter' version '0.2.6'
2017-02-20 16:05:48 +0000 [info]: gem 'fluent-plugin-elasticsearch' version '1.9.2'
2017-02-20 16:05:48 +0000 [info]: gem 'fluent-plugin-influxdb' version '0.3.2'
2017-02-20 16:05:48 +0000 [info]: gem 'fluent-plugin-kafka' version '0.4.1'
2017-02-20 16:05:48 +0000 [info]: gem 'fluent-plugin-mongo' version '0.7.16'
2017-02-20 16:05:48 +0000 [info]: gem 'fluent-plugin-rewrite-tag-filter' version '1.5.5'
2017-02-20 16:05:48 +0000 [info]: gem 'fluent-plugin-s3' version '0.8.0'
2017-02-20 16:05:48 +0000 [info]: gem 'fluent-plugin-scribe' version '0.10.14'
2017-02-20 16:05:48 +0000 [info]: gem 'fluent-plugin-td' version '0.10.29'
2017-02-20 16:05:48 +0000 [info]: gem 'fluent-plugin-td-monitoring' version '0.2.2'
2017-02-20 16:05:48 +0000 [info]: gem 'fluent-plugin-webhdfs' version '0.4.2'
2017-02-20 16:05:48 +0000 [info]: gem 'fluentd' version '0.12.31'
2017-02-20 16:05:48 +0000 [info]: adding match pattern="td.*.*" type="tdlog"
2017-02-20 16:05:48 +0000 [info]: adding match pattern="debug.**" type="stdout"
2017-02-20 16:05:48 +0000 [info]: adding match pattern="logs.app_platform_logs" type="elasticsearch"
2017-02-20 16:05:48 +0000 [error]: unexpected error error="[502] "
  2017-02-20 16:05:48 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/elasticsearch-transport-1.0.18/lib/elasticsearch/transport/transport/base.rb:201:in `__raise_transport_error'
  2017-02-20 16:05:48 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/elasticsearch-transport-1.0.18/lib/elasticsearch/transport/transport/base.rb:312:in `perform_request'
  2017-02-20 16:05:48 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/elasticsearch-transport-1.0.18/lib/elasticsearch/transport/transport/http/faraday.rb:20:in `perform_request'
  2017-02-20 16:05:48 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/elasticsearch-transport-1.0.18/lib/elasticsearch/transport/client.rb:128:in `perform_request'
  2017-02-20 16:05:48 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/elasticsearch-api-1.0.18/lib/elasticsearch/api/actions/ping.rb:20:in `ping'
  2017-02-20 16:05:48 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-elasticsearch-1.9.2/lib/fluent/plugin/out_elasticsearch.rb:160:in `client'
  2017-02-20 16:05:48 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-elasticsearch-1.9.2/lib/fluent/plugin/elasticsearch_index_template.rb:12:in `template_exists?'
  2017-02-20 16:05:48 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-elasticsearch-1.9.2/lib/fluent/plugin/elasticsearch_index_template.rb:23:in `template_install'
  2017-02-20 16:05:48 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-elasticsearch-1.9.2/lib/fluent/plugin/out_elasticsearch.rb:91:in `configure'
  2017-02-20 16:05:48 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.31/lib/fluent/agent.rb:133:in `add_match'
  2017-02-20 16:05:48 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.31/lib/fluent/agent.rb:64:in `block in configure'
  2017-02-20 16:05:48 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.31/lib/fluent/agent.rb:57:in `each'
  2017-02-20 16:05:48 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.31/lib/fluent/agent.rb:57:in `configure'
  2017-02-20 16:05:48 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.31/lib/fluent/root_agent.rb:86:in `configure'
  2017-02-20 16:05:48 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.31/lib/fluent/engine.rb:129:in `configure'
  2017-02-20 16:05:48 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.31/lib/fluent/engine.rb:103:in `run_configure'
  2017-02-20 16:05:48 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.31/lib/fluent/supervisor.rb:489:in `run_configure'
  2017-02-20 16:05:48 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.31/lib/fluent/supervisor.rb:160:in `block in start'
  2017-02-20 16:05:48 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.31/lib/fluent/supervisor.rb:366:in `call'
  2017-02-20 16:05:48 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.31/lib/fluent/supervisor.rb:366:in `main_process'
  2017-02-20 16:05:48 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.31/lib/fluent/supervisor.rb:339:in `block in supervise'
  2017-02-20 16:05:48 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.31/lib/fluent/supervisor.rb:338:in `fork'
  2017-02-20 16:05:48 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.31/lib/fluent/supervisor.rb:338:in `supervise'
  2017-02-20 16:05:48 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.31/lib/fluent/supervisor.rb:156:in `start'
  2017-02-20 16:05:48 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.31/lib/fluent/command/fluentd.rb:173:in `<top (required)>'
  2017-02-20 16:05:48 +0000 [error]: /opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
  2017-02-20 16:05:48 +0000 [error]: /opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
  2017-02-20 16:05:48 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.31/bin/fluentd:5:in `<top (required)>'
  2017-02-20 16:05:48 +0000 [error]: /opt/td-agent/embedded/bin/fluentd:23:in `load'
  2017-02-20 16:05:48 +0000 [error]: /opt/td-agent/embedded/bin/fluentd:23:in `<top (required)>'
  2017-02-20 16:05:48 +0000 [error]: /usr/sbin/td-agent:7:in `load'
  2017-02-20 16:05:48 +0000 [error]: /usr/sbin/td-agent:7:in `<main>'
2017-02-20 16:05:48 +0000 [info]: process finished code=256
2017-02-20 16:05:48 +0000 [warn]: process died within 1 second. exit.
```

fluent config: 

```
<source>
 @type tail
 path /syslog-logs/*/app-platform.log
 pos_file /etc/td-agent/tail_pos_file/app-platform.pos
 tag logs.app_platform_logs
 format /^(?<syslog_writetime>[a-zA-Z]{3} ( [0-9]{1}|[0-9]{2}) [^ ]*) (?<log_host_origin>[^ ]*) (?<log_tag>[^ ]*) \[[^ ]* (?<host_writetime>[^\]]*)\] (?<msg>.*)$/
 read_from_head true
</source>

<match logs.app_platform_logs>
  type elasticsearch
  host XXXXX.eu-west-1.aws.found.io
  port 9243
  scheme https
  user "XXXXX"
  password "XXXXX"
  ssl_verify false
  logstash_format true
  logstash_prefix app_platform
  type_name logs
  time_key host_writetime
  time_key_format "%b %e %H:%M:%S %Y"
  time_key_exclude_timestamp false
  template_name "app_platform"
  template_file "/etc/td-agent/es-mapping-templates/app_platform"

  #buffer config
  buffer_type memory
  buffer_chunk_limit 100m #should not exceed http.max_content_length of Elasticsetup which is 100mb by default
  buffer_queue_limit 128
  flush_interval 1s
  disable_retry_limit true
  retry_limit 20 #only used if disable_retry_limit is set to false
  retry_wait 60s #Value will double each time until max_retry_wait is reached
  max_retry_wait 1800s
  buffer_queue_full_action exception #see http://docs.fluentd.org/v0.12/articles/buffer-plugin-overview#bufferqueuefullaction for different behaviors
</match>
```

**Comment by cosmo0920** [comment]
Related to #105?

**Comment by cosmo0920** [comment]
This crash is caused in `#configure` phase.

Detail:

`#configure` -> `#template_install` -> `#template_exists?` -> crash!!!

Adding error handling in `#configure` phase looks not good for me.
Because `#configure` should prune bad states before actual running.

The following patch should solve Fluentd crash in your environment?

```diff
diff --git a/lib/fluent/plugin/elasticsearch_index_template.rb b/lib/fluent/plug
in/elasticsearch_index_template.rb
index f31e92c..ee5c848 100644
--- a/lib/fluent/plugin/elasticsearch_index_template.rb
+++ b/lib/fluent/plugin/elasticsearch_index_template.rb
@@ -11,6 +11,8 @@ module Fluent::ElasticsearchIndexTemplate
   def template_exists?(name)
     client.indices.get_template(:name => name)
     return true
+  rescue *client.transport.host_unreachable_exceptions => e
+    false
   rescue Elasticsearch::Transport::Transport::Errors::NotFound
     return false
   end
```

**Comment by cosmo0920** [comment]
BadGateway error should not continue configure phase.
Make sure your elasticsearch setting is correct in your config file.
