### ISSUE TITLE
unknown method during chunks sending

### ISSUE THREAD

**Issue by Kuckkuck** [uken/fluent-plugin-elasticsearch#246]
#### Problem
unkown method next time and chunks cannot be send, after switched to grok parsing logs.

my settings:
<match **>
   @type elasticsearch
   host
   port 
   user 
   password
   template_name "logstash"
   template_file "/etc/fluent/fluent-logstash.json"
   time_as_integer false
   @log_level info
   buffer_type "memory"
   buffer_chunk_limit 48m
   buffer_queue_limit 128
   buffer_queue_full_action exception
   flush_interval 1s
   retry_wait 2s
   include_tag_key true
   logstash_format true
   max_retry_wait 30s
   disable_retry_limit
   request_timeout 60s
   reload_connections true
   reload_on_failure true
   resurrect_after 120
   reconnect_on_error true
   num_threads 4
 </match>
...

#### Steps to replicate
2017-03-17 08:53:30 +0000 [warn]: #0 failed to flush the buffer. retry_time=0 next_retry_seconds=2017-03-17 08:53:31 +0000 chunk="54ae94d6a43402b6774c0bda78305a6b" error_class=Elasticsearch::Transport::Transport::Errors::ServiceUnavailable error="[503] {\"error\":{\"root_cause\":[{\"type\":\"circuit_breaking_exception\",\"reason\":\"[parent] Data too large, data for [<http_request>] would be larger than limit of [7265668300/6.7gb]\",\"bytes_wanted\":7267069945,\"bytes_limit\":7265668300}],\"type\":\"circuit_breaking_exception\",\"reason\":\"[parent] Data too large, data for [<http_request>] would be larger than limit of [7265668300/6.7gb]\",\"bytes_wanted\":7267069945,\"bytes_limit\":7265668300},\"status\":503}"
  2017-03-17 08:53:30 +0000 [warn]: #0 suppressed same stacktrace
2017-03-17 08:53:30 +0000 [warn]: #0 retry succeeded. chunk_id="54ae94fb854eb4bb19094389d484ff91"
2017-03-17 08:53:30 +0000 [error]: #0 error on output thread error_class=NoMethodError error="undefined method `next_time' for nil:NilClass"
  2017-03-17 08:53:30 +0000 [error]: #0 /var/lib/gems/2.3.0/gems/fluentd-0.14.12/lib/fluent/plugin/output.rb:1242:in `block in flush_thread_run'
  2017-03-17 08:53:30 +0000 [error]: #0 /var/lib/gems/2.3.0/gems/fluentd-0.14.12/lib/fluent/plugin/output.rb:1242:in `synchronize'
2017-03-17 08:53:30 +0000 [error]: #0 error on output thread error_class=NoMethodError error="undefined method `next_time' for nil:NilClass"
2017-03-17 08:53:30 +0000 [error]: #0 error on output thread error_class=NoMethodError error="undefined method `next_time' for nil:NilClass"
  2017-03-17 08:53:30 +0000 [error]: #0 /var/lib/gems/2.3.0/gems/fluentd-0.14.12/lib/fluent/plugin/output.rb:1242:in `block in flush_thread_run'
  2017-03-17 08:53:30 +0000 [error]: #0 /var/lib/gems/2.3.0/gems/fluentd-0.14.12/lib/fluent/plugin/output.rb:1242:in `synchronize'
  2017-03-17 08:53:30 +0000 [error]: #0 /var/lib/gems/2.3.0/gems/fluentd-0.14.12/lib/fluent/plugin/output.rb:1242:in `flush_thread_run'
  2017-03-17 08:53:30 +0000 [error]: #0 /var/lib/gems/2.3.0/gems/fluentd-0.14.12/lib/fluent/plugin/output.rb:401:in `block (2 levels) in start'
  2017-03-17 08:53:30 +0000 [error]: #0 /var/lib/gems/2.3.0/gems/fluentd-0.14.12/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
  2017-03-17 08:53:30 +0000 [error]: #0 /var/lib/gems/2.3.0/gems/fluentd-0.14.12/lib/fluent/plugin/output.rb:1242:in `flush_thread_run'
  2017-03-17 08:53:30 +0000 [error]: #0 /var/lib/gems/2.3.0/gems/fluentd-0.14.12/lib/fluent/plugin/output.rb:401:in `block (2 levels) in start'
  2017-03-17 08:53:30 +0000 [error]: #0 /var/lib/gems/2.3.0/gems/fluentd-0.14.12/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
2017-03-17 08:53:30 +0000 [warn]: #0 thread exited by unexpected error plugin=Fluent::ElasticsearchOutput title=:flush_thread_11 error_class=NoMethodError error="undefined method `next_time' for nil:NilClass"
2017-03-17 08:53:30 +0000 [warn]: #0 thread exited by unexpected error plugin=Fluent::ElasticsearchOutput title=:flush_thread_9 error_class=NoMethodError error="undefined method `next_time' for nil:NilClass"
2017-03-17 08:53:30 +0000 [error]: #0 unexpected error error_class=NoMethodError error="undefined method `next_time' for nil:NilClass"
  2017-03-17 08:53:30 +0000 [error]: #0 /var/lib/gems/2.3.0/gems/fluentd-0.14.12/lib/fluent/plugin/output.rb:1242:in `block in flush_thread_run'
  2017-03-17 08:53:30 +0000 [error]: #0 /var/lib/gems/2.3.0/gems/fluentd-0.14.12/lib/fluent/plugin/output.rb:1242:in `block in flush_thread_run'
  2017-03-17 08:53:30 +0000 [error]: #0 /var/lib/gems/2.3.0/gems/fluentd-0.14.12/lib/fluent/plugin/output.rb:1242:in `synchronize'
  2017-03-17 08:53:30 +0000 [error]: #0 /var/lib/gems/2.3.0/gems/fluentd-0.14.12/lib/fluent/plugin/output.rb:1242:in `flush_thread_run'
  2017-03-17 08:53:30 +0000 [error]: #0 /var/lib/gems/2.3.0/gems/fluentd-0.14.12/lib/fluent/plugin/output.rb:401:in `block (2 levels) in start'
  2017-03-17 08:53:30 +0000 [error]: #0 /var/lib/gems/2.3.0/gems/fluentd-0.14.12/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
  2017-03-17 08:53:30 +0000 [error]: #0 /var/lib/gems/2.3.0/gems/fluentd-0.14.12/lib/fluent/plugin/output.rb:1242:in `synchronize'
  2017-03-17 08:53:30 +0000 [error]: #0 /var/lib/gems/2.3.0/gems/fluentd-0.14.12/lib/fluent/plugin/output.rb:1242:in `flush_thread_run'
  2017-03-17 08:53:30 +0000 [error]: #0 /var/lib/gems/2.3.0/gems/fluentd-0.14.12/lib/fluent/plugin/output.rb:401:in `block (2 levels) in start'
  2017-03-17 08:53:30 +0000 [error]: #0 /var/lib/gems/2.3.0/gems/fluentd-0.14.12/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
2017-03-17 08:53:30 +0000 [error]: #0 unexpected error error_class=NoMethodError error="undefined method `next_time' for nil:NilClass"

**Comment by Kuckkuck** [comment]
btw. it is always the first chunk with the same id, which cannot be send to elasticsearch:

2017-03-17 09:17:00 +0000 [warn]: #0 retry succeeded. chunk_id="54ae99b3d0d00b359902f279df65d026"
2017-03-17 09:17:00 +0000 [warn]: #0 failed to flush the buffer. retry_time=0 next_retry_seconds=2017-03-17 09:17:01 +0000 chunk="54ae99a36a5a1bdbc482b3b598563501" error_class=Elasticsearch::Transport::Transport::Errors::ServiceUnavailable error="[503] {\"error\":{\"root_cause\":[{\"type\":\"circuit_breaking_exception\",\"reason\":\"[parent] Data too large, data for [<http_request>] would be larger than limit of [7265668300/6.7gb]\",\"bytes_wanted\":7267179946,\"bytes_limit\":7265668300}],\"type\":\"circuit_breaking_exception\",\"reason\":\"[parent] Data too large, data for [<http_request>] would be larger than limit of [7265668300/6.7gb]\",\"bytes_wanted\":7267179946,\"bytes_limit\":7265668300},\"status\":503}"
2017-03-17 09:17:00 +0000 [warn]: #0 retry succeeded. chunk_id="54ae99b3d9d332cd8b6b0ad826358d02"
2017-03-17 09:17:01 +0000 [warn]: #0 failed to flush the buffer. retry_time=0 next_retry_seconds=2017-03-17 09:17:02 +0000 chunk="54ae99a36a5a1bdbc482b3b598563501" error_class=Elasticsearch::Transport::Transport::Errors::ServiceUnavailable error="[503] {\"error\":{\"root_cause\":[{\"type\":\"circuit_breaking_exception\",\"reason\":\"[parent] Data too large, data for [<http_request>] would be larger than limit of [7265668300/6.7gb]\",\"bytes_wanted\":7267179946,\"bytes_limit\":7265668300}],\"type\":\"circuit_breaking_exception\",\"reason\":\"[parent] Data too large, data for [<http_request>] would be larger than limit of [7265668300/6.7gb]\",\"bytes_wanted\":7267179946,\"bytes_limit\":7265668300},\"status\":503}"

The the chunks are stored in memory and if the pod is deleted the chunks should be gone. I have no idea, why after a restart the first chunk is too large.
Any idea?

Thanks a lot and regards,

Olaf

**Comment by repeatedly** [comment]
> 2017-03-17 08:53:30 +0000 [error]: #0 error on output thread error_class=NoMethodError error="undefined method next_time' for nil:NilClass" 2017-03-17 08:53:30 +0000 [error]: #0 /var/lib/gems/2.3.0/gems/fluentd-0.14.12/lib/fluent/plugin/output.rb:1242:inblock in flush_thread_run'

It seems a bug of fluentd core. I assume plugin itself is not releated with this message.

**Comment by igorpeshansky** [comment]
> It seems a bug of fluentd core. I assume plugin itself is not releated with this message.

@repeatedly https://github.com/fluent/fluentd/issues/1555 was opened a few days ago and then closed inexplicably by the reporter. Would it make sense to reopen it? We're being affected by the same issue.

**Comment by cosmo0920** [comment]
@Kuckkuck Could you try Fluentd v0.14.19 or later to confirm to be fixed or not to be.

**Comment by Kuckkuck** [comment]
yes it's working. All my fluentd nodes are on 0.14.20. Fixed since 0.14.19.
