### ISSUE TITLE
Data too large exception

### ISSUE THREAD

**Issue by jklap** [uken/fluent-plugin-elasticsearch#251]
In testing today (and pushing through a large number of logs to fluentd) I'd started to get the following error from Elastic:

```
2017-04-13 14:23:49 -0400 [warn]: temporarily failed to flush the buffer. next_retry=2017-04-13 14:23:48 -0400 error_class="Elasticsearch::Transport::Transport::Errors::ServiceUnavailable" error="[503] {\"error\":{\"root_cause\":[{\"type\":\"circuit_breaking_exception\",\"reason\":\"[parent] Data too large, data for [<http_request>] would be larger than limit of [2242655027/2gb]\",\"bytes_wanted\":2267000752,\"bytes_limit\":2242655027}],\"type\":\"circuit_breaking_exception\",\"reason\":\"[parent] Data too large, data for [<http_request>] would be larger than limit of [2242655027/2gb]\",\"bytes_wanted\":2267000752,\"bytes_limit\":2242655027},\"status\":503}" plugin_id="catchall-elastic-access"
```

Stack trace:

```
2017-04-13 14:23:50 -0400 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/elasticsearch-transport-5.0.3/lib/elasticsearch/transport/transport/base.rb:201:in `__raise_transport_error'
2017-04-13 14:23:50 -0400 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/elasticsearch-transport-5.0.3/lib/elasticsearch/transport/transport/base.rb:318:in `perform_request'
2017-04-13 14:23:50 -0400 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/elasticsearch-transport-5.0.3/lib/elasticsearch/transport/transport/http/faraday.rb:20:in `perform_request'
2017-04-13 14:23:50 -0400 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/elasticsearch-transport-5.0.3/lib/elasticsearch/transport/client.rb:131:in `perform_request'
2017-04-13 14:23:50 -0400 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/elasticsearch-api-5.0.3/lib/elasticsearch/api/actions/bulk.rb:95:in `bulk'
2017-04-13 14:23:50 -0400 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-elasticsearch-1.9.2/lib/fluent/plugin/out_elasticsearch.rb:353:in `send_bulk'
2017-04-13 14:23:50 -0400 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-elasticsearch-1.9.2/lib/fluent/plugin/out_elasticsearch.rb:339:in `write_objects'
2017-04-13 14:23:50 -0400 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.31/lib/fluent/output.rb:490:in `write'
2017-04-13 14:23:50 -0400 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.31/lib/fluent/buffer.rb:354:in `write_chunk'
2017-04-13 14:23:50 -0400 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.31/lib/fluent/buffer.rb:333:in `pop'
2017-04-13 14:23:50 -0400 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.31/lib/fluent/output.rb:342:in `try_flush'
2017-04-13 14:23:50 -0400 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.31/lib/fluent/output.rb:149:in `run'
```

I'm currently using the elasticsearch plugin with forest as such:

```
<match **>
   @id catchall-elastic
   @type forest
   subtype elasticsearch
   <template>
      @id catchall-elastic-${tag}
      logstash_format true
      reconnect_on_error true
      type_name ${tag_parts[0]}
      include_tag_key true
      buffer_type memory
      buffer_chunk_limit 20m
   </template>
</match>
```

Looking at the fluentd stats, I see the following for this plugin:

```
"buffer_queue_length": 11,
"buffer_total_queued_size": 197320091,
```

Obviously a large amount of data buffered in fluentd, but from what I understand, fluentd is pushing 20m (max) buffers into the elasticsearch plugin which is then pushing them into Elastic.

So how is it we are hitting the 2G circuit break in Elastic?

Is this an issue with Elastic, fluentd or this plugin?

**Comment by jklap** [comment]
I'm pretty sure after additional testing this is an Elastic issue (we are running 5.2.2). The request breaker continues to grow in size and doesn't shrink. Will open a ticket there.

**Comment by jklap** [comment]
I've narrowed down the problem to an issue with Elastic (or presumed issue until they tell me otherwise :)

It seems to have to do with the bulk import request's connection being abruptly closed (see https://github.com/elastic/elasticsearch/issues/24113).

Note that the impact to users here is that if you are seeing connection issues from the elastic plugin you may run into this issue.

ie issues like this may contribute:
```
Could not push logs to Elasticsearch, resetting connection and trying again. read timeout reached
```

In which case it may help to tune to an appropriate value:
```
request_timeout 20s
````
