### ISSUE TITLE
Failed to flush the buffer on Fluentd 0.14.14

### ISSUE THREAD

**Issue by anthonyhaussman** [uken/fluent-plugin-elasticsearch#252]
#### Problem

It seems that the fluent-plugin-elasticsearch with Fluentd 0.14.14 has some problem.
I have a lot of problem of buffer management and the foward to es stop.

#### Steps to replicate

Here is the configuration that I use:

```
<source>
  @type forward
  port 24224
</source>

<source>
  @type monitor_agent
  bind 0.0.0.0
  port 24220
</source>

<match fluent.**>
  @type null
</match>

<match **>
  @type elasticsearch
  <buffer>
    @type file
    path /data/fluent/queue_log.*.buffer
    compress gzip
    chunk_limit_size 16m  # 16MB compressed events
    flush_interval 60s
    flush_at_shutdown true
    retry_wait 1s
    flush_interval 1s
    disable_retry_limit true
    retry_limit 20 #only used if disable_retry_limit is set to false
    retry_wait 60s #Value will double each time until max_retry_wait is reached
    max_retry_wait 1800s
    buffer_queue_full_action exception
  </buffer>
  hosts es-01.toto.com:9200,es-02.toto.com:9200,es-03.toto.com:9200
  user plop
  password plip
  ssl_verify false
  logstash_format true
  logstash_prefix logstash
  logstash_dateformat %Y.%m.%d
  request_timeout 15s
  reload_connections true
  reload_on_failure true # defaults to false, can be useful to quickly remove a dead node from the list of addresses
  resurrect_after 30 # defaults to 60s
  reconnect_on_error true
</match>
```

At the start, some buffer option does not work:
```
2017-04-23 15:57:34 +0000 [warn]: parameter 'disable_retry_limit' in <buffer>
  @type "file"
  path "/data/fluent/queue_log.*.buffer"
  compress gzip
  chunk_limit_size 16m
  flush_interval 1s
  flush_at_shutdown true
  retry_wait 60s
  disable_retry_limit true
  retry_limit 20
  max_retry_wait 1800s
  buffer_queue_full_action exception
</buffer> is not used.
2017-04-23 15:57:34 +0000 [warn]: parameter 'retry_limit' in <buffer>
  @type "file"
  path "/data/fluent/queue_log.*.buffer"
  compress gzip
  chunk_limit_size 16m
  flush_interval 1s
  flush_at_shutdown true
  retry_wait 60s
  disable_retry_limit true
  retry_limit 20
  max_retry_wait 1800s
  buffer_queue_full_action exception
</buffer> is not used.
2017-04-23 15:57:34 +0000 [warn]: parameter 'max_retry_wait' in <buffer>
  @type "file"
  path "/data/fluent/queue_log.*.buffer"
  compress gzip
  chunk_limit_size 16m
  flush_interval 1s
  flush_at_shutdown true
  retry_wait 60s
  disable_retry_limit true
  retry_limit 20
  max_retry_wait 1800s
  buffer_queue_full_action exception
</buffer> is not used.
2017-04-23 15:57:34 +0000 [warn]: parameter 'buffer_queue_full_action' in <buffer>
  @type "file"
  path "/data/fluent/queue_log.*.buffer"
  compress gzip
  chunk_limit_size 16m
  flush_interval 1s
  flush_at_shutdown true
  retry_wait 60s
  disable_retry_limit true
  retry_limit 20
  max_retry_wait 1800s
  buffer_queue_full_action exception
</buffer> is not used.
```

And after some restart, buffer can't be flushed:
```
2017-04-23 15:57:34 +0000 [info]: #0 starting fluentd worker pid=10069 ppid=10015 worker=0
2017-04-23 15:57:34 +0000 [info]: #0 listening port port=24224 bind="0.0.0.0"
2017-04-23 15:57:34 +0000 [info]: #0 fluentd worker is now running worker=0
2017-04-23 15:57:34 +0000 [warn]: #0 failed to flush the buffer. retry_time=0 next_retry_seconds=2017-04-23 15:58:34 +0000 chunk="54dd76bbc85ddeeb1c7fe4a4de7a21e0" error_class=MessagePack::UnknownExtTypeError error="unexpected extension type"
  2017-04-23 15:57:34 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluentd-0.14.14/lib/fluent/event.rb:323:in `each'
  2017-04-23 15:57:34 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluentd-0.14.14/lib/fluent/event.rb:323:in `block in each'
  2017-04-23 15:57:34 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluentd-0.14.14/lib/fluent/plugin/buffer/file_chunk.rb:170:in `open'
  2017-04-23 15:57:34 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluentd-0.14.14/lib/fluent/event.rb:322:in `each'
  2017-04-23 15:57:34 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluent-plugin-elasticsearch-1.9.3/lib/fluent/plugin/out_elasticsearch.rb:282:in `write_objects'
  2017-04-23 15:57:34 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluentd-0.14.14/lib/fluent/compat/output.rb:524:in `write'
  2017-04-23 15:57:34 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluentd-0.14.14/lib/fluent/compat/output.rb:131:in `write'
  2017-04-23 15:57:34 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluentd-0.14.14/lib/fluent/plugin/output.rb:1038:in `try_flush'
  2017-04-23 15:57:34 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluentd-0.14.14/lib/fluent/plugin/output.rb:1263:in `flush_thread_run'
  2017-04-23 15:57:34 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluentd-0.14.14/lib/fluent/plugin/output.rb:415:in `block (2 levels) in start'
  2017-04-23 15:57:34 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluentd-0.14.14/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
2017-04-23 15:58:34 +0000 [warn]: #0 failed to flush the buffer. retry_time=0 next_retry_seconds=2017-04-23 15:58:34 +0000 chunk="54dd76bbc85ddeeb1c7fe4a4de7a21e0" error_class=MessagePack::UnknownExtTypeError error="unexpected extension type"
  2017-04-23 15:58:34 +0000 [warn]: #0 suppressed same stacktrace
2017-04-23 15:59:27 +0000 [warn]: #0 failed to flush the buffer. retry_time=1 next_retry_seconds=2017-04-23 15:59:27 +0000 chunk="54dd76bbc85ddeeb1c7fe4a4de7a21e0" error_class=MessagePack::UnknownExtTypeError error="unexpected extension type"
  2017-04-23 15:59:27 +0000 [warn]: #0 suppressed same stacktrace
2017-04-23 16:01:25 +0000 [warn]: #0 failed to flush the buffer. retry_time=2 next_retry_seconds=2017-04-23 16:01:25 +0000 chunk="54dd76bbc85ddeeb1c7fe4a4de7a21e0" error_class=MessagePack::UnknownExtTypeError error="unexpected extension type"
  2017-04-23 16:01:25 +0000 [warn]: #0 suppressed same stacktrace
```

**Comment by anthonyhaussman** [comment]
I close the ticket.
My bad, I have managed to write a better buffer configuration.
If someone need my conf:
```
<source>
  @type forward
  port 24224
</source>

<source>
  @type monitor_agent
  bind 0.0.0.0
  port 24220
</source>

<match fluent.**>
  @type null
</match>

<match **>
  @type elasticsearch

  # Buffering
  buffer_type file
  buffer_chunk_limit 32m
  buffer_queue_limit 8192
  num_threads 4
  retry_limit 5
  retry_wait 1s
  flush_at_shutdown true
  <buffer>
    @type file
    path /data/fluent/queue_log.*.buffer
    compress gzip
    chunk_limit_size 32m  # 32MB compressed events
    total_limit_size 250g
    flush_interval 60s
    flush_at_shutdown true
    flush_thread_count 4
    retry_max_times 10
    retry_wait 1s
  </buffer

  # ElasticSearch
  hosts es-01.toto.com:9200,es-02.toto.com:9200,es-03.toto.com:9200
  user plop
  password plip
  ssl_verify false
  logstash_format true
  logstash_prefix logstash
  logstash_dateformat %Y.%m.%d
  request_timeout 15s
  reload_connections true
  reload_on_failure true # defaults to false, can be useful to quickly remove a dead node from the list of addresses
  resurrect_after 30 # defaults to 60s
  reconnect_on_error true
</match>
```
