### ISSUE TITLE
plugin does not work with file buffer

### ISSUE THREAD

**Issue by portante** [uken/fluent-plugin-elasticsearch#260]
#### Problem
When using a `file` buffer, we get the error:

```
emit transaction failed: error_class=Encoding::UndefinedConversionError error="\"\\x93\" from ASCII-8BIT to UTF-8" tag="final.greped.nova.compute"
```

fluentd v0.12.29
Ruby 2.0.0
RHEL 7.4 Beta
...

#### Steps to replicate

```
[root@perf34 fluentd]# /usr/bin/fluentd -c /etc/fluentd/fluent.conf
2017-06-02 17:34:03 +0000 [info]: reading config file path="/etc/fluentd/fluent.conf"
2017-06-02 17:34:03 +0000 [info]: starting fluentd-0.12.29
2017-06-02 17:34:03 +0000 [info]: gem 'fluent-mixin-config-placeholders' version '0.3.0'
2017-06-02 17:34:03 +0000 [info]: gem 'fluent-plugin-elasticsearch' version '0.8.0'
2017-06-02 17:34:03 +0000 [info]: gem 'fluent-plugin-record-modifier' version '0.3.0'
2017-06-02 17:34:03 +0000 [info]: gem 'fluentd' version '0.12.29'
2017-06-02 17:34:03 +0000 [info]: adding filter pattern="greped.*.** final.*.**" type="record_transformer"
2017-06-02 17:34:03 +0000 [info]: adding filter pattern="fluent.**" type="record_transformer"
2017-06-02 17:34:03 +0000 [info]: adding filter pattern="fluent.** greped.*.** final.*.**" type="record_transformer"
2017-06-02 17:34:03 +0000 [info]: adding filter pattern="kubernetes.pods.** kubernetes.services.** kubernetes.endpoints.** kubernetes.namespaces.**" type="record_transformer"
2017-06-02 17:34:03 +0000 [info]: adding filter pattern="kubernetes.events.**" type="record_transformer"
2017-06-02 17:34:03 +0000 [info]: adding filter pattern="**" type="record_transformer"
2017-06-02 17:34:03 +0000 [info]: adding match pattern="*.**" type="elasticsearch"
2017-06-02 17:34:03 +0000 [info]: adding source type="forward"
2017-06-02 17:34:03 +0000 [info]: using configuration file: <ROOT>
  <source>
    @type forward
    bind 0.0.0.0
    port 4000
  </source>
  <filter greped.*.** final.*.**>
    @type record_transformer
    enable_ruby
    remove_keys loglevel
    <record>
      level ${loglevel}
    </record>
  </filter>
  <filter fluent.**>
    @type record_transformer
    enable_ruby
    <record>
      level ${tag_parts[1] == "warn" ? "warning" : tag_parts[1] == "error" ? "err" : tag_parts[1] == "fatal" ? "crit" : tag_parts[1]}
    </record>
  </filter>
  <filter fluent.** greped.*.** final.*.**>
    @type record_transformer
    enable_ruby
    <record>
      level ${level == "ERROR" ? "err" : level == "CRITICAL" ? "crit" : level.downcase}
    </record>
  </filter>
  <filter kubernetes.pods.** kubernetes.services.** kubernetes.endpoints.** kubernetes.namespaces.**>
    @type record_transformer
    <record>
      level info
    </record>
  </filter>
  <filter kubernetes.events.**>
    @type record_transformer
    enable_ruby
    <record>
      level ${record['type'] == "Warning" ? "warning" : "info" }
    </record>
  </filter>
  <filter **>
    @type record_transformer
    enable_ruby
    <record>
      fluentd:received_at ${Time.now.utc.strftime("%Y-%m-%dT%H:%M:%S.%6N")}
    </record>
  </filter>
  <match *.**>
    @type elasticsearch
    hosts 192.168.10.44:9200
    logstash_format true
    include_tag_key true
    tag_key fluentd:tag
    flush_interval 1s
    request_timeout 120s
    buffer_type file
    buffer_path /srv/data/fluentd/buffer/
    buffer_chunk_limit 1m
    buffer_queue_limit 2048
  </match>
</ROOT>
2017-06-02 17:34:03 +0000 [info]: listening fluent socket on 0.0.0.0:4000
2017-06-02 17:34:16 +0000 [warn]: emit transaction failed: error_class=Encoding::UndefinedConversionError error="\"\\x93\" from ASCII-8BIT to UTF-8" tag="final.greped.nova.compute"
  2017-06-02 17:34:16 +0000 [warn]: /usr/share/gems/gems/fluentd-0.12.29/lib/fluent/plugin/buf_file.rb:39:in `write'
  2017-06-02 17:34:16 +0000 [warn]: /usr/share/gems/gems/fluentd-0.12.29/lib/fluent/plugin/buf_file.rb:39:in `<<'
  2017-06-02 17:34:16 +0000 [warn]: /usr/share/gems/gems/fluentd-0.12.29/lib/fluent/buffer.rb:200:in `block in emit'
  2017-06-02 17:34:16 +0000 [warn]: /usr/share/ruby/monitor.rb:211:in `mon_synchronize'
  2017-06-02 17:34:16 +0000 [warn]: /usr/share/gems/gems/fluentd-0.12.29/lib/fluent/buffer.rb:193:in `emit'
  2017-06-02 17:34:16 +0000 [warn]: /usr/share/gems/gems/fluentd-0.12.29/lib/fluent/output.rb:268:in `emit'
  2017-06-02 17:34:16 +0000 [warn]: /usr/share/gems/gems/fluentd-0.12.29/lib/fluent/event_router.rb:154:in `emit'
  2017-06-02 17:34:16 +0000 [warn]: /usr/share/gems/gems/fluentd-0.12.29/lib/fluent/event_router.rb:90:in `emit_stream'
  2017-06-02 17:34:16 +0000 [warn]: /usr/share/gems/gems/fluentd-0.12.29/lib/fluent/plugin/in_forward.rb:165:in `on_message'
  2017-06-02 17:34:16 +0000 [warn]: /usr/share/gems/gems/fluentd-0.12.29/lib/fluent/plugin/in_forward.rb:301:in `call'
  2017-06-02 17:34:16 +0000 [warn]: /usr/share/gems/gems/fluentd-0.12.29/lib/fluent/plugin/in_forward.rb:301:in `block in on_read_msgpack'
  2017-06-02 17:34:16 +0000 [warn]: /usr/share/gems/gems/fluentd-0.12.29/lib/fluent/plugin/in_forward.rb:300:in `feed_each'
  2017-06-02 17:34:16 +0000 [warn]: /usr/share/gems/gems/fluentd-0.12.29/lib/fluent/plugin/in_forward.rb:300:in `on_read_msgpack'
  2017-06-02 17:34:16 +0000 [warn]: /usr/share/gems/gems/cool.io-1.4.5/lib/cool.io/io.rb:123:in `on_readable'
  2017-06-02 17:34:16 +0000 [warn]: /usr/share/gems/gems/cool.io-1.4.5/lib/cool.io/io.rb:186:in `on_readable'
  2017-06-02 17:34:16 +0000 [warn]: /usr/share/gems/gems/cool.io-1.4.5/lib/cool.io/loop.rb:88:in `run_once'
  2017-06-02 17:34:16 +0000 [warn]: /usr/share/gems/gems/cool.io-1.4.5/lib/cool.io/loop.rb:88:in `run'
  2017-06-02 17:34:16 +0000 [warn]: /usr/share/gems/gems/fluentd-0.12.29/lib/fluent/plugin/in_forward.rb:107:in `run'
2017-06-02 17:34:16 +0000 [error]: forward error error=#<Encoding::UndefinedConversionError: "\x93" from ASCII-8BIT to UTF-8> error_class=Encoding::UndefinedConversionError
  2017-06-02 17:34:16 +0000 [error]: suppressed same stacktrace
2017-06-02 17:34:16 +0000 [warn]: emit transaction failed: error_class=Encoding::UndefinedConversionError error="\"\\x93\" from ASCII-8BIT to UTF-8" tag="fluent.warn"
  2017-06-02 17:34:16 +0000 [warn]: /usr/share/gems/gems/fluentd-0.12.29/lib/fluent/plugin/buf_file.rb:39:in `write'
  2017-06-02 17:34:16 +0000 [warn]: /usr/share/gems/gems/fluentd-0.12.29/lib/fluent/plugin/buf_file.rb:39:in `<<'
  2017-06-02 17:34:16 +0000 [warn]: /usr/share/gems/gems/fluentd-0.12.29/lib/fluent/buffer.rb:200:in `block in emit'
  2017-06-02 17:34:16 +0000 [warn]: /usr/share/ruby/monitor.rb:211:in `mon_synchronize'
  2017-06-02 17:34:16 +0000 [warn]: /usr/share/gems/gems/fluentd-0.12.29/lib/fluent/buffer.rb:193:in `emit'
  2017-06-02 17:34:16 +0000 [warn]: /usr/share/gems/gems/fluentd-0.12.29/lib/fluent/output.rb:268:in `emit'
  2017-06-02 17:34:16 +0000 [warn]: /usr/share/gems/gems/fluentd-0.12.29/lib/fluent/event_router.rb:154:in `emit'
  2017-06-02 17:34:16 +0000 [warn]: /usr/share/gems/gems/fluentd-0.12.29/lib/fluent/event_router.rb:90:in `emit_stream'
  2017-06-02 17:34:16 +0000 [warn]: /usr/share/gems/gems/fluentd-0.12.29/lib/fluent/event_router.rb:81:in `emit'
  2017-06-02 17:34:16 +0000 [warn]: /usr/share/gems/gems/fluentd-0.12.29/lib/fluent/engine.rb:177:in `block in log_event_loop'
  2017-06-02 17:34:16 +0000 [warn]: /usr/share/gems/gems/fluentd-0.12.29/lib/fluent/engine.rb:175:in `each'
  2017-06-02 17:34:16 +0000 [warn]: /usr/share/gems/gems/fluentd-0.12.29/lib/fluent/engine.rb:175:in `log_event_loop'
2017-06-02 17:34:16 +0000 [error]: failed to emit fluentd's log event tag="fluent.warn" event={"error_class"=>"Encoding::UndefinedConversionError", "error"=>"\"\\x93\" from ASCII-8BIT to UTF-8", "tag"=>"final.greped.nova.compute", "message"=>"emit transaction failed: error_class=Encoding::UndefinedConversionError error=\"\\\"\\\\x93\\\" from ASCII-8BIT to UTF-8\" tag=\"final.greped.nova.compute\""} error_class=Encoding::UndefinedConversionError error=#<Encoding::UndefinedConversionError: "\x93" from ASCII-8BIT to UTF-8>
2017-06-02 17:34:16 +0000 [warn]: emit transaction failed: error_class=Encoding::UndefinedConversionError error="\"\\x93\" from ASCII-8BIT to UTF-8" tag="fluent.error"
  2017-06-02 17:34:16 +0000 [warn]: suppressed same stacktrace
```

**Comment by nhosoi** [comment]
It is not a problem of the file buffer type, but an issue of encoding, is it?  I'd think the same error would be issued even if the memory buffer type is chosen...

For some reason, Fluentd sets "ASCII-8BIT" as a default encoding.  I think we prefer to set UTF-8 for our encoding?  (I'm looking for the method to set it...)

I also tried the file buffer type in this pull request (I'm going to separate that part to another pull request, though):
https://github.com/openshift/origin-aggregated-logging/pull/461
I did not run into the problem probably because my tested logs did not have 8bit massages.  I think we should add the test data containing 8bit/multi-byte characters...

**Comment by nhosoi** [comment]
Sorry, I was wrong.  I found this statement in [1]:
  Character encoding
  Fluentd assumes configuration file is UTF-8 or ASCII.

Then, the message contained non UTF-8 characters?  Could there be a sample log that caused the exception?

[1] http://docs.fluentd.org/v0.12/articles/config-file#character-encoding

**Comment by portante** [comment]
Our fluentd instance works fine with the `memory` buffer, all logs are dropped when using the `file` buffer, with the error message printed as originally reported.

**Comment by cosmo0920** [comment]
I've tried to reproduce this issue with v0.14.
But I couldn't reproduce.

This issue might be occurred with v0.12.

**Comment by sradco** [comment]
Same issue for me with v0.12

**Comment by cosmo0920** [comment]
@sradco Any chance to evaluate v0.14 in your environment?
I think that this is problematic limitation of v0.12.
