### ISSUE TITLE
Regex for spring boot app

### ISSUE THREAD

**Issue by shavo007** [uken/fluent-plugin-elasticsearch#314]
#### Problem
Trying to  ingest logs using fluentd for spring boot microservice. 
...

#### Steps to replicate

I am deploying fluentd as daemonset on kubernetes
I followed the config located here : 
https://github.com/coreos/tectonic-docs/blob/master/Documentation/files/logging/fluentd-configmap.yaml

I want to handle my logs specifically using regex. I tested at fluentular
```
http://fluentular.herokuapp.com/parse?regexp=%5E%28%3F%3Cdate%3E%5B0-9%5D%2B-%5B0-9%5D%2B-%5B0-9%5D%2B%5Cs%2B%5B0-9%5D%2B%3A%5B0-9%5D%2B%3A%5B0-9%5D%2B.%5B0-9%5D%2B%29%5Cs%2B%28%3F%3Clog_level%3E%5BAa%5Dlert%7CALERT%7C%5BTt%5Drace%7CTRACE%7C%5BDd%5Debug%7CDEBUG%7C%5BNn%5Dotice%7CNOTICE%7C%5BIi%5Dnfo%7CINFO%7C%5BWw%5Darn%3F%28%3F%3Aing%29%3F%7CWARN%3F%28%3F%3AING%29%3F%7C%5BEe%5Drr%3F%28%3F%3Aor%29%3F%7CERR%3F%28%3F%3AOR%29%3F%7C%5BCc%5Drit%3F%28%3F%3Aical%29%3F%7CCRIT%3F%28%3F%3AICAL%29%3F%7C%5BFf%5Datal%7CFATAL%7C%5BSs%5Devere%7CSEVERE%7CEMERG%28%3F%3AENCY%29%3F%7C%5BEe%5Dmerg%28%3F%3Aency%29%3F%29%5Cs%2B%28%3F%3Cpid%3E%5B0-9%5D%2B%29%5Cs%2B---%5Cs%2B%28%3F%3Cmessage%3E.*%29%24&input=2017-11-08+23%3A52%3A51.572++WARN+1+---+%5Bnio-8080-exec-8%5D+c.r.a.r.exception.RaidrExceptionHandler++%3A+Raidr+Exception+occurred+%3A+No+xml+file+exists+in+archive+500145%2F20170622%2F500145_20170622_075538_17.zip&time_format=%25Y-%25m-%25d
```

Sample conf is 

```
  raidr-input.conf: |
    # Example:
    <source>
      type tail
      read_from_head true
      format /^(?<date>[0-9]+-[0-9]+-[0-9]+\s+[0-9]+:[0-9]+:[0-9]+.[0-9]+)\s+(?<log_level>[Aa]lert|ALERT|[Tt]race|TRACE|[Dd]ebug|DEBUG|[Nn]otice|NOTICE|[Ii]nfo|INFO|[Ww]arn?(?:ing)?|WARN?(?:ING)?|[Ee]rr?(?:or)?|ERR?(?:OR)?|[Cc]rit?(?:ical)?|CRIT?(?:ICAL)?|[Ff]atal|FATAL|[Ss]evere|SEVERE|EMERG(?:ENCY)?|[Ee]merg(?:ency)?)\s+(?<pid>[0-9]+)\s+---\s+(?<message>.*)$/
      path /var/log/containers/alcyon-raidr**.log
      pos_file /var/log/alcyon-raidr.log.pos
      tag kube.dev.raidr
    </source>

```

But it does not create these fields in elasticsearch. 

Sample output using default console appender is:

```
2017-11-09 03:29:42.957  INFO 1 --- [nio-8080-exec-6] raidr.util.ZipHelper  :message
2017-11-09 03:29:43.000  WARN 1 --- [nio-8080-exec-6] r.exception.RaidrExceptionHandler  : Raidr Exception occurred : No xml file exists in archive 500145/20170622/500145_20170622_075538_17.zip
 raidr.exception.RaidrException: No xml file exists in archive 500145/20170622/500145_20170622_075538_17.zip
	at raidr.service.UploadMediaService.parseIncidentXML(UploadMediaService.java:101)
	at raidr.service.UploadMediaService.uploadMediaFiles(UploadMediaService.java:53)
	at raidr.service.RaidrService.extractFileSendToDocStoreAndGetReferences(RaidrService.java:31)
	at raidr.controller.MigrationController.extractFileSendToDocStoreAndGetReferences(MigrationController.java:33)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

```

In fluentd logs I get lots of errors:

```
2017-11-09 03:45:44 +0000 [warn]: pattern not match:

```

#### Using Fluentd and ES plugin versions

```
 starting fluentd-0.12.39
2017-11-09 03:43:42 +0000 [info]: gem 'fluent-plugin-elasticsearch' version '1.9.5'
2017-11-09 03:43:42 +0000 [info]: gem 'fluent-plugin-kubernetes_metadata_filter' version '0.28.0'
2017-11-09 03:43:42 +0000 [info]: gem 'fluent-plugin-prometheus' version '0.3.0'
2017-11-09 03:43:42 +0000 [info]: gem 'fluent-plugin-record-reformer' version '0.9.1'
2017-11-09 03:43:42 +0000 [info]: gem 'fluent-plugin-rewrite-tag-filter' version '1.5.6'
2017-11-09 03:43:42 +0000 [info]: gem 'fluent-plugin-secure-forward' version '0.4.5'
2017-11-09 03:43:42 +0000 [info]: gem 'fluent-plugin-systemd' version '0.0.8'
2017-11-09 03:43:42 +0000 [info]: gem 'fluentd' version '0.12.39'

```

**Comment by cosmo0920** [comment]
This is `in_tail`'s format usage issue, right?

**Comment by shavo007** [comment]
yep @cosmo0920  the sample conf is above similar to"

```
 raidr-input.conf: |
    # Example:
    <source>
      type tail
      read_from_head true
      format /^(?<date>[0-9]+-[0-9]+-[0-9]+\s+[0-9]+:[0-9]+:[0-9]+.[0-9]+)\s+(?<log_level>[Aa]lert|ALERT|[Tt]race|TRACE|[Dd]ebug|DEBUG|[Nn]otice|NOTICE|[Ii]nfo|INFO|[Ww]arn?(?:ing)?|WARN?(?:ING)?|[Ee]rr?(?:or)?|ERR?(?:OR)?|[Cc]rit?(?:ical)?|CRIT?(?:ICAL)?|[Ff]atal|FATAL|[Ss]evere|SEVERE|EMERG(?:ENCY)?|[Ee]merg(?:ency)?)\s+(?<pid>[0-9]+)\s+---\s+(?<message>.*)$/
      path /var/log/containers/alcyon-raidr**.log
      pos_file /var/log/alcyon-raidr.log.pos
      tag kube.dev.raidr
    </source>
```

**Comment by cosmo0920** [comment]
Umm..., here is fluent plugin ES repository.
Could you send your question in [Fluentd Mailing List](https://groups.google.com/forum/?fromgroups#!forum/fluentd) or [Fluentd Community Slack](https://slack.fluentd.org/).
Closing.

**Comment by shavo007** [comment]
ok. will do
