### ISSUE TITLE
the scheme http does not accept registry part when use FQDN

### ISSUE THREAD

**Issue by wzcwts521** [uken/fluent-plugin-elasticsearch#337]
#### Problem
Error
`error_class=URI::InvalidURIError error="the scheme http does not accept registry part: d_es_pso_nginx.db.XXX.XXXX.net:9200 (or bad hostname?)`
Logs
```
2017-11-28 13:15:01 -0800 [info]: using configuration file: <ROOT>
  <source>
    @type tail
    path "/var/log/nginx/*access.log"
    pos_file "/var/log/td-agent/nginx_access.log.pos"
    tag "nginx.access"
    format /^(?<host>[^ ]*) - (?<remote_user>[^ ]*) \[(?<time>[^\]]*)\] "(?<request_type>[^ ]*) (?<request_url>[^ ]*) (?<request_http_protocol>[^ ]*)" (?<status>[^"]*) (?<body_bytes_sent>[^ ]*) "(?<http_referer>[^ ]*)" "(?<http_user_agent>[^\"]*)" "(?<http_x_forwarded_for>[^ ])"rt=(?<request_time>[^ ]*)  ua="(?<upstream_addr>[^ ]*)" uct="(?<upstream_connect_time>[^ ]*)" ucs="(?<upstream_cache_status>[^ ]*)"uht="(?<upstream_header_time>[^ ]*)" urt="(?<upstream_response_time>[^ ]*)"?$/
    time_format %d/%b/%Y:%H:%M:%S %z
    <parse>
      time_format %d/%b/%Y:%H:%M:%S %z
      @type regexp
      expression ^(?<host>[^ ]*) - (?<remote_user>[^ ]*) \[(?<time>[^\]]*)\] "(?<request_type>[^ ]*) (?<request_url>[^ ]*) (?<request_http_protocol>[^ ]*)" (?<status>[^"]*) (?<body_bytes_sent>[^ ]*) "(?<http_referer>[^ ]*)" "(?<http_user_agent>[^\"]*)" "(?<http_x_forwarded_for>[^ ])"rt=(?<request_time>[^ ]*)  ua="(?<upstream_addr>[^ ]*)" uct="(?<upstream_connect_time>[^ ]*)" ucs="(?<upstream_cache_status>[^ ]*)"uht="(?<upstream_header_time>[^ ]*)" urt="(?<upstream_response_time>[^ ]*)"?$
    </parse>
  </source>
  <match nginx.*>
    @type elasticsearch
    host "d_es_pso_nginx.db.xxx.xxxx.net"
    logstash_format true
    port 9200
    index_name "nginxdev"
    logstash_prefix "nginxdev1"
    type_name "fluentd"
    flush_interval 5s
    <buffer>
      flush_interval 5s
    </buffer>
  </match>
</ROOT>
2017-11-28 13:15:01 -0800 [info]: starting fluentd-0.14.22 pid=1497 ruby="2.1.10"
2017-11-28 13:15:01 -0800 [info]: spawn command to main:  cmdline=["/opt/td-agent/embedded/bin/ruby", "-Eascii-8bit:ascii-8bit", "/usr/sbin/td-agent", "--log", "/var/log/td-agent/td-agent.log", "--use-v1-config", "--group", "td-agent", "--daemon", "/var/run/td-agent/td-agent.pid", "--under-supervisor"]
2017-11-28 13:15:02 -0800 [info]: gem 'fluent-mixin-plaintextformatter' version '0.2.6'
2017-11-28 13:15:02 -0800 [info]: gem 'fluent-plugin-elasticsearch' version '2.0.0'
2017-11-28 13:15:02 -0800 [info]: gem 'fluent-plugin-kafka' version '0.6.1'
2017-11-28 13:15:02 -0800 [info]: gem 'fluent-plugin-mongo' version '0.8.1'
2017-11-28 13:15:02 -0800 [info]: gem 'fluent-plugin-rewrite-tag-filter' version '1.5.6'
2017-11-28 13:15:02 -0800 [info]: gem 'fluent-plugin-s3' version '0.8.5'
2017-11-28 13:15:02 -0800 [info]: gem 'fluent-plugin-scribe' version '0.10.14'
2017-11-28 13:15:02 -0800 [info]: gem 'fluent-plugin-td' version '0.10.29'
2017-11-28 13:15:02 -0800 [info]: gem 'fluent-plugin-td-monitoring' version '0.2.3'
2017-11-28 13:15:02 -0800 [info]: gem 'fluent-plugin-webhdfs' version '0.7.1'
2017-11-28 13:15:02 -0800 [info]: gem 'fluentd' version '0.14.22'
2017-11-28 13:15:02 -0800 [info]: gem 'fluentd' version '0.12.40'
2017-11-28 13:15:02 -0800 [info]: adding match pattern="nginx.*" type="elasticsearch"
2017-11-28 13:15:02 -0800 [info]: #0 'flush_interval' is configured at out side of <buffer>. 'flush_mode' is set to 'interval' to keep existing behaviour
2017-11-28 13:15:02 -0800 [info]: adding source type="tail"
2017-11-28 13:15:02 -0800 [info]: #0 starting fluentd worker pid=1507 ppid=1502 worker=0
2017-11-28 13:15:02 -0800 [info]: #0 following tail of /var/log/nginx/uns_access.log
2017-11-28 13:15:02 -0800 [info]: #0 following tail of /var/log/nginx/stb_access.log
2017-11-28 13:15:02 -0800 [info]: #0 following tail of /var/log/nginx/access.log
2017-11-28 13:15:02 -0800 [info]: #0 fluentd worker is now running worker=0
2017-11-28 13:15:07 -0800 [warn]: #0 failed to flush the buffer. retry_time=0 next_retry_seconds=2017-11-28 13:15:08 -0800 chunk="55f11831c40d97fa1c00ab519813df87" error_class=URI::InvalidURIError error="the scheme http does not accept registry part: d_es_pso_nginx.db:9200 (or bad hostname?)"
  2017-11-28 13:15:07 -0800 [warn]: #0 /opt/td-agent/embedded/lib/ruby/2.1.0/uri/generic.rb:214:in `initialize'
  2017-11-28 13:15:07 -0800 [warn]: #0 /opt/td-agent/embedded/lib/ruby/2.1.0/uri/common.rb:214:in `new'
  2017-11-28 13:15:07 -0800 [warn]: #0 /opt/td-agent/embedded/lib/ruby/2.1.0/uri/common.rb:214:in `parse'
  2017-11-28 13:15:07 -0800 [warn]: #0 /opt/td-agent/embedded/lib/ruby/2.1.0/uri/common.rb:747:in `parse'
  2017-11-28 13:15:07 -0800 [warn]: #0 /opt/td-agent/embedded/lib/ruby/2.1.0/uri/common.rb:1232:in `URI'
  2017-11-28 13:15:07 -0800 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/faraday-0.13.1/lib/faraday/utils.rb:275:in `call'
  2017-11-28 13:15:07 -0800 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/faraday-0.13.1/lib/faraday/utils.rb:275:in `URI'
  2017-11-28 13:15:07 -0800 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/faraday-0.13.1/lib/faraday/connection.rb:312:in `url_prefix='
  2017-11-28 13:15:07 -0800 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/faraday-0.13.1/lib/faraday/connection.rb:80:in `initialize'
  2017-11-28 13:15:07 -0800 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/elasticsearch-transport-6.0.0/lib/elasticsearch/transport/transport/http/faraday.rb:38:in `new'
  2017-11-28 13:15:07 -0800 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/elasticsearch-transport-6.0.0/lib/elasticsearch/transport/transport/http/faraday.rb:38:in `__build_connection'
  2017-11-28 13:15:07 -0800 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/elasticsearch-transport-6.0.0/lib/elasticsearch/transport/transport/base.rb:138:in `block in __build_connections'
  2017-11-28 13:15:07 -0800 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/elasticsearch-transport-6.0.0/lib/elasticsearch/transport/transport/base.rb:130:in `map'
  2017-11-28 13:15:07 -0800 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/elasticsearch-transport-6.0.0/lib/elasticsearch/transport/transport/base.rb:130:in `__build_connections'
  2017-11-28 13:15:07 -0800 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/elasticsearch-transport-6.0.0/lib/elasticsearch/transport/transport/base.rb:40:in `initialize'
  2017-11-28 13:15:07 -0800 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-elasticsearch-2.0.0/lib/fluent/plugin/out_elasticsearch.rb:174:in `new'
  2017-11-28 13:15:07 -0800 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-elasticsearch-2.0.0/lib/fluent/plugin/out_elasticsearch.rb:174:in `client'
  2017-11-28 13:15:07 -0800 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-elasticsearch-2.0.0/lib/fluent/plugin/out_elasticsearch.rb:419:in `rescue in send_bulk'
  2017-11-28 13:15:07 -0800 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-elasticsearch-2.0.0/lib/fluent/plugin/out_elasticsearch.rb:414:in `send_bulk'
  2017-11-28 13:15:07 -0800 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-elasticsearch-2.0.0/lib/fluent/plugin/out_elasticsearch.rb:401:in `write'
  2017-11-28 13:15:07 -0800 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.22/lib/fluent/plugin/output.rb:1089:in `try_flush'
  2017-11-28 13:15:07 -0800 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.22/lib/fluent/plugin/output.rb:1314:in `flush_thread_run'
  2017-11-28 13:15:07 -0800 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.22/lib/fluent/plugin/output.rb:439:in `block (2 levels) in start'
  2017-11-28 13:15:07 -0800 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.22/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
2017-11-28 13:15:08 -0800 [warn]: #0 failed to flush the buffer. retry_time=0 next_retry_seconds=2017-11-28 13:15:08 -0800 chunk="55f11831c40d97fa1c00ab519813df87" error_class=URI::InvalidURIError error="the scheme http does not accept registry part: d_es_pso_nginx.db.xxx.xxxx.net:9200 (or bad hostname?)"
  2017-11-28 13:15:08 -0800 [warn]: #0 suppressed same stacktrace
```

#### Steps to replicate

```
@include /etc/td-agent/config.d/*.conf

<match nginx.*>
  @type elasticsearch
  host d_es_pso_nginx.db.xxx.xxxx.net
  logstash_format true
  port 9200
  index_name nginxdev
  logstash_prefix nginxdev1
  type_name fluentd
  flush_interval 5s
</match>

```

#### Expected Behavior or What you need to ask

...

#### Using Fluentd and ES plugin versions
```
td-agent 0.14.22
```

```
/opt/td-agent/embedded/bin/ruby --version
ruby 2.1.10p492 (2016-04-01 revision 54464) [x86_64-linux]
```

```
./embedded/bin/gem list --local |grep ela
elasticsearch (6.0.0)
elasticsearch-api (6.0.0)
elasticsearch-transport (6.0.0)
fluent-plugin-elasticsearch (2.0.0)
```

**Comment by cosmo0920** [comment]
```ruby
require 'uri'
URI("d_es_pso_nginx.db.xxx.xxxx.net") # Set actual fqdn
```

can parse actual fqdn?

**Comment by cosmo0920** [comment]
No response.
I'm closing for now.
