### ISSUE TITLE
Errors using elasticsearch_dynamic on kubernetes deploy

### ISSUE THREAD

**Issue by vasartori** [uken/fluent-plugin-elasticsearch#339]
#### Problem
Using the option elasticsearch_dynamic on default kubernetes fluentd image, on logs I get this error:
Works for a little bit secounds (it create the dynamic index on ES), and stop to send logs.

Error Message:
```
2017-12-13 18:37:45 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2017-12-13 18:37:46 +0000 error_class="NoMethodError" error="undefined method `[]' for nil:NilClass" plugin_id="object:3f9d73342f4c"
  2017-12-13 18:37:45 +0000 [warn]: /var/lib/gems/2.3.0/gems/fluent-plugin-elasticsearch-1.9.7/lib/fluent/plugin/out_elasticsearch_dynamic.rb:240:in `eval'
  2017-12-13 18:37:45 +0000 [warn]: /var/lib/gems/2.3.0/gems/fluent-plugin-elasticsearch-1.9.7/lib/fluent/plugin/out_elasticsearch_dynamic.rb:240:in `eval'
  2017-12-13 18:37:45 +0000 [warn]: /var/lib/gems/2.3.0/gems/fluent-plugin-elasticsearch-1.9.7/lib/fluent/plugin/out_elasticsearch_dynamic.rb:240:in `expand_param'
  2017-12-13 18:37:45 +0000 [warn]: /var/lib/gems/2.3.0/gems/fluent-plugin-elasticsearch-1.9.7/lib/fluent/plugin/out_elasticsearch_dynamic.rb:130:in `block (2 levels) in write_objects'
  2017-12-13 18:37:45 +0000 [warn]: /var/lib/gems/2.3.0/gems/fluent-plugin-elasticsearch-1.9.7/lib/fluent/plugin/out_elasticsearch_dynamic.rb:125:in `each'
  2017-12-13 18:37:45 +0000 [warn]: /var/lib/gems/2.3.0/gems/fluent-plugin-elasticsearch-1.9.7/lib/fluent/plugin/out_elasticsearch_dynamic.rb:125:in `each_with_index'
  2017-12-13 18:37:45 +0000 [warn]: /var/lib/gems/2.3.0/gems/fluent-plugin-elasticsearch-1.9.7/lib/fluent/plugin/out_elasticsearch_dynamic.rb:125:in `block in write_objects'
  2017-12-13 18:37:45 +0000 [warn]: /var/lib/gems/2.3.0/gems/fluentd-0.12.40/lib/fluent/plugin/buf_memory.rb:67:in `feed_each'
  2017-12-13 18:37:45 +0000 [warn]: /var/lib/gems/2.3.0/gems/fluentd-0.12.40/lib/fluent/plugin/buf_memory.rb:67:in `msgpack_each'
  2017-12-13 18:37:45 +0000 [warn]: /var/lib/gems/2.3.0/gems/fluent-plugin-elasticsearch-1.9.7/lib/fluent/plugin/out_elasticsearch_dynamic.rb:121:in `write_objects'
  2017-12-13 18:37:45 +0000 [warn]: /var/lib/gems/2.3.0/gems/fluentd-0.12.40/lib/fluent/output.rb:490:in `write'
  2017-12-13 18:37:45 +0000 [warn]: /var/lib/gems/2.3.0/gems/fluentd-0.12.40/lib/fluent/buffer.rb:354:in `write_chunk'
  2017-12-13 18:37:45 +0000 [warn]: /var/lib/gems/2.3.0/gems/fluentd-0.12.40/lib/fluent/buffer.rb:333:in `pop'
  2017-12-13 18:37:45 +0000 [warn]: /var/lib/gems/2.3.0/gems/fluentd-0.12.40/lib/fluent/output.rb:342:in `try_flush'
  2017-12-13 18:37:45 +0000 [warn]: /var/lib/gems/2.3.0/gems/fluentd-0.12.40/lib/fluent/output.rb:149:in `run'
2017-12-13 18:37:45 +0000 [info]: Connection opened to Elasticsearch cluster => {:host=>"elasticsearch-logging", :port=>9200, :scheme=>"http"}
```
#### ConfigFile
```
<match fluent.**>
  type null
</match>

@include /etc/fluent/config.d/*.conf

<source>
  type tail
  path /var/log/containers/*.log
  pos_file /var/log/es-containers.log.pos
  time_format %Y-%m-%dT%H:%M:%S.%NZ
  tag kubernetes.*
  read_from_head true
  format multi_format
  <pattern>
    format json
    time_key time
    time_format %Y-%m-%dT%H:%M:%S.%NZ
  </pattern>
  <pattern>
    format /^(?<time>.+) (?<stream>stdout|stderr) [^ ]* (?<log>.*)$/
    time_format %Y-%m-%dT%H:%M:%S.%N%:z
  </pattern>
</source># Takes the messages sent over TCP
<source>
  type forward
</source># Prometheus Exporter Plugin
<source>
  @type prometheus
</source>
<source>
  @type monitor_agent
</source>
<source>
  @type prometheus_monitor
  <labels>
    host ${hostname}
  </labels>
</source>
<source>
  @type prometheus_output_monitor
  <labels>
    host ${hostname}
  </labels>
</source>
<source>
  @type prometheus_tail_monitor
  <labels>
    host ${hostname}
  </labels>
</source># Enriches records with Kubernetes metadata
<filter kubernetes.**>
  type kubernetes_metadata
</filter>
<match **>
   @type elasticsearch_dynamic
   log_level trace
   include_tag_key true
   host elasticsearch-logging
   port 9200
   logstash_format true
   logstash_dateformat %Y.%m.%d-%H
   logstash_prefix ${record['kubernetes']['namespace_name']}
   type_name kubernetes-without-namespace
   target_index_key kubernetes-withou-namespace
   # Set the chunk limits.
   buffer_chunk_limit 2M
   buffer_queue_limit 8
   flush_interval 5s
   # Never wait longer than 5 minutes between retries.
   max_retry_wait 30
   # Disable the limit on the number of retries (retry forever).
   disable_retry_limit
   # Use multiple threads for processing.
   num_threads 2
</match># Example:
<source>
  type tail
  format /^(?<time>[^ ]* [^ ,]*)[^\[]*\[[^\]]*\]\[(?<severity>[^ \]]*) *\] (?<message>.*)$/
  time_format %Y-%m-%d %H:%M:%S
  path /var/log/salt/minion
  pos_file /var/log/es-salt.pos
  tag salt
</source>
<source>
  type tail
  format syslog
  path /var/log/startupscript.log
  pos_file /var/log/es-startupscript.log.pos
  tag startupscript
</source>
<source>
  type tail
  format /^time="(?<time>[^)]*)" level=(?<severity>[^ ]*) msg="(?<message>[^"]*)"( err="(?<error>[^"]*)")?( statusCode=($<status_code>\d+))?/
  path /var/log/docker.log
  pos_file /var/log/es-docker.log.pos
  tag docker
</source>
<source>
  type tail
  # Not parsing this, because it doesn't have anything particularly useful to
  # parse out of it (like severities).
  format none
  path /var/log/etcd.log
  pos_file /var/log/es-etcd.log.pos
  tag etcd
</source>
<source>
  type tail
  format multiline
  multiline_flush_interval 5s
  format_firstline /^\w\d{4}/
  format1 /^(?<severity>\w)(?<time>\d{4} [^\s]*)\s+(?<pid>\d+)\s+(?<source>[^ \]]+)\] (?<message>.*)/
  time_format %m%d %H:%M:%S.%N
  path /var/log/kubelet.log
  pos_file /var/log/es-kubelet.log.pos
  tag kubelet
</source>
<source>
  type tail
  format multiline
  multiline_flush_interval 5s
  format_firstline /^\w\d{4}/
  format1 /^(?<severity>\w)(?<time>\d{4} [^\s]*)\s+(?<pid>\d+)\s+(?<source>[^ \]]+)\] (?<message>.*)/
  time_format %m%d %H:%M:%S.%N
  path /var/log/kube-proxy.log
  pos_file /var/log/es-kube-proxy.log.pos
  tag kube-proxy
</source>
<source>
  type tail
  format multiline
  multiline_flush_interval 5s
  format_firstline /^\w\d{4}/
  format1 /^(?<severity>\w)(?<time>\d{4} [^\s]*)\s+(?<pid>\d+)\s+(?<source>[^ \]]+)\] (?<message>.*)/
  time_format %m%d %H:%M:%S.%N
  path /var/log/kube-apiserver.log
  pos_file /var/log/es-kube-apiserver.log.pos
  tag kube-apiserver
</source>
<source>
  type tail
  format multiline
  multiline_flush_interval 5s
  format_firstline /^\w\d{4}/
  format1 /^(?<severity>\w)(?<time>\d{4} [^\s]*)\s+(?<pid>\d+)\s+(?<source>[^ \]]+)\] (?<message>.*)/
  time_format %m%d %H:%M:%S.%N
  path /var/log/kube-controller-manager.log
  pos_file /var/log/es-kube-controller-manager.log.pos
  tag kube-controller-manager
</source>
<source>
  type tail
  format multiline
  multiline_flush_interval 5s
  format_firstline /^\w\d{4}/
  format1 /^(?<severity>\w)(?<time>\d{4} [^\s]*)\s+(?<pid>\d+)\s+(?<source>[^ \]]+)\] (?<message>.*)/
  time_format %m%d %H:%M:%S.%N
  path /var/log/kube-scheduler.log
  pos_file /var/log/es-kube-scheduler.log.pos
  tag kube-scheduler
</source>
<source>
  type tail
  format multiline
  multiline_flush_interval 5s
  format_firstline /^\w\d{4}/
  format1 /^(?<severity>\w)(?<time>\d{4} [^\s]*)\s+(?<pid>\d+)\s+(?<source>[^ \]]+)\] (?<message>.*)/
  time_format %m%d %H:%M:%S.%N
  path /var/log/rescheduler.log
  pos_file /var/log/es-rescheduler.log.pos
  tag rescheduler
</source>
<source>
  type tail
  format multiline
  multiline_flush_interval 5s
  format_firstline /^\w\d{4}/
  format1 /^(?<severity>\w)(?<time>\d{4} [^\s]*)\s+(?<pid>\d+)\s+(?<source>[^ \]]+)\] (?<message>.*)/
  time_format %m%d %H:%M:%S.%N
  path /var/log/glbc.log
  pos_file /var/log/es-glbc.log.pos
  tag glbc
</source>
<source>
  type tail
  format multiline
  multiline_flush_interval 5s
  format_firstline /^\w\d{4}/
  format1 /^(?<severity>\w)(?<time>\d{4} [^\s]*)\s+(?<pid>\d+)\s+(?<source>[^ \]]+)\] (?<message>.*)/
  time_format %m%d %H:%M:%S.%N
  path /var/log/cluster-autoscaler.log
  pos_file /var/log/es-cluster-autoscaler.log.pos
  tag cluster-autoscaler
</source>
<source>
  type systemd
  filters [{ "_SYSTEMD_UNIT": "docker.service" }]
  pos_file /var/log/gcp-journald-docker.pos
  read_from_head true
  tag docker
</source>
<source>
  type systemd
  filters [{ "_SYSTEMD_UNIT": "kubelet.service" }]
  pos_file /var/log/gcp-journald-kubelet.pos
  read_from_head true
  tag kubelet
</source>
<source>
  type systemd
  filters [{ "_SYSTEMD_UNIT": "node-problem-detector.service" }]
  pos_file /var/log/gcp-journald-node-problem-detector.pos
  read_from_head true
  tag node-problem-detector
</source>

```
#### Using Fluentd and ES plugin versions

* fluentd 0.12.40
* fluent-plugin-elasticsearch 1.9.5

**Comment by cosmo0920** [comment]
elasticsearch_dynamic uses eval to process each records at runtime.
Could you check malformed records in your pipeline?

**Comment by cosmo0920** [comment]
It seems that `record['kubernetes']['namespace_name']` contains unexpected or empty value.

```irb
irb> record = {}
=> {}
irb> expand_param(record['kubernetes']['namespace_name'])
NoMethodError: undefined method `[]' for nil:NilClass
	from (irb):68
	from ~/.rbenv/versions/2.4.2/bin/irb:11:in `<main>'
irb> 
```

**Comment by cosmo0920** [comment]
Could you confirm `record['kubernetes']['namespace_name']` value on payload?

**Comment by vasartori** [comment]
@cosmo0920 Sorry for the delay on response.
The problem seems be here:
```<pattern>
    format json
    time_key time
    time_format %Y-%m-%dT%H:%M:%S.%NZ
  </pattern>
  <pattern>
    format /^(?<time>.+) (?<stream>stdout|stderr) [^ ]* (?<log>.*)$/
    time_format %Y-%m-%dT%H:%M:%S.%N%:z
  </pattern>```

When I use the format to none, everything works "fine" (write the raw line from docker on ES)
I solve this problem upgrading the elasticsearch-plugin, fluentd and others plugins.
The image is available here:  vasartori/fluentd-elasticsearch:latest
And the configs here: https://github.com/vasartori/fluentd-es-kubernetes
