### ISSUE TITLE
Timestamp not Parsing

### ISSUE THREAD

**Issue by bcharboneauiherb** [uken/fluent-plugin-elasticsearch#365]
#### Problem
```
2018-02-20 08:56:49 -0800 [warn]: #0 fluent/log.rb:336:warn: dump an error event: error_class=ArgumentError error="invalid date" location="C:/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-elasticsearch-2.4.0/lib/fluent/plugin/out_elasticsearch.rb:166:in `strptime'" tag="Fluent::ElasticsearchOutput::TimeParser.error" time=#<Fluent::EventTime:0x0000000006029850 @sec=1519145809, @nsec=530531000> record={"tag"=>"payment", "time"=>#<Fluent::EventTime:0x0000000006029c60 @sec=1519145803, @nsec=729659000>, "format"=>"%-m/%d/%Y %-I:%M:%S %p", "value"=>"2/20/2018 8:27:42 AM"}
```

#### Steps to replicate
Message
```
[2/20/2018 8:34:08 AM]	[MapResponseToParameters] Refund Response:
```
Config
```
<source>
  @type tail
  path C:/Logs*
  pos_file logs.log.pos
  limit_recently_modified 1h
  #read_from_head true
  <parse>
    @type multiline_grok
    grok_pattern \[(?<sourceTimestamp>%{DATE_US} %{TIME} (AM|PM))\]\t(?<tempMessage>(.|\r|\n)*)
    multiline_start_regexp /\[[0-9]{1,2}\/[0-9]{1,2}\/[0-9]{4}\s[0-9]{1,2}\:[0-9]{2}\:[0-9]{2}\s(?:A|P)M\]/
  </parse>
    tag logs
	@label @logs
</source>
<label @logs>
<filter logs>
   @type record_transformer
    <record>
      appName Logs
      level INFO
    </record>
</filter>
<match payment>
    @type copy
    # Output to Console
    <store>
      @type stdout
    </store>
    # Output to ElasticSearch
    <store>
      @type elasticsearch
      host es-cluster-pmt.iherb.net
      port 443
      scheme https
      ssl_verify false
      logstash_format true
      include_tag_key true
      time_key sourceTimestamp
      time_key_format %-m/%d/%Y %-I:%M:%S %p
      type_name logs
      reload_connections false
      buffer_type file
      buffer_path /var/log/td-agent/logs.*.buffer
      buffer_queue_full_action block
      buffer_chunk_limit 2M
      buffer_queue_limit 8
      flush_interval 2s
      max_retry_wait 30
      disable_retry_limit
      logstash_prefix fluentd-test
    </store>
  </match>
</label>
```
#### Expected Behavior or What you need to ask
date should be parsable based on pattern provided to time_key_format.
...

#### Using Fluentd and ES plugin versions

* OS version Windows Server 2012 R2
* td-agent 3.1.1
     fluentd 1.0.2
* ES plugin 2.x.y or 1.x.y
actionmailer (4.2.10)
actionpack (4.2.10)
actionview (4.2.10)
activejob (4.2.10)
activemodel (4.2.10)
activerecord (4.2.10)
activesupport (4.2.10)
addressable (2.5.2)
arel (6.0.4)
aws-partitions (1.42.0)
aws-sdk-core (3.11.0)
aws-sdk-kms (1.3.0)
aws-sdk-s3 (1.8.0)
aws-sdk-sqs (1.3.0)
aws-sigv4 (1.0.2)
bigdecimal (default: 1.3.0)
builder (3.2.3)
bundler (1.16.0)
celluloid (0.15.2)
concurrent-ruby (1.0.5)
cool.io (1.5.3)
crass (1.0.3)
did_you_mean (1.1.0)
dig_rb (1.0.1)
draper (1.4.0)
**elasticsearch (5.0.4)
elasticsearch-api (5.0.4)
elasticsearch-transport (5.0.4)**
erubis (2.7.0)
excon (0.60.0)
faraday (0.14.0)
ffi (1.9.18)
ffi-win32-extensions (1.0.3)
fluent-logger (0.7.2)
fluent-plugin-concat (2.2.0)
**fluent-plugin-elasticsearch (2.4.0)**
fluent-plugin-grok-parser (2.1.5)
fluent-plugin-kafka (0.6.5)
fluent-plugin-rewrite-tag-filter (2.0.1)
fluent-plugin-s3 (1.1.0)
fluent-plugin-td (1.0.0)
fluent-plugin-td-monitoring (0.2.3)
fluent-plugin-webhdfs (1.2.2)
fluent-plugin-windows-eventlog (0.2.2)
fluentd (1.0.2)
font-awesome-rails (4.7.0.3)
globalid (0.4.1)
haml (4.0.7)
haml-rails (0.5.3)
hike (1.2.3)
hirb (0.7.3)
http_parser.rb (0.6.0)
httpclient (2.8.2.4)
i18n (0.9.5)
io-console (default: 0.4.6)
ipaddress (0.8.3)
jbuilder (2.7.0)
jmespath (1.3.1)
jquery-rails (3.1.4)
json (default: 2.0.4)
loofah (2.2.0)
ltsv (0.1.0)
mail (2.7.0)
mini_mime (1.0.0)
mini_portile2 (2.3.0)
minitest (5.10.1)
mixlib-cli (1.7.0)
mixlib-config (2.2.4)
mixlib-log (1.7.1)
mixlib-shellout (2.2.7 universal-mingw32)
msgpack (1.2.0)
multi_json (1.13.1)
multipart-post (2.0.0)
net-telnet (0.1.1)
nokogiri (1.8.1 x64-mingw32)
ohai (6.20.0)
oj (3.3.9)
openssl (default: 2.0.5)
parallel (1.12.1)
power_assert (0.4.1)
psych (default: 2.2.2)
public_suffix (3.0.1)
rack (1.6.8)
rack-test (0.6.3)
rails (4.2.10)
rails-deprecated_sanitizer (1.0.3)
rails-dom-testing (1.0.9)
rails-html-sanitizer (1.0.3)
railties (4.2.10)
rake (12.0.0)
rdoc (default: 5.0.0)
request_store (1.4.0)
ruby-kafka (0.5.1)
ruby-progressbar (1.9.0)
rubyzip (1.2.1)
sass (3.2.19)
sass-rails (4.0.4)
serverengine (2.0.5)
settingslogic (2.0.9)
sigdump (0.2.4)
sprockets (2.11.3)
sprockets-rails (2.3.3)
strptime (0.2.3)
sucker_punch (1.0.5)
systemu (2.5.2)
td (0.15.7)
td-client (1.0.4)
td-logger (0.3.27)
test-unit (3.2.3)
thor (0.20.0)
thread_safe (0.3.6)
tilt (1.4.1)
timers (1.1.0)
tzinfo (1.2.4)
tzinfo-data (1.2017.3)
webhdfs (0.8.0)
win32-api (1.7.1 universal-mingw32, 1.7.0 universal-mingw32)
win32-event (0.6.3)
win32-eventlog (0.6.7)
win32-ipc (0.7.0, 0.6.6)
win32-process (0.8.3)
win32-service (0.8.10)
windows-api (0.4.4)
windows-pr (1.2.6)
wmi-lite (1.0.0)
xmlrpc (0.2.1)
yajl-ruby (1.3.1)
zip-zip (0.3)

**Comment by cosmo0920** [comment]
Please paste your full log without sensitive information.

**Comment by okkez** [comment]
Could you try following?:

```
time_key_format %m/%d/%Y %I:%M:%S %p
```

BTW, what do you mean `%-m` and `%-I`? I could not find the format specifier with `-` in strptime(3).

**Comment by okkez** [comment]
See also 
* http://ruby-doc.org/stdlib-2.5.0/libdoc/date/rdoc/DateTime.html#method-c-_strptime
* http://ruby-doc.org/stdlib-2.5.0/libdoc/date/rdoc/DateTime.html#method-i-strftime

Fluentd uses `Time.strptime` to parse time string.
`strptime` does not support specification of flags and width unlike strftime.

**Comment by cosmo0920** [comment]
FYI: ES plugin also uses `strptime` gem which can handle `Time.strptime` format.
It cannot handle `%-m` and `%-I`.

**Comment by bcharboneauiherb** [comment]
its strptime?   i thought it was strftime  f not p
i used the following but perhaps i got my languages wrong. the page i used as a reference is for python not ruby. sry similar but not the same formats.

http://strftime.org/

in strftime
%-m  don't pad a numerical output for month.

So am I right in assuming the %m in strptime should handle it with or without numerical padding since it does not support flags?

**Comment by okkez** [comment]
strptime parses string that represents timestamp.
strftime formats time object to string.

fluent-plugin-grok-parser does not convert type from string in your configuration.
out_elasticsearch's `time_key` can specify the field name in your record that represents time, but the field value is String type.
out_elasticsearch's `time_key_format` can specify format to parse the field value specified by `time_key` and to convert string value to time (internal representation).
And then out_elasticsearch normalizes the time value to send record to Elasticsearch.

See details: https://github.com/uken/fluent-plugin-elasticsearch/blob/master/lib/fluent/plugin/out_elasticsearch.rb#L173-L189

**Comment by bcharboneauiherb** [comment]
gotcha, thanks for the explanation and the help again @okkez 
However, with time_key_format %m/%d/%Y %I:%M:%S %p it still does not parse

here is the output I ran it through jsonlint to prettify it for readability.

```
2018-02-22 09:17:51 -0800 [warn]: #0 Elasticsearch rejected 54 documents due to invalid field arguments 
2018-02-22 09:17:51 -0800 [error]: #0 Could not push log to Elasticsearch: 
{
	"took" => 16, "errors" => true, "items" => [{
			"index" => {
				"_index" => "fluentd-test-2018.02.22", "_type" => "payment", "_id" => "ofeFvmEBt6iKPON7cfmw", "status" => 400, "error" => {
					"type" => "mapper_parsing_exception", "reason" => "failed to parse [@timestamp]", "caused_by" => {
						"type" => "illegal_argument_exception", "reason" => "Invalid format: \"2/22/2018 9:17:32 AM\" is malformed at \"/22/2018 9:17:32 AM\""
					}
				}
			}
	}]
}
```

**Comment by okkez** [comment]
I've tried to reproduce your situation, but I couldn't reproduce it.
I don't use Elasticsearch's template.

Do you use [Elasticsearch's template](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-templates.html)?

**Comment by bcharboneauiherb** [comment]
I do not have a ES template for this test index.

I am using ElasticSearch 6.0.1 if that makes a difference.

**Comment by gio00** [comment]
Same problem here:
Fluentd 1.2.5
Elasticsearch 6.2.3

Error log:
`#0 dump an error event: error_class=ArgumentError error="invalid date" location="/var/lib/gems/2.3.0/gems/fluent-plugin-elasticsearch-2.11.10/lib/fluent/plugin/out_elasticsearch.rb:301:in 'strptime'" tag="Fluent::ElasticsearchOutput::TimeParser.error" time=2018-09-21 11:05:50.920516189 +0000 record={"tag"=>"b4ba81b1a7a7", "time"=>2018-09-21 11:04:45.502153660 +0000, "format"=>"%Y-%m-%d %H:%M:%S,%f", "value"=>"2018-06-13 18:33:17,378"}`

Fluent.conf

```
<source>
  @type forward
  port 24224
  bind 0.0.0.0
</source>

<filter **>
  @type parser
  emit_invalid_record_to_error false
  key_name log
  reserve_data true
 <parse>
   @type regexp
   expression /\[(?<timestamp>\d*-\d*-\d*\s*\d*:\d*:\d*,\d*)\:\s*(?<level>.*?)\/(?<process>.*?)]/
 </parse>
</filter>

<match **>
  @type elasticsearch
  logstash_format true
  host elasticsearch
  port 9200
  index_name fluentd
  type_name fluentd
  include_tag_key true
  time_key  timestamp
  time_key_format %Y-%m-%d %H:%M:%S,%f
</match>
```

Log:
```
[2018-06-13 18:33:17,378: INFO/MainProcess] message
```
