### ISSUE TITLE
`logstash_format` without `_type`

### ISSUE THREAD

**Issue by sandstrom** [uken/fluent-plugin-elasticsearch#368]
Since `_type` is [deprecated](https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-type-field.html), perhaps `logstash_format` should stop emitting the `_type` value, or it could be added as a configurable option to skip the `_type` field.

What do you think?

**Comment by cosmo0920** [comment]
This plugin depends on [elasticsearch-ruby](https://github.com/elastic/elasticsearch-ruby) client library.
This seems not to permit to omit `_type` for now on bluk operation:

```diff
diff --git a/lib/fluent/plugin/out_elasticsearch.rb b/lib/fluent/plugin/out_elasticsea
rch.rb
index ab729d4..8c05d85 100644
--- a/lib/fluent/plugin/out_elasticsearch.rb
+++ b/lib/fluent/plugin/out_elasticsearch.rb
@@ -76,6 +76,7 @@ module Fluent::Plugin
     config_param :pipeline, :string, :default => nil
     config_param :with_transporter_log, :bool, :default => false
     config_param :content_type, :enum, list: [:"application/json", :"application/x-nd
json"], :default => :"application/x-ndjson"
+    config_param :omit_meta_type, :bool, :default => true
 
     config_section :buffer do
       config_set_default :@type, DEFAULT_BUFFER_TYPE
@@ -410,7 +411,10 @@ module Fluent::Plugin
 
         meta.clear
         meta["_index".freeze] = target_index
-        meta["_type".freeze] = target_type
+
+        if !@omit_meta_type
+          meta["_type".freeze] = target_type
+        end
 
         if @pipeline
           meta["pipeline".freeze] = @pipeline
```

```log
2018-02-27 11:51:15 +0900 [info]: #1 Connection opened to Elasticsearch cluster => {:host=>"localhost", :port=>9200, :scheme=>"http"}
2018-02-27 11:51:15 +0900 [warn]: #1 failed to flush the buffer. retry_time=0 next_retry_seconds=2018-02-27 11:51:16 +0900 chunk="56628ad7b5129a51dbf2966f96c28b24" error_class=Elasticsearch::Transport::Transport::Errors::BadRequest error="[400] {\"error\":{\"root_cause\":[{\"type\":\"action_request_validation_exception\",\"reason\":\"Validation Failed: 1: type is missing;\"}],\"type\":\"action_request_validation_exception\",\"reason\":\"Validation Failed: 1: type is missing;\"},\"status\":400}"
  2018-02-27 11:51:15 +0900 [warn]: #1 /Users/cosmo/GitHub/fluent-plugin-elasticsearch/vendor/bundle/ruby/2.5.0/gems/elasticsearch-transport-6.0.1/lib/elasticsearch/transport/transport/base.rb:202:in `__raise_transport_error'
  2018-02-27 11:51:15 +0900 [warn]: #1 /Users/cosmo/GitHub/fluent-plugin-elasticsearch/vendor/bundle/ruby/2.5.0/gems/elasticsearch-transport-6.0.1/lib/elasticsearch/transport/transport/base.rb:319:in `perform_request'
  2018-02-27 11:51:15 +0900 [warn]: #1 /Users/cosmo/GitHub/fluent-plugin-elasticsearch/vendor/bundle/ruby/2.5.0/gems/elasticsearch-transport-6.0.1/lib/elasticsearch/transport/transport/http/faraday.rb:20:in `perform_request'
  2018-02-27 11:51:15 +0900 [warn]: #1 /Users/cosmo/GitHub/fluent-plugin-elasticsearch/vendor/bundle/ruby/2.5.0/gems/elasticsearch-transport-6.0.1/lib/elasticsearch/transport/client.rb:131:in `perform_request'
  2018-02-27 11:51:15 +0900 [warn]: #1 /Users/cosmo/GitHub/fluent-plugin-elasticsearch/vendor/bundle/ruby/2.5.0/gems/elasticsearch-api-6.0.1/lib/elasticsearch/api/actions/bulk.rb:95:in `bulk'
  2018-02-27 11:51:15 +0900 [warn]: #1 /Users/cosmo/GitHub/fluent-plugin-elasticsearch/lib/fluent/plugin/out_elasticsearch.rb:452:in `send_bulk'
  2018-02-27 11:51:15 +0900 [warn]: #1 /Users/cosmo/GitHub/fluent-plugin-elasticsearch/lib/fluent/plugin/out_elasticsearch.rb:438:in `write'
  2018-02-27 11:51:15 +0900 [warn]: #1 /Users/cosmo/GitHub/fluent-plugin-elasticsearch/vendor/bundle/ruby/2.5.0/gems/fluentd-1.1.0/lib/fluent/plugin/output.rb:1094:in `try_flush'
  2018-02-27 11:51:15 +0900 [warn]: #1 /Users/cosmo/GitHub/fluent-plugin-elasticsearch/vendor/bundle/ruby/2.5.0/gems/fluentd-1.1.0/lib/fluent/plugin/output.rb:1319:in `flush_thread_run'
  2018-02-27 11:51:15 +0900 [warn]: #1 /Users/cosmo/GitHub/fluent-plugin-elasticsearch/vendor/bundle/ruby/2.5.0/gems/fluentd-1.1.0/lib/fluent/plugin/output.rb:439:in `block (2 levels) in start'
  2018-02-27 11:51:15 +0900 [warn]: #1 /Users/cosmo/GitHub/fluent-plugin-elasticsearch/vendor/bundle/ruby/2.5.0/gems/fluentd-1.1.0/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
{"_index"=>"fluentd"}
2018-02-27 11:51:16 +0900 [warn]: #1 failed to flush the buffer. retry_time=0 next_retry_seconds=2018-02-27 11:51:16 +0900 chunk="56628ad7b5129a51dbf2966f96c28b24" error_class=Elasticsearch::Transport::Transport::Errors::BadRequest error="[400] {\"error\":{\"root_cause\":[{\"type\":\"action_request_validation_exception\",\"reason\":\"Validation Failed: 1: type is missing;\"}],\"type\":\"action_request_validation_exception\",\"reason\":\"Validation Failed: 1: type is missing;\"},\"status\":400}"
  2018-02-27 11:51:16 +0900 [warn]: #1 suppressed same stacktrace
```

**Comment by sandstrom** [comment]
Thanks @cosmo0920! 🥇 

I should have been more thoroughly in my own research before opening my ticket. Anyway, I did some more research and apparently this is the deprecation schedule.

So basically, if we add an option to this plugin, it should still include a type value, but it should be `_doc` for 6.x and 7.x and only in 8.x should it be omitted.

***

#### Deprecation Schedule for _type, from ElasticSearch official documentation

Elasticsearch 6.x
- **Indices created in 6.x only allow a single-type per index. Any name can be used for the type, but there can be only one. The preferred type name is _doc**, so that index APIs have the same path as they will have in 7.0: PUT {index}/_doc/{id} and POST {index}/_doc

Elasticsearch 7.x
- **The type parameter in URLs are optional.** For instance, indexing a document no longer requires a document type. The new index APIs are PUT {index}/_doc/{id} in case of explicit ids and POST {index}/_doc for auto-generated ids.
- The GET|PUT _mapping APIs support a query string parameter (include_type_name) which indicates whether the body should include a layer for the type name. It defaults to true. 7.x indices which don’t have an explicit type will use the dummy type name _doc.

Elasticsearch 8.x
- **The type parameter is no longer supported in URLs.**
- The include_type_name parameter defaults to false.

SOURCE:
https://www.elastic.co/guide/en/elasticsearch/reference/current/removal-of-types.html#_schedule_for_removal_of_mapping_types

**Comment by cosmo0920** [comment]
This plugin sends events with bulk API.
Bulk API also will support single-type per index?

**Comment by sandstrom** [comment]
@cosmo0920 Yes, it'll be the same.

**Comment by cosmo0920** [comment]
> Indices created in 6.x only allow a single-type per index

I've investigated what means.
logstash-output-elasticsearch uses a single fixed value of `_type` when it detects to communicates 6 or above ES server/cluster.
https://github.com/logstash-plugins/logstash-output-elasticsearch/pull/712

So, this plugin should deprecated `@target_type_key` feature.
Because this changes `_type` meta field dynamically.

**Comment by cosmo0920** [comment]
#371 handles this issue.
If #371 is merged, can we close this?
Or, we should still open until ES 9 when `include_in_type` parameter is removed?

**Comment by sandstrom** [comment]
Awesom! 🎉 

I think we can close this! ES9 is still far away 😄
