### ISSUE TITLE
ES output broken after ES outage

### ISSUE THREAD

**Issue by dmnfortytwo** [uken/fluent-plugin-elasticsearch#375]
I've got cluster with following configuration:
- 2 ES master&data nodes
- 2 td-agent nodes with in_forward and out_elasticsearch with elasticsearch client node (data: false, master: false) on each node.

One day ES masters gone down because of memory issues. After recovery td-agents cannot send data to ES:

```
2018-03-03 15:08:12 +0000 [warn]: #0 Could not push logs to Elasticsearch, resetting connection and trying again. Connection reset by peer (Errno::ECONNRESET)
2018-03-03 15:08:14 +0000 [info]: #0 Connection opened to Elasticsearch cluster => {:host=>"localhost", :port=>9200, :scheme=>"http"}
2018-03-03 15:08:14 +0000 [warn]: #0 Could not push logs to Elasticsearch, resetting connection and trying again. Connection reset by peer (Errno::ECONNRESET)
2018-03-03 15:08:14 +0000 [debug]: #0 Created new chunk chunk_id="56683764ad5e859d4104ac357491e5ef" metadata=#<struct Fluent::Plugin::Buffer::Metadata timekey=nil, tag="syslog.daemon.info", variables=nil>
2018-03-03 15:08:18 +0000 [info]: #0 Connection opened to Elasticsearch cluster => {:host=>"localhost", :port=>9200, :scheme=>"http"}
2018-03-03 15:08:18 +0000 [debug]: #0 taking back chunk for errors. chunk="566745dbaa61f7ac3626ec83f956d0c2"
2018-03-03 15:08:18 +0000 [warn]: #0 failed to flush the buffer. retry_time=1 next_retry_seconds=2018-03-03 15:08:08 +0000 chunk="566745dbaa61f7ac3626ec83f956d0c2" error_class=Fluent::Plugin::ElasticsearchOutput::ConnectionFailure error="Could not push logs to Elasticsearch after 2 retries. Connection reset by peer (Errno::ECONNRESET)"
  2018-03-03 15:08:18 +0000 [warn]: #0 suppressed same stacktrace
```

ES node on localhost was actually alive:

```
# curl -XGET localhost:9200
{
  "name" : "harvester-gce-eu-1",
  "cluster_name" : "logs",
  "cluster_uuid" : "BY1pbzMbQJyL3KcgSY3qcA",
  "version" : {
    "number" : "6.2.2",
    "build_hash" : "10b1edd",
    "build_date" : "2018-02-16T19:01:30.685723Z",
    "build_snapshot" : false,
    "lucene_version" : "7.2.1",
    "minimum_wire_compatibility_version" : "5.6.0",
    "minimum_index_compatibility_version" : "5.0.0"
  },
  "tagline" : "You Know, for Search"
}

```
I've used tcpdump to check if there were really resets and found this error message from ES:

`{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"text is empty (possibly HTTP/0.9)"}],"type":"illegal_argument_exception","reason":"text is empty (possibly HTTP/0.9)"},"status":400}  `

output config:

```
<match **>
  @type elasticsearch
  @log_level debug
  host localhost
  port 9200
  target_type_key @target_key
  type_name fluentd
  target_index_key target_index
  logstash_format true
  logstash_prefix fallback
  time_key @timestamp
  include_timestamp true
  reload_on_failure true
  <buffer>
    @type file
    flush_interval 10s
    retry_timeout 10d
    path /var/lib/td-agent/buffers/output_elasticsearch
  </buffer>
</match>
```

2018-03-03 12:30:12 +0000 [info]: gem 'fluent-plugin-elasticsearch' version '2.4.0'
2018-03-03 12:30:12 +0000 [info]: gem 'fluent-plugin-kafka' version '0.6.5'
2018-03-03 12:30:12 +0000 [info]: gem 'fluent-plugin-rewrite-tag-filter' version '2.0.1'
2018-03-03 12:30:12 +0000 [info]: gem 'fluent-plugin-s3' version '1.1.0'
2018-03-03 12:30:12 +0000 [info]: gem 'fluent-plugin-td' version '1.0.0'
2018-03-03 12:30:12 +0000 [info]: gem 'fluent-plugin-td-monitoring' version '0.2.3'
2018-03-03 12:30:12 +0000 [info]: gem 'fluent-plugin-webhdfs' version '1.2.2'
2018-03-03 12:30:12 +0000 [info]: gem 'fluentd' version '1.0.2'```

Ubuntu 14.04
td-agent 1.0.2 (package 3.1.1-0)
elasticsearch 6.2.2

**Comment by cosmo0920** [comment]
Could you set `reconnect_on_error` as true?

```aconf
<match **>
  @type elasticsearch
  @log_level debug
  host localhost
  port 9200
  target_type_key @target_key
  type_name fluentd
  target_index_key target_index
  logstash_format true
  logstash_prefix fallback
  time_key @timestamp
  include_timestamp true
  reload_on_failure true
  <buffer>
    @type file
    flush_interval 10s
    retry_timeout 10d
    path /var/lib/td-agent/buffers/output_elasticsearch
    reconnect_on_error true
  </buffer>
</match>
```

Otherwise, ES plugin still tries to use old invalid connection.

**Comment by cosmo0920** [comment]
I'm closing this issue.
If above solution does not resolve this, please re-open this issue.

**Comment by dmnfortytwo** [comment]
That did not help. I got another ES outage so both of my td-agent nodes are dead.
One without reconnect_on_error setting:
```2018-03-05 15:14:38 +0000 [warn]: #0 Could not push logs to Elasticsearch, resetting connection and trying again. Connection reset by peer (Errno::ECONNRESET)
2018-03-05 15:14:40 +0000 [debug]: #0 Created new chunk chunk_id="566abc8ee9bc92806a2838ebd36bec3a" metadata=#<struct Fluent::Plugin::Buffer::Metadata timekey=nil, tag="syslog.authpriv.info", variables=nil>
2018-03-05 15:14:40 +0000 [info]: #0 Connection opened to Elasticsearch cluster => {:host=>"localhost", :port=>9200, :scheme=>"http"}
2018-03-05 15:14:40 +0000 [warn]: #0 Could not push logs to Elasticsearch, resetting connection and trying again. Connection reset by peer (Errno::ECONNRESET)
2018-03-05 15:14:43 +0000 [debug]: #0 Created new chunk chunk_id="566abc926ad65e6fc30b3279f4b13b21" metadata=#<struct Fluent::Plugin::Buffer::Metadata timekey=nil, tag="parsed.collectd", variables=nil>
2018-03-05 15:14:43 +0000 [debug]: #0 Created new chunk chunk_id="566abc92a75971c0465eece304513767" metadata=#<struct Fluent::Plugin::Buffer::Metadata timekey=nil, tag="parsed.puppet_agent", variables=nil>
2018-03-05 15:14:44 +0000 [info]: #0 Connection opened to Elasticsearch cluster => {:host=>"localhost", :port=>9200, :scheme=>"http"}
2018-03-05 15:14:44 +0000 [debug]: #0 taking back chunk for errors. chunk="566745dbaa61f7ac3626ec83f956d0c2"
2018-03-05 15:14:44 +0000 [warn]: #0 failed to flush the buffer. retry_time=4 next_retry_seconds=2018-03-05 15:14:34 +0000 chunk="566745dbaa61f7ac3626ec83f956d0c2" error_class=Fluent::Plugin::ElasticsearchOutput::ConnectionFailure error="Could not push logs to Elasticsearch after 2 retries. Broken pipe (Errno::EPIPE)"
  2018-03-05 15:14:44 +0000 [warn]: #0 suppressed same stacktrace
```
Second with reconnect_on_error true:

```2018-03-05 15:12:14 +0000 [info]: #0 fluentd worker is now running worker=0
2018-03-05 15:12:15 +0000 [info]: #0 Connection opened to Elasticsearch cluster => {:host=>"localhost", :port=>9200, :scheme=>"http"}
2018-03-05 15:12:45 +0000 [warn]: #0 Could not push logs to Elasticsearch, resetting connection and trying again. read timeout reached
2018-03-05 15:12:45 +0000 [info]: #0 Connection opened to Elasticsearch cluster => {:host=>"localhost", :port=>9200, :scheme=>"http"}
2018-03-05 15:13:16 +0000 [warn]: #0 Could not push logs to Elasticsearch, resetting connection and trying again. read timeout reached
2018-03-05 15:13:16 +0000 [info]: #0 Connection opened to Elasticsearch cluster => {:host=>"localhost", :port=>9200, :scheme=>"http"}
2018-03-05 15:13:46 +0000 [warn]: #0 failed to flush the buffer. retry_time=0 next_retry_seconds=2018-03-05 15:13:47 +0000 chunk="5669a687fd2ca86a68ff4ea7851af034" error_class=Fluent::Plugin::ElasticsearchOutput::ConnectionFailure error="Could not push logs to Elasticsearch after 2 retries. read timeout reached"
  2018-03-05 15:13:46 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-elasticsearch-2.4.0/lib/fluent/plugin/out_elasticsearch.rb:438:in `rescue in send_bulk'
  2018-03-05 15:13:46 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-elasticsearch-2.4.0/lib/fluent/plugin/out_elasticsearch.rb:424:in `send_bulk'
  2018-03-05 15:13:46 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-elasticsearch-2.4.0/lib/fluent/plugin/out_elasticsearch.rb:411:in `write'
  2018-03-05 15:13:46 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.0.2/lib/fluent/plugin/output.rb:1093:in `try_flush'
  2018-03-05 15:13:46 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.0.2/lib/fluent/plugin/output.rb:1318:in `flush_thread_run'
  2018-03-05 15:13:46 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.0.2/lib/fluent/plugin/output.rb:439:in `block (2 levels) in start'
  2018-03-05 15:13:46 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.0.2/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
2018-03-05 15:14:19 +0000 [warn]: #0 Could not push logs to Elasticsearch, resetting connection and trying again. read timeout reached
2018-03-05 15:14:21 +0000 [info]: #0 Connection opened to Elasticsearch cluster => {:host=>"localhost", :port=>9200, :scheme=>"http"}
2018-03-05 15:14:51 +0000 [warn]: #0 Could not push logs to Elasticsearch, resetting connection and trying again. read timeout reached
2018-03-05 15:14:55 +0000 [info]: #0 Connection opened to Elasticsearch cluster => {:host=>"localhost", :port=>9200, :scheme=>"http"}
```

**Comment by dmnfortytwo** [comment]
It works well.
I had to clean indices which were created during outage because they were abnormal large (~600M records per day vs 1M usual) and kibana timed out when I tried to browse it, but now cluster looks green and shiny.

**Comment by dmnfortytwo** [comment]
I've just renamed es buffer directory on one td-agent node and restarted td-agent. Works like a charm. But there are two questions:
- How can I push old data to es?
- What shall I do after next es outage?

**Comment by dmnfortytwo** [comment]
Again same problem. No ES outage this time, output just silently stopped working and after restart I got this in log: 

```
2018-03-05 19:24:12 +0000 [warn]: #0 Could not push logs to Elasticsearch, resetting connection and trying again. Broken pipe (Errno::EPIPE)
2018-03-05 19:24:14 +0000 [info]: #0 Connection opened to Elasticsearch cluster => {:host=>"localhost", :port=>9200, :scheme=>"http"}
2018-03-05 19:24:14 +0000 [warn]: #0 Could not push logs to Elasticsearch, resetting connection and trying again. Connection reset by peer (Errno::ECONNRESET)
2018-03-05 19:24:18 +0000 [info]: #0 Connection opened to Elasticsearch cluster => {:host=>"localhost", :port=>9200, :scheme=>"http"}
2018-03-05 19:24:18 +0000 [warn]: #0 failed to flush the buffer. retry_time=6 next_retry_seconds=2018-03-05 19:24:07 +0000 chunk="566af1e7840e344fba5a650e354d9c07" error_class=Fluent::Plugin::ElasticsearchOutput::ConnectionFailure error="Could not push logs to Elasticsearch after 2 retries. Connection reset by peer (Errno::ECONNRESET)"
  2018-03-05 19:24:18 +0000 [warn]: #0 suppressed same stacktrace
2018-03-05 19:25:30 +0000 [warn]: #0 Could not push logs to Elasticsearch, resetting connection and trying again. Connection reset by peer (Errno::ECONNRESET)
2018-03-05 19:25:32 +0000 [info]: #0 Connection opened to Elasticsearch cluster => {:host=>"localhost", :port=>9200, :scheme=>"http"}
2018-03-05 19:25:32 +0000 [warn]: #0 Could not push logs to Elasticsearch, resetting connection and trying again. Connection reset by peer (Errno::ECONNRESET)
```

```
root@harvester-gce-eu-1:/var/lib/td-agent/buffers# curl -XGET 'localhost:9200/_cluster/health?pretty'
{
  "cluster_name" : "logs",
  "status" : "green",
  "timed_out" : false,
  "number_of_nodes" : 6,
  "number_of_data_nodes" : 2,
  "active_primary_shards" : 1854,
  "active_shards" : 3708,
  "relocating_shards" : 0,
  "initializing_shards" : 0,
  "unassigned_shards" : 0,
  "delayed_unassigned_shards" : 0,
  "number_of_pending_tasks" : 0,
  "number_of_in_flight_fetch" : 0,
  "task_max_waiting_in_queue_millis" : 0,
  "active_shards_percent_as_number" : 100.0
}
```

**Comment by cosmo0920** [comment]
How about the following configuration?

```aconf
Could you set `reconnect_on_error` as true?

```aconf
<match **>
  @type elasticsearch
  @log_level debug
  host localhost
  port 9200
  target_type_key @target_key
  type_name fluentd
  target_index_key target_index
  logstash_format true
  logstash_prefix fallback
  time_key @timestamp
  include_timestamp true
  reload_on_failure true
  reconnect_on_error true
  with_transporter_log true
  <buffer>
    @type file
    flush_interval 10s
    retry_timeout 10d
    path /var/lib/td-agent/buffers/output_elasticsearch
  </buffer>
</match>
```

**Comment by cosmo0920** [comment]
ES plugin's default behavior is throwing away transporter log.
This behavior sometimes hides what causes error.

**Comment by dmnfortytwo** [comment]
```
2018-03-06 07:43:27 +0000 [info]: #0 Connection opened to Elasticsearch cluster => {:host=>"localhost", :port=>9200, :scheme=>"http"}
2018-03-06 07:43:57 +0000 [warn]: #0 Could not push logs to Elasticsearch, resetting connection and trying again. read timeout reached
2018-03-06 07:43:59 +0000 [info]: #0 Connection opened to Elasticsearch cluster => {:host=>"localhost", :port=>9200, :scheme=>"http"}
2018-03-06 07:44:29 +0000 [warn]: #0 Could not push logs to Elasticsearch, resetting connection and trying again. read timeout reached
2018-03-06 07:44:31 +0000 [info]: #0 Connection opened to Elasticsearch cluster => {:host=>"localhost", :port=>9200, :scheme=>"http"}
2018-03-06 07:45:02 +0000 [debug]: #0 taking back chunk for errors. chunk="5669a687fd2ca86a68ff4ea7851af034"
2018-03-06 07:45:02 +0000 [warn]: #0 failed to flush the buffer. retry_time=0 next_retry_seconds=2018-03-06 07:45:03 +0000 chunk="5669a687fd2ca86a68ff4ea7851af034" error_class=Fluent::Plugin::ElasticsearchOutput::ConnectionFailure error="Could not push logs to Elasticsearch after 2 retries. read timeout reached"
  2018-03-06 07:45:02 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-elasticsearch-2.4.0/lib/fluent/plugin/out_elasticsearch.rb:438:in `rescue in send_bulk'
  2018-03-06 07:45:02 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-elasticsearch-2.4.0/lib/fluent/plugin/out_elasticsearch.rb:424:in `send_bulk'
  2018-03-06 07:45:02 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-elasticsearch-2.4.0/lib/fluent/plugin/out_elasticsearch.rb:411:in `write'
  2018-03-06 07:45:02 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.0.2/lib/fluent/plugin/output.rb:1093:in `try_flush'
  2018-03-06 07:45:02 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.0.2/lib/fluent/plugin/output.rb:1318:in `flush_thread_run'
  2018-03-06 07:45:02 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.0.2/lib/fluent/plugin/output.rb:439:in `block (2 levels) in start'
  2018-03-06 07:45:02 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.0.2/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
2018-03-06 07:45:34 +0000 [warn]: #0 Could not push logs to Elasticsearch, resetting connection and trying again. read timeout reached
2018-03-06 07:45:36 +0000 [info]: #0 Connection opened to Elasticsearch cluster => {:host=>"localhost", :port=>9200, :scheme=>"http"}
2018-03-06 07:46:07 +0000 [warn]: #0 Could not push logs to Elasticsearch, resetting connection and trying again. read timeout reached
2018-03-06 07:46:11 +0000 [info]: #0 Connection opened to Elasticsearch cluster => {:host=>"localhost", :port=>9200, :scheme=>"http"}
2018-03-06 07:46:41 +0000 [debug]: #0 taking back chunk for errors. chunk="5669a687fd2ca86a68ff4ea7851af034"
2018-03-06 07:46:41 +0000 [warn]: #0 failed to flush the buffer. retry_time=0 next_retry_seconds=2018-03-06 07:45:03 +0000 chunk="5669a687fd2ca86a68ff4ea7851af034" error_class=Fluent::Plugin::ElasticsearchOutput::ConnectionFailure error="Could not push logs to Elasticsearch after 2 retries. read timeout reached"
  2018-03-06 07:46:41 +0000 [warn]: #0 suppressed same stacktrace
2018-03-06 07:47:13 +0000 [warn]: #0 Could not push logs to Elasticsearch, resetting connection and trying again. read timeout reached

```

+ some messages like

` 2018-03-06 07:50:14 +0000 [debug]: #0 Created new chunk chunk_id="566b9b15ba8ee6ad8f52711a1d528bda" metadata=#<struct Fluent::Plugin::Buffer::Metadata timekey=nil, tag="syslog.auth.info", variables=nil>`

**Comment by dmnfortytwo** [comment]
Set java heap to 8gb (node has 32g memory). Nothing changed.
ES node on localhost is ingest only, data nodes are separate.

**Comment by cosmo0920** [comment]
https://github.com/uken/fluent-plugin-elasticsearch/issues/205 seems to be same issue.
Too many connections are opened between ES plugin and ES cluster.

**Comment by dmnfortytwo** [comment]
```
<match **>
  @type elasticsearch
  @log_level debug
  host localhost
  port 9200
  target_type_key @target_key
  type_name fluentd
  target_index_key target_index
  logstash_format true
  logstash_prefix fallback
  time_key @timestamp
  include_timestamp true
  reload_on_failure true
  reconnect_on_error true
  with_transporter_log true
  buffer_chunk_limit 4m
  buffer_queue_limit 32
  reload_connections false
  <buffer>
    @type file
    flush_interval 10s
    retry_timeout 10d
    path /var/lib/td-agent/buffers/output_elasticsearch
  </buffer>
</match>

```

Nothing changed

**Comment by dmnfortytwo** [comment]
```
root@harvester-gce-eu-2:/var/log/td-agent# netstat -anp | grep 9200
tcp        0      0 127.0.0.1:42520         127.0.0.1:9200          TIME_WAIT   -               
tcp        0      0 127.0.0.1:42518         127.0.0.1:9200          TIME_WAIT   -               
tcp        0      0 127.0.0.1:42528         127.0.0.1:9200          TIME_WAIT   -               
tcp        0      0 127.0.0.1:42534         127.0.0.1:9200          ESTABLISHED 5885/ruby       
tcp        0      0 127.0.0.1:42524         127.0.0.1:9200          TIME_WAIT   -               
tcp        0      0 127.0.0.1:42530         127.0.0.1:9200          TIME_WAIT   -               
tcp        0      0 127.0.0.1:42514         127.0.0.1:9200          TIME_WAIT   -               
tcp        0      0 127.0.0.1:42522         127.0.0.1:9200          TIME_WAIT   -               
tcp        0      0 127.0.0.1:42512         127.0.0.1:9200          TIME_WAIT   -               
tcp        0      0 127.0.0.1:42526         127.0.0.1:9200          TIME_WAIT   -               
tcp        0      0 127.0.0.1:42506         127.0.0.1:9200          TIME_WAIT   -               
tcp        0      0 127.0.0.1:42508         127.0.0.1:9200          TIME_WAIT   -               
tcp        0      0 127.0.0.1:42510         127.0.0.1:9200          TIME_WAIT   -               
tcp6       0      0 :::9200                 :::*                    LISTEN      4619/java       
tcp6       0      0 127.0.0.1:9200          127.0.0.1:42534         ESTABLISHED 4619/java 
```

**Comment by cosmo0920** [comment]
I have no idea GCE limitation, but it seems to be left listening 9200/tcp connections.

**Comment by dmnfortytwo** [comment]
What do you mean?
Its a general linux node, no special cloud limitations.

**Comment by dmnfortytwo** [comment]
Well.. I've reduced java heap on ES data nodes from 30g to 16g (with total of 54g mem) and make output look like this:
```
<match **>
  @type elasticsearch
  host localhost
  port 9200
  target_type_key @target_key
  type_name fluentd
  target_index_key target_index
  logstash_format true
  logstash_prefix fallback
  time_key @timestamp
  include_timestamp true
  reload_on_failure true
  reconnect_on_error true
  with_transporter_log true
  buffer_chunk_limit 16m
  buffer_queue_limit 4
  reload_connections false
  <buffer>
    @type file
    flush_interval 10s
    retry_timeout 10d
    path /var/lib/td-agent/buffers/output_elasticsearch
  </buffer>
</match>
```
aand it works. Kinda slow, but buffer directory reduces in size.

**Comment by dmnfortytwo** [comment]
Please also see #378

**Comment by cosmo0920** [comment]
You should set JVM heap size not to be exceeded 27GB.
Because 30GB JVM heap size steals memory cache which is managed by operating system.
