### ISSUE TITLE
elasticsearch_dynamic doesn't send logs at all when it can not reach Elasticsearch 

### ISSUE THREAD

**Issue by ahrtr** [uken/fluent-plugin-elasticsearch#424]
There are two elasticsearch clusters, which can be reached using http://${record['tenantid']}-elasticsearch:9200.  I use elasticsearch_dynamic to send each log to the correct elasticsearch dynamically. The configuration for the output plugin is as below. Basically it's working well. Once I provide a wrong tenantid in a log entry, then fluentd can't reach the elasticsearch, and it keeps trying. It's fine, but the issue is that it doesn't send any other normal log entries any more, even they have correct tenantid. 
 
```
      @type elasticsearch_dynamic
      host ${record['tenantid']}-elasticsearch
      port 9200
      index_name ${record['target_index']}
      <buffer>
          @type memory
          retry_type periodic
          retry_randomize false
          retry_timeout 1h

          flush_mode interval
          flush_interval 10s

          chunk_limit_size 1MB
          total_limit_size 64MB
          chunk_limit_records 10
      </buffer>
    </match>
```

The versions are as below:

> fluentd: 1.1.3
> fluent-plugin-elasticsearch :2.9.2

**Comment by cosmo0920** [comment]
Could you paste stacktrace without sensitive information?
Basically, it is hard to solve this issue.
ES dynamic plugin might fail to send because sending targets will be evaluated each chunk.
One chunk can be send but the other chunk might fail to send.

**Comment by ahrtr** [comment]
Sure, will provide more details soon. 

Just to double confirm, the fluent-plugin-elasticsearch will never get two log entries with different elasticsearch targets included in the same chunk, correct? In other words, all log entries included in a chunk have the same target?

**Comment by cosmo0920** [comment]
I have no idea without stack trace
Because ES dynamic plugin uses Ruby’s black magic. :imp:.

**Comment by ahrtr** [comment]
2018-05-26 02:32:09 +0000 [info]: starting fluentd-1.1.3 pid=6 ruby="2.3.3"
2018-05-26 02:32:09 +0000 [info]: spawn command to main:  cmdline=["/usr/bin/ruby2.3", "-Eascii-8bit:ascii-8bit", "/fluentd/vendor/bundle/ruby/2.3.0/bin/fluentd", "-c", "/fluentd/etc/fluentd.conf", "-p", "/fluentd/plugins", "--gemfile", "/fluentd/Gemfile", "--under-supervisor"]
2018-05-26 02:32:09 +0000 [info]: gem 'fluent-plugin-elasticsearch' version '2.9.2'
2018-05-26 02:32:09 +0000 [info]: gem 'fluent-plugin-kubernetes_metadata_filter' version '2.0.0'
2018-05-26 02:32:09 +0000 [info]: gem 'fluent-plugin-systemd' version '1.0.0'
2018-05-26 02:32:09 +0000 [info]: gem 'fluentd' version '1.1.3'
2018-05-26 02:32:09 +0000 [info]: adding filter pattern="audit.log" type="grep"
2018-05-26 02:32:09 +0000 [info]: adding filter pattern="audit.log" type="parser"
2018-05-26 02:32:09 +0000 [info]: adding match pattern="audit.log" type="elasticsearch_dynamic"
2018-05-26 02:32:09 +0000 [info]: adding source type="tail"
2018-05-26 02:32:09 +0000 [warn]: parameter 'retry' in <buffer>
  @type "memory"
  retry timeout 1h
  retry_type periodic
  retry_randomize false
  flush_mode interval
  flush_interval 10s
  chunk_limit_size 1MB
  total_limit_size 64MB
  chunk_limit_records 10
</buffer> is not used.
2018-05-26 02:32:09 +0000 [info]: #0 starting fluentd worker pid=12 ppid=6 worker=0
2018-05-26 02:32:09 +0000 [info]: #0 following tail of /var/lib/docker/containers/ae83090dadc5b25e3012b8363c9d3106b81a1a785126ea255f3e2c5f50a7eb28/ae83090dadc5b25e3012b8363c9d3106b81a1a785126ea255f3e2c5f50a7eb28-json.log
2018-05-26 02:32:09 +0000 [info]: #0 following tail of /var/lib/docker/containers/6a57199ef840b652c5a30df106fd6f163f4eacb78f914c686277eed4bf709863/6a57199ef840b652c5a30df106fd6f163f4eacb78f914c686277eed4bf709863-json.log
......
......
......
2018-05-26 02:32:09 +0000 [info]: #0 fluentd worker is now running worker=0
2018-05-26 02:39:26 +0000 [warn]: #0 failed to flush the buffer. retry_time=0 next_retry_seconds=2018-05-26 02:39:27 +0000 chunk="56d12ca698c259646320ccd107d067cb" error_class=Fluent::Plugin::ElasticsearchOutput::ConnectionFailure error="Can not reach Elasticsearch cluster ({:host=>\"wrongtenantid-elasticsearch\", :port=>9200, :scheme=>\"http\"})!"
  2018-05-26 02:39:26 +0000 [warn]: #0 /fluentd/vendor/bundle/ruby/2.3.0/gems/fluent-plugin-elasticsearch-2.9.2/lib/fluent/plugin/out_elasticsearch_dynamic.rb:67:in `client'
  2018-05-26 02:39:26 +0000 [warn]: #0 /fluentd/vendor/bundle/ruby/2.3.0/gems/fluent-plugin-elasticsearch-2.9.2/lib/fluent/plugin/out_elasticsearch_dynamic.rb:226:in `rescue in send_bulk'
  2018-05-26 02:39:26 +0000 [warn]: #0 /fluentd/vendor/bundle/ruby/2.3.0/gems/fluent-plugin-elasticsearch-2.9.2/lib/fluent/plugin/out_elasticsearch_dynamic.rb:221:in `send_bulk'
  2018-05-26 02:39:26 +0000 [warn]: #0 /fluentd/vendor/bundle/ruby/2.3.0/gems/fluent-plugin-elasticsearch-2.9.2/lib/fluent/plugin/out_elasticsearch_dynamic.rb:214:in `block in write'
  2018-05-26 02:39:26 +0000 [warn]: #0 /fluentd/vendor/bundle/ruby/2.3.0/gems/fluent-plugin-elasticsearch-2.9.2/lib/fluent/plugin/out_elasticsearch_dynamic.rb:213:in `each'
  2018-05-26 02:39:26 +0000 [warn]: #0 /fluentd/vendor/bundle/ruby/2.3.0/gems/fluent-plugin-elasticsearch-2.9.2/lib/fluent/plugin/out_elasticsearch_dynamic.rb:213:in `write'
  2018-05-26 02:39:26 +0000 [warn]: #0 /fluentd/vendor/bundle/ruby/2.3.0/gems/fluentd-1.1.3/lib/fluent/plugin/output.rb:1096:in `try_flush'
  2018-05-26 02:39:26 +0000 [warn]: #0 /fluentd/vendor/bundle/ruby/2.3.0/gems/fluentd-1.1.3/lib/fluent/plugin/output.rb:1329:in `flush_thread_run'
  2018-05-26 02:39:26 +0000 [warn]: #0 /fluentd/vendor/bundle/ruby/2.3.0/gems/fluentd-1.1.3/lib/fluent/plugin/output.rb:439:in `block (2 levels) in start'
  2018-05-26 02:39:26 +0000 [warn]: #0 /fluentd/vendor/bundle/ruby/2.3.0/gems/fluentd-1.1.3/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
2018-05-26 02:39:27 +0000 [warn]: #0 failed to flush the buffer. retry_time=0 next_retry_seconds=2018-05-26 02:39:27 +0000 chunk="56d12ca698c259646320ccd107d067cb" error_class=Fluent::Plugin::ElasticsearchOutput::ConnectionFailure error="Can not reach Elasticsearch cluster ({:host=>\"wrongtenantid-elasticsearch\", :port=>9200, :scheme=>\"http\"})!"
  2018-05-26 02:39:27 +0000 [warn]: #0 suppressed same stacktrace
2018-05-26 02:39:28 +0000 [warn]: #0 failed to flush the buffer. retry_time=1 next_retry_seconds=2018-05-26 02:39:28 +0000 chunk="56d12ca698c259646320ccd107d067cb" error_class=Fluent::Plugin::ElasticsearchOutput::ConnectionFailure error="Can not reach Elasticsearch cluster ({:host=>\"wrongtenantid-elasticsearch\", :port=>9200, :scheme=>\"http\"})!"
  2018-05-26 02:39:28 +0000 [warn]: #0 suppressed same stacktrace
2018-05-26 02:39:30 +0000 [warn]: #0 failed to flush the buffer. retry_time=2 next_retry_seconds=2018-05-26 02:39:29 +0000 chunk="56d12ca698c259646320ccd107d067cb" error_class=Fluent::Plugin::ElasticsearchOutput::ConnectionFailure error="Can not reach Elasticsearch cluster ({:host=>\"wrongtenantid-elasticsearch\", :port=>9200, :scheme=>\"http\"})!"
  2018-05-26 02:39:30 +0000 [warn]: #0 suppressed same stacktrace
2018-05-26 02:39:31 +0000 [warn]: #0 failed to flush the buffer. retry_time=3 next_retry_seconds=2018-05-26 02:39:31 +0000 chunk="56d12ca698c259646320ccd107d067cb" error_class=Fluent::Plugin::ElasticsearchOutput::ConnectionFailure error="Can not reach Elasticsearch cluster ({:host=>\"wrongtenantid-elasticsearch\", :port=>9200, :scheme=>\"http\"})!"
  2018-05-26 02:39:31 +0000 [warn]: #0 suppressed same stacktrace
......
......
......

**Comment by ahrtr** [comment]
One related minor issue is that I configured "retry wait  5", but it seems that the actually retry interval was 1 second.

**Comment by cosmo0920** [comment]
I guess that it might be related to Fluentd core issue: https://github.com/fluent/fluentd/issues/1967

**Comment by ahrtr** [comment]
I just did some tests, it seems that the all log entries with different elasticsearch targets were included in the same chunk, it's exactly the reason why other normal log entries were not sent either. 

Let's work with an example. I generated two log entries, one of them had a wrong tenantid, and the other had a correct tenantid, so they had different targets, which were http://wrongtenantid.elasticsearch:9200 and http://tenant1.elasticsearch:9200 respectively. 

My expectation was that the output plugin should keep trying sending the first one per the retry configuration, and the second one should can be sent out successfully. But actually oth of them were included in the same chunk, and the output plugin kept retrying using the wrong target http://wrongtenantid.elasticsearch:9200, and eventually all of them were dropped when maximum retry times or retry timeout were reached. 

So the log entries with different targets should be included in different chunks.

**Comment by cosmo0920** [comment]
> My expectation was that the output plugin should keep trying sending the first one per the retry configuration, and the second one should can be sent out in a separate chunk successfully. But actually both of them were included in the same chunk, and the output plugin kept retrying using the wrong target http://wrongtenantid.elasticsearch:9200, and eventually all of them were dropped when maximum retry times or retry timeout were reached.

Currently, only one connection is cached.

> So the log entries with different targets should be included in different chunks.

How about use the following buffer configuration?
The following configuration will separate chunk with tenantid in chunk.

```aconf
﻿    <match **>
      @type elasticsearch_dynamic
      host ${record['tenantid']}-elasticsearch
      port 9200
      index_name ${record['target_index']}
      <buffer tag, tenantid>
          @type memory
          retry_type periodic
          retry_randomize false
          retry_timeout 1h

          flush_mode interval
          flush_interval 10s

          chunk_limit_size 1MB
          total_limit_size 64MB
          chunk_limit_records 10
      </buffer>
    </match>
```

**Comment by ahrtr** [comment]
Thanks for the response.

I tried your configuration, and it did not work. I generated three log entries, the first one had a wrong tenantid, and the other two had correct tenantid. But it seemed that all of them were dropped when hitting limit.  

> 2018-05-26 04:09:01 +0000 [error]: #0 failed to flush the buffer, and hit limit for retries. dropping all chunks in the buffer queue. retry_times=5 records=3 error_class=Fluent::Plugin::ElasticsearchOutput::ConnectionFailure error="Can not reach Elasticsearch cluster ({:host=>\"usdef73zj3zhwspjpc5r-elasticsearch\", :port=>9200, :scheme=>\"http\"})!"
>   2018-05-26 04:09:01 +0000 [error]: #0 suppressed same stacktrace

Another concern is that why 'tag' must be included in buffer key list? Based on my test, indeed the 'tag' must be included. But  I just saw an example without including tag in fluentd official site. 
https://docs.fluentd.org/v1.0/articles/buffer-section#other-keys

**Comment by cosmo0920** [comment]
> If only one connection is cached, then it should be a bug of elasticsearch_dynamic. What do you think?

This is not bug.
If it’s true,  elasticsearch_dynamic should cache infinite connection.
Because elasticsearch_dynamic can send log different elasticsearch clusters in every request.

> Another concern is that why 'tag' must be included in buffer key list? Based on my test, indeed the 'tag' must be included. But I just saw an example without including tag in fluentd official site.
https://docs.fluentd.org/v1.0/articles/buffer-section#other-keys

This is not always needed. Buffer directive attributes are used in separating chunk mechanism.

When using `<buffer tag>` , chunks will be separated with tag.
When using `<buffer YOUR_KEY_IN_RECORD>`, chunks will be separated with a custom key in record.

**Comment by cosmo0920** [comment]
> It seems that what you said "only one connection is cached" means that there is only one worker. In other words, the output plugin can only send one chuck each time. Please correct me if I am wrong.

:+1:

> Anyway, I tried <buffer, tag, tenantid>, and fluentd could be started successfully. But it seemed that different log entries with different elasticsearch targets were still included in one chunk, and all of them were dropped at the end

Huh!?
https://docs.fluentd.org/v1.0/articles/buffer-section#chunk-keys says that using custom key will split chunk per custom key.

**Comment by ahrtr** [comment]
Yes, I saw the official guide as well.  But it did not work anway.

I am still confused why `<buffer tenantid>` did not work.  It should work per the following guide, 
https://docs.fluentd.org/v1.0/articles/buffer-section#other-keys

**Comment by cosmo0920** [comment]
Could you report documentaion issue in [fluentd-docs](https://github.com/fluent/fluentd-docs) repository?
Documentation issue should report there.

**Comment by ahrtr** [comment]
#https://github.com/fluent/fluentd-docs/issues/499

**Comment by cosmo0920** [comment]
This issue should solve with https://github.com/uken/fluent-plugin-elasticsearch/pull/433.
