### ISSUE TITLE
java.lang.IllegalArgumentException: Rejecting mapping update to [logstash-2018.07.05] as the final mapping would have more than 1 type: [event, fluentd]

### ISSUE THREAD

**Issue by UncleTawnos** [uken/fluent-plugin-elasticsearch#442]
#### Problem
ES 6.x can have only one mapping per index, fluent is trying to create two

```[2018-07-05T12:42:27,616][DEBUG][o.e.a.b.TransportShardBulkAction] [logstash-2018.07.05][4] failed to execute bulk item (index) BulkShardRequest [[logstash-2018.07.05][4]] containing [127] requests
java.lang.IllegalArgumentException: Rejecting mapping update to [logstash-2018.07.05] as the final mapping would have more than 1 type: [event, fluentd]
        at org.elasticsearch.index.mapper.MapperService.internalMerge(MapperService.java:501) ~[elasticsearch-6.2.2.jar:6.2.2]
        at org.elasticsearch.index.mapper.MapperService.internalMerge(MapperService.java:353) ~[elasticsearch-6.2.2.jar:6.2.2]
        at org.elasticsearch.index.mapper.MapperService.merge(MapperService.java:285) ~[elasticsearch-6.2.2.jar:6.2.2]
        at org.elasticsearch.cluster.metadata.MetaDataMappingService$PutMappingExecutor.applyRequest(MetaDataMappingService.java:313) ~[elasticsearch-6.2.2.jar:6.2.2]
        at org.elasticsearch.cluster.metadata.MetaDataMappingService$PutMappingExecutor.execute(MetaDataMappingService.java:230) ~[elasticsearch-6.2.2.jar:6.2.2]
        at org.elasticsearch.cluster.service.MasterService.executeTasks(MasterService.java:643) ~[elasticsearch-6.2.2.jar:6.2.2]
        at org.elasticsearch.cluster.service.MasterService.calculateTaskOutputs(MasterService.java:273) ~[elasticsearch-6.2.2.jar:6.2.2]
        at org.elasticsearch.cluster.service.MasterService.runTasks(MasterService.java:198) ~[elasticsearch-6.2.2.jar:6.2.2]
        at org.elasticsearch.cluster.service.MasterService$Batcher.run(MasterService.java:133) ~[elasticsearch-6.2.2.jar:6.2.2]
        at org.elasticsearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:150) ~[elasticsearch-6.2.2.jar:6.2.2]
        at org.elasticsearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:188) ~[elasticsearch-6.2.2.jar:6.2.2]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:573) ~[elasticsearch-6.2.2.jar:6.2.2]
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:244) ~[elasticsearch-6.2.2.jar:6.2.2]
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:207) ~[elasticsearch-6.2.2.jar:6.2.2]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_161]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_161]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
```

When index is created, it contains `events` mapping by default
```
{
  "logstash-2018.07.05": {
    "aliases": {},
    "mappings": {
      "event": {
        "date_detection": false
      }
    },
    "settings": {
      "index": {
        "creation_date": "1530794406884",
        "number_of_shards": "5",
        "number_of_replicas": "1",
        "uuid": "huAAae5eQW2JyhH8xtHA-A",
        "version": {
          "created": "6020299"
        },
        "provided_name": "logstash-2018.07.05"
      }
    }
  }
}
```
While doing bulk update, fluentd is creating `fluentd` mapping which breaks things

#### Steps to replicate
1. Deploy fluentd-daemonset fluent/fluentd-kubernetes-daemonset:v1.2-debian-elasticsearch
2. Connect to ES 6.2
3. Observe ES logs

#### Expected Behavior or What you need to ask
Indexes beeing populated with data

Issue is very similar to #412

#### Using Fluentd and ES plugin versions

* Fluentd v1.2.2
* fluent-plugin-elasticsearch (2.11.1)
* Gemfile https://github.com/fluent/fluentd-kubernetes-daemonset/blob/master/docker-image/v1.2/debian-elasticsearch/Gemfile.lock
* ES version 6.2-oss

**Comment by cosmo0920** [comment]
Could you try to specify `type_name event` explicitly in configuration?

**Comment by UncleTawnos** [comment]
that seems to at works, data is populating into indices, I will run some tests and share my findings

**Comment by lawliet89** [comment]
@UncleTawnos Are you using the `elasticsearch_dynamic` variant of the plugin instead of `elasticsearch`?

I notice that in the "static" variant, there is [code](https://github.com/uken/fluent-plugin-elasticsearch/blob/838190ac1f52a368769767cc2aedaf58e56611be/lib/fluent/plugin/out_elasticsearch.rb#L494-L515) to prevent setting `_type` to anything other than `_doc`, but this behaviour is not present in the [dynamic](https://github.com/uken/fluent-plugin-elasticsearch/blob/838190ac1f52a368769767cc2aedaf58e56611be/lib/fluent/plugin/out_elasticsearch_dynamic.rb#L189) version. Maybe this is the cause of the issue?

**Comment by UncleTawnos** [comment]
what do you mean by confirming payload?

**Comment by cosmo0920** [comment]
I mean that adding `p bulk_messages` above [the line](https://github.com/uken/fluent-plugin-elasticsearch/blob/838190ac1f52a368769767cc2aedaf58e56611be/lib/fluent/plugin/out_elasticsearch.rb#L447) and check dumped messages.

And it seems that `type_name fluentd` is suitable for your situation.

**Comment by cosmo0920** [comment]
I've sent the PR https://github.com/fluent/fluentd-kubernetes-daemonset/pull/185.

**Comment by cosmo0920** [comment]
It seems that specifying type_name fluentd is an solution for this issue.
If you encounter same problem about this. please reopen or comment on this issue.

**Comment by UncleTawnos** [comment]
confirm, works now correctly
