### ISSUE TITLE
Support `${tag}` for dynamic configuration

### ISSUE THREAD

**Issue by lawliet89** [uken/fluent-plugin-elasticsearch#448]
#### Problem
I would like to suggest adding `${tag}` for dynamic configuration

#### Steps to replicate

If I use `${tag}` now as below:

```
<match xxx.** yy.** zz.**>
    @type elasticsearch_dynamic
    host xxx
    scheme https
    logstash_format true
    logstash_prefix "${tag}"
    port 1234
</match>

```

I get the following stack trace:

```
/usr/lib/ruby/gems/2.4.0/gems/fluent-plugin-elasticsearch-2.11.1/lib/fluent/plugin/out_elasticsearch_dynamic.rb:268:in `sub!': no implicit conversion of nil into String (TypeError)
	from /usr/lib/ruby/gems/2.4.0/gems/fluent-plugin-elasticsearch-2.11.1/lib/fluent/plugin/out_elasticsearch_dynamic.rb:268:in `expand_param'
	from /usr/lib/ruby/gems/2.4.0/gems/fluent-plugin-elasticsearch-2.11.1/lib/fluent/plugin/out_elasticsearch_dynamic.rb:24:in `block in configure'
	from /usr/lib/ruby/gems/2.4.0/gems/fluent-plugin-elasticsearch-2.11.1/lib/fluent/plugin/out_elasticsearch_dynamic.rb:23:in `each'
	from /usr/lib/ruby/gems/2.4.0/gems/fluent-plugin-elasticsearch-2.11.1/lib/fluent/plugin/out_elasticsearch_dynamic.rb:23:in `each_with_index'
	from /usr/lib/ruby/gems/2.4.0/gems/fluent-plugin-elasticsearch-2.11.1/lib/fluent/plugin/out_elasticsearch_dynamic.rb:23:in `configure'
	from /usr/lib/ruby/gems/2.4.0/gems/fluentd-1.2.3/lib/fluent/plugin.rb:164:in `configure'
	from /usr/lib/ruby/gems/2.4.0/gems/fluentd-1.2.3/lib/fluent/plugin/multi_output.rb:74:in `block in configure'
	from /usr/lib/ruby/gems/2.4.0/gems/fluentd-1.2.3/lib/fluent/plugin/multi_output.rb:63:in `each'
	from /usr/lib/ruby/gems/2.4.0/gems/fluentd-1.2.3/lib/fluent/plugin/multi_output.rb:63:in `configure'
	from /usr/lib/ruby/gems/2.4.0/gems/fluentd-1.2.3/lib/fluent/plugin/out_copy.rb:36:in `configure'
	from /usr/lib/ruby/gems/2.4.0/gems/fluentd-1.2.3/lib/fluent/plugin.rb:164:in `configure'
	from /usr/lib/ruby/gems/2.4.0/gems/fluentd-1.2.3/lib/fluent/agent.rb:130:in `add_match'
	from /usr/lib/ruby/gems/2.4.0/gems/fluentd-1.2.3/lib/fluent/agent.rb:72:in `block in configure'
	from /usr/lib/ruby/gems/2.4.0/gems/fluentd-1.2.3/lib/fluent/agent.rb:64:in `each'
	from /usr/lib/ruby/gems/2.4.0/gems/fluentd-1.2.3/lib/fluent/agent.rb:64:in `configure'
	from /usr/lib/ruby/gems/2.4.0/gems/fluentd-1.2.3/lib/fluent/root_agent.rb:112:in `configure'
	from /usr/lib/ruby/gems/2.4.0/gems/fluentd-1.2.3/lib/fluent/engine.rb:131:in `configure'
	from /usr/lib/ruby/gems/2.4.0/gems/fluentd-1.2.3/lib/fluent/engine.rb:96:in `run_configure'
	from /usr/lib/ruby/gems/2.4.0/gems/fluentd-1.2.3/lib/fluent/supervisor.rb:795:in `run_configure'
	from /usr/lib/ruby/gems/2.4.0/gems/fluentd-1.2.3/lib/fluent/supervisor.rb:579:in `dry_run'
	from /usr/lib/ruby/gems/2.4.0/gems/fluentd-1.2.3/lib/fluent/supervisor.rb:597:in `supervise'
	from /usr/lib/ruby/gems/2.4.0/gems/fluentd-1.2.3/lib/fluent/supervisor.rb:502:in `run_supervisor'
	from /usr/lib/ruby/gems/2.4.0/gems/fluentd-1.2.3/lib/fluent/command/fluentd.rb:310:in `<top (required)>'
	from /usr/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/gems/2.4.0/gems/fluentd-1.2.3/bin/fluentd:8:in `<top (required)>'
	from /usr/bin/fluentd:23:in `load'
	from /usr/bin/fluentd:23:in `<main>'
```

Looking through the code, setting 

```
logstash_prefix "${tag || 'placeholder'}"
```

works but this is heavily dependent on the inner workings of the plugin.

May I suggest adding `tag` handling to the `if/elsif` code [here](https://github.com/uken/fluent-plugin-elasticsearch/blob/5f9557094f6e6d0f404ef999bd59ce2d194af5cf/lib/fluent/plugin/out_elasticsearch_dynamic.rb#L261-L266)?

#### Using Fluentd and ES plugin versions

* Fluentd v1.2.2
* ES plugin 2.11.1

**Comment by lawliet89** [comment]
Thanks for the suggestion -- I didn't realise fluentd had a placeholder feature.

I used the `elasticsearch_dynamic` in the past for `tag_parts` but I am guessing I don't need that now.
