### ISSUE TITLE
Crash when one of many elasticsearch cluster cannot be connected when fluentd start.

### ISSUE THREAD

**Issue by Misterhex** [uken/fluent-plugin-elasticsearch#475]
We configure fluentd to write to multiple elasticsearch clusters, but fluentd crash on startup if one of many configured elasticsearch could not be connected. 

I was expecting that it could re-try the failed cluster and continue shipping logs to the other available cluster, and buffer logs for the failed cluster.

I also notice if the connections dropped off after startup, it continue running for other store which is expected behaviour.

Version:
td-agent-3.2.0
fluent-plugin-prometheus 1.0.1
Elasticsearch: 6.3.2

**Comment by cosmo0920** [comment]
Could you write using your Fluentd version and ES version.

**Comment by Misterhex** [comment]
@cosmo0920 Updated, apologies.

**Comment by cosmo0920** [comment]
Awesome. Thank you!

**Comment by cosmo0920** [comment]
I’ll take a look the next week.
Sorry for inconvenience. 😓

**Comment by Misterhex** [comment]
@cosmo0920 thanks a lot

**Comment by cosmo0920** [comment]
Ah, I forgot to ask sharing your error log.
Could you share your Fluentd error log?

**Comment by Misterhex** [comment]
@cosmo0920 I have found what i need.

```
<store ignore_error> 

https://github.com/fluent/fluentd/pull/303

**Comment by cosmo0920** [comment]
No problem. Thanks!

**Comment by Misterhex** [comment]
I am re-opening this as the issues still persist on startup even with `<store ignore_error>`

stacktrace
```
2018-09-27 05:13:06 +0000 [info]: parsing config file is succeeded path="/etc/td-agent/td-agent.conf"
--
  | 2018-09-27 05:13:06 +0000 [info]: adding rewrite_tag_filter rule: $.kubernetes.namespace_name [#<Fluent::PluginHelper::RecordAccessor::Accessor:0x0000000001b420c0 @keys=["kubernetes", "namespace_name"]>, /^(.+)$/, "", "kube-namespace.$1"]
  | 2018-09-27 05:13:06 +0000 [info]: [kubernetes_out_elasticsearch_openshift] Connection opened to Elasticsearch cluster => {:host=>"elasticsearch.xxx.svc", :port=>9200, :scheme=>"http"}
  | 2018-09-27 05:13:06 +0000 [info]: [kubernetes_out_elasticsearch_openshift] Template 'kubernetes' overwritten with /etc/td-agent/index-template/kubernetes.json.
  | /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-elasticsearch-2.4.0/lib/fluent/plugin/out_elasticsearch.rb:199:in `client': Can not reach Elasticsearch cluster ({:host=>"xxx.xxx.xxx.xxx", :port=>9200, :scheme=>"https", :user=>"fluentd", :password=>"obfuscated"})! (Fluent::Plugin::ElasticsearchOutput::ConnectionFailure)
  | from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-elasticsearch-2.4.0/lib/fluent/plugin/elasticsearch_index_template.rb:19:in `template_put'
  | from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-elasticsearch-2.4.0/lib/fluent/plugin/elasticsearch_index_template.rb:24:in `template_install'
  | from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-elasticsearch-2.4.0/lib/fluent/plugin/out_elasticsearch.rb:118:in `configure'
  | from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.0.2/lib/fluent/plugin.rb:164:in `configure'
  | from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.0.2/lib/fluent/plugin/multi_output.rb:74:in `block in configure'
  | from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.0.2/lib/fluent/plugin/multi_output.rb:63:in `each'
  | from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.0.2/lib/fluent/plugin/multi_output.rb:63:in `configure'
  | from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.0.2/lib/fluent/plugin/out_copy.rb:36:in `configure'
  | from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.0.2/lib/fluent/plugin.rb:164:in `configure'
  | from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.0.2/lib/fluent/agent.rb:130:in `add_match'
  | from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.0.2/lib/fluent/agent.rb:72:in `block in configure'
  | from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.0.2/lib/fluent/agent.rb:64:in `each'
  | from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.0.2/lib/fluent/agent.rb:64:in `configure'
  | from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.0.2/lib/fluent/label.rb:31:in `configure'
  | from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.0.2/lib/fluent/root_agent.rb:109:in `block in configure'
  | from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.0.2/lib/fluent/root_agent.rb:109:in `each'
  | from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.0.2/lib/fluent/root_agent.rb:109:in `configure'
  | from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.0.2/lib/fluent/engine.rb:131:in `configure'
  | from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.0.2/lib/fluent/engine.rb:96:in `run_configure'
  | from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.0.2/lib/fluent/supervisor.rb:770:in `run_configure'
  | from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.0.2/lib/fluent/supervisor.rb:553:in `dry_run'
  | from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.0.2/lib/fluent/supervisor.rb:571:in `supervise'
  | from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.0.2/lib/fluent/supervisor.rb:476:in `run_supervisor'
  | from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.0.2/lib/fluent/command/fluentd.rb:310:in `<top (required)>'
  | from /opt/td-agent/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  | from /opt/td-agent/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  | from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.0.2/bin/fluentd:8:in `<top (required)>'
  | from /opt/td-agent/embedded/bin/fluentd:22:in `load'
  | from /opt/td-agent/embedded/bin/fluentd:22:in `<top (required)>'
  | from /usr/sbin/td-agent:7:in `load'
  | from /usr/sbin/td-agent:7:in `<main>'
```

**Comment by Misterhex** [comment]
My desired behaviour would be that the plugin start up even when one of the many configured elasticsearch cluster is down and continue shipping logs to other store.

It shouldn't throw the exception and crash fluentd.

This plugin should buffer events for that store and retry the connection.

Am i missing some configuration?

**Comment by Misterhex** [comment]
It looks like it tries to put index template on startup and if the cluster is down, it crashes fluentd.

**Comment by Misterhex** [comment]
issues looks related to #198

**Comment by cosmo0920** [comment]
Could you upgrade ES plugin 2.10.3 or 2.11.10 (current latest)?

**Comment by aelbarkani** [comment]
@cosmo0920  can we reopen this issue ?

we are having serious problems with banzaicloud's logging operator when destinations are elasticsearch clusters.
https://github.com/banzaicloud/logging-operator/issues/491

@tarokkk has tried https://github.com/uken/fluent-plugin-elasticsearch#fluentd-seems-to-hang-if-it-unable-to-connect-elasticsearch-why, which didn't work

**Comment by yaroslavkasatikov** [comment]
Totally support this. Could you please investigate the issue? It is the serious blocker for us:(

**Comment by cosmo0920** [comment]
Could you open an new issue?

**Comment by cosmo0920** [comment]
Commenting closed issue without following issue template is not helpful and not reproducible.
