### ISSUE TITLE
 unexpected error error_class=SystemStackError error="stack level too deep"

### ISSUE THREAD

**Issue by fghorbel** [uken/fluent-plugin-elasticsearch#477]
#### Problem
```
2018-09-28 16:46:27 +0000 [warn]: #0 thread exited by unexpected error plugin=Fluent::Plugin::ElasticsearchOutput title=:flush_thread_6 error_class=SystemStackError error="stack level too deep"
2018-09-28 16:46:27 +0000 [error]: #0 unexpected error error_class=SystemStackError error="stack level too deep"
  2018-09-28 16:46:27 +0000 [error]: #0 /usr/local/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/faraday-0.15.3/lib/faraday/utils.rb:32:in `dup'
  2018-09-28 16:46:27 +0000 [error]: #0 /usr/local/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/faraday-0.15.3/lib/faraday/utils.rb:32:in `initialize_copy'
  2018-09-28 16:46:27 +0000 [error]: #0 /usr/local/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/faraday-0.15.3/lib/faraday/connection.rb:396:in `initialize_dup'
  2018-09-28 16:46:27 +0000 [error]: #0 /usr/local/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/faraday-0.15.3/lib/faraday/connection.rb:396:in `dup'
  2018-09-28 16:46:27 +0000 [error]: #0 /usr/local/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/faraday-0.15.3/lib/faraday/connection.rb:396:in `block in build_request'
  2018-09-28 16:46:27 +0000 [error]: #0 /usr/local/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/faraday-0.15.3/lib/faraday/request.rb:26:in `block in create'
  2018-09-28 16:46:27 +0000 [error]: #0 /usr/local/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/faraday-0.15.3/lib/faraday/request.rb:25:in `tap'
  2018-09-28 16:46:27 +0000 [error]: #0 /usr/local/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/faraday-0.15.3/lib/faraday/request.rb:25:in `create'
  2018-09-28 16:46:27 +0000 [error]: #0 /usr/local/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/faraday-0.15.3/lib/faraday/connection.rb:394:in `build_request'
  2018-09-28 16:46:27 +0000 [error]: #0 /usr/local/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/faraday-0.15.3/lib/faraday/connection.rb:379:in `run_request'
  2018-09-28 16:46:27 +0000 [error]: #0 /usr/local/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/elasticsearch-transport-6.1.0/lib/elasticsearch/transport/transport/http/faraday.rb:23:in `block in perform_reques
t'
  2018-09-28 16:46:27 +0000 [error]: #0 /usr/local/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/elasticsearch-transport-6.1.0/lib/elasticsearch/transport/transport/base.rb:266:in `perform_request'
  2018-09-28 16:46:27 +0000 [error]: #0 /usr/local/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/elasticsearch-transport-6.1.0/lib/elasticsearch/transport/transport/http/faraday.rb:20:in `perform_request'
  2018-09-28 16:46:27 +0000 [error]: #0 /usr/local/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/elasticsearch-transport-6.1.0/lib/elasticsearch/transport/transport/sniffer.rb:31:in `block in hosts'
  2018-09-28 16:46:27 +0000 [error]: #0 /usr/local/rbenv/versions/2.5.1/lib/ruby/2.5.0/timeout.rb:93:in `block in timeout'
  2018-09-28 16:46:27 +0000 [error]: #0 /usr/local/rbenv/versions/2.5.1/lib/ruby/2.5.0/timeout.rb:103:in `timeout'
  2018-09-28 16:46:27 +0000 [error]: #0 /usr/local/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/elasticsearch-transport-6.1.0/lib/elasticsearch/transport/transport/sniffer.rb:30:in `hosts'
  2018-09-28 16:46:27 +0000 [error]: #0 /usr/local/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/elasticsearch-transport-6.1.0/lib/elasticsearch/transport/transport/base.rb:80:in `reload_connections!'
  2018-09-28 16:46:27 +0000 [error]: #0 /usr/local/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/elasticsearch-transport-6.1.0/lib/elasticsearch/transport/transport/base.rb:293:in `rescue in perform_request'
  2018-09-28 16:46:27 +0000 [error]: #0 /usr/local/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/elasticsearch-transport-6.1.0/lib/elasticsearch/transport/transport/base.rb:256:in `perform_request'
  2018-09-28 16:46:27 +0000 [error]: #0 /usr/local/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/elasticsearch-transport-6.1.0/lib/elasticsearch/transport/transport/http/faraday.rb:20:in `perform_request'
  2018-09-28 16:46:27 +0000 [error]: #0 /usr/local/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/elasticsearch-transport-6.1.0/lib/elasticsearch/transport/transport/sniffer.rb:31:in `block in hosts'
  2018-09-28 16:46:27 +0000 [error]: #0 /usr/local/rbenv/versions/2.5.1/lib/ruby/2.5.0/timeout.rb:93:in `block in timeout'
  2018-09-28 16:46:27 +0000 [error]: #0 /usr/local/rbenv/versions/2.5.1/lib/ruby/2.5.0/timeout.rb:103:in `timeout'
  2018-09-28 16:46:27 +0000 [error]: #0 /usr/local/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/elasticsearch-transport-6.1.0/lib/elasticsearch/transport/transport/sniffer.rb:30:in `hosts'
  2018-09-28 16:46:27 +0000 [error]: #0 /usr/local/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/elasticsearch-transport-6.1.0/lib/elasticsearch/transport/transport/base.rb:80:in `reload_connections!'
  2018-09-28 16:46:27 +0000 [error]: #0 /usr/local/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/elasticsearch-transport-6.1.0/lib/elasticsearch/transport/transport/base.rb:293:in `rescue in perform_request'
  2018-09-28 16:46:27 +0000 [error]: #0 /usr/local/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/elasticsearch-transport-6.1.0/lib/elasticsearch/transport/transport/base.rb:256:in `perform_request'
  2018-09-28 16:46:27 +0000 [error]: #0 /usr/local/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/elasticsearch-transport-6.1.0/lib/elasticsearch/transport/transport/http/faraday.rb:20:in `perform_request'
  2018-09-28 16:46:27 +0000 [error]: #0 /usr/local/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/elasticsearch-transport-6.1.0/lib/elasticsearch/transport/transport/sniffer.rb:31:in `block in hosts'
  2018-09-28 16:46:27 +0000 [error]: #0 /usr/local/rbenv/versions/2.5.1/lib/ruby/2.5.0/timeout.rb:93:in `block in timeout'
  2018-09-28 16:46:27 +0000 [error]: #0 /usr/local/rbenv/versions/2.5.1/lib/ruby/2.5.0/timeout.rb:103:in `timeout'
  2018-09-28 16:46:27 +0000 [error]: #0 /usr/local/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/elasticsearch-transport-6.1.0/lib/elasticsearch/transport/transport/sniffer.rb:30:in `hosts'
  2018-09-28 16:46:27 +0000 [error]: #0 /usr/local/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/elasticsearch-transport-6.1.0/lib/elasticsearch/transport/transport/base.rb:80:in `reload_connections!'
  2018-09-28 16:46:27 +0000 [error]: #0 /usr/local/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/elasticsearch-transport-6.1.0/lib/elasticsearch/transport/transport/base.rb:293:in `rescue in perform_request'
  2018-09-28 16:46:27 +0000 [error]: #0 /usr/local/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/elasticsearch-transport-6.1.0/lib/elasticsearch/transport/transport/base.rb:256:in `perform_request'
  2018-09-28 16:46:27 +0000 [error]: #0 /usr/local/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/elasticsearch-transport-6.1.0/lib/elasticsearch/transport/transport/http/faraday.rb:20:in `perform_request'
  2018-09-28 16:46:27 +0000 [error]: #0 /usr/local/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/elasticsearch-transport-6.1.0/lib/elasticsearch/transport/transport/sniffer.rb:31:in `block in hosts'
  2018-09-28 16:46:27 +0000 [error]: #0 /usr/local/rbenv/versions/2.5.1/lib/ruby/2.5.0/timeout.rb:93:in `block in timeout'
  2018-09-28 16:46:27 +0000 [error]: #0 /usr/local/rbenv/versions/2.5.1/lib/ruby/2.5.0/timeout.rb:103:in `timeout'
```

...

#### Steps to replicate

Either clone and modify https://gist.github.com/pitr/9a518e840db58f435911

**OR**

Provide example config and message

```
<source>
  @type tail

   format none
   rotate_wait 300s


   path "#{ENV['APPS_LOGS_LOG_PATTERN']}"

   pos_file /mnt/buffers/nginx_log.pos
   read_from_head true
   tag nginx.log.info.*

   @label @NGINX_LOGS

</source>

```
---

```
<match nginx.log.info.**>
@type forest
subtype copy
<template>

  <store>

    @type elasticsearch
    hosts "#{ENV['ELS_HOST']}"
    user "#{ENV['ELS_USER']}"
    password "#{ENV['ELS_PWD']}"
    reload_on_failure true
    ssl_version TLSv1_2
    scheme https
    time_key  time
    logstash_format true
    logstash_prefix appslogs-nginx
    request_timeout 15s
    template_file /mnt/nginx-template.json
    template_name "#{ENV['ELS_TEMPLATE_NAME']}"
    template_overwrite true
    logstash_dateformat %Y%m%d
    include_tag_key true
    tag_key @log_name
    ssl_verify false
    type_name _doc

  <buffer tag>
      flush_mode interval
#      flush_mode immediate
      @type file
      flush_interval 10s
      path  /mnt/buffers/${tag}/
      flush_thread_count 8 
      flush_thread_interval 5s
      total_limit_size 1G
      retry_max_times 2
      retry_wait 10s
      chunk_limit_size 8M
      queued_chunks_limit_size 1G

       overflow_action block
    </buffer>
</store>

#<store>
#@type stdout
#</store>

</template>

</match>
```
#### Expected Behavior or What you need to ask

...

#### Using Fluentd and ES plugin versions

* OS version
  Debian 9 

  * paste result of ``fluentd --version`` or ``td-agent --version``

* ES plugin 2.x.y or 1.x.y
 ```
 * 2018-09-28 16:41:54 +0000 [info]: starting fluentd-1.2.5 pid=11 ruby="2.5.1"
2018-09-28 16:41:54 +0000 [info]: spawn command to main:  cmdline=["/usr/local/rbenv/versions/2.5.1/bin/ruby", "-Eascii-8bit:ascii-8bit", "/usr/local/rbenv/versions/2.5.1/bin/fluentd", "-c", "/etc/fluentd/fluent
d.conf", "--under-supervisor"]
2018-09-28 16:41:54 +0000 [info]: gem 'fluent-plugin-detect-exceptions' version '0.0.11'
2018-09-28 16:41:54 +0000 [info]: gem 'fluent-plugin-elasticsearch' version '2.11.10'
2018-09-28 16:41:54 +0000 [info]: gem 'fluent-plugin-exclude-filter' version '0.0.1'
2018-09-28 16:41:54 +0000 [info]: gem 'fluent-plugin-firehose' version '0.0.11'
2018-09-28 16:41:54 +0000 [info]: gem 'fluent-plugin-forest' version '0.3.3'
2018-09-28 16:41:54 +0000 [info]: gem 'fluent-plugin-multi-format-parser' version '1.0.0'
2018-09-28 16:41:54 +0000 [info]: gem 'fluent-plugin-parser' version '0.6.1'
2018-09-28 16:41:54 +0000 [info]: gem 'fluent-plugin-record-modifier' version '1.1.0'
2018-09-28 16:41:54 +0000 [info]: gem 'fluent-plugin-record-reformer' version '0.9.1'
2018-09-28 16:41:54 +0000 [info]: gem 'fluent-plugin-rename-key' version '0.4.1'
2018-09-28 16:41:54 +0000 [info]: gem 'fluent-plugin-secure-forward' version '0.4.5'
2018-09-28 16:41:54 +0000 [info]: gem 'fluent-plugin-webhdfs' version '1.2.3'
2018-09-28 16:41:54 +0000 [info]: gem 'fluentd' version '1.2.5'
2018-09-28 16:41:54 +0000 [info]: adding filter in @NGINX_LOGS pattern="nginx.log.info.**" type="parser"
2018-09-28 16:41:54 +0000 [info]: adding match in @NGINX_LOGS pattern="nginx.log.info.**" type="forest"
2018-09-28 16:41:54 +0000 [info]: adding match in @ERROR pattern="*.**" type="stdout"
2018-09-28 16:41:54 +0000 [info]: adding match pattern="fluent.**" type="null"
2018-09-28 16:41:54 +0000 [info]: adding source type="forward"
2018-09-28 16:41:54 +0000 [info]: adding source type="tail"
2018-09-28 16:41:54 +0000 [warn]: section <parse> is not used in <filter nginx.log.info.**> of multi_format plugin
2018-09-28 16:41:54 +0000 [warn]: section <parse> is not used in <filter nginx.log.info.**> of multi_format plugin
2018-09-28 16:41:54 +0000 [info]: #0 starting fluentd worker pid=315 ppid=11 worker=0
```

  * paste result of ``fluent-gem list``, ``td-agent-gem list`` or your Gemfile.lock

```
  *fluent-plugin-detect-exceptions (0.0.11)
fluent-plugin-elasticsearch (2.11.10)
fluent-plugin-exclude-filter (0.0.1)
fluent-plugin-firehose (0.0.11)
fluent-plugin-forest (0.3.3)
fluent-plugin-multi-format-parser (1.0.0)
fluent-plugin-parser (0.6.1)
fluent-plugin-record-modifier (1.1.0)
fluent-plugin-record-reformer (0.9.1)
fluent-plugin-rename-key (0.4.1)
fluent-plugin-secure-forward (0.4.5)
fluent-plugin-webhdfs (1.2.3)
fluentd (1.2.5)

```
* ES version (optional)
6.2.2

**Comment by cosmo0920** [comment]
It seems that version incompatibility between elasticsearch client and Elasticsearch causes this issue.
Could you use elasticsearch, elasticsearch-api, and elasticsearch-transport v2.0.2 versions?
See also: https://docs.fluentd.org/v1.0/articles/out_elasticsearch#cannot-send-events-to-elasticsearch

**Comment by fghorbel** [comment]
I don t think it s compatibility issue. My ES is on version 6.2.2  and the gems are

```
→gem list elasticsearch

*** LOCAL GEMS ***

elasticsearch (6.1.0)
elasticsearch-api (6.1.0)
elasticsearch-transport (6.1.0)
fluent-plugin-elasticsearch (2.11.10)
```

It works for a small period of time then it crashes with `unexpected error error_class=SystemStackError error="stack level too deep"`. The error is generated only when i sat the `flush_thread_count 8 ` to more than 1. However, with flush_thread_count = 1,  I dont catch up with the tail input plugin, and as a result, i end up with many missing event logs.

**Comment by cosmo0920** [comment]
Without forest plugin works as expected?
In Fluentd v1, fluent-plugin-forest sometime does not work as expected.

**Comment by fghorbel** [comment]
Before, it was without the plugin `forest plugin ` and it threw the same error after being run for period of time. I tried to add the forest plugin to alleviate the problem, however, it didn t help.

**Comment by fghorbel** [comment]
Today, i have the following error

`2018-10-02 16:42:35 +0000 [warn]: #0 failed to flush the buffer. retry_time=0 next_retry_seconds=2018-10-02 16:42:35 +0000 chunk="577419b363d9fd314028906df3347813" error_class=ThreadError error="deadlock; recursive locking"`

**Comment by mindw** [comment]
Try setting 
```
reload_on_failure false
```
More information:
https://github.com/elastic/elasticsearch-ruby/issues/177

**Comment by anthonyhaussman** [comment]
Hi,

Actually have the same problem:
```
 ## First warning concerning the stack level too deep
[warn]: #23 thread exited by unexpected error plugin=Fluent::Plugin::ElasticsearchOutput title=:flush_thread_5 error_class=SystemStackError error="stack level too deep"

 ## The stacktrace who repeat himself several time
[error]: #23 unexpected error error_class=SystemStackError error="stack level too deep"
[error]: #23 /opt/td-agent/embedded/lib/ruby/2.4.0/uri/rfc3986_parser.rb:22:in `match'
[error]: #23 /opt/td-agent/embedded/lib/ruby/2.4.0/uri/rfc3986_parser.rb:22:in `split'
[error]: #23 /opt/td-agent/embedded/lib/ruby/2.4.0/uri/rfc3986_parser.rb:73:in `parse'
[error]: #23 /opt/td-agent/embedded/lib/ruby/2.4.0/uri/common.rb:231:in `parse'
[error]: #23 /opt/td-agent/embedded/lib/ruby/2.4.0/uri/common.rb:737:in `URI'
[error]: #23 /opt/fluentd/embedded/lib/ruby/gems/2.4.0/gems/faraday-0.15.3/lib/faraday/utils.rb:275:in `call'
[error]: #23 /opt/fluentd/embedded/lib/ruby/gems/2.4.0/gems/faraday-0.15.3/lib/faraday/utils.rb:275:in `URI'
[error]: #23 /opt/fluentd/embedded/lib/ruby/gems/2.4.0/gems/faraday-0.15.3/lib/faraday/connection.rb:477:in `proxy_for_request'
[error]: #23 /opt/fluentd/embedded/lib/ruby/gems/2.4.0/gems/faraday-0.15.3/lib/faraday/connection.rb:377:in `run_request'
[error]: #23 /opt/fluentd/embedded/lib/ruby/gems/2.4.0/gems/elasticsearch-transport-6.1.0/lib/elasticsearch/transport/transport/http/faraday.rb:23:in `block in perform_request'
[error]: #23 /opt/fluentd/embedded/lib/ruby/gems/2.4.0/gems/elasticsearch-transport-6.1.0/lib/elasticsearch/transport/transport/base.rb:266:in `perform_request'
[error]: #23 /opt/fluentd/embedded/lib/ruby/gems/2.4.0/gems/elasticsearch-transport-6.1.0/lib/elasticsearch/transport/transport/http/faraday.rb:20:in `perform_request'
[error]: #23 /opt/fluentd/embedded/lib/ruby/gems/2.4.0/gems/elasticsearch-transport-6.1.0/lib/elasticsearch/transport/transport/sniffer.rb:31:in `block in hosts'
[error]: #23 /opt/td-agent/embedded/lib/ruby/2.4.0/timeout.rb:93:in `block in timeout'
[error]: #23 /opt/td-agent/embedded/lib/ruby/2.4.0/timeout.rb:103:in `timeout'
[error]: #23 /opt/fluentd/embedded/lib/ruby/gems/2.4.0/gems/elasticsearch-transport-6.1.0/lib/elasticsearch/transport/transport/sniffer.rb:30:in `hosts'
[error]: #23 /opt/fluentd/embedded/lib/ruby/gems/2.4.0/gems/elasticsearch-transport-6.1.0/lib/elasticsearch/transport/transport/base.rb:80:in `reload_connections!'
[error]: #23 /opt/fluentd/embedded/lib/ruby/gems/2.4.0/gems/elasticsearch-transport-6.1.0/lib/elasticsearch/transport/transport/base.rb:293:in `rescue in perform_request'
[error]: #23 /opt/fluentd/embedded/lib/ruby/gems/2.4.0/gems/elasticsearch-transport-6.1.0/lib/elasticsearch/transport/transport/base.rb:256:in `perform_request'
[error]: #23 /opt/fluentd/embedded/lib/ruby/gems/2.4.0/gems/elasticsearch-transport-6.1.0/lib/elasticsearch/transport/transport/http/faraday.rb:20:in `perform_request'
[error]: #23 /opt/fluentd/embedded/lib/ruby/gems/2.4.0/gems/elasticsearch-transport-6.1.0/lib/elasticsearch/transport/transport/sniffer.rb:31:in `block in hosts'
[error]: #23 /opt/td-agent/embedded/lib/ruby/2.4.0/timeout.rb:93:in `block in timeout'
[error]: #23 /opt/td-agent/embedded/lib/ruby/2.4.0/timeout.rb:103:in `timeout'
...

 ## Following by problematic threads exit
[warn]: #23 thread doesn't exit correctly (killed or other reason) plugin=Fluent::Plugin::ElasticsearchOutput title=:flush_thread_1 thread=#<Thread:0x00007f78eda38140@/opt/fluentd/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.3.0/lib/fluent/plugin_helper/thread.rb:70 aborting> error=nil
[warn]: #23 thread doesn't exit correctly (killed or other reason) plugin=Fluent::Plugin::ElasticsearchOutput title=:flush_thread_1 thread=#<Thread:0x00007f78eda38140@/opt/fluentd/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.3.0/lib/fluent/plugin_helper/thread.rb:70 aborting> error=nil
[warn]: #23 thread doesn't exit correctly (killed or other reason) plugin=Fluent::Plugin::ElasticsearchOutput title=:flush_thread_3 thread=#<Thread:0x00007f78eda33870@/opt/fluentd/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.3.0/lib/fluent/plugin_helper/thread.rb:70 aborting> error=nil
[warn]: #23 thread doesn't exit correctly (killed or other reason) plugin=Fluent::Plugin::ElasticsearchOutput title=:flush_thread_2 thread=#<Thread:0x00007f78eda33cf8@/opt/fluentd/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.3.0/lib/fluent/plugin_helper/thread.rb:70 aborting> error=nil
...

 ## Finished by the the stop of one fluentd worker 
[info]: Worker 23 finished unexpectedly with status 1
```
Right after that, the worker restart immediatly which is a good thing.

Here is my configuration:
```
<match access_log.**>
  @type elasticsearch

  # Buffering
  slow_flush_log_threshold 90
  <buffer>
    @type file
    path /data/fluent/access_log
    chunk_limit_size 256m
    total_limit_size 40g
    flush_interval 60s
    flush_at_shutdown true
    flush_thread_count 8
    retry_max_times 10
    retry_wait 1s
    retry_forever
    overflow_action block
  </buffer>

  # ElasticSearch
  scheme https
  hosts es-01-01.adm.mydomain.com:9444,es-01-02.adm.mydomain.com:9444,es-01-03.adm.mydomain.com:9444,es-01-04.adm.mydomain.com:9444,es-01-05.adm.mydomain.com:9444,es-01-06.adm.mydomain.com:9444,es-01-07.adm.mydomain.com:9444,es-01-08.adm.mydomain.com:9444,es-01-09.adm.mydomain.com:9444,es-01-10.adm.mydomain.com:9444,es-01-11.adm.mydomain.com:9444,es-01-12.adm.mydomain.com:9444,es-01-13.adm.mydomain.com:9444,es-01-14.adm.mydomain.com:9444

  # SSL
  ssl_version TLSv1_2
  ca_file /usr/local/share/ca-certificates/ca.crt
  client_cert /etc/ssl/certs/server-bundle.pem
  client_key /etc/ssl/private/server-key.pem

  # ES Index
  logstash_format true
  logstash_prefix access
  logstash_dateformat %Y.%m.%d
  request_timeout 15s
  reload_connections true
  reload_on_failure true
  resurrect_after 30
  reconnect_on_error true
</match>
```

Version of gems:
fluentd (1.3.0)
fluent-plugin-elasticsearch (2.12.1)
elasticsearch (6.1.0)
elasticsearch-api (6.1.0)
elasticsearch-transport (6.1.0)

Version of ElasticSearch: 6.4.2

I would like to avoid to disable the `reload_on_failure` option, this one could be useful to quickly remove a dead node.

**Comment by cosmo0920** [comment]
Anyone get this issue with fluent-plugin-elasticsearch v3.0.0 or later?
I think that this issue should be resolved by https://github.com/uken/fluent-plugin-elasticsearch/pull/519.

**Comment by cosmo0920** [comment]
Some user reports this error does not occur in his environment with recently ES plugin.
Closing.

**Comment by eherot** [comment]
I am using `fluent-plugin-elasticsearch-3.5.3` and I am experiencing this issue. Interestingly in my setup I never get the SystemStackError but if I dump the stack on the running process I can clearly see that I am having this exact issue:

```
  Thread #<Thread:0x007f3a631425b8> status=sleep priority=0
      /var/lib/gems/2.3.0/gems/excon-0.65.0/lib/excon/socket.rb:288:in `select'
      /var/lib/gems/2.3.0/gems/excon-0.65.0/lib/excon/socket.rb:288:in `select_with_timeout'
      /var/lib/gems/2.3.0/gems/excon-0.65.0/lib/excon/socket.rb:149:in `rescue in block in connect'
      /var/lib/gems/2.3.0/gems/excon-0.65.0/lib/excon/socket.rb:130:in `block in connect'
      /var/lib/gems/2.3.0/gems/excon-0.65.0/lib/excon/socket.rb:121:in `each'
      /var/lib/gems/2.3.0/gems/excon-0.65.0/lib/excon/socket.rb:121:in `connect'
      /var/lib/gems/2.3.0/gems/excon-0.65.0/lib/excon/socket.rb:47:in `initialize'
      /var/lib/gems/2.3.0/gems/excon-0.65.0/lib/excon/connection.rb:457:in `new'
      /var/lib/gems/2.3.0/gems/excon-0.65.0/lib/excon/connection.rb:457:in `socket'
      /var/lib/gems/2.3.0/gems/excon-0.65.0/lib/excon/connection.rb:116:in `request_call'
      /var/lib/gems/2.3.0/gems/excon-0.65.0/lib/excon/middlewares/mock.rb:56:in `request_call'
      /var/lib/gems/2.3.0/gems/excon-0.65.0/lib/excon/middlewares/instrumentor.rb:34:in `request_call'
      /var/lib/gems/2.3.0/gems/excon-0.65.0/lib/excon/middlewares/idempotent.rb:19:in `request_call'
      /var/lib/gems/2.3.0/gems/excon-0.65.0/lib/excon/middlewares/base.rb:22:in `request_call'
      /var/lib/gems/2.3.0/gems/excon-0.65.0/lib/excon/middlewares/base.rb:22:in `request_call'
      /var/lib/gems/2.3.0/gems/excon-0.65.0/lib/excon/connection.rb:270:in `request'
      /var/lib/gems/2.3.0/gems/faraday-0.15.4/lib/faraday/adapter/excon.rb:52:in `call'
      /var/lib/gems/2.3.0/gems/faraday-0.15.4/lib/faraday/rack_builder.rb:143:in `build_response'
      /var/lib/gems/2.3.0/gems/faraday-0.15.4/lib/faraday/connection.rb:387:in `run_request'
      /var/lib/gems/2.3.0/gems/elasticsearch-transport-6.8.0/lib/elasticsearch/transport/transport/http/faraday.rb:23:in `block in perform_request'
      /var/lib/gems/2.3.0/gems/elasticsearch-transport-6.8.0/lib/elasticsearch/transport/transport/base.rb:266:in `perform_request'
      /var/lib/gems/2.3.0/gems/elasticsearch-transport-6.8.0/lib/elasticsearch/transport/transport/http/faraday.rb:20:in `perform_request'
      /var/lib/gems/2.3.0/gems/elasticsearch-transport-6.8.0/lib/elasticsearch/transport/transport/sniffer.rb:31:in `block in hosts'
      /usr/lib/ruby/2.3.0/timeout.rb:91:in `block in timeout'
      /usr/lib/ruby/2.3.0/timeout.rb:101:in `timeout'
      /var/lib/gems/2.3.0/gems/elasticsearch-transport-6.8.0/lib/elasticsearch/transport/transport/sniffer.rb:30:in `hosts'
      /var/lib/gems/2.3.0/gems/elasticsearch-transport-6.8.0/lib/elasticsearch/transport/transport/base.rb:80:in `reload_connections!'
      /var/lib/gems/2.3.0/gems/elasticsearch-transport-6.8.0/lib/elasticsearch/transport/transport/base.rb:293:in `rescue in perform_request'
      /var/lib/gems/2.3.0/gems/elasticsearch-transport-6.8.0/lib/elasticsearch/transport/transport/base.rb:256:in `perform_request'
      /var/lib/gems/2.3.0/gems/elasticsearch-transport-6.8.0/lib/elasticsearch/transport/transport/http/faraday.rb:20:in `perform_request'
      /var/lib/gems/2.3.0/gems/elasticsearch-transport-6.8.0/lib/elasticsearch/transport/transport/sniffer.rb:31:in `block in hosts'
      /usr/lib/ruby/2.3.0/timeout.rb:91:in `block in timeout'
      /usr/lib/ruby/2.3.0/timeout.rb:101:in `timeout'
      /var/lib/gems/2.3.0/gems/elasticsearch-transport-6.8.0/lib/elasticsearch/transport/transport/sniffer.rb:30:in `hosts'
      /var/lib/gems/2.3.0/gems/elasticsearch-transport-6.8.0/lib/elasticsearch/transport/transport/base.rb:80:in `reload_connections!'
      /var/lib/gems/2.3.0/gems/elasticsearch-transport-6.8.0/lib/elasticsearch/transport/transport/base.rb:293:in `rescue in perform_request'
      /var/lib/gems/2.3.0/gems/elasticsearch-transport-6.8.0/lib/elasticsearch/transport/transport/base.rb:256:in `perform_request'
      /var/lib/gems/2.3.0/gems/elasticsearch-transport-6.8.0/lib/elasticsearch/transport/transport/http/faraday.rb:20:in `perform_request'
      /var/lib/gems/2.3.0/gems/elasticsearch-transport-6.8.0/lib/elasticsearch/transport/transport/sniffer.rb:31:in `block in hosts'
      /usr/lib/ruby/2.3.0/timeout.rb:91:in `block in timeout'
      /usr/lib/ruby/2.3.0/timeout.rb:101:in `timeout'
```

**Comment by kalkrishnan** [comment]
Facing the same issue, plugin list:

2020-09-07 04:00:28 +0000 [info]: parsing config file is succeeded path="/etc/td-agent/td-agent.conf"
2020-09-07 04:00:28 +0000 [info]: gem 'fluent-plugin-concat' version '2.4.0'
2020-09-07 04:00:28 +0000 [info]: gem 'fluent-plugin-detect-exceptions' version '0.0.13'
2020-09-07 04:00:28 +0000 [info]: gem 'fluent-plugin-elasticsearch' version '4.1.2'
2020-09-07 04:00:28 +0000 [info]: gem 'fluent-plugin-kafka' version '0.13.0'
2020-09-07 04:00:28 +0000 [info]: gem 'fluent-plugin-multi-format-parser' version '1.0.0'
2020-09-07 04:00:28 +0000 [info]: gem 'fluent-plugin-prometheus' version '1.7.3'
2020-09-07 04:00:28 +0000 [info]: gem 'fluent-plugin-prometheus_pushgateway' version '0.0.2'
2020-09-07 04:00:28 +0000 [info]: gem 'fluent-plugin-record-modifier' version '2.1.0'
2020-09-07 04:00:28 +0000 [info]: gem 'fluent-plugin-rewrite-tag-filter' version '2.2.0'
2020-09-07 04:00:28 +0000 [info]: gem 'fluent-plugin-s3' version '1.3.1'
2020-09-07 04:00:28 +0000 [info]: gem 'fluent-plugin-systemd' version '1.0.2'
2020-09-07 04:00:28 +0000 [info]: gem 'fluent-plugin-td' version '1.1.0'
2020-09-07 04:00:28 +0000 [info]: gem 'fluent-plugin-td-monitoring' version '0.2.4'
2020-09-07 04:00:28 +0000 [info]: gem 'fluent-plugin-webhdfs' version '1.2.4'
2020-09-07 04:00:28 +0000 [info]: gem 'fluentd' version '1.10.2'

This was working a while ago. I recently restarted the td-agent and have been facing this issue since.
