### ISSUE TITLE
SSL proxy nginx to ElasticSearch - ssl_socket.rb / stack level too deep

### ISSUE THREAD

**Issue by anthonyhaussman** [uken/fluent-plugin-elasticsearch#494]
#### Problem

Hi,
I'm actually trying to set my ElasticSearch cluster in SSL via a ProxyPass nginx.
I have configure nginx with a require ssl_verify_client and set my fluent-plugin-elasticsearch configuration with the SSL configuration.

When I start fluentd, it returns this:

```
...
Oct 29 17:44:45 log-01-01 fluentd[6442]: log writing failed. execution expired
Oct 29 17:44:45 log-01-01 fluentd[6442]: log writing failed. execution expired
Oct 29 17:44:45 log-01-01 fluentd[6442]: log writing failed. execution expired
Oct 29 17:44:45 log-01-01 fluentd[6442]: /opt/fluentd/embedded/lib/ruby/gems/2.4.0/gems/excon-0.62.0/lib/excon/ssl_socket.rb:10:in `initialize': stack level too deep (SystemStackError)
Oct 29 17:44:45 log-01-01 fluentd[6442]:         from /opt/fluentd/embedded/lib/ruby/gems/2.4.0/gems/excon-0.62.0/lib/excon/connection.rb:429:in `new'
Oct 29 17:44:45 log-01-01 fluentd[6442]:         from /opt/fluentd/embedded/lib/ruby/gems/2.4.0/gems/excon-0.62.0/lib/excon/connection.rb:429:in `socket'
Oct 29 17:44:45 log-01-01 fluentd[6442]:         from /opt/fluentd/embedded/lib/ruby/gems/2.4.0/gems/excon-0.62.0/lib/excon/connection.rb:111:in `request_call'
Oct 29 17:44:45 log-01-01 fluentd[6442]:         from /opt/fluentd/embedded/lib/ruby/gems/2.4.0/gems/excon-0.62.0/lib/excon/middlewares/mock.rb:48:in `request_call'
Oct 29 17:44:45 log-01-01 fluentd[6442]:         from /opt/fluentd/embedded/lib/ruby/gems/2.4.0/gems/excon-0.62.0/lib/excon/middlewares/instrumentor.rb:26:in `request_call'
Oct 29 17:44:45 log-01-01 fluentd[6442]:         from /opt/fluentd/embedded/lib/ruby/gems/2.4.0/gems/excon-0.62.0/lib/excon/middlewares/base.rb:16:in `request_call'
Oct 29 17:44:45 log-01-01 fluentd[6442]:         from /opt/fluentd/embedded/lib/ruby/gems/2.4.0/gems/excon-0.62.0/lib/excon/middlewares/base.rb:16:in `request_call'
Oct 29 17:44:45 log-01-01 fluentd[6442]:         from /opt/fluentd/embedded/lib/ruby/gems/2.4.0/gems/excon-0.62.0/lib/excon/middlewares/base.rb:16:in `request_call'
Oct 29 17:44:45 log-01-01 fluentd[6442]:          ... 9266 levels...
Oct 29 17:44:45 log-01-01 fluentd[6442]:         from /opt/td-agent/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
Oct 29 17:44:45 log-01-01 fluentd[6442]:         from /opt/fluentd/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.5/bin/fluentd:8:in `<top (required)>'
Oct 29 17:44:45 log-01-01 fluentd[6442]:         from /opt/fluentd/embedded/bin/fluentd:22:in `load'
Oct 29 17:44:45 log-01-01 fluentd[6442]:         from /opt/fluentd/embedded/bin/fluentd:22:in `<main>'
Oct 29 17:44:45 log-01-01 systemd[1]: fluentd.service: Control process exited, code=exited status=1
Oct 29 17:44:45 log-01-01 systemd[1]: Failed to start fluentd: Fluentd based data collector for Treasure Data.
Oct 29 17:44:45 log-01-01 systemd[1]: fluentd.service: Unit entered failed state.
Oct 29 17:44:45 log-01-01 systemd[1]: fluentd.service: Failed with result 'exit-code'.
```

On the fluentd log:
```
2018-10-29 17:52:57 +0100 [warn]: #7 [Faraday::ConnectionFailed] Attempt 2 connecting to {:host=>"es-01-01.toto.com", :port=>9444, :scheme=>"https", :protocol=>"https"}
2018-10-29 17:52:57 +0100 [error]: #7 [Faraday::ConnectionFailed] Connection reset by peer - SSL_connect (Errno::ECONNRESET) {:host=>"es-01-02.toto.com", :port=>9444, :scheme=>"https", :protocol=>"https"}
2018-10-29 17:52:57 +0100 [warn]: #7 [Faraday::ConnectionFailed] Attempt 3 connecting to {:host=>"es-01-02.toto.com", :port=>9444, :scheme=>"https", :protocol=>"https"}
2018-10-29 17:52:57 +0100 [error]: #7 [Faraday::ConnectionFailed] Connection reset by peer - SSL_connect (Errno::ECONNRESET) {:host=>"es-01-01.toto.com", :port=>9444, :scheme=>"https", :protocol=>"https"}
2018-10-29 17:52:57 +0100 [warn]: #7 [Faraday::ConnectionFailed] Attempt 4 connecting to {:host=>"es-01-01.toto.com", :port=>9444, :scheme=>"https", :protocol=>"https"}
2018-10-29 17:52:57 +0100 [error]: #7 [Faraday::ConnectionFailed] Connection reset by peer - SSL_connect (Errno::ECONNRESET) {:host=>"es-01-02.toto.com", :port=>9444, :scheme=>"https", :protocol=>"https"}
2018-10-29 17:52:57 +0100 [warn]: #7 [Faraday::ConnectionFailed] Attempt 5 connecting to {:host=>"es-01-02.toto.com", :port=>9444, :scheme=>"https", :protocol=>"https"}
2018-10-29 17:52:57 +0100 [error]: #7 [Faraday::ConnectionFailed] Connection reset by peer - SSL_connect (Errno::ECONNRESET) {:host=>"es-01-01.toto.com", :port=>9444, :scheme=>"https", :protocol=>"https"}
2018-10-29 17:52:57 +0100 [warn]: #7 [Faraday::ConnectionFailed] Attempt 6 connecting to {:host=>"es-01-01.toto.com", :port=>9444, :scheme=>"https", :protocol=>"https"}
2018-10-29 17:52:57 +0100 [fatal]: #7 [Faraday::ConnectionFailed] Cannot connect to {:host=>"es-01-01.toto.com", :port=>9444, :scheme=>"https", :protocol=>"https"} after 6 tries
```

#### Steps to replicate

Fluentd ES plugin configuration:
```
<match access_log.**>
  @type elasticsearch

  @log_level debug
  with_transporter_log true

  # Buffering
  slow_flush_log_threshold 90
  <buffer>
    @type file
    path /data/fluent/access_log
    chunk_limit_size 256m
    total_limit_size 40g
    flush_interval 60s
    flush_at_shutdown true
    flush_thread_count 8
    retry_max_times 10
    retry_wait 1s
    retry_forever
    overflow_action block
  </buffer>

  # ElasticSearch
  scheme https
  hosts es-01-01.toto.com:9444,es-01-02.toto.com:9444

  # SSL
  ca_file /usr/local/share/ca-certificates/ca.crt
  client_cert /etc/ssl/certs/server-bundle.pem
  client_key /etc/ssl/private/server-key.pem

  # ES Index
  logstash_format true
  logstash_prefix access
  logstash_dateformat %Y.%m.%d
  request_timeout 15s
  reload_connections true
  reload_on_failure true
  resurrect_after 30
  reconnect_on_error true
</match>
```

Nginx configuration:
```
server {
    listen 1.2.3.4:9444;
    server_name es-01-01.toto.com;
    ssl on;
    ssl_certificate /etc/ssl/certs/server-bundle.pem;
    ssl_certificate_key /etc/ssl/private/server-key.pem;
    ssl_client_certificate /etc/ssl/certs/ca.pem;
    ssl_verify_client   on;
    ssl_verify_depth    2;

    # Reference : https://cipherli.st/
    ssl_protocols TLSv1.2;
    ssl_prefer_server_ciphers on;
    ssl_ciphers "EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH";
    ssl_ecdh_curve secp384r1; # Requires nginx >= 1.1.0
    ssl_session_cache shared:SSL:10m;
    ssl_session_tickets off; # Requires nginx >= 1.5.9
    ssl_stapling on; # Requires nginx >= 1.3.7
    ssl_stapling_verify on; # Requires nginx => 1.3.7
    resolver 127.0.0.1 valid=300s;
    resolver_timeout 5s;
    add_header Strict-Transport-Security "max-age=63072000; includeSubDomains; preload";
    add_header X-Frame-Options DENY;
    add_header X-Content-Type-Options nosniff;

    client_max_body_size 64M;
    keepalive_timeout 5;

    location / {
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_pass http://localhost:9200;
    }
}
```

#### Using Fluentd and ES plugin versions

* Fluentd v1.2.5
* elasticsearch 6.1.0
* elasticsearch-api 6.1.0
* elasticsearch-transport 6.1.0
* excon 0.62.0
* ES version 6.4.2
* Nginx version 1.10.3

**Comment by cosmo0920** [comment]
Could you use `ssl_version TLSv1_2`?
Default TLS version is set as `TLSv1` due to historical reason.

**Comment by anthonyhaussman** [comment]
> Could you use `ssl_version TLSv1_2`?
> Default TLS version is set as `TLSv1` due to historical reason.

Yep, this was the solution.
Thanks for your help and sorry for the inconvenience. :smile: 

I close the ticket.

**Comment by cosmo0920** [comment]
No problem.
I'll add FAQ for mismatch ssl_version on nginx proxy sutiation.
