### ISSUE TITLE
Fluent plugin fails to resolve host 

### ISSUE THREAD

**Issue by Mymetique** [uken/fluent-plugin-elasticsearch#528]
Hello,

We are using fluent on arch linux and have something like this in our conf :

`
@type systemd
tag native
path /var/log/journal

@type local
persistent true
path /var/log/systemd.pos

fields_strip_underscores true
fields_lowercase true

read_from_head true

<match **>
@type elasticsearch
include_tag_key true
host elasticsearch
port 9200
scheme http
reload_connections true
logstash_prefix logstash
tag_key @log_name
logstash_format true
type_name fluentd

flush_thread_count 2
flush_interval 5s
chunk_limit_size 2M
queue_limit_length 32
retry_max_interval 30
retry_forever true

`

As you can see host is elasticsearch, we can ping and access 'elasticsearch' from this node. When we run fluent, it will work for a while then it will start to throw errors like :

error_class=Fluent::Plugin::ElasticsearchOutput::RecoverableRequestFailure error="could not push logs to Elasticsearch cluster ({:host=>\"elasticsearch\", :port=>9200, :scheme=>\"http\"}): Connection refused - connect(2) for 127.0.0.1:9200 (Errno::ECONNREFUSED)

Well of course connection is refused on 127.0.0.1, but why fluent resolves elasticsearch as localhost while in the node's routes it is something completely different ?

Thanks for you help.

**Comment by cosmo0920** [comment]
Could you fill the following additional issue template?

```
#### Expected Behavior or What you need to ask

...

#### Using Fluentd and ES plugin versions

* OS version
* Bare Metal or within Docker or Kubernetes or others?
* Fluentd v0.12 or v0.14/v1.0
  * paste result of ``fluentd --version`` or ``td-agent --version``
* ES plugin 2.x.y or 1.x.y
  * paste boot log of fluentd or td-agent
  * paste result of ``fluent-gem list``, ``td-agent-gem list`` or your Gemfile.lock
* ES version (optional)
```

**Comment by cosmo0920** [comment]
> error_class=Fluent::Plugin::ElasticsearchOutput::RecoverableRequestFailure error="could not push logs to Elasticsearch cluster ({:host=>"elasticsearch", :port=>9200, :scheme=>"http"}): Connection refused - connect(2) for 127.0.0.1:9200 (Errno::ECONNREFUSED)

`curl elasticsearch:9200`  can get the following response?

```
{
  "name" : "eycK1t_",
  "cluster_name" : "elasticsearch_username",
  "cluster_uuid" : "UUIDS",
  "version" : {
    "number" : "6.4.2",
    "build_flavor" : "oss",
    "build_type" : "tar",
    "build_hash" : "04711c2",
    "build_date" : "2018-09-26T13:34:09.098244Z",
    "build_snapshot" : false,
    "lucene_version" : "7.4.0",
    "minimum_wire_compatibility_version" : "5.6.0",
    "minimum_index_compatibility_version" : "5.0.0"
  },
  "tagline" : "You Know, for Search"
}
```

If not so, your elasticsearch settings change listening port.

**Comment by antoinep92** [comment]
#### Expected Behavior or What you need to ask

We have a `172.18.0.1 elasticsearch` in our `/etc/hosts` and configure fluent to output logs to elasticsearch on the host `elasticsearch`, so we expect fluent to connect to `172.18.0.1` ; instead it's (sometimes) trying to connect to `127.0.0.1` which obviously fails. It seems like the host is incorrectly resolved.

#### Using Fluentd and ES plugin versions

* OS version: ArchLinux, kernel 4.20.0, systemd 240
* Bare Metal or within Docker or Kubernetes : bare metal. We have fluent running both on bare metal (for host logs) and kubernetes (for pod logs). This issue only affects the bare metal services.
* Fluentd v0.12 or v0.14/v1.0 : `fluentd 1.3.3`
* ES plugin 2.x.y or 1.x.y
  * paste boot log of fluentd or td-agent
```
Jan 16 11:01:50 oc001 systemd[1]: Started FluentD.
Jan 17 16:08:02 oc001 ruby[32539]: 2019-01-17 16:08:02 +0100 [warn]: #0 failed to flush the buffer. retry_time=0 next_retry_seconds=2019-01-17 16:08:03 +0100 chunk="57fa8c27a0044d8017ccd819a63a5254" error_class=Fluent::Plugin::ElasticsearchOutput::RecoverableRequestFailure error="could not push logs to Elasticsearch cluster ({:host=>\"elasticsearch\", :port=>9200, :scheme=>\"http\"}): Connection refused - connect(2) for 127.0.0.1:9200 (Errno::ECONNREFUSED)"
Jan 17 16:08:02 oc001 ruby[32539]:   2019-01-17 16:08:02 +0100 [warn]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluent-plugin-elasticsearch-3.0.1/lib/fluent/plugin/out_elasticsearch.rb:645:in `rescue in send_bulk'
Jan 17 16:08:02 oc001 ruby[32539]:   2019-01-17 16:08:02 +0100 [warn]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluent-plugin-elasticsearch-3.0.1/lib/fluent/plugin/out_elasticsearch.rb:627:in `send_bulk'
Jan 17 16:08:02 oc001 ruby[32539]:   2019-01-17 16:08:02 +0100 [warn]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluent-plugin-elasticsearch-3.0.1/lib/fluent/plugin/out_elasticsearch.rb:534:in `block in write'
Jan 17 16:08:02 oc001 ruby[32539]:   2019-01-17 16:08:02 +0100 [warn]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluent-plugin-elasticsearch-3.0.1/lib/fluent/plugin/out_elasticsearch.rb:533:in `each'
Jan 17 16:08:02 oc001 ruby[32539]:   2019-01-17 16:08:02 +0100 [warn]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluent-plugin-elasticsearch-3.0.1/lib/fluent/plugin/out_elasticsearch.rb:533:in `write'
Jan 17 16:08:02 oc001 ruby[32539]:   2019-01-17 16:08:02 +0100 [warn]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.3.3/lib/fluent/plugin/output.rb:1123:in `try_flush'
Jan 17 16:08:02 oc001 ruby[32539]:   2019-01-17 16:08:02 +0100 [warn]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.3.3/lib/fluent/plugin/output.rb:1423:in `flush_thread_run'
Jan 17 16:08:02 oc001 ruby[32539]:   2019-01-17 16:08:02 +0100 [warn]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.3.3/lib/fluent/plugin/output.rb:452:in `block (2 levels) in start'
Jan 17 16:08:02 oc001 ruby[32539]:   2019-01-17 16:08:02 +0100 [warn]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.3.3/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
Jan 17 16:08:03 oc001 ruby[32539]: 2019-01-17 16:08:03 +0100 [warn]: #0 failed to flush the buffer. retry_time=1 next_retry_seconds=2019-01-17 16:08:04 +0100 chunk="57fa8c27a0044d8017ccd819a63a5254" error_class=Fluent::Plugin::ElasticsearchOutput::RecoverableRequestFailure error="could not push logs to Elasticsearch cluster ({:host=>\"elasticsearch\", :port=>9200, :scheme=>\"http\"}): Connection refused - connect(2) for 127.0.0.1:9200 (Errno::ECONNREFUSED)"
```
  * paste result of ``fluent-gem list``, ``td-agent-gem list`` or your Gemfile.lock
```
fluent-gem list

*** LOCAL GEMS ***

bigdecimal (default: 1.3.4)
cmath (default: 1.0.0)
cool.io (1.5.3)
csv (default: 1.0.0)
date (default: 1.0.0)
dbm (default: 1.0.0)
dig_rb (1.0.1)
elasticsearch (6.1.0)
elasticsearch-api (6.1.0)
elasticsearch-transport (6.1.0)
etc (default: 1.0.0)
excon (0.62.0)
faraday (0.15.3)
fcntl (default: 1.0.0)
ffi (1.9.25)
fiddle (default: 1.0.0)
fileutils (default: 1.0.2)
fluent-plugin-elasticsearch (3.0.1, 2.12.1)
fluent-plugin-systemd (1.0.1)
fluentd (1.3.3, 1.3.0)
gdbm (default: 2.0.0)
http_parser.rb (0.6.0)
io-console (default: 0.4.6)
ipaddr (default: 1.2.0)
json (default: 2.1.0)
msgpack (1.2.4)
multi_json (1.13.1)
multipart-post (2.0.0)
openssl (default: 2.1.2)
psych (default: 3.0.2)
scanf (default: 1.0.0)
sdbm (default: 1.0.0)
serverengine (2.1.0)
sigdump (0.2.4)
stringio (default: 0.0.1)
strptime (0.2.3)
strscan (default: 1.0.0)
systemd-journal (1.3.3)
thread_safe (0.3.6)
tzinfo (1.2.5)
tzinfo-data (1.2018.7)
webrick (default: 1.4.2)
yajl-ruby (1.4.1)
zlib (default: 1.0.0)
```
* ES version (optional)
```
curl elasticsearch:9200
{
  "name" : "ER0e27M",
  "cluster_name" : "logs",
  "cluster_uuid" : "Z5Dj2BI7QlO0E0L8a-A-XQ",
  "version" : {
    "number" : "6.5.4",
    "build_flavor" : "default",
    "build_type" : "tar",
    "build_hash" : "d2ef93d",
    "build_date" : "2018-12-17T21:17:40.758843Z",
    "build_snapshot" : false,
    "lucene_version" : "7.5.0",
    "minimum_wire_compatibility_version" : "5.6.0",
    "minimum_index_compatibility_version" : "5.0.0"
  },
  "tagline" : "You Know, for Search"
}
```

**Comment by antoinep92** [comment]
The problem is generally solved by restarting the fluent service. But it reappears after some time.

**Comment by cosmo0920** [comment]
> We have a `172.18.0.1 elasticsearch` in our `/etc/hosts` and configure fluent to output logs to elasticsearch on the host `elasticsearch`, so we expect fluent to connect to `172.18.0.1` ; instead it's (sometimes) trying to connect to `127.0.0.1` which obviously fails. It seems like the host is incorrectly resolved.

Umm..., it is DNS issue.
I'm personally recommending to use IP address instead of DNS name.

**Comment by antoinep92** [comment]
It makes our deployment more complex, but we'll try that for a few days on a test env.
If the issue goes away, it means that either we have an issue in our DNS conf (unlikely since as I said it's statically written in `/etc/hosts`), or the fluent elastic search client has a bug related to DNS resolution.
If the issue reappears, maybe it's just that the error message was misleading and we'll get a more helpful error. In any case I'll let you know.

**Comment by antoinep92** [comment]
Ok the issue is back, so I guess the error message was a bit misleading. Now we are getting:
```
2019-01-23 16:32:40 +0100 [warn]: #0 fluent/log.rb:342:warn: failed to flush the buffer. retry_time=401 next_retry_seconds=2019-01-23 16:33:12 +0100 chunk="580202d28eeffca5c2a8ac7772cd8bbd" error_class=Fluent::Plugin::ElasticsearchOutput::RecoverableRequestFailure error="could not push logs to Elasticsearch cluster ({:host=>\"172.18.0.1\", :port=>9200, :scheme=>\"http\"}): Connection refused - connect(2) for 127.0.0.1:9200 (Errno::ECONNREFUSED)"
```

So apparently it's configured to connect to `172.18.0.1` but it says it failed to connect to `127.0.0.1` :thinking:

**Comment by cosmo0920** [comment]
I guess that one of the culprit this issue is `reload_connections true`.
Could you specify it as false?

**Comment by antoinep92** [comment]
Seems to work better, but it may be unrelated and due to elasticsearch upgrades.
But there is definitely an issue in the resolver, because I accidentally `chmod +x /etc/hosts` and fluent started resolving to `127.0.0.1` instead of the correct address in /etc/hosts or failing with a resolution error.

**Comment by nandlalyadav57** [comment]
Did we found a solution to this case by any chance?

**Comment by davidgarciaMontreal** [comment]
I have the same issue on fluent-plugin-elasticsearch-5.0.3. I believe, I found a work-around by using the hosts rather than the host and port parameters.
`
  @type elasticsearch
  host 192.168.101.101
  port 4242
  hosts 192.168.101.101:4242
  `

**Comment by col-panic** [comment]
Still seems to be the case with `fluent/fluentd:v1.17-1`
