### ISSUE TITLE
Template index ignored if elasticsearch is unavailable on fluentd start

### ISSUE THREAD

**Issue by xnike** [uken/fluent-plugin-elasticsearch#567]
Hi, 

I caught that fluent-plugin-elasticsearch ignores exception on creation of template index in case elasticsearch is not running on fluentd starting (i.e. fluentd started faster that elasticsearch on deploy to kubernetes):
```
2019-03-25 11:38:35 +0000 [info]: [elasticsearch] Template configured and already installed.
2019-03-25 11:38:37 +0000 [info]: [elasticsearch] The alias 'current-logstash' is created for the index '<logstash-default-{now/d}-000001>'
2019-03-25 11:38:37 +0000 [warn]: [elasticsearch] Could not connect Elasticsearch or obtain version. Assuming Elasticsearch 5.
2019-03-25 11:38:46 +0000 [warn]: [elasticsearch] failed to flush the buffer. retry_time=0 next_retry_seconds=2019-03-25 11:38:47 +0000 chunk="584e9a574acd4407b375a5e8475e9130" error_class=Fluent::Plugin::ElasticsearchOutput::RecoverableRequestFailure error="could not push logs to Elasticsearch cluster ({:host=>\"rl-elasticsearch-service\", :port=>9200, :scheme=>\"http\"}): Connection refused - connect(2) for 10.98.114.113:9200 (Errno::ECONNREFUSED)"
  2019-03-25 11:38:46 +0000 [warn]: /var/lib/gems/2.3.0/gems/fluent-plugin-elasticsearch-3.0.2/lib/fluent/plugin/out_elasticsearch.rb:655:in `rescue in send_bulk'
  2019-03-25 11:38:46 +0000 [warn]: /var/lib/gems/2.3.0/gems/fluent-plugin-elasticsearch-3.0.2/lib/fluent/plugin/out_elasticsearch.rb:638:in `send_bulk'
  2019-03-25 11:38:46 +0000 [warn]: /var/lib/gems/2.3.0/gems/fluent-plugin-elasticsearch-3.0.2/lib/fluent/plugin/out_elasticsearch.rb:544:in `block in write'
  2019-03-25 11:38:46 +0000 [warn]: /var/lib/gems/2.3.0/gems/fluent-plugin-elasticsearch-3.0.2/lib/fluent/plugin/out_elasticsearch.rb:543:in `each'
  2019-03-25 11:38:46 +0000 [warn]: /var/lib/gems/2.3.0/gems/fluent-plugin-elasticsearch-3.0.2/lib/fluent/plugin/out_elasticsearch.rb:543:in `write'
  2019-03-25 11:38:46 +0000 [warn]: /var/lib/gems/2.3.0/gems/fluentd-1.3.3/lib/fluent/plugin/output.rb:1123:in `try_flush'
  2019-03-25 11:38:46 +0000 [warn]: /var/lib/gems/2.3.0/gems/fluentd-1.3.3/lib/fluent/plugin/output.rb:1423:in `flush_thread_run'
  2019-03-25 11:38:46 +0000 [warn]: /var/lib/gems/2.3.0/gems/fluentd-1.3.3/lib/fluent/plugin/output.rb:452:in `block (2 levels) in start'
  2019-03-25 11:38:46 +0000 [warn]: /var/lib/gems/2.3.0/gems/fluentd-1.3.3/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
2019-03-25 11:38:47 +0000 [warn]: [elasticsearch] failed to flush the buffer. retry_time=1 next_retry_seconds=2019-03-25 11:38:48 +0000 chunk="584e9a574acd4407b375a5e8475e9130" error_class=Fluent::Plugin::ElasticsearchOutput::RecoverableRequestFailure error="could not push logs to Elasticsearch cluster ({:host=>\"rl-elasticsearch-service\", :port=>9200, :scheme=>\"http\"}): Connection refused - connect(2) for 10.98.114.113:9200 (Errno::ECONNREFUSED)"
  2019-03-25 11:38:47 +0000 [warn]: suppressed same stacktrace
2019-03-25 11:38:48 +0000 [warn]: [elasticsearch] failed to flush the buffer. retry_time=2 next_retry_seconds=2019-03-25 11:38:50 +0000 chunk="584e9a574acd4407b375a5e8475e9130" error_class=Fluent::Plugin::ElasticsearchOutput::RecoverableRequestFailure error="could not push logs to Elasticsearch cluster ({:host=>\"rl-elasticsearch-service\", :port=>9200, :scheme=>\"http\"}): Connection refused - connect(2) for 10.98.114.113:9200 (Errno::ECONNREFUSED)"
  2019-03-25 11:38:48 +0000 [warn]: /var/lib/gems/2.3.0/gems/fluent-plugin-elasticsearch-3.0.2/lib/fluent/plugin/out_elasticsearch.rb:655:in `rescue in send_bulk'
  2019-03-25 11:38:48 +0000 [warn]: /var/lib/gems/2.3.0/gems/fluent-plugin-elasticsearch-3.0.2/lib/fluent/plugin/out_elasticsearch.rb:638:in `send_bulk'
  2019-03-25 11:38:48 +0000 [warn]: /var/lib/gems/2.3.0/gems/fluent-plugin-elasticsearch-3.0.2/lib/fluent/plugin/out_elasticsearch.rb:544:in `block in write'
  2019-03-25 11:38:48 +0000 [warn]: /var/lib/gems/2.3.0/gems/fluent-plugin-elasticsearch-3.0.2/lib/fluent/plugin/out_elasticsearch.rb:543:in `each'
  2019-03-25 11:38:48 +0000 [warn]: /var/lib/gems/2.3.0/gems/fluent-plugin-elasticsearch-3.0.2/lib/fluent/plugin/out_elasticsearch.rb:543:in `write'
  2019-03-25 11:38:48 +0000 [warn]: /var/lib/gems/2.3.0/gems/fluentd-1.3.3/lib/fluent/plugin/output.rb:1123:in `try_flush'
  2019-03-25 11:38:48 +0000 [warn]: /var/lib/gems/2.3.0/gems/fluentd-1.3.3/lib/fluent/plugin/output.rb:1423:in `flush_thread_run'
  2019-03-25 11:38:48 +0000 [warn]: /var/lib/gems/2.3.0/gems/fluentd-1.3.3/lib/fluent/plugin/output.rb:452:in `block (2 levels) in start'
  2019-03-25 11:38:48 +0000 [warn]: /var/lib/gems/2.3.0/gems/fluentd-1.3.3/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
2019-03-25 11:38:48 +0000 [warn]: [elasticsearch] failed to flush the buffer. retry_time=3 next_retry_seconds=2019-03-25 11:38:53 +0000 chunk="584e9a592c8fceb248d60262f4e16ff7" error_class=Fluent::Plugin::ElasticsearchOutput::RecoverableRequestFailure error="could not push logs to Elasticsearch cluster ({:host=>\"rl-elasticsearch-service\", :port=>9200, :scheme=>\"http\"}): Connection refused - connect(2) for 10.98.114.113:9200 (Errno::ECONNREFUSED)"
  2019-03-25 11:38:48 +0000 [warn]: suppressed same stacktrace
2019-03-25 11:38:53 +0000 [warn]: [elasticsearch] failed to flush the buffer. retry_time=4 next_retry_seconds=2019-03-25 11:39:01 +0000 chunk="584e9a574acd4407b375a5e8475e9130" error_class=Fluent::Plugin::ElasticsearchOutput::RecoverableRequestFailure error="could not push logs to Elasticsearch cluster ({:host=>\"rl-elasticsearch-service\", :port=>9200, :scheme=>\"http\"}): Connection refused - connect(2) for 10.98.114.113:9200 (Errno::ECONNREFUSED)"
  2019-03-25 11:38:53 +0000 [warn]: suppressed same stacktrace
2019-03-25 11:38:53 +0000 [warn]: [elasticsearch] failed to flush the buffer. retry_time=5 next_retry_seconds=2019-03-25 11:39:07 +0000 chunk="584e9a592c8fceb248d60262f4e16ff7" error_class=Fluent::Plugin::ElasticsearchOutput::RecoverableRequestFailure error="could not push logs to Elasticsearch cluster ({:host=>\"rl-elasticsearch-service\", :port=>9200, :scheme=>\"http\"}): Connection refused - connect(2) for 10.98.114.113:9200 (Errno::ECONNREFUSED)"
  2019-03-25 11:38:53 +0000 [warn]: suppressed same stacktrace
2019-03-25 11:39:07 +0000 [warn]: [elasticsearch] failed to flush the buffer. retry_time=6 next_retry_seconds=2019-03-25 11:39:40 +0000 chunk="584e9a574acd4407b375a5e8475e9130" error_class=Fluent::Plugin::ElasticsearchOutput::RecoverableRequestFailure error="could not push logs to Elasticsearch cluster ({:host=>\"rl-elasticsearch-service\", :port=>9200, :scheme=>\"http\"}): Connection refused - connect(2) for 10.98.114.113:9200 (Errno::ECONNREFUSED)"
  2019-03-25 11:39:07 +0000 [warn]: suppressed same stacktrace
2019-03-25 11:39:07 +0000 [warn]: [elasticsearch] failed to flush the buffer. retry_time=7 next_retry_seconds=2019-03-25 11:39:36 +0000 chunk="584e9a592c8fceb248d60262f4e16ff7" error_class=Fluent::Plugin::ElasticsearchOutput::RecoverableRequestFailure error="could not push logs to Elasticsearch cluster ({:host=>\"rl-elasticsearch-service\", :port=>9200, :scheme=>\"http\"}): Connection refused - connect(2) for 10.98.114.113:9200 (Errno::ECONNREFUSED)"
  2019-03-25 11:39:07 +0000 [warn]: suppressed same stacktrace
2019-03-25 11:39:39 +0000 [warn]: [elasticsearch] retry succeeded. chunk_id="584e9a592c8fceb248d60262f4e16ff7"
```
This skipping lead to creating index defined in **index_name** field of configuration and broken rollover via curator, because only one index is created (current-logstash), not index with template (logstash-default-{now/d}-000001) plus alias (current-logstash).

It's a 100% reproducible case.

---

I am using ELK images provided by kubernetes project:
* docker.elastic.co/kibana/kibana-oss:6.3.2
* quay.io/pires/docker-elasticsearch-curator:5.5.1
* k8s.gcr.io/elasticsearch:v6.3.0
* k8s.gcr.io/fluentd-elasticsearch:v2.4.0:
```
root@rl-fluentd-0:/# cat /Gemfile
source 'https://rubygems.org'

gem 'activesupport', '~>5.2.2'
gem 'fluentd', '<=1.3.3'
gem 'fluent-plugin-concat', '~>2.3.0'
gem 'fluent-plugin-detect-exceptions', '~>0.0.11'
gem 'fluent-plugin-elasticsearch', '~>3.0.1'
gem 'fluent-plugin-kubernetes_metadata_filter', '~>2.1.6'
gem 'fluent-plugin-multi-format-parser', '~>1.0.0'
gem 'fluent-plugin-prometheus', '~>1.3.0'
gem 'fluent-plugin-systemd', '~>1.0.1'
gem 'oj', '~>3.7.6'
```
And following configuration:
* containers.input.conf:
```
<source>
  @id containers.log
  @type tail
  exclude_path ["/var/log/containers/fluentd*.log"]
  format json
  path /var/log/containers/*.log
  pos_file /var/log/containers.log.pos
  read_from_head false
  tag kubernetes.*
  time_format %Y-%m-%dT%H:%M:%S.%NZ
</source>

<filter kubernetes.**>
  @type kubernetes_metadata
</filter>
```
* output.conf:
```
<match **>
  @id elasticsearch
  @type elasticsearch
  @log_level info
  type_name fluentd
  include_tag_key true
  host rl-elasticsearch-service
  port 9200
  customize_template { "some_key": "some_value" }
  deflector_alias current-logstash
  include_timestamp true
  index_name current-logstash
  logstash_format false
  rollover_index true
  template_file /etc/fluent/config.d/logstash.template
  template_name template-logstash
  <buffer>
	@type file
	path /var/log/fluentd-buffers/kubernetes.system.buffer
	flush_mode interval
	retry_type exponential_backoff
	flush_thread_count 2
	flush_interval 5s
	retry_forever
	retry_max_interval 30
	chunk_limit_size 2M
	queue_limit_length 8
	overflow_action block
  </buffer>
</match>
```
* logstash.template:
```
{
  "aliases": {
  },
  "index_patterns": ["logstash-*"],
  "mappings": {
  },
  "settings": {
	"number_of_shards": "5",
	"number_of_replicas": "2"
  }
}
```

---
**Actual**: plugin ignores exception during creation index from template give up on any connectivity issue
**Expected**: wait starting elasticsearch before giving up on creating index from template

**Comment by cosmo0920** [comment]
Could you specify `max_retry_putting_template` option?
https://github.com/uken/fluent-plugin-elasticsearch#max_retry_putting_template

**Comment by xnike** [comment]
I posted my configuration as is, i.e. everything not mention has default value.
Anyway I don't see in logs any attempts to putting template only data from buffer.

**Comment by cosmo0920** [comment]
ES plugin 3.1.0 is already implemented to retry template installation:
https://github.com/uken/fluent-plugin-elasticsearch/blob/v3.0.1/lib/fluent/plugin/out_elasticsearch.rb#L172-L187
If it is not working on your k8s environment, it is curious.... :confounded:

**Comment by xnike** [comment]
Sorry, I don't know Ruby and could not review code at the moment, but as per log above
```
 2019-03-25 11:38:35 +0000 [info]: [elasticsearch] Template configured and already installed.
```
looks like exception is just ignored so no another retry attempts were made at all.


Here is logs for the case when fluentd is started after elasticsearch is up and running:

```
2019-03-27 10:29:56 +0000 [info]: [elasticsearch] Template configured, but no template installed. Installed 'template-logstash' from /etc/fluent/config.d/logstash.template.
2019-03-27 10:29:56 +0000 [info]: [elasticsearch] The alias 'current-logstash' is created for the index '<logstash-default-{now/d}-000001>'
2019-03-27 10:29:56 +0000 [info]: [elasticsearch] Detected ES 6.x: ES 7.x will only accept `_doc` in type_name.

```

**Comment by cosmo0920** [comment]
@ialidzhikov Is this issue occurred in your k8s environment with the latest k8s.gcr.io/fluentd-elasticsearch image(v2.5.0)?
Sorry for the sudden replying.

**Comment by ialidzhikov** [comment]
Shouldn't the index_name (`current-logstash`) match the index_pattern in the template (`logstash-*`)?  I guess it does not make sense to wait index to be created from template when the index_name does not match the index_pattern.

In our config, currently we have:
- fluentd.conf
```
logstash_format true
template_name foo
template_file /etc/fluent/config.d/default.template
```

- default.template
```
{
  "index_patterns": ["logstash-*"],
  "settings": {
    "index": {
      "number_of_shards": "3",
      "number_of_replicas": "0",
      "refresh_interval": "60s",
      "translog": {
        "durability": "async"
      }
    }
  }
}
```

**Comment by xnike** [comment]
> Shouldn't the index_name (`current-logstash`) match the index_pattern in the template (`logstash-*`)? I guess it does not make sense to wait index to be created from template when the index_name does not match the index_pattern.
> 
> In our config, currently we have:
> 
> * fluentd.conf
> 
> ```
> logstash_format true
> template_name foo
> template_file /etc/fluent/config.d/default.template
> ```
> * default.template
> 
> ```
> {
>   "index_patterns": ["logstash-*"],
>   "settings": {
>     "index": {
>       "number_of_shards": "3",
>       "number_of_replicas": "0",
>       "refresh_interval": "60s",
>       "translog": {
>         "durability": "async"
>       }
>     }
>   }
> }
> ```

As per documentation:

```
logstash_format true 
```

Setting this option to true will ignore the index_name setting

**Comment by xnike** [comment]
As for now 2.4.0 is the latest one in [repository](https://console.cloud.google.com/gcr/images/google_containers/GLOBAL/fluentd-elasticsearch?gcrImageListsize=30).

I have to point out that I use rollover index, i.e. plugin stores log records in index current-logstash alias pointing to and rollover transparently changing alias from one index to another if needed.

I've made some research:

* in case of removing **index_name** from configuration plugin tries to push template:

```
2019-03-28 11:55:23 +0000 [warn]: [elasticsearch] Could not push template(s) to Elasticsearch, resetting connection and trying again. Connection refused - connect(2) for 10.106.166.181:9200 (Errno::ECONNREFUSED)
2019-03-28 11:55:27 +0000 [warn]: [elasticsearch] Could not push template(s) to Elasticsearch, resetting connection and trying again. Connection refused - connect(2) for 10.106.166.181:9200 (Errno::ECONNREFUSED)
2019-03-28 11:55:35 +0000 [warn]: [elasticsearch] Could not push template(s) to Elasticsearch, resetting connection and trying again. Connection refused - connect(2) for 10.106.166.181:9200 (Errno::ECONNREFUSED)
2019-03-28 11:55:51 +0000 [warn]: [elasticsearch] Could not push template(s) to Elasticsearch, resetting connection and trying again. Connection refused - connect(2) for 10.106.166.181:9200 (Errno::ECONNREFUSED)
2019-03-28 11:55:51 +0000 [info]: [elasticsearch] Template configured, but no template installed. Installed 'template-logstash' from /etc/fluent/config.d/logstash.template.
```
but "fluentd" index is created automatically and all logs will be stored in it. No working rollover during a day as expected via Rolling API.

* in case of removing **index_name** from configuration and setting logstash_format to true:
plugin tries to push template  as in a previous case; logstash-2019.03.28 index created, and all logs stored in it. No working rollover during a day as expected via Rolling API.

As for now I don't see how to configure plugin to work correctly with rolling indexes.

Looks like configuration I already have plus  waiting in initContainers for running elasticsearch is a best available workaround.

**Comment by cosmo0920** [comment]
@xnike If you cannot wait booting ES cluster which is running on k8s, you can specify `default_elasticsearch_version` and `verify_es_version_at_startup` parameters:

* https://github.com/uken/fluent-plugin-elasticsearch#default_elasticsearch_version
* https://github.com/uken/fluent-plugin-elasticsearch#verify_es_version_at_startup

Specifying these parameter will skip connecting for ES to obtain major version:

https://github.com/uken/fluent-plugin-elasticsearch/blob/master/lib/fluent/plugin/out_elasticsearch.rb#L247-L253

I'm considering default suitable these parameters for k8s pod.

**Comment by xnike** [comment]
Thank you @cosmo0920, these 2 parameters make the trick.
Now I has working configuration for rolling index without extra workarounds.
