### ISSUE TITLE
Impossible to install on CentOS7

### ISSUE THREAD

**Issue by Spredzy** [uken/fluent-plugin-elasticsearch#57]
Trying to install the plugin on a CentOS7 box, I end up with the following trace

``` bash
[root@td ~]# cat /etc/redhat-release
CentOS Linux release 7.0.1406 (Core)
[root@td ~]# uname -a
Linux td 3.10.0-123.el7.x86_64 #1 SMP Mon Jun 30 12:09:22 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
[root@td ~]# ruby --version
ruby 2.0.0p353 (2013-11-22) [x86_64-linux]
[root@td ~]# gem --version
2.0.14
[root@td ~]# rpm -qa | grep -e curl -e openssl
openssl-libs-1.0.1e-34.el7_0.3.x86_64
openssl-devel-1.0.1e-34.el7_0.3.x86_64
libcurl-7.29.0-19.el7.x86_64
python-pycurl-7.19.0-17.el7.x86_64
openssl-1.0.1e-34.el7_0.3.x86_64
curl-7.29.0-19.el7.x86_64
libcurl-devel-7.29.0-19.el7.x86_64
[root@td ~]# /opt/td-agent/embedded/bin/fluent-gem install fluent-plugin-elasticsearch
Building native extensions.  This could take a while...
ERROR:  Error installing fluent-plugin-elasticsearch:
        ERROR: Failed to build gem native extension.

    /opt/td-agent/embedded/bin/ruby extconf.rb
checking for curl-config... yes
checking for rb_thread_blocking_region()... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/opt/td-agent/embedded/bin/ruby
        --with-curl-dir
        --without-curl-dir
        --with-curl-include
        --without-curl-include=${curl-dir}/include
        --with-curl-lib
        --without-curl-lib=${curl-dir}/lib
/opt/td-agent/embedded/lib/ruby/2.1.0/mkmf.rb:456:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
       from /opt/td-agent/embedded/lib/ruby/2.1.0/mkmf.rb:541:in `try_link0'
        from /opt/td-agent/embedded/lib/ruby/2.1.0/mkmf.rb:556:in `try_link'
       from /opt/td-agent/embedded/lib/ruby/2.1.0/mkmf.rb:742:in `try_func'
        from /opt/td-agent/embedded/lib/ruby/2.1.0/mkmf.rb:1027:in `block in have_func'
       from /opt/td-agent/embedded/lib/ruby/2.1.0/mkmf.rb:918:in `block in checking_for'
        from /opt/td-agent/embedded/lib/ruby/2.1.0/mkmf.rb:351:in `block (2 levels) in postpone'
       from /opt/td-agent/embedded/lib/ruby/2.1.0/mkmf.rb:321:in `open'
        from /opt/td-agent/embedded/lib/ruby/2.1.0/mkmf.rb:351:in `block in postpone'
       from /opt/td-agent/embedded/lib/ruby/2.1.0/mkmf.rb:321:in `open'
        from /opt/td-agent/embedded/lib/ruby/2.1.0/mkmf.rb:347:in `postpone'
       from /opt/td-agent/embedded/lib/ruby/2.1.0/mkmf.rb:917:in `checking_for'
        from /opt/td-agent/embedded/lib/ruby/2.1.0/mkmf.rb:1026:in `have_func'
       from extconf.rb:47:in `<main>'

extconf failed, exit code 1

Gem files will remain installed in /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/patron-0.4.18 for inspection.
Results logged to /opt/td-agent/embedded/lib/ruby/gems/2.1.0/extensions/x86_64-linux/2.1.0/patron-0.4.18/gem_make.out
[root@td ~]#
```

**Comment by vhosakot** [comment]
Thanks to @pitr. `yum install gcc gcc-c++ ruby-devel` resolved this error in CentOS for me.
