### ISSUE TITLE
Bulk upload fails with undefined method `has_key?' for nil:NilClass" error.

### ISSUE THREAD

**Issue by mightwork** [uken/fluent-plugin-elasticsearch#595]
#### Problem
Bulk upload fails with the following message:
```
[warn]: #0 dump an error event: error_class=Fluent::Plugin::ElasticsearchOutput::RecoverableRequestFailure error="could not push logs to Elasticsearch cluster ({:host=>\"elasticsearch.kube-analytics.svc.cluster.local\", :port=>9200, :scheme=>\"http\", :user=>\"elastic\", :password=>\"obfuscated\"}): undefined method `has_key?' for nil:NilClass" location="/fluentd/vendor/bundle/ruby/2.3.0/gems/fluent-plugin-elasticsearch-3.5.1/lib/fluent/plugin/out_elasticsearch.rb:758:in `rescue in send_bulk'"
```
...

#### Steps to replicate
No steps to reproduce. 

#### Expected Behavior or What you need to ask
Seeing this on all of our fluentd pods for the past couple of days. Elasticsearch logs are also not showing anything related. 

#### Using Fluentd and ES plugin versions

* OS version
 Linux  4.4.0-1054-aws #63-Ubuntu SMP x86_64 x86_64 x86_64 GNU/Linux
* Bare Metal or within Docker or Kubernetes or others?
 Kubernetes
* Fluentd v0.12 or v0.14/v1.0
  fluentd 1.3.3
* ES plugin 3.x.y/2.x.y or 1.x.y
  3.5.1
```
2019-06-03 15:44:33 +0000 [info]: starting fluentd-1.3.3 pid=7 ruby="2.3.3"
2019-06-03 15:44:33 +0000 [info]: spawn command to main:  cmdline=["/usr/bin/ruby2.3", "-Eascii-8bit:ascii-8bit", "/fluentd/vendor/bundle/ruby/2.3.0/bin/fluentd", "-c", "/fluentd/etc/fluent.conf", "-p", "/fluentd/plugins", "--gemfile", "/fluentd/Gemfile", "--under-supervisor"]
2019-06-03 15:44:33 +0000 [info]: gem 'fluent-plugin-elasticsearch' version '3.5.1'
2019-06-03 15:44:33 +0000 [info]: gem 'fluent-plugin-kubernetes_metadata_filter' version '2.1.6'
2019-06-03 15:44:33 +0000 [info]: gem 'fluent-plugin-out_rawtcp' version '0.0.1'
2019-06-03 15:44:33 +0000 [info]: gem 'fluent-plugin-rewrite-tag-filter' version '2.2.0'
2019-06-03 15:44:33 +0000 [info]: gem 'fluent-plugin-s3' version '1.1.10'
2019-06-03 15:44:33 +0000 [info]: gem 'fluent-plugin-systemd' version '1.0.2'
2019-06-03 15:44:33 +0000 [info]: gem 'fluentd' version '1.3.3'
```
  * paste result of ``fluent-gem list``, ``td-agent-gem list`` or your Gemfile.lock
```
*** LOCAL GEMS ***

activesupport (5.2.3)
addressable (2.6.0)
aws-eventstream (1.0.3)
aws-partitions (1.161.0)
aws-sdk-core (3.51.0)
aws-sdk-kms (1.18.0)
aws-sdk-s3 (1.36.1)
aws-sdk-sqs (1.13.0)
aws-sigv4 (1.1.0)
bigdecimal (1.2.8)
bundler (1.16.2)
concurrent-ruby (1.1.5)
cool.io (1.5.4)
dig_rb (1.0.1)
domain_name (0.5.20180417)
elasticsearch (7.0.0)
elasticsearch-api (7.0.0)
elasticsearch-transport (7.0.0)
ethon (0.12.0)
excon (0.64.0)
faraday (0.15.4)
ffi (1.10.0)
fluent-config-regexp-type (1.0.0)
fluent-plugin-elasticsearch (3.5.1)
fluent-plugin-kubernetes_metadata_filter (2.1.6)
fluent-plugin-out_rawtcp (0.0.1)
fluent-plugin-rewrite-tag-filter (2.2.0)
fluent-plugin-s3 (1.1.10)
fluent-plugin-systemd (1.0.2)
fluentd (1.3.3)
http (0.9.8)
http-cookie (1.0.3)
http-form_data (1.0.3)
http_parser.rb (0.6.0)
i18n (1.6.0)
io-console (0.4.5)
jmespath (1.4.0)
json (1.8.3)
kubeclient (1.1.4)
lru_redux (1.1.0)
mime-types (3.2.2)
mime-types-data (3.2019.0331)
minitest (5.11.3)
msgpack (1.2.10)
multi_json (1.13.1)
multipart-post (2.1.1)
netrc (0.11.0)
oj (3.5.1)
psych (2.1.0)
public_suffix (3.0.3)
rdoc (4.2.1)
recursive-open-struct (1.0.0)
rest-client (2.0.2)
serverengine (2.1.1)
sigdump (0.2.4)
strptime (0.2.3)
systemd-journal (1.3.3)
thread_safe (0.3.6)
typhoeus (1.3.1)
tzinfo (1.2.5)
tzinfo-data (1.2019.1)
unf (0.1.4)
unf_ext (0.0.7.6)
yajl-ruby (1.4.1)
```
* ES version
 7.0.1

**Comment by rafaelmagu** [comment]
AM seeing this with ES 6.3.2 as well on Fluentd 1.4.2 (ES plugin 3.5.1).

**Comment by JustDolanIt** [comment]
Got same issue in K8s:

```
2019-07-11 11:47:58 +0000 [warn]: dump an error event: error_class=Fluent::Plugin::ElasticsearchOutput::RecoverableRequestFailure error="could not push logs to Elasticsearch cluster ({:host=>\"elasticsearch-elasticsearch-single\", :port=>9200, :scheme=>\"http\"}): undefined method `has_key?' for nil:NilClass" location="/var/lib/gems/2.3.0/gems/fluent-plugin-elasticsearch-3.5.2/lib/fluent/plugin/out_elasticsearch.rb:757:in `rescue in send_bulk'" tag="kubernetes.var.log.containers.bitshares-2-6684558cf7-gxcff_prod_bitshares-2-938d500dd438a18ed15f04aa43c5efb7ec6d3bb279abacbb6284d1f9cd1ee8c3.log" time=2019-07-10 16:58:13.629449699 +0000 record={"log"=>"3493628ms th_a       database_api.cpp:244          database_api_impl    ] creating database api 322510992\n", "stream"=>"stderr", "docker"=>{"container_id"=>"938d500dd438a18ed15f04aa43c5efb7ec6d3bb279abacbb6284d1f9cd1ee8c3"}, "kubernetes"=>{"container_name"=>"bitshares-2", "namespace_name"=>"prod", "pod_name"=>"bitshares-2-6684558cf7-gxcff", "container_image"=>"bitshares:3", "container_image_id"=>"docker-pullable://bitshares@sha256:6aa96cc4d5893bb6537dc067eec08ef1cde3d58e9a28ac8b6c248302111edc6f", "pod_id"=>"fd8b9401-994b-11e9-8ca9-42010a9c0082", "labels"=>{"app"=>"bitshares-2", "pod-template-hash"=>"2240114793"}, "host"=>"gke-main-labeled-318e8496-6xgd", "master_url"=>"https://10.27.240.1:443/api", "namespace_id"=>"cfed09ad-2b71-11e8-a63d-42010a9c0110"}, "@timestamp"=>"2019-07-10T16:58:13.629449699+00:00", "tag"=>"kubernetes.var.log.containers.bitshares-2-6684558cf7-gxcff_prod_bitshares-2-938d500dd438a18ed15f04aa43c5efb7ec6d3bb279abacbb6284d1f9cd1ee8c3.log"}
```

**Using Fluentd and ES plugin versions**

* OS version
  Linux 4.14.127+ #1 SMP Tue Jun 18 18:32:10 PDT 2019 x86_64 GNU/Linux
* Bare Metal or within Docker or Kubernetes or others?
  Kubernetes
* Fluentd v0.12 or v0.14/v1.0
  fluentd 1.4.2
* ES plugin 3.x.y/2.x.y or 1.x.y
  3.5.2
* ES version
  6.5.3
* paste result of fluent-gem list, td-agent-gem list or your Gemfile.lock
```
activesupport (5.2.3)
addressable (2.6.0)
base91 (0.0.1)
bigdecimal (1.2.8)
concurrent-ruby (1.1.5)
cool.io (1.5.4)
did_you_mean (1.0.0)
dig_rb (1.0.1)
domain_name (0.5.20190701)
elasticsearch (7.2.0)
elasticsearch-api (7.2.0)
elasticsearch-transport (7.2.0)
excon (0.64.0)
faraday (0.15.4)
ffi (1.11.1)
fluent-plugin-concat (2.3.0)
fluent-plugin-detect-exceptions (0.0.12)
fluent-plugin-elasticsearch (3.5.2)
fluent-plugin-genhashvalue (1.1)
fluent-plugin-kubernetes_metadata_filter (2.1.6)
fluent-plugin-multi-format-parser (1.0.0)
fluent-plugin-prometheus (1.3.0)
fluent-plugin-systemd (1.0.2)
fluentd (1.4.2)
http (0.9.8)
http-cookie (1.0.3)
http-form_data (1.0.3)
http_parser.rb (0.6.0)
i18n (1.6.0)
io-console (0.4.5)
json (1.8.3)
kubeclient (1.1.4)
lru_redux (1.1.0)
mime-types (3.2.2)
mime-types-data (3.2019.0331)
minitest (5.11.3, 5.9.0)
msgpack (1.3.0)
multi_json (1.13.1)
multipart-post (2.1.1)
murmurhash3 (0.1.6)
net-telnet (0.1.1)
netrc (0.11.0)
oj (3.7.12)
power_assert (0.2.7)
prometheus-client (0.9.0)
psych (2.1.0)
public_suffix (3.1.1)
quantile (0.2.1)
rake (10.5.0)
rdoc (4.2.1)
recursive-open-struct (1.0.0)
rest-client (2.0.2)
serverengine (2.1.1)
sigdump (0.2.4)
strptime (0.2.3)
systemd-journal (1.3.3)
test-unit (3.1.7)
thread_safe (0.3.6)
tzinfo (1.2.5)
tzinfo-data (1.2019.2)
unf (0.1.4)
unf_ext (0.0.7.6)
yajl-ruby (1.4.1)
```

**Comment by JustDolanIt** [comment]
I've debuged where this issue happens: https://github.com/uken/fluent-plugin-elasticsearch/blob/7cc851916d007228b040e49b936b49fa5a30224b/lib/fluent/plugin/elasticsearch_error_handler.rb#L59

But why - I couldn't understand

**Comment by JustDolanIt** [comment]
I've tried to wrap 

https://github.com/uken/fluent-plugin-elasticsearch/blob/7cc851916d007228b040e49b936b49fa5a30224b/lib/fluent/plugin/elasticsearch_error_handler.rb#L59-L110 

in

```ruby
if !item.nil?
  ...
else
  stats[:niled_items] += 1
end
```

Errors stopped flushing into console, but it basically drops nearly all messages:

```
2019-07-11 14:51:32 +0000 [debug]: [elasticsearch] Indexed (op = create), 13762 successes, 2018 duplicates, 53233 niled_items
```

On the bright side, atleast some logs started to flow into ES

Yet I'm pretty sure that this solution is far from being good, yet I hope it may help in diagnose

**Comment by cosmo0920** [comment]
Sorry for being late.
Could you try this patch?
https://github.com/uken/fluent-plugin-elasticsearch/compare/handle-nil-items-resp
