### ISSUE TITLE
Crash with with_transporter_log enabled

### ISSUE THREAD

**Issue by a-hat** [uken/fluent-plugin-elasticsearch#599]
#### Problem

Fluentd crashes on startup, when `with_transporter_log true` is specified in config.

```
2019-06-14 12:31:29 +0000 [error]: unexpected error error_class=NoMethodError error="undefined method `info?' for #<Fluent::PluginLogger:0x007f9cb85ea928>\nDid you mean?  info\n               INFO"
  2019-06-14 12:31:29 +0000 [error]: /var/lib/gems/2.3.0/gems/elasticsearch-transport-7.0.0/lib/elasticsearch/transport/transport/loggable.rb:70:in `log_info'
  2019-06-14 12:31:29 +0000 [error]: /var/lib/gems/2.3.0/gems/elasticsearch-transport-7.0.0/lib/elasticsearch/transport/transport/base.rb:189:in `__log_response'
  2019-06-14 12:31:29 +0000 [error]: /var/lib/gems/2.3.0/gems/elasticsearch-transport-7.0.0/lib/elasticsearch/transport/transport/base.rb:345:in `perform_request'
  2019-06-14 12:31:29 +0000 [error]: /var/lib/gems/2.3.0/gems/elasticsearch-transport-7.0.0/lib/elasticsearch/transport/transport/http/faraday.rb:37:in `perform_request'
  2019-06-14 12:31:29 +0000 [error]: /var/lib/gems/2.3.0/gems/elasticsearch-transport-7.0.0/lib/elasticsearch/transport/client.rb:160:in `perform_request'
  2019-06-14 12:31:29 +0000 [error]: /var/lib/gems/2.3.0/gems/elasticsearch-api-7.0.0/lib/elasticsearch/api/actions/info.rb:32:in `info'
  2019-06-14 12:31:29 +0000 [error]: /var/lib/gems/2.3.0/gems/fluent-plugin-elasticsearch-3.4.3/lib/fluent/plugin/out_elasticsearch.rb:323:in `detect_es_major_version'
  2019-06-14 12:31:29 +0000 [error]: /var/lib/gems/2.3.0/gems/fluent-plugin-elasticsearch-3.4.3/lib/fluent/plugin/out_elasticsearch.rb:250:in `block in configure'
  2019-06-14 12:31:29 +0000 [error]: /var/lib/gems/2.3.0/gems/fluent-plugin-elasticsearch-3.4.3/lib/fluent/plugin/elasticsearch_index_template.rb:35:in `retry_operate'
  2019-06-14 12:31:29 +0000 [error]: /var/lib/gems/2.3.0/gems/fluent-plugin-elasticsearch-3.4.3/lib/fluent/plugin/out_elasticsearch.rb:249:in `configure'
  2019-06-14 12:31:29 +0000 [error]: /var/lib/gems/2.3.0/gems/fluentd-1.4.2/lib/fluent/plugin.rb:164:in `configure'
  2019-06-14 12:31:29 +0000 [error]: /var/lib/gems/2.3.0/gems/fluentd-1.4.2/lib/fluent/agent.rb:130:in `add_match'
  2019-06-14 12:31:29 +0000 [error]: /var/lib/gems/2.3.0/gems/fluentd-1.4.2/lib/fluent/agent.rb:72:in `block in configure'
  2019-06-14 12:31:29 +0000 [error]: /var/lib/gems/2.3.0/gems/fluentd-1.4.2/lib/fluent/agent.rb:64:in `each'
  2019-06-14 12:31:29 +0000 [error]: /var/lib/gems/2.3.0/gems/fluentd-1.4.2/lib/fluent/agent.rb:64:in `configure'
  2019-06-14 12:31:29 +0000 [error]: /var/lib/gems/2.3.0/gems/fluentd-1.4.2/lib/fluent/label.rb:31:in `configure'
  2019-06-14 12:31:29 +0000 [error]: /var/lib/gems/2.3.0/gems/fluentd-1.4.2/lib/fluent/root_agent.rb:147:in `block in configure'
  2019-06-14 12:31:29 +0000 [error]: /var/lib/gems/2.3.0/gems/fluentd-1.4.2/lib/fluent/root_agent.rb:147:in `each'
  2019-06-14 12:31:29 +0000 [error]: /var/lib/gems/2.3.0/gems/fluentd-1.4.2/lib/fluent/root_agent.rb:147:in `configure'
  2019-06-14 12:31:29 +0000 [error]: /var/lib/gems/2.3.0/gems/fluentd-1.4.2/lib/fluent/engine.rb:131:in `configure'
  2019-06-14 12:31:29 +0000 [error]: /var/lib/gems/2.3.0/gems/fluentd-1.4.2/lib/fluent/engine.rb:96:in `run_configure'
  2019-06-14 12:31:29 +0000 [error]: /var/lib/gems/2.3.0/gems/fluentd-1.4.2/lib/fluent/supervisor.rb:801:in `run_configure'
  2019-06-14 12:31:29 +0000 [error]: /var/lib/gems/2.3.0/gems/fluentd-1.4.2/lib/fluent/supervisor.rb:548:in `block in run_worker'
  2019-06-14 12:31:29 +0000 [error]: /var/lib/gems/2.3.0/gems/fluentd-1.4.2/lib/fluent/supervisor.rb:730:in `main_process'
  2019-06-14 12:31:29 +0000 [error]: /var/lib/gems/2.3.0/gems/fluentd-1.4.2/lib/fluent/supervisor.rb:544:in `run_worker'
  2019-06-14 12:31:29 +0000 [error]: /var/lib/gems/2.3.0/gems/fluentd-1.4.2/lib/fluent/command/fluentd.rb:316:in `<top (required)>'
  2019-06-14 12:31:29 +0000 [error]: /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  2019-06-14 12:31:29 +0000 [error]: /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  2019-06-14 12:31:29 +0000 [error]: /var/lib/gems/2.3.0/gems/fluentd-1.4.2/bin/fluentd:8:in `<top (required)>'
  2019-06-14 12:31:29 +0000 [error]: /usr/local/bin/fluentd:22:in `load'
  2019-06-14 12:31:29 +0000 [error]: /usr/local/bin/fluentd:22:in `<main>'
```

...

#### Steps to replicate

Example config:

```
<match **>
        @id elasticsearch
        @type elasticsearch
        #@log_level info
        @log_level warn

        with_transporter_log true
        validate_client_version true
        log_es_400_reason true

        include_tag_key true
        type_name _doc
        host "#{ENV['OUTPUT_HOST']}"
        port "#{ENV['OUTPUT_PORT']}"
        scheme "#{ENV['OUTPUT_SCHEME']}"
        ssl_verify "#{ENV['OUTPUT_SSL_VERIFY']}"
        ssl_version "#{ENV['OUTPUT_SSL_VERSION']}"
        {{- if .Values.elasticsearch.auth.enabled }}
              user "#{ENV['OUTPUT_USER']}"
              password "#{ENV['OUTPUT_PASSWORD']}"
        {{- end }}
        logstash_format true
        logstash_prefix "#{ENV['LOGSTASH_PREFIX']}"
        reconnect_on_error true
        <buffer>
          @type file
          path /var/log/fluentd-buffers/kubernetes.system.buffer
          flush_mode interval
          retry_type exponential_backoff
          flush_thread_count 2
          flush_interval 5s
          retry_forever
          retry_max_interval 30
          chunk_limit_size "#{ENV['OUTPUT_BUFFER_CHUNK_LIMIT']}"
          queue_limit_length "#{ENV['OUTPUT_BUFFER_QUEUE_LIMIT']}"
          overflow_action block
        </buffer>
      </match>
```

I am using this [helm chart](https://github.com/kiwigrid/helm-charts/tree/master/charts/fluentd-elasticsearch)

Version of fluent-plugin-elasticsearch is 3.4.3, fluentd is 1.4.2

**Comment by cosmo0920** [comment]
https://github.com/uken/fluent-plugin-elasticsearch/commit/66b4d2bffea9be9861a16f169101efd5e431b384
This issue is already fixed master in this plugin.
This issue is not ES plugin issue but ES plugin helm chart.
Anyway, thanks for using this plugin.
I'm closing this issue now.

**Comment by cosmo0920** [comment]
FYI: Fluentd ES helm chart is updated to v3.5.2.
https://github.com/kubernetes/kubernetes/pull/79014

You can avoid this crash with updating helm chart.
