### ISSUE TITLE
Plugin 3.x.x fails to work with Humio

### ISSUE THREAD

**Issue by kapodes** [uken/fluent-plugin-elasticsearch#603]
#### Problem
I use this plugin to export logs to humio which exposes ES bulk API. However it's not 100% same. So if I use latest 3.X versions of the plugin fluentd fails to start since plugin can't detect ES major version. Before in 2.x versions it just assumed version 6 and everything worked fine.
You can check similar issue from the past https://github.com/uken/fluent-plugin-elasticsearch/issues/478
...

#### Steps to replicate

```
2019-06-21 09:18:07 +0000 [info]: Worker 0 finished unexpectedly with status 1
2019-06-21 09:18:08 +0000 [info]: gem 'fluent-plugin-elasticsearch' version '3.5.2'
2019-06-21 09:18:08 +0000 [info]: gem 'fluentd' version '1.5.2'
2019-06-21 09:18:08 +0000 [info]: adding filter pattern="kube.**" type="grep"
2019-06-21 09:18:08 +0000 [info]: adding filter pattern="kube.**" type="record_transformer"
2019-06-21 09:18:08 +0000 [info]: adding match pattern="kube.**" type="elasticsearch"
2019-06-21 09:18:08 +0000 [error]: #0 unexpected error error_class=NoMethodError error="undefined method `[]' for nil:NilClass"
  2019-06-21 09:18:08 +0000 [error]: #0 /usr/local/bundle/gems/fluent-plugin-elasticsearch-3.5.2/lib/fluent/plugin/out_elasticsearch.rb:335:in `detect_es_major_version'
  2019-06-21 09:18:08 +0000 [error]: #0 /usr/local/bundle/gems/fluent-plugin-elasticsearch-3.5.2/lib/fluent/plugin/out_elasticsearch.rb:245:in `block in configure'
  2019-06-21 09:18:08 +0000 [error]: #0 /usr/local/bundle/gems/fluent-plugin-elasticsearch-3.5.2/lib/fluent/plugin/elasticsearch_index_template.rb:35:in `retry_operate'
  2019-06-21 09:18:08 +0000 [error]: #0 /usr/local/bundle/gems/fluent-plugin-elasticsearch-3.5.2/lib/fluent/plugin/out_elasticsearch.rb:244:in `configure'
  2019-06-21 09:18:08 +0000 [error]: #0 /usr/local/bundle/gems/fluentd-1.5.2/lib/fluent/plugin.rb:164:in `configure'
  2019-06-21 09:18:08 +0000 [error]: #0 /usr/local/bundle/gems/fluentd-1.5.2/lib/fluent/agent.rb:130:in `add_match'
  2019-06-21 09:18:08 +0000 [error]: #0 /usr/local/bundle/gems/fluentd-1.5.2/lib/fluent/agent.rb:72:in `block in configure'
  2019-06-21 09:18:08 +0000 [error]: #0 /usr/local/bundle/gems/fluentd-1.5.2/lib/fluent/agent.rb:64:in `each'
  2019-06-21 09:18:08 +0000 [error]: #0 /usr/local/bundle/gems/fluentd-1.5.2/lib/fluent/agent.rb:64:in `configure'
  2019-06-21 09:18:08 +0000 [error]: #0 /usr/local/bundle/gems/fluentd-1.5.2/lib/fluent/root_agent.rb:150:in `configure'
  2019-06-21 09:18:08 +0000 [error]: #0 /usr/local/bundle/gems/fluentd-1.5.2/lib/fluent/engine.rb:131:in `configure'
  2019-06-21 09:18:08 +0000 [error]: #0 /usr/local/bundle/gems/fluentd-1.5.2/lib/fluent/engine.rb:96:in `run_configure'
  2019-06-21 09:18:08 +0000 [error]: #0 /usr/local/bundle/gems/fluentd-1.5.2/lib/fluent/supervisor.rb:801:in `run_configure'
  2019-06-21 09:18:08 +0000 [error]: #0 /usr/local/bundle/gems/fluentd-1.5.2/lib/fluent/supervisor.rb:548:in `block in run_worker'
  2019-06-21 09:18:08 +0000 [error]: #0 /usr/local/bundle/gems/fluentd-1.5.2/lib/fluent/supervisor.rb:730:in `main_process'
  2019-06-21 09:18:08 +0000 [error]: #0 /usr/local/bundle/gems/fluentd-1.5.2/lib/fluent/supervisor.rb:544:in `run_worker'
  2019-06-21 09:18:08 +0000 [error]: #0 /usr/local/bundle/gems/fluentd-1.5.2/lib/fluent/command/fluentd.rb:316:in `<top (required)>'
  2019-06-21 09:18:08 +0000 [error]: #0 /usr/local/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
  2019-06-21 09:18:08 +0000 [error]: #0 /usr/local/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
  2019-06-21 09:18:08 +0000 [error]: #0 /usr/local/bundle/gems/fluentd-1.5.2/bin/fluentd:8:in `<top (required)>'
  2019-06-21 09:18:08 +0000 [error]: #0 /usr/local/bundle/bin/fluentd:23:in `load'
  2019-06-21 09:18:08 +0000 [error]: #0 /usr/local/bundle/bin/fluentd:23:in `<main>'
```

#### Expected Behavior or What you need to ask
Fluentd starts and logs are sent :)

**Comment by kapodes** [comment]
Found misconfiguration in fluent.conf
New versions of Humio can resolve dataspace from token so custom path not needed. just leave it empty in fluent.conf like

```
      @type elasticsearch
      scheme http
      host {{ .Values.humio.host }}
      port {{ .Values.humio.port }}
      path
      user {{ required "A humio repository ingress token" .Values.humio.token }}
      password none

```
