### ISSUE TITLE
fluentd does not start with fluent-plugin-elasticsearch 3.5.2

### ISSUE THREAD

**Issue by msproact** [uken/fluent-plugin-elasticsearch#605]
#### Problem

Fluentd 1.6.0 does not start with `fluent-plugin-elasticsearch` 3.5.2 installed:

```
Jul  9 15:37:28 fluentd systemd[1]: Starting Fluentd...
Jul  9 15:37:28 fluentd fluentd[1878]: 2019-07-09 15:37:28 +0200 [info]: parsing config file is succeeded path="/etc/fluent/fluent.conf"
Jul  9 15:37:28 fluentd fluentd[1878]: /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:113:in `require': unable to find a version of 'fluentd' to activate (Gem::Loa
dError)
Jul  9 15:37:28 fluentd fluentd[1878]: #011from /var/lib/gems/2.3.0/gems/fluent-plugin-elasticsearch-3.5.2/lib/fluent/log-ext.rb:1:in `<top (required)>'
Jul  9 15:37:28 fluentd fluentd[1878]: #011from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `require'
Jul  9 15:37:28 fluentd fluentd[1878]: #011from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `rescue in require'
Jul  9 15:37:28 fluentd fluentd[1878]: #011from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
Jul  9 15:37:28 fluentd fluentd[1878]: #011from /var/lib/gems/2.3.0/gems/fluent-plugin-elasticsearch-3.5.2/lib/fluent/plugin/out_elasticsearch.rb:16:in `<top (required)>'
Jul  9 15:37:28 fluentd fluentd[1878]: #011from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
Jul  9 15:37:28 fluentd fluentd[1878]: #011from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
Jul  9 15:37:28 fluentd fluentd[1878]: #011from /var/lib/gems/2.3.0/gems/fluentd-1.6.0/lib/fluent/registry.rb:102:in `block in search'
Jul  9 15:37:28 fluentd fluentd[1878]: #011from /var/lib/gems/2.3.0/gems/fluentd-1.6.0/lib/fluent/registry.rb:99:in `each'
Jul  9 15:37:28 fluentd fluentd[1878]: #011from /var/lib/gems/2.3.0/gems/fluentd-1.6.0/lib/fluent/registry.rb:99:in `search'
Jul  9 15:37:28 fluentd fluentd[1878]: #011from /var/lib/gems/2.3.0/gems/fluentd-1.6.0/lib/fluent/registry.rb:44:in `lookup'
Jul  9 15:37:28 fluentd fluentd[1878]: #011from /var/lib/gems/2.3.0/gems/fluentd-1.6.0/lib/fluent/plugin.rb:146:in `new_impl'
Jul  9 15:37:28 fluentd fluentd[1878]: #011from /var/lib/gems/2.3.0/gems/fluentd-1.6.0/lib/fluent/plugin.rb:104:in `new_output'
Jul  9 15:37:28 fluentd fluentd[1878]: #011from /var/lib/gems/2.3.0/gems/fluentd-1.6.0/lib/fluent/agent.rb:128:in `add_match'
Jul  9 15:37:28 fluentd fluentd[1878]: #011from /var/lib/gems/2.3.0/gems/fluentd-1.6.0/lib/fluent/agent.rb:72:in `block in configure'
Jul  9 15:37:28 fluentd fluentd[1878]: #011from /var/lib/gems/2.3.0/gems/fluentd-1.6.0/lib/fluent/agent.rb:64:in `each'
Jul  9 15:37:28 fluentd fluentd[1878]: #011from /var/lib/gems/2.3.0/gems/fluentd-1.6.0/lib/fluent/agent.rb:64:in `configure'
Jul  9 15:37:28 fluentd fluentd[1878]: #011from /var/lib/gems/2.3.0/gems/fluentd-1.6.0/lib/fluent/label.rb:31:in `configure'
Jul  9 15:37:28 fluentd fluentd[1878]: #011from /var/lib/gems/2.3.0/gems/fluentd-1.6.0/lib/fluent/root_agent.rb:147:in `block in configure'
Jul  9 15:37:28 fluentd fluentd[1878]: #011from /var/lib/gems/2.3.0/gems/fluentd-1.6.0/lib/fluent/root_agent.rb:147:in `each'
Jul  9 15:37:28 fluentd fluentd[1878]: #011from /var/lib/gems/2.3.0/gems/fluentd-1.6.0/lib/fluent/root_agent.rb:147:in `configure'
Jul  9 15:37:28 fluentd fluentd[1878]: #011from /var/lib/gems/2.3.0/gems/fluentd-1.6.0/lib/fluent/engine.rb:131:in `configure'
Jul  9 15:37:28 fluentd fluentd[1878]: #011from /var/lib/gems/2.3.0/gems/fluentd-1.6.0/lib/fluent/engine.rb:96:in `run_configure'
Jul  9 15:37:28 fluentd fluentd[1878]: #011from /var/lib/gems/2.3.0/gems/fluentd-1.6.0/lib/fluent/supervisor.rb:804:in `run_configure'
Jul  9 15:37:28 fluentd fluentd[1878]: #011from /var/lib/gems/2.3.0/gems/fluentd-1.6.0/lib/fluent/supervisor.rb:581:in `dry_run'
Jul  9 15:37:28 fluentd fluentd[1878]: #011from /var/lib/gems/2.3.0/gems/fluentd-1.6.0/lib/fluent/supervisor.rb:599:in `supervise'
Jul  9 15:37:28 fluentd fluentd[1878]: #011from /var/lib/gems/2.3.0/gems/fluentd-1.6.0/lib/fluent/supervisor.rb:504:in `run_supervisor'
Jul  9 15:37:28 fluentd fluentd[1878]: #011from /var/lib/gems/2.3.0/gems/fluentd-1.6.0/lib/fluent/command/fluentd.rb:314:in `<top (required)>'
Jul  9 15:37:28 fluentd fluentd[1878]: #011from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
Jul  9 15:37:28 fluentd fluentd[1878]: #011from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
Jul  9 15:37:28 fluentd fluentd[1878]: #011from /var/lib/gems/2.3.0/gems/fluentd-1.6.0/bin/fluentd:8:in `<top (required)>'
Jul  9 15:37:28 fluentd fluentd[1878]: #011from /usr/local/bin/fluentd:22:in `load'
Jul  9 15:37:28 fluentd fluentd[1878]: #011from /usr/local/bin/fluentd:22:in `<main>'
Jul  9 15:37:28 fluentd systemd[1]: fluentd.service: Control process exited, code=exited status=1
Jul  9 15:37:28 fluentd systemd[1]: Failed to start Fluentd.
Jul  9 15:37:28 fluentd systemd[1]: fluentd.service: Unit entered failed state.
Jul  9 15:37:28 fluentd systemd[1]: fluentd.service: Failed with result 'exit-code'.
Jul  9 15:37:29 fluentd systemd[1]: fluentd.service: Service hold-off time over, scheduling restart.
Jul  9 15:37:29 fluentd systemd[1]: Stopped Fluentd.
Jul  9 15:37:29 fluentd systemd[1]: fluentd.service: Start request repeated too quickly.
Jul  9 15:37:29 fluentd systemd[1]: Failed to start Fluentd.
Jul  9 15:37:29 fluentd systemd[1]: fluentd.service: Unit entered failed state.
Jul  9 15:37:29 fluentd systemd[1]: fluentd.service: Failed with result 'exit-code'.
Jul  9 15:39:11 fluentd systemd[1]: Starting Fluentd...
```

It works with `fluent-plugin-elasticsearch` 3.4.2.

#### Steps to replicate

- Have `fluent-plugin-elasticsearch` 3.5.2 installed with a configuration that uses it
- Start Fluentd. Happened with various Fluentd versions, this time with 1.6.0.

The Fluentd configuration I use is:

```
## built-in TCP input
## $ echo <json> | fluent-cat <tag>
<source>
        @type forward
        @id forward_input
</source>

<source>
        @type syslog
        @id in_syslog
        @label @SYSLOG
        tag syslog
        port 5140
        protocol_type tcp
        message_format auto
        priority_key severity
        facility_key facility
</source>

<label @SYSLOG>
        <match syslog.**>
                @type elasticsearch
                hosts elasticsearch1a,elasticsearch1b,elasticsearch1c
                port 9200
                index_name fluentd-syslog
                type_name fluentd
                include_timestamp true
        </match>
</label>

<label @FLUENT_LOG>
        <match fluent.**>
                @type elasticsearch
                hosts elasticsearch1a,elasticsearch1b,elasticsearch1c
                port 9200
                index_name fluentd-internal
                type_name fluentd
                include_timestamp true
        </match>
</label>
```

That label stuff might be overkill, but with `fluent-plugin-elasticsearch` upto 3.4.2 it works.

#### Expected Behavior or What you need to ask

Fluentd starts with `fluent-plugin-elasticsearch` 3.5.2

#### Using Fluentd and ES plugin versions

* OS version: Debian 9.9
* KVM VM on Proxmox VE 4.4
* fluentd 1.6.0
* ES plugin 3.5.2.
* ES version: 7.2.0

All gems:

```
% fluent-gem list

*** LOCAL GEMS ***

bigdecimal (1.4.4, 1.4.3, 1.3.5, 1.3.4, 1.2.8)
concurrent-ruby (1.1.5, 1.1.4)
cool.io (1.5.4, 1.5.3)
did_you_mean (1.0.0)
dig_rb (1.0.1)
elasticsearch (7.2.0, 7.1.0, 7.0.0, 6.3.0, 6.2.0, 6.1.0, 6.0.2, 6.0.1, 6.0.0)
elasticsearch-api (7.2.0, 7.1.0, 7.0.0, 6.3.0, 6.2.0, 6.1.0, 6.0.2, 6.0.1, 6.0.0)
elasticsearch-transport (7.2.0, 7.1.0, 7.0.0, 6.3.0, 6.2.0, 6.1.0, 6.0.2, 6.0.1, 6.0.0)
excon (0.64.0, 0.62.0, 0.60.0)
faraday (0.15.4, 0.15.2, 0.15.0, 0.14.0)
fluent-plugin-elasticsearch (3.5.2, 3.4.2, 3.4.0, 3.3.0, 3.2.0, 3.1.0, 2.11.6, 2.11.1, 2.10.1, 2.9.2, 2.8.0, 2.6.0, 2.4.1)
fluentd (1.6.0, 1.5.0, 1.4.1, 1.4.0, 1.3.3, 1.2.5, 1.2.3, 1.2.1, 1.1.3, 1.1.1, 1.1.0)
http_parser.rb (0.6.0)
io-console (0.4.7, 0.4.6, 0.4.5)
json (2.2.0, 2.1.0, 1.8.3)
minitest (5.11.3, 5.9.0)
msgpack (1.3.0, 1.2.10, 1.2.9, 1.2.7, 1.2.6, 1.2.4, 1.2.2)
multi_json (1.13.1)
multipart-post (2.1.1, 2.0.0)
net-telnet (0.2.0, 0.1.1)
power_assert (1.1.4, 1.1.3, 1.1.1, 0.2.7)
psych (3.1.0, 3.0.2, 2.1.0)
rake (12.3.2, 12.3.1, 12.3.0, 10.5.0)
rdoc (6.1.1, 6.0.4, 6.0.3, 6.0.1, 4.2.1)
serverengine (2.1.1, 2.1.0, 2.0.7, 2.0.6)
sigdump (0.2.4)
strptime (0.2.3)
test-unit (3.3.3, 3.3.2, 3.3.1, 3.3.0, 3.2.8, 3.2.7, 3.1.7)
thread_safe (0.3.6)
tzinfo (2.0.0, 1.2.5, 1.2.4)
tzinfo-data (1.2019.2, 1.2019.1, 1.2018.9, 1.2018.5, 1.2018.4, 1.2018.3, 1.2017.3)
yajl-ruby (1.4.1, 1.4.0, 1.3.1)
```

After

```
% fluent-gem uninstall --version 3.5.2 fluent-plugin-elasticsearch
Successfully uninstalled fluent-plugin-elasticsearch-3.5.2
```

Fluentd starts just fine.

**Comment by cosmo0920** [comment]
Could you provide log which is generated with raw fluentd and ES plugin procedure?

**Comment by msproact** [comment]
I do not understand what you mean. How would I do this?

**Comment by cosmo0920** [comment]
* Please launch Fluentd without `systemctl`.
* Please provide ES plugin installation command.

**Comment by msproact** [comment]
Installation of most recent ES plugin:

```
root@fluentd:~# fluent-gem update
Updating installed gems
Updating did_you_mean
ERROR:  Error installing did_you_mean:
        did_you_mean requires Ruby version >= 2.5.0.
Updating fluent-plugin-elasticsearch
Fetching: fluent-plugin-elasticsearch-3.5.2.gem (100%)
Successfully installed fluent-plugin-elasticsearch-3.5.2
Parsing documentation for fluent-plugin-elasticsearch-3.5.2
Installing ri documentation for fluent-plugin-elasticsearch-3.5.2
Installing darkfish documentation for fluent-plugin-elasticsearch-3.5.2
Done installing documentation for fluent-plugin-elasticsearch after 0 seconds
Parsing documentation for fluent-plugin-elasticsearch-3.5.2
Done installing documentation for fluent-plugin-elasticsearch after 0 seconds
Gems updated: did_you_mean fluent-plugin-elasticsearch
```

Ruby version (Standard Ruby version in Debian 9.9):

```
root@fluentd:~# ruby --version
ruby 2.3.3p222 (2016-11-21) [x86_64-linux-gnu]
```

Systemd service used (adapted from TD-Agent service):

```
root@fluentd:~# cat /etc/systemd/system/fluentd.service
[Unit]
Description=Fluentd
Documentation=https://docs.fluentd.org/
After=network.target

[Service]
Type=forking
ExecStart=/usr/local/bin/fluentd -d /run/fluentd.pid
PIDFile=/run/fluentd.pid
Restart=on-failure

[Install]
WantedBy=multi-user.target
```

Start directly on console:

```
root@fluentd:~# /usr/local/bin/fluentd -d /run/fluentd.pid
2019-07-10 10:34:53 +0200 [info]: parsing config file is succeeded path="/etc/fluent/fluent.conf"
/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:113:in `require': unable to find a version of 'fluentd' to activate (Gem::LoadError)
        from /var/lib/gems/2.3.0/gems/fluent-plugin-elasticsearch-3.5.2/lib/fluent/log-ext.rb:1:in `<top (required)>'
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `require'
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `rescue in require'
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
        from /var/lib/gems/2.3.0/gems/fluent-plugin-elasticsearch-3.5.2/lib/fluent/plugin/out_elasticsearch.rb:16:in `<top (required)>'
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /var/lib/gems/2.3.0/gems/fluentd-1.6.0/lib/fluent/registry.rb:102:in `block in search'
        from /var/lib/gems/2.3.0/gems/fluentd-1.6.0/lib/fluent/registry.rb:99:in `each'
        from /var/lib/gems/2.3.0/gems/fluentd-1.6.0/lib/fluent/registry.rb:99:in `search'
        from /var/lib/gems/2.3.0/gems/fluentd-1.6.0/lib/fluent/registry.rb:44:in `lookup'
        from /var/lib/gems/2.3.0/gems/fluentd-1.6.0/lib/fluent/plugin.rb:146:in `new_impl'
        from /var/lib/gems/2.3.0/gems/fluentd-1.6.0/lib/fluent/plugin.rb:104:in `new_output'
        from /var/lib/gems/2.3.0/gems/fluentd-1.6.0/lib/fluent/agent.rb:128:in `add_match'
        from /var/lib/gems/2.3.0/gems/fluentd-1.6.0/lib/fluent/agent.rb:72:in `block in configure'
        from /var/lib/gems/2.3.0/gems/fluentd-1.6.0/lib/fluent/agent.rb:64:in `each'
        from /var/lib/gems/2.3.0/gems/fluentd-1.6.0/lib/fluent/agent.rb:64:in `configure'
        from /var/lib/gems/2.3.0/gems/fluentd-1.6.0/lib/fluent/label.rb:31:in `configure'
        from /var/lib/gems/2.3.0/gems/fluentd-1.6.0/lib/fluent/root_agent.rb:147:in `block in configure'
        from /var/lib/gems/2.3.0/gems/fluentd-1.6.0/lib/fluent/root_agent.rb:147:in `each'
        from /var/lib/gems/2.3.0/gems/fluentd-1.6.0/lib/fluent/root_agent.rb:147:in `configure'
        from /var/lib/gems/2.3.0/gems/fluentd-1.6.0/lib/fluent/engine.rb:131:in `configure'
        from /var/lib/gems/2.3.0/gems/fluentd-1.6.0/lib/fluent/engine.rb:96:in `run_configure'
        from /var/lib/gems/2.3.0/gems/fluentd-1.6.0/lib/fluent/supervisor.rb:804:in `run_configure'
        from /var/lib/gems/2.3.0/gems/fluentd-1.6.0/lib/fluent/supervisor.rb:581:in `dry_run'
        from /var/lib/gems/2.3.0/gems/fluentd-1.6.0/lib/fluent/supervisor.rb:599:in `supervise'
        from /var/lib/gems/2.3.0/gems/fluentd-1.6.0/lib/fluent/supervisor.rb:504:in `run_supervisor'
        from /var/lib/gems/2.3.0/gems/fluentd-1.6.0/lib/fluent/command/fluentd.rb:314:in `<top (required)>'
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /var/lib/gems/2.3.0/gems/fluentd-1.6.0/bin/fluentd:8:in `<top (required)>'
        from /usr/local/bin/fluentd:22:in `load'
        from /usr/local/bin/fluentd:22:in `<main>'
```

**Comment by msproact** [comment]
Running without argument for PID file:

```
root@fluentd:~# /usr/local/bin/fluentd
2019-07-10 10:37:06 +0200 [info]: parsing config file is succeeded path="/etc/fluent/fluent.conf"
/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:113:in `require': unable to find a version of 'fluentd' to activate (Gem::LoadError)
        from /var/lib/gems/2.3.0/gems/fluent-plugin-elasticsearch-3.5.2/lib/fluent/log-ext.rb:1:in `<top (required)>'
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `require'
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `rescue in require'
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
        from /var/lib/gems/2.3.0/gems/fluent-plugin-elasticsearch-3.5.2/lib/fluent/plugin/out_elasticsearch.rb:16:in `<top (required)>'
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /var/lib/gems/2.3.0/gems/fluentd-1.6.0/lib/fluent/registry.rb:102:in `block in search'
        from /var/lib/gems/2.3.0/gems/fluentd-1.6.0/lib/fluent/registry.rb:99:in `each'
        from /var/lib/gems/2.3.0/gems/fluentd-1.6.0/lib/fluent/registry.rb:99:in `search'
        from /var/lib/gems/2.3.0/gems/fluentd-1.6.0/lib/fluent/registry.rb:44:in `lookup'
        from /var/lib/gems/2.3.0/gems/fluentd-1.6.0/lib/fluent/plugin.rb:146:in `new_impl'
        from /var/lib/gems/2.3.0/gems/fluentd-1.6.0/lib/fluent/plugin.rb:104:in `new_output'
        from /var/lib/gems/2.3.0/gems/fluentd-1.6.0/lib/fluent/agent.rb:128:in `add_match'
        from /var/lib/gems/2.3.0/gems/fluentd-1.6.0/lib/fluent/agent.rb:72:in `block in configure'
        from /var/lib/gems/2.3.0/gems/fluentd-1.6.0/lib/fluent/agent.rb:64:in `each'
        from /var/lib/gems/2.3.0/gems/fluentd-1.6.0/lib/fluent/agent.rb:64:in `configure'
        from /var/lib/gems/2.3.0/gems/fluentd-1.6.0/lib/fluent/label.rb:31:in `configure'
        from /var/lib/gems/2.3.0/gems/fluentd-1.6.0/lib/fluent/root_agent.rb:147:in `block in configure'
        from /var/lib/gems/2.3.0/gems/fluentd-1.6.0/lib/fluent/root_agent.rb:147:in `each'
        from /var/lib/gems/2.3.0/gems/fluentd-1.6.0/lib/fluent/root_agent.rb:147:in `configure'
        from /var/lib/gems/2.3.0/gems/fluentd-1.6.0/lib/fluent/engine.rb:131:in `configure'
        from /var/lib/gems/2.3.0/gems/fluentd-1.6.0/lib/fluent/engine.rb:96:in `run_configure'
        from /var/lib/gems/2.3.0/gems/fluentd-1.6.0/lib/fluent/supervisor.rb:804:in `run_configure'
        from /var/lib/gems/2.3.0/gems/fluentd-1.6.0/lib/fluent/supervisor.rb:581:in `dry_run'
        from /var/lib/gems/2.3.0/gems/fluentd-1.6.0/lib/fluent/supervisor.rb:599:in `supervise'
        from /var/lib/gems/2.3.0/gems/fluentd-1.6.0/lib/fluent/supervisor.rb:504:in `run_supervisor'
        from /var/lib/gems/2.3.0/gems/fluentd-1.6.0/lib/fluent/command/fluentd.rb:314:in `<top (required)>'
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /var/lib/gems/2.3.0/gems/fluentd-1.6.0/bin/fluentd:8:in `<top (required)>'
        from /usr/local/bin/fluentd:22:in `load'
        from /usr/local/bin/fluentd:22:in `<main>'
```

**Comment by cosmo0920** [comment]
I guess that `/usr/local/bin/fluent` points the wrong path.
Could you please check the correct place where fluentd command is put?

**Comment by msproact** [comment]
I schedule it for next week. Currently busy holding a training.

**Comment by msproact** [comment]
I do not have a `fluent` command, but I do have a `fluentd` command:

root@fluentd:~# which fluent
root@fluentd:~# which fluentd
/usr/local/bin/fluentd

Which is:

```
root@fluentd:~# cat /usr/local/bin/fluentd
#!/usr/bin/ruby2.3
#
# This file was generated by RubyGems.
#
# The application 'fluentd' is installed as part of a gem, and
# this file is here to facilitate running it.
#

require 'rubygems'

version = ">= 0.a"

if ARGV.first
  str = ARGV.first
  str = str.dup.force_encoding("BINARY") if str.respond_to? :force_encoding
  if str =~ /\A_(.*)_\z/ and Gem::Version.correct?($1) then
    version = $1
    ARGV.shift
  end
end

load Gem.bin_path('fluentd', 'fluentd', version)
```

I did `fluent-gem clean fluentd` which removed all old versions of fluentd and the bug was still there.

Then I did `fluent-gem clean` to remove all other old gems and the issue does still happen.

I currently have:

```
root@fluentd:~# gem list

*** LOCAL GEMS ***

bigdecimal (1.4.4, 1.2.8)
concurrent-ruby (1.1.5)
cool.io (1.5.4)
did_you_mean (1.0.0)
dig_rb (1.0.1)
elasticsearch (7.3.0)
elasticsearch-api (7.3.0)
elasticsearch-transport (7.3.0)
excon (0.66.0)
faraday (0.15.4)
fluent-plugin-elasticsearch (3.5.4)
fluentd (1.6.3)
http_parser.rb (0.6.0)
io-console (0.4.8, 0.4.5)
json (2.2.0, 1.8.3)
minitest (5.11.3, 5.9.0)
msgpack (1.3.1)
multi_json (1.13.1)
multipart-post (2.1.1)
net-telnet (0.2.0, 0.1.1)
power_assert (1.1.5, 0.2.7)
psych (3.1.0, 2.1.0)
rake (12.3.3, 10.5.0)
rdoc (6.1.1, 4.2.1)
serverengine (2.1.1)
sigdump (0.2.4)
strptime (0.2.3)
test-unit (3.3.3, 3.1.7)
thread_safe (0.3.6)
tzinfo (2.0.0)
tzinfo-data (1.2019.2)
yajl-ruby (1.4.1)
```

And have a different issue now:

```
Aug 12 14:38:22 fluentd fluentd[1272]: /usr/lib/ruby/2.3.0/rubygems/specification.rb:2290:in `raise_if_conflicts': Unable to activate fluentd-1.6.3, because tzinfo-2.0.0 conflicts with tzinfo (~> 1.0) (Gem::ConflictError)
```

However only `tzinfo (2.0.0)` is installed. I see what I can do with this.

**Comment by cosmo0920** [comment]
Could you install tzinfo v1.2.5 with fluent-gem?
Fluentd says that tzinfo v2 doesn't satisfy its tzinfo dependency constraint.

**Comment by msproact** [comment]
Thanks cosmo0920. That did it. I install tzinfo v1.2.5 removed the v2 version and install tzinfo-data again and now fluentd starts. Would you like me to file an issue about fluentd not working with tzinfo v2?

**Comment by msproact** [comment]
That probably is not even a bug. I just upgraded Debian Stretch to Debian Buster on this VM and thus had to reinstall fluentd and fluent-plugin-elasticsearch gems and it installed tzinfo v1.2.5 (instead of v2).

Anyway I believe this issue could be closed now.

**Comment by cosmo0920** [comment]
Fluentd HEAD uses tzinfo v2 now:
https://github.com/fluent/fluentd/commit/2918ee4fefaf7db101f655e0dad14cae98dbfeaa
Yep, we can close this issue.

**Comment by msproact** [comment]
Thanks, cosmo0920
