### ISSUE TITLE
Plugin get's stuck in a retry forever after a recoverable request failure error

### ISSUE THREAD

**Issue by rolandjitsu** [uken/fluent-plugin-elasticsearch#626]
(check apply)
- [x] read [the contribution guideline](https://github.com/uken/fluent-plugin-elasticsearch/blob/master/CONTRIBUTING.md)

#### Problem
The plugin gets stuck and cannot send logs to ES. It also never recovers or tries more than a few times. If I restart fluentd, then it recovers but all the logs sent during the time it was stuck are lost.

...

#### Steps to replicate

Either clone and modify https://gist.github.com/pitr/9a518e840db58f435911

**OR**

The config I'm using:
```conf
# Receive messages from Fluent Bit
# https://docs.fluentd.org/v1.0/articles/in_forward
<source>
  @type forward
  #@log_level debug
  host 0.0.0.0
  port 5000
  <transport tls>
    cert_path /etc/td-agent/certs/fluentd.cert.pem
    private_key_path /etc/td-agent/certs/fluentd.key.pem
    private_key_passphrase somepass
    client_cert_auth true
    ca_path /etc/td-agent/certs/ca.cert.pem
  </transport>
  <security>
    self_hostname some.domain.com
    shared_key somesharedsecret
  </security>
</source>
# Save data in ES
# https://docs.fluentd.org/v1.0/articles/out_elasticsearch
<match {cpu,memory,disk,net}>
  @type elasticsearch
  #@log_level debug
  hosts 10.x.x.x:9200,10.x.x.x:9200
  user fluentd
  password "#{ENV['FLD_ES_PASS']}"
  index_name ${tag}
  include_timestamp true
  # If record does not have @timestamp key
  # See https://bit.ly/2VdhtFO
  time_key datetime
  #time_key_format %Y-%m-%dT%H:%M:%S.%N
  # https://github.com/uken/fluent-plugin-elasticsearch#reload_connections
  reload_connections false
  reload_on_failure true
  reconnect_on_error true
  <buffer>
    # Flush every 5s
    # https://docs.fluentd.org/v1.0/articles/output-plugin-overview#control-flushing
    flush_mode interval
    flush_interval 1
    flush_thread_count 2
  </buffer>
</match>
```

and this is the exception I see:
```
2019-08-16 12:12:39 +0000 [warn]: #0 failed to flush the buffer. retry_time=0 next_retry_seconds=2019-08-16 12:12:40 +0000 chunk="5903ae64176ae9bb20a96f7f10d4a1cb" error_class=Fluent::Plugin::ElasticsearchOutput::RecoverableRequestFailure error="could not push logs to Elasticsearch cluster ({:host=>\"10.x.x.3\", :port=>9200, :scheme=>\"http\", :user=>\"fluentd\", :password=>\"obfuscated\"}, {:host=>\"10.x.x.4\", :port=>9200, :scheme=>\"http\", :user=>\"fluentd\", :password=>\"obfuscated\"}): read timeout reached"
  2019-08-16 12:12:39 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-elasticsearch-3.4.3/lib/fluent/plugin/out_elasticsearch.rb:734:in `rescue in send_bulk'
  2019-08-16 12:12:39 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-elasticsearch-3.4.3/lib/fluent/plugin/out_elasticsearch.rb:709:in `send_bulk'
  2019-08-16 12:12:39 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-elasticsearch-3.4.3/lib/fluent/plugin/out_elasticsearch.rb:616:in `block in write'
  2019-08-16 12:12:39 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-elasticsearch-3.4.3/lib/fluent/plugin/out_elasticsearch.rb:615:in `each'
  2019-08-16 12:12:39 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-elasticsearch-3.4.3/lib/fluent/plugin/out_elasticsearch.rb:615:in `write'
  2019-08-16 12:12:39 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.4.2/lib/fluent/plugin/output.rb:1125:in `try_flush'
  2019-08-16 12:12:39 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.4.2/lib/fluent/plugin/output.rb:1425:in `flush_thread_run'
  2019-08-16 12:12:39 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.4.2/lib/fluent/plugin/output.rb:454:in `block (2 levels) in start'
  2019-08-16 12:12:39 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.4.2/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
2019-08-16 12:12:49 +0000 [warn]: #0 failed to flush the buffer. retry_time=1 next_retry_seconds=2019-08-16 12:12:49 +0000 chunk="5903ae6ab250b4ae22cb4ed30c17e33d" error_class=Fluent::Plugin::ElasticsearchOutput::RecoverableRequestFailure error="could not push logs to Elasticsearch cluster ({:host=>\"10.x.x.3\", :port=>9200, :scheme=>\"http\", :user=>\"fluentd\", :password=>\"obfuscated\"}, {:host=>\"10.x.x.4\", :port=>9200, :scheme=>\"http\", :user=>\"fluentd\", :password=>\"obfuscated\"}): read timeout reached"
  2019-08-16 12:12:49 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-elasticsearch-3.4.3/lib/fluent/plugin/out_elasticsearch.rb:734:in `rescue in send_bulk'
  2019-08-16 12:12:49 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-elasticsearch-3.4.3/lib/fluent/plugin/out_elasticsearch.rb:709:in `send_bulk'
  2019-08-16 12:12:49 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-elasticsearch-3.4.3/lib/fluent/plugin/out_elasticsearch.rb:616:in `block in write'
  2019-08-16 12:12:49 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-elasticsearch-3.4.3/lib/fluent/plugin/out_elasticsearch.rb:615:in `each'
  2019-08-16 12:12:49 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-elasticsearch-3.4.3/lib/fluent/plugin/out_elasticsearch.rb:615:in `write'
  2019-08-16 12:12:49 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.4.2/lib/fluent/plugin/output.rb:1125:in `try_flush'
  2019-08-16 12:12:49 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.4.2/lib/fluent/plugin/output.rb:1425:in `flush_thread_run'
  2019-08-16 12:12:49 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.4.2/lib/fluent/plugin/output.rb:454:in `block (2 levels) in start'
  2019-08-16 12:12:49 +0000 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.4.2/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
2019-08-16 12:13:03 +0000 [warn]: #0 failed to flush the buffer. retry_time=2 next_retry_seconds=2019-08-16 12:13:05 +0000 chunk="5903ae64176ae9bb20a96f7f10d4a1cb" error_class=Fluent::Plugin::ElasticsearchOutput::RecoverableRequestFailure error="could not push logs to Elasticsearch cluster ({:host=>\"10.x.x.3\", :port=>9200, :scheme=>\"http\", :user=>\"fluentd\", :password=>\"obfuscated\"}, {:host=>\"10.x.x.4\", :port=>9200, :scheme=>\"http\", :user=>\"fluentd\", :password=>\"obfuscated\"}): read timeout reached"
  2019-08-16 12:13:03 +0000 [warn]: #0 suppressed same stacktrace
2019-08-16 12:13:13 +0000 [warn]: #0 failed to flush the buffer. retry_time=3 next_retry_seconds=2019-08-16 12:13:17 +0000 chunk="5903ae6ab250b4ae22cb4ed30c17e33d" error_class=Fluent::Plugin::ElasticsearchOutput::RecoverableRequestFailure error="could not push logs to Elasticsearch cluster ({:host=>\"10.x.x.3\", :port=>9200, :scheme=>\"http\", :user=>\"fluentd\", :password=>\"obfuscated\"}, {:host=>\"10.x.x.4\", :port=>9200, :scheme=>\"http\", :user=>\"fluentd\", :password=>\"obfuscated\"}): read timeout reached"
```

#### Expected Behavior or What you need to ask
It should be able to recover and keep logs in a buffer until it can send them to ES.

...

#### Using Fluentd and ES plugin versions

* OS version
  * Linux fluentd 4.15.0-1030-gcp #32-Ubuntu SMP Wed Apr 10 10:27:45 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
* Bare Metal or within Docker or Kubernetes or others?
  * Bare metal, running on GCE.
* Fluentd v0.12 or v0.14/v1.0
  * td-agent 1.4.2
* ES plugin 3.x.y/2.x.y or 1.x.y
```
2019-08-16 12:50:22 +0000 [info]: gem 'fluent-plugin-elasticsearch' version '3.4.3'
2019-08-16 12:50:22 +0000 [info]: gem 'fluent-plugin-kafka' version '0.9.2'
2019-08-16 12:50:22 +0000 [info]: gem 'fluent-plugin-prometheus' version '1.3.0'
2019-08-16 12:50:22 +0000 [info]: gem 'fluent-plugin-record-modifier' version '2.0.1'
2019-08-16 12:50:22 +0000 [info]: gem 'fluent-plugin-rewrite-tag-filter' version '2.1.1'
2019-08-16 12:50:22 +0000 [info]: gem 'fluent-plugin-s3' version '1.1.9'
2019-08-16 12:50:22 +0000 [info]: gem 'fluent-plugin-td' version '1.0.0'
2019-08-16 12:50:22 +0000 [info]: gem 'fluent-plugin-td-monitoring' version '0.2.4'
2019-08-16 12:50:22 +0000 [info]: gem 'fluent-plugin-webhdfs' version '1.2.3'
2019-08-16 12:50:22 +0000 [info]: gem 'fluentd' version '1.4.2'
```
```

*** LOCAL GEMS ***

addressable (2.6.0)
aws-eventstream (1.0.3)
aws-partitions (1.149.0)
aws-sdk-core (3.48.3)
aws-sdk-kms (1.16.0)
aws-sdk-s3 (1.36.0)
aws-sdk-sqs (1.13.0)
aws-sigv4 (1.1.0)
bigdecimal (default: 1.3.2)
bundler (1.16.6)
cool.io (1.5.4)
did_you_mean (1.1.0)
dig_rb (1.0.1)
digest-crc (0.4.1)
elasticsearch (6.3.0)
elasticsearch-api (6.3.0)
elasticsearch-transport (6.3.0)
excon (0.64.0)
faraday (0.15.4)
ffi (1.10.0)
fluent-config-regexp-type (1.0.0)
fluent-logger (0.8.0)
fluent-plugin-elasticsearch (3.4.3)
fluent-plugin-kafka (0.9.2)
fluent-plugin-prometheus (1.3.0)
fluent-plugin-record-modifier (2.0.1)
fluent-plugin-rewrite-tag-filter (2.1.1)
fluent-plugin-s3 (1.1.9)
fluent-plugin-td (1.0.0)
fluent-plugin-td-monitoring (0.2.4)
fluent-plugin-webhdfs (1.2.3)
fluentd (1.4.2)
hirb (0.7.3)
http_parser.rb (0.6.0)
httpclient (2.8.2.4)
io-console (default: 0.4.6)
ipaddress (0.8.3)
jmespath (1.4.0)
json (default: 2.0.4)
ltsv (0.1.2)
mini_portile2 (2.4.0)
minitest (5.10.1)
mixlib-cli (1.7.0)
mixlib-config (2.2.4)
mixlib-log (1.7.1)
mixlib-shellout (2.2.7)
msgpack (1.2.9)
multi_json (1.13.1)
multipart-post (2.0.0)
net-telnet (0.1.1)
nokogiri (1.10.3)
ohai (6.20.0)
oj (3.7.11)
openssl (default: 2.0.9)
parallel (1.17.0)
power_assert (0.4.1)
prometheus-client (0.9.0)
psych (default: 2.2.2)
public_suffix (3.0.3)
quantile (0.2.1)
rake (12.3.2, 12.0.0)
rdkafka (0.4.2)
rdoc (default: 5.0.0)
ruby-kafka (0.7.6)
ruby-progressbar (1.10.0)
rubyzip (1.2.2)
serverengine (2.1.1)
sigdump (0.2.4)
strptime (0.2.3)
systemu (2.5.2)
td (0.16.4)
td-client (1.0.6)
td-logger (0.3.27)
test-unit (3.2.3)
thread_safe (0.3.6)
tzinfo (1.2.5)
tzinfo-data (1.2019.1)
webhdfs (0.8.0)
xmlrpc (0.2.1)
yajl-ruby (1.4.1)
zip-zip (0.3)
```
* ES version (optional)
  * 7.0.1
* ES template(s) (optional)

**Comment by cosmo0920** [comment]
Could you increase `request_timeout` value?
https://github.com/uken/fluent-plugin-elasticsearch/issues/620#issuecomment-519788865

And we recommend to use file buffer instead of memory buffer.
https://docs.fluentd.org/buffer/file

**Comment by rolandjitsu** [comment]
@cosmo0920 I've just done that. Also switched to file buffer. I will let you know if that solved the issue.

**Comment by cosmo0920** [comment]
No response. Closing.

**Comment by vishalk663** [comment]
Hi @rolandjitsu 

By using file buffer your issue resolved?

because we are also getting the same error

**Comment by rolandjitsu** [comment]
> Hi @rolandjitsu
> 
> By using file buffer your issue resolved?
> 
> because we are also getting the same error

Yes, once we switched to file buffer, we haven't seen any of those failures anymore.
