### ISSUE TITLE
more information in connection error log

### ISSUE THREAD

**Issue by seapy** [uken/fluent-plugin-elasticsearch#64]
recently i receive fluent log message, but it can't display host or port information.

my elasticsearch server use cluster(6 server), i don't know which server has a problem.

cluster don't have a problem, when i restart fluent it works.

td-agent.conf

```
<match apache.access>
  type elasticsearch
  hosts x.x.x.x:10200,x.x.x.y:10200,x.x.x.z:10200,x.x.x.a:10200,x.x.x.b:10200,x.x.x.c:10200
  type_name access-log
  logstash_format true
  logstash_prefix logstash
  utc_index false
  request_timeout 20s

  # buffer
  buffer_type file
  buffer_path /var/log/td-agent/buffer/apache-access-elasticsearch.*.buffer
  buffer_chunk_limit 8m
  buffer_queue_limit 10000
  flush_interval 60
  retry_limit 17
</match>
```

fluent log
```
2014-08-12 07:53:45 +0900 [warn]: temporarily failed to flush the buffer. next_retry=2014-08-12 10:17:52 +0900 error_class="Faraday::ConnectionFailed" error="couldn't connect to host" instance=69894834792040
  2014-08-12 07:53:45 +0900 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/patron-0.4.18/lib/patron/session.rb:223:in `handle_request'
  2014-08-12 07:53:45 +0900 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/patron-0.4.18/lib/patron/session.rb:223:in `request'
  2014-08-12 07:53:45 +0900 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/faraday-0.9.0/lib/faraday/adapter/patron.rb:33:in `call'
  2014-08-12 07:53:45 +0900 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/faraday-0.9.0/lib/faraday/rack_builder.rb:139:in `build_response'
  2014-08-12 07:53:45 +0900 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/faraday-0.9.0/lib/faraday/connection.rb:377:in `run_request'
  2014-08-12 07:53:45 +0900 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/elasticsearch-transport-0.4.11/lib/elasticsearch/transport/transport/http/faraday.rb:21:in `block in perform_request'
  2014-08-12 07:53:45 +0900 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/elasticsearch-transport-0.4.11/lib/elasticsearch/transport/transport/base.rb:187:in `call'
  2014-08-12 07:53:45 +0900 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/elasticsearch-transport-0.4.11/lib/elasticsearch/transport/transport/base.rb:187:in `perform_request'
  2014-08-12 07:53:45 +0900 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/elasticsearch-transport-0.4.11/lib/elasticsearch/transport/transport/http/faraday.rb:20:in `perform_request'
  2014-08-12 07:53:45 +0900 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/elasticsearch-transport-0.4.11/lib/elasticsearch/transport/client.rb:92:in `perform_request'
  2014-08-12 07:53:45 +0900 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/elasticsearch-api-0.4.11/lib/elasticsearch/api/actions/ping.rb:19:in `ping'
  2014-08-12 07:53:45 +0900 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluent-plugin-elasticsearch-0.4.0/lib/fluent/plugin/out_elasticsearch.rb:50:in `client'
  2014-08-12 07:53:45 +0900 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluent-plugin-elasticsearch-0.4.0/lib/fluent/plugin/out_elasticsearch.rb:108:in `send'
  2014-08-12 07:53:45 +0900 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluent-plugin-elasticsearch-0.4.0/lib/fluent/plugin/out_elasticsearch.rb:103:in `write'
  2014-08-12 07:53:45 +0900 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.10.50/lib/fluent/buffer.rb:296:in `write_chunk'
  2014-08-12 07:53:45 +0900 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.10.50/lib/fluent/buffer.rb:276:in `pop'
  2014-08-12 07:53:45 +0900 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.10.50/lib/fluent/output.rb:310:in `try_flush'
  2014-08-12 07:53:45 +0900 [warn]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.10.50/lib/fluent/output.rb:132:in `run'
```

**Comment by pitr** [comment]
fixed in v0.5.0
