### ISSUE TITLE
Always receive a 400 Bad request when trying to use plugin with Logsene

### ISSUE THREAD

**Issue by marklieberman** [uken/fluent-plugin-elasticsearch#68]
I'm trying to push logs to an Elasticsearch compatible application called Logsene. See https://sematext.atlassian.net/wiki/display/PUBLOGSENE/Index+Events+via+Elasticsearch+API

The problem is that I always receive a 400 error when pushing using fluent plugin. I can cURL the same log message and it works fine.

I have cloned the repo and build the gem using the latest code from github. I've tried a variety of configurations with and without HTTPS, for example:

```
<match>
  type elasticsearch
  host logsene-receiver.sematext.com
  port 80
  path /**MYSECRETKEY**/fluentd
  index_name **MYSECRETKEY**
  type_name fluentd
</match>
```

and

```
<match>
  type elasticsearch
  hosts http://logsene-receiver.sematext.com:80/**MYSECRETKEY**/fluentd
  index_name **MYSECRETKEY**
  type_name fluentd
</match>
```

I always get an error like the following:

```
2014-09-02 21:04:59 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2014-09-02 21:09:39 +0000 error_class="Elasticsearch::Transport::Transport::Errors::BadRequest" error="[400] " instance=70175379032060
  2014-09-02 21:04:59 +0000 [warn]: /usr/lib/fluent/ruby/lib/ruby/gems/1.9.1/gems/elasticsearch-transport-0.4.11/lib/elasticsearch/transport/transport/base.rb:132:in `__raise_transport_error'
  2014-09-02 21:04:59 +0000 [warn]: /usr/lib/fluent/ruby/lib/ruby/gems/1.9.1/gems/elasticsearch-transport-0.4.11/lib/elasticsearch/transport/transport/base.rb:227:in `perform_request'
  2014-09-02 21:04:59 +0000 [warn]: /usr/lib/fluent/ruby/lib/ruby/gems/1.9.1/gems/elasticsearch-transport-0.4.11/lib/elasticsearch/transport/transport/http/faraday.rb:20:in `perform_request'
  2014-09-02 21:04:59 +0000 [warn]: /usr/lib/fluent/ruby/lib/ruby/gems/1.9.1/gems/elasticsearch-transport-0.4.11/lib/elasticsearch/transport/client.rb:92:in `perform_request'
  2014-09-02 21:04:59 +0000 [warn]: /usr/lib/fluent/ruby/lib/ruby/gems/1.9.1/gems/elasticsearch-api-0.4.11/lib/elasticsearch/api/actions/ping.rb:19:in `ping'
  2014-09-02 21:04:59 +0000 [warn]: /usr/lib/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluent-plugin-elasticsearch-0.4.0/lib/fluent/plugin/out_elasticsearch.rb:55:in `client'
  2014-09-02 21:04:59 +0000 [warn]: /usr/lib/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluent-plugin-elasticsearch-0.4.0/lib/fluent/plugin/out_elasticsearch.rb:138:in `send'
  2014-09-02 21:04:59 +0000 [warn]: /usr/lib/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluent-plugin-elasticsearch-0.4.0/lib/fluent/plugin/out_elasticsearch.rb:133:in `write'
  2014-09-02 21:04:59 +0000 [warn]: /usr/lib/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.10.50/lib/fluent/buffer.rb:296:in `write_chunk'
  2014-09-02 21:04:59 +0000 [warn]: /usr/lib/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.10.50/lib/fluent/buffer.rb:276:in `pop'
  2014-09-02 21:04:59 +0000 [warn]: /usr/lib/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.10.50/lib/fluent/output.rb:310:in `try_flush'
  2014-09-02 21:04:59 +0000 [warn]: /usr/lib/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.10.50/lib/fluent/output.rb:132:in `run'
```

**Comment by countergram** [comment]
For the benefit of people Googling: Logsene requires the path `/<index>/_bulk` or `/<index>/<type>/_bulk` to be used. This plugin will only send to `/_bulk`.
