### ISSUE TITLE
Using template_overwrite causes ES cluster to overload 

### ISSUE THREAD

**Issue by juhtie01** [uken/fluent-plugin-elasticsearch#683]
(check apply)
- [x] read [the contribution guideline](https://github.com/uken/fluent-plugin-elasticsearch/blob/master/CONTRIBUTING.md)

#### Problem
We have a 12-node ES cluster running in a Kubernetes cluster with 18 Fluentd pods sending logs to the cluster. When we upgraded to ES 7.3 series, we also enabled `template_overwrite` option for the ES plugin. This seems to have caused the ES cluster to overload, causing issues like some Fluentd pods being unable to flush their buffers to Elasticsearch, daily ES curator jobs failing, etc. When the option was disabled on one cluster, all Fluentd buffers got emptied almost immediately and no errors related to index template creation were found in the ES logs. 

#### Steps to replicate

Config:
```
...
  <match **>
    @id hosts_out_copy
    @type copy
    deep_copy true

    <store>
      @type elasticsearch
      @id elasticsearch

      # enable to debug, the log_level creates huge amount of logs!
      # with_transporter_log true
      @log_level warn

      # connectivity
      host elasticsearch-logging
      port 9200
      default_elasticsearch_version 7

      unrecoverable_error_types ["out_of_memory_error"]

      sniffer_class_name "Fluent::Plugin::ElasticsearchSimpleSniffer"

      # per ES plugin FAQ recommendation for k8s
      reload_connections false
      reload_on_failure false
      reconnect_on_error true

      logstash_format true

      template_file "/etc/fluent/#{ENV['TEMPLATE_FILE']}"
      template_name logstash
      template_overwrite true

      prefer_oj_serializer true

      request_timeout 120
      http_backend typhoeus
      slow_flush_log_threshold 60

      # prevent duplicate log entries and updates
      id_key _hash
      remove_keys _hash
      write_operation create

      time_key time

      include_tag_key false
      <buffer>
        @type file
        path /var/log/fluentd-buffers/kubernetes.system.buffer

        ## retry params
        # this is the default, reproduced for readability
        retry_type exponential_backoff
        disable_chunk_backup true

        # Disable the limit on the number of retries (retry forever).
        retry_forever true
        retry_max_interval 30

        ## buffering params
        # like everyone else (copied from k8s reference)
        chunk_limit_size 2m

        # Total size of the buffer (2MiB/chunk * 256 chunk) = 512Mi
        queue_limit_length 256

        ## flushing params
        # Use multiple threads for processing.
        flush_thread_count 4

        # Never wait longer than 5 seconds between retries.
        flush_interval 5s

        # block input in case we can't reach ES
        overflow_action block

      </buffer>
    </store>
...
```

Pending tasks in ES:
```
[root@es-master-1 elasticsearch]# curl localhost:9200/_cluster/pending_tasks
{"tasks":[{"insert_order":20277463,"priority":"URGENT","source":"create-index-template [logstash], cause [api]","executing":true,"time_in_queue_millis":3483,"time_in_queue":"3.4s"},
{"insert_order":20277467,"priority":"URGENT","source":"create-index-template [logstash], cause [api]","executing":false,"time_in_queue_millis":2781,"time_in_queue":"2.7s"},
{"insert_order":20277469,"priority":"URGENT","source":"create-index-template [logstash], cause [api]","executing":false,"time_in_queue_millis":2405,"time_in_queue":"2.4s"},
{"insert_order":20277468,"priority":"URGENT","source":"install-token-metadata","executing":false,"time_in_queue_millis":2447,"time_in_queue":"2.4s"},
{"insert_order":20277473,"priority":"URGENT","source":"create-index-template [logstash], cause [api]","executing":false,"time_in_queue_millis":2265,"time_in_queue":"2.2s"},
{"insert_order":20277470,"priority":"URGENT","source":"create-index-template [logstash], cause [api]","executing":false,"time_in_queue_millis":2358,"time_in_queue":"2.3s"},
{"insert_order":20277472,"priority":"URGENT","source":"create-index-template [logstash], cause [api]","executing":false,"time_in_queue_millis":2267,"time_in_queue":"2.2s"},
{"insert_order":20277471,"priority":"URGENT","source":"create-index-template [logstash], cause [api]","executing":false,"time_in_queue_millis":2321,"time_in_queue":"2.3s"},
{"insert_order":20277482,"priority":"URGENT","source":"create-index-template [logstash], cause [api]","executing":false,"time_in_queue_millis":2082,"time_in_queue":"2s"},
{"insert_order":20277489,"priority":"URGENT","source":"create-index-template [logstash], cause [api]","executing":false,"time_in_queue_millis":1798,"time_in_queue":"1.7s"},
{"insert_order":20277478,"priority":"URGENT","source":"create-index-template [logstash], cause [api]","executing":false,"time_in_queue_millis":2134,"time_in_queue":"2.1s"},
{"insert_order":20277474,"priority":"URGENT","source":"create-index-template [logstash], cause [api]","executing":false,"time_in_queue_millis":2262,"time_in_queue":"2.2s"},
{"insert_order":20277475,"priority":"URGENT","source":"create-index-template [logstash], cause [api]","executing":false,"time_in_queue_millis":2137,"time_in_queue":"2.1s"},
{"insert_order":20277477,"priority":"URGENT","source":"create-index-template [logstash], cause [api]","executing":false,"time_in_queue_millis":2135,"time_in_queue":"2.1s"},
{"insert_order":20277484,"priority":"URGENT","source":"create-index-template [logstash], cause [api]","executing":false,"time_in_queue_millis":1952,"time_in_queue":"1.9s"},
{"insert_order":20277486,"priority":"URGENT","source":"create-index-template [logstash], cause [api]","executing":false,"time_in_queue_millis":1951,"time_in_queue":"1.9s"},
{"insert_order":20277373,"priority":"HIGH","source":"put-mapping","executing":false,"time_in_queue_millis":14310,"time_in_queue":"14.3s"}
...
```

A lot of errors in es-master logs about failing operations, example:
```
{"type": "server", "timestamp": "2019-12-11T08:15:14,668+0000", "level": "DEBUG", "component": "o.e.a.a.i.m.p.TransportPutMappingAction", "cluster.name": "elasticsearchdb", "node.name": "es-master-1", "cluster.uuid": "To-zsS3IRF6dCNiJNGAV2Q", "node.id": "DpSQGG7GSpmPhAkxUvAW9g",  "message": "failed to put mappings on indices [[[logstash-2019.12.11/EAKOo_MCTjyRx3tOcZBWpg]]], type [_doc]" , 
"stacktrace": ["org.elasticsearch.cluster.metadata.ProcessClusterEventTimeoutException: failed to process cluster event (put-mapping) within 30s",
"at org.elasticsearch.cluster.service.MasterService$Batcher.lambda$onTimeout$0(MasterService.java:134) [elasticsearch-7.3.2.jar:7.3.2]",
"at java.util.ArrayList.forEach(ArrayList.java:1540) [?:?]",
"at org.elasticsearch.cluster.service.MasterService$Batcher.lambda$onTimeout$1(MasterService.java:133) [elasticsearch-7.3.2.jar:7.3.2]",
"at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:688) [elasticsearch-7.3.2.jar:7.3.2]",
"at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]",
"at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]",
"at java.lang.Thread.run(Thread.java:835) [?:?]"] }
```

Errors in Fluentd logs:
``` 
2019-12-10 14:49:38 +0000 [warn]: #0 [elasticsearch] failed to flush the buffer. retry_time=4 next_retry_seconds=2019-12-10 14:49:46 +0000 chunk="599599b41a8799a1514fdea5490f2efd" error_class=Elasticsearch::Transport::Transport::Errors::ServiceUnavailable error="[503] {\"error\":{\"root_cause\":[{\"type\":\"process_cluster_event_timeout_exception\",\"reason\":\"failed to process cluster event (create-index-template [logstash], cause [api]) within 30s\"}],\"type\":\"process_cluster_event_timeout_exception\",\"reason\":\"failed to process cluster event (create-index-template [logstash], cause [api]) within 30s\"},\"status\":503}"
  2019-12-10 14:49:38 +0000 [warn]: #0 suppressed same stacktrace
```

#### Expected Behavior or What you need to ask

I would expect the `template_overwrite` command to back off on trying to create the index, if the operation is not successful. With just 18 pods doing the operation every 30 seconds and possibly retrying, ES cluster needs to synchronize the cluster configuration almost every second, which on a highly loaded cluster causes tasks to time out.

#### Using Fluentd and ES plugin versions

* OS version: Container Linux 2247.5.0
* Bare Metal or within Docker or Kubernetes or others? Kubernetes 1.15.5
* Fluentd v0.12 or v0.14/v1.0: fluentd-1.7.4
* ES plugin 3.x.y/2.x.y or 1.x.y: 'fluent-plugin-elasticsearch' version '3.6.1'
* ES version (optional): 7.3.2
* ES template(s) (optional)

**Comment by cosmo0920** [comment]
> I would expect the `template_overwrite` command to back off on trying to create the index, if the operation is not successful.

No. `retry_type exponential_backoff` is for buffer. Not for ES template installation.

Just my curiosity, `template_overwrite` in the every request is really needed?
i.e. Elasticsearch template changes every request is needed?

**Comment by juhtie01** [comment]
No, template doesn't change all that often.

For this topic, it looks like we may have misunderstood the option documentation - the intent was not to change the template mapping on every time fluentd pushes to ES, but to make sure that the template exists even if fluentd pods start up while ES is not ready.

**Comment by juhtie01** [comment]
Thanks for your help @cosmo0920. I will close this issue, as it does not seem to be a bug in the plugin but rather in our understanding of how it works.
