### ISSUE TITLE
Getting NoMethodError while running fluentd daemonset in Amazon EKS 

### ISSUE THREAD

**Issue by diptimanadak** [uken/fluent-plugin-elasticsearch#689]
I am trying to send error logs from Amazon EKS to external elasticsearch cluster.
```log
2019-12-27 06:26:22 +0000 [error]: #0 unexpected error error_class=NoMethodError error="undefined method `[]' for nil:NilClass"
  2019-12-27 06:26:22 +0000 [error]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluent-plugin-elasticsearch-3.5.5/lib/fluent/plugin/out_elasticsearch.rb:336:in `detect_es_major_version'
  2019-12-27 06:26:22 +0000 [error]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluent-plugin-elasticsearch-3.5.5/lib/fluent/plugin/out_elasticsearch.rb:246:in `block in configure'
  2019-12-27 06:26:22 +0000 [error]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluent-plugin-elasticsearch-3.5.5/lib/fluent/plugin/elasticsearch_index_template.rb:35:in `retry_operate'
  2019-12-27 06:26:22 +0000 [error]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluent-plugin-elasticsearch-3.5.5/lib/fluent/plugin/out_elasticsearch.rb:245:in `configure'
  2019-12-27 06:26:22 +0000 [error]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.7.0/lib/fluent/plugin.rb:164:in `configure'
  2019-12-27 06:26:22 +0000 [error]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.7.0/lib/fluent/agent.rb:130:in `add_match'
  2019-12-27 06:26:22 +0000 [error]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.7.0/lib/fluent/agent.rb:72:in `block in configure'
  2019-12-27 06:26:22 +0000 [error]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.7.0/lib/fluent/agent.rb:64:in `each'
  2019-12-27 06:26:22 +0000 [error]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.7.0/lib/fluent/agent.rb:64:in `configure'
  2019-12-27 06:26:22 +0000 [error]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.7.0/lib/fluent/root_agent.rb:150:in `configure'
  2019-12-27 06:26:22 +0000 [error]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.7.0/lib/fluent/engine.rb:131:in `configure'
  2019-12-27 06:26:22 +0000 [error]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.7.0/lib/fluent/engine.rb:96:in `run_configure'
  2019-12-27 06:26:22 +0000 [error]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.7.0/lib/fluent/supervisor.rb:804:in `run_configure'
  2019-12-27 06:26:22 +0000 [error]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.7.0/lib/fluent/supervisor.rb:550:in `block in run_worker'
  2019-12-27 06:26:22 +0000 [error]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.7.0/lib/fluent/supervisor.rb:733:in `main_process'
  2019-12-27 06:26:22 +0000 [error]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.7.0/lib/fluent/supervisor.rb:546:in `run_worker'
  2019-12-27 06:26:22 +0000 [error]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.7.0/lib/fluent/command/fluentd.rb:320:in `<top (required)>'
  2019-12-27 06:26:22 +0000 [error]: #0 /usr/local/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
  2019-12-27 06:26:22 +0000 [error]: #0 /usr/local/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
  2019-12-27 06:26:22 +0000 [error]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.7.0/bin/fluentd:8:in `<top (required)>'
  2019-12-27 06:26:22 +0000 [error]: #0 /fluentd/vendor/bundle/ruby/2.6.0/bin/fluentd:23:in `load'
  2019-12-27 06:26:22 +0000 [error]: #0 /fluentd/vendor/bundle/ruby/2.6.0/bin/fluentd:23:in `<main>'
2019-12-27 06:26:22 +0000 [info]: Worker 0 finished unexpectedly with status 1
2019-12-27 06:26:23 +0000 [info]: gem 'fluent-plugin-concat' version '2.3.0'
2019-12-27 06:26:23 +0000 [info]: gem 'fluent-plugin-elasticsearch' version '3.5.5'
2019-12-27 06:26:23 +0000 [info]: gem 'fluent-plugin-grok-parser' version '2.5.1'
2019-12-27 06:26:23 +0000 [info]: gem 'fluent-plugin-json-in-json-2' version '1.0.2'
2019-12-27 06:26:23 +0000 [info]: gem 'fluent-plugin-kubernetes_metadata_filter' version '2.1.6'
2019-12-27 06:26:23 +0000 [info]: gem 'fluent-plugin-multi-format-parser' version '1.0.0'
2019-12-27 06:26:23 +0000 [info]: gem 'fluent-plugin-prometheus' version '1.5.0'
2019-12-27 06:26:23 +0000 [info]: gem 'fluent-plugin-record-modifier' version '2.0.1'
2019-12-27 06:26:23 +0000 [info]: gem 'fluent-plugin-rewrite-tag-filter' version '2.2.0'
2019-12-27 06:26:23 +0000 [info]: gem 'fluent-plugin-systemd' version '1.0.2'
2019-12-27 06:26:23 +0000 [info]: gem 'fluentd' version '1.7.0'
2019-12-27 06:26:23 +0000 [info]: adding match pattern="fluent.**" type="null"
2019-12-27 06:26:23 +0000 [info]: adding filter pattern="kubernetes.**" type="kubernetes_metadata"
2019-12-27 06:26:23 +0000 [info]: adding match pattern="**" type="elasticsearch"
```

Configuration
```yaml
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluentd
  namespace: kube-system

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: fluentd
  namespace: kube-system
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - namespaces
  verbs:
  - get
  - list
  - watch

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: fluentd
roleRef:
  kind: ClusterRole
  name: fluentd
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: fluentd
  namespace: kube-system
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd
  namespace: kube-system
  labels:
    k8s-app: fluentd-logging
    version: v1
spec:
  selector:
    matchLabels:
      k8s-app: fluentd-logging
      version: v1
  template:
    metadata:
      labels:
        k8s-app: fluentd-logging
        version: v1
    spec:
      serviceAccount: fluentd
      serviceAccountName: fluentd
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: fluentd
        image: fluent/fluentd-kubernetes-daemonset:v1.7.0-debian-elasticsearch7-1.0
        env:
        - name:  FLUENT_ELASTICSEARCH_HOST
          value: "X.X.X.X"
        - name:  FLUENT_ELASTICSEARCH_PORT
          value: "8888"
        - name: FLUENT_ELASTICSEARCH_SCHEME
          value: "http"
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
```

I feel, I am doing something wrong here. Can anyone guide me to figure what's wrong

**Comment by cosmo0920** [comment]
Could you confirm that whether k8s pod in AKS can access external Elasticsearch cluster?

**Comment by cosmo0920** [comment]
From v4.1.2, we use Hash#dig to retrieve nested hash object which includes Elasticsearch version information.
https://github.com/uken/fluent-plugin-elasticsearch/commit/7e4f30384bcdff5ad13d69caa1b8626ee947f14a

Hash#dig doesn't throw NoMethod Error just returns `nil`.
This exception shouldn't be shown fluent-plugin-elasticsearch v4.1.2 or later.
Closing.
