### ISSUE TITLE
uninitialized constant Faraday::Error::ConnectionFailed

### ISSUE THREAD

**Issue by montanaflynn** [uken/fluent-plugin-elasticsearch#699]
(check apply)
- [x] read [the contribution guideline](https://github.com/uken/fluent-plugin-elasticsearch/blob/master/CONTRIBUTING.md)

#### Problem

I cannot get the plugin to connect to elasticsearch. I can curl the elasticsearch with:

`curl -i https://montana:password@elasticsearch-example.aivencloud.com:12770`

But when running fluentd I get the following logs. I tried setting `with_transporter_log true` but it seems to have no effect on the logs.

```
2020-01-19 15:00:44 +0000 [info]: Worker 0 finished unexpectedly with status 1
2020-01-19 15:00:44 +0000 [info]: adding match pattern="**" type="copy"
2020-01-19 15:00:45 +0000 [error]: #0 unexpected error error_class=NameError error="uninitialized constant Faraday::Error::ConnectionFailed"
  2020-01-19 15:00:45 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/http/faraday.rb:51:in `host_unreachable_exceptions'
  2020-01-19 15:00:45 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluent-plugin-elasticsearch-3.8.0/lib/fluent/plugin/elasticsearch_index_template.rb:36:in `rescue in retry_operate'
  2020-01-19 15:00:45 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluent-plugin-elasticsearch-3.8.0/lib/fluent/plugin/elasticsearch_index_template.rb:34:in `retry_operate'
  2020-01-19 15:00:45 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluent-plugin-elasticsearch-3.8.0/lib/fluent/plugin/out_elasticsearch.rb:264:in `configure'
  2020-01-19 15:00:45 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.8.1/lib/fluent/plugin.rb:173:in `configure'
  2020-01-19 15:00:45 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.8.1/lib/fluent/plugin/multi_output.rb:74:in `block in configure'
  2020-01-19 15:00:45 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.8.1/lib/fluent/plugin/multi_output.rb:63:in `each'
  2020-01-19 15:00:45 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.8.1/lib/fluent/plugin/multi_output.rb:63:in `configure'
  2020-01-19 15:00:45 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.8.1/lib/fluent/plugin/out_copy.rb:38:in `configure'
  2020-01-19 15:00:45 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.8.1/lib/fluent/plugin.rb:173:in `configure'
  2020-01-19 15:00:45 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.8.1/lib/fluent/agent.rb:132:in `add_match'
  2020-01-19 15:00:45 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.8.1/lib/fluent/agent.rb:74:in `block in configure'
  2020-01-19 15:00:45 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.8.1/lib/fluent/agent.rb:64:in `each'
  2020-01-19 15:00:45 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.8.1/lib/fluent/agent.rb:64:in `configure'
  2020-01-19 15:00:45 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.8.1/lib/fluent/root_agent.rb:146:in `configure'
  2020-01-19 15:00:45 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.8.1/lib/fluent/engine.rb:104:in `configure'
  2020-01-19 15:00:45 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.8.1/lib/fluent/engine.rb:79:in `run_configure'
  2020-01-19 15:00:45 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.8.1/lib/fluent/supervisor.rb:533:in `block in run_worker'
  2020-01-19 15:00:45 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.8.1/lib/fluent/supervisor.rb:740:in `main_process'
  2020-01-19 15:00:45 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.8.1/lib/fluent/supervisor.rb:528:in `run_worker'
  2020-01-19 15:00:45 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.8.1/lib/fluent/command/fluentd.rb:338:in `<top (required)>'
  2020-01-19 15:00:45 +0000 [error]: #0 /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
  2020-01-19 15:00:45 +0000 [error]: #0 /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
  2020-01-19 15:00:45 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.8.1/bin/fluentd:8:in `<top (required)>'
  2020-01-19 15:00:45 +0000 [error]: #0 /usr/bin/fluentd:23:in `load'
  2020-01-19 15:00:45 +0000 [error]: #0 /usr/bin/fluentd:23:in `<main>'
```

...

#### Steps to replicate

Either clone and modify https://gist.github.com/pitr/9a518e840db58f435911

**OR**

Provide example config and message

```
  <store>
    @type elasticsearch
    host elasticsearch-example.aivencloud.com
    user montana
    password example
    port 12770
    schema https
    with_transporter_log true
  </store>
```

#### Expected Behavior or What you need to ask`

How can I see why the connection fails? The `with_transporter_log true` seems to not have any effect.

#### Using Fluentd and ES plugin versions

* OS version: 
Alpine 8.3.0
* Bare Metal or within Docker or Kubernetes or others? 
Docker
* Fluentd v0.12 or v0.14/v1.0: v1.0
 fluentd 1.8.1
* ES plugin 3.x.y/2.x.y or 1.x.y
```
2020-01-19 15:00:18 +0000 [info]: parsing config file is succeeded path="/fluentd/etc/fluent.conf"
2020-01-19 15:00:18 +0000 [info]: gem 'fluent-plugin-elasticsearch' version '3.8.0'
2020-01-19 15:00:18 +0000 [info]: gem 'fluent-plugin-s3' version '1.0.0'
2020-01-19 15:00:18 +0000 [info]: gem 'fluentd' version '1.8.1'
```
* ES version (optional)
7.5.1
* ES template(s) (optional)

**Comment by montanaflynn** [comment]
Wow I just realized this is because I was using `schema` instead of `scheme`.

I think the logs should point this out but I'll close the issue as it's been resolved.

**Comment by cosmo0920** [comment]
@montanaflynn I guess that Fluentd says 'schema' parameter is not used when specifiying schema instead of scheme. Could you comfirm it?

**Comment by lucasteles22** [comment]
The real problem is another.

The elasticsearch gem does not have the version assigned.
The last version on ruby gems `7.4.0` has an error on dependency gem `elasticsearch-transport-7.4.0`. 

`elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/http/fa
raday.rb:51`.

```rb
          def host_unreachable_exceptions
            [::Faraday::Error::ConnectionFailed, ::Faraday::Error::TimeoutError]
          end
```

The syntax above belongs to Faraday < 1.0
The right syntax should be:

```rb
          def host_unreachable_exceptions
            [
                ::Faraday::ConnectionFailed,
                ::Faraday::TimeoutError,
                ::Faraday.const_defined?(:ServerError) ? ::Faraday::ServerError : nil,
                ::Faraday::SSLError
            ].compact
          end
```
This code above is on master branch from `https://github.com/elastic/elasticsearch-ruby`

My suggestion:
Assign elasticsearch gem  to previous versions or get from github master. I don't like of the second suggestion, but, the exception does not throw anymore.

**Comment by cosmo0920** [comment]
I'm waiting for the new release of elasticsearch-transport gem 7.x and 6.x.
fluentd ecosystem doesn't like such workaround.
See: https://github.com/elastic/elasticsearch-ruby/pull/752

**Comment by lucasteles22** [comment]
Me too.
But, leave free the gem versions is a problem, right?

**Comment by cosmo0920** [comment]
> But, leave free the gem version is a problem, right?

Monolithic versioning is not good for me. Thanks.

**Comment by montanaflynn** [comment]
@cosmo0920 to answer your question, no fluentd doesn't mention `schema` anywhere.

Here are the full logs:

```
2020-01-21 09:08:39 +0000 [info]: parsing config file is succeeded path="/fluentd/etc/fluent.conf"
2020-01-21 09:08:39 +0000 [info]: gem 'fluent-mixin-config-placeholders' version '0.4.0'
2020-01-21 09:08:39 +0000 [info]: gem 'fluent-plugin-elasticsearch' version '3.8.0'
2020-01-21 09:08:39 +0000 [info]: gem 'fluentd' version '1.8.1'
2020-01-21 09:08:40 +0000 [info]: using configuration file: <ROOT>
  <source>
    @type forward
    port 24224
    bind "0.0.0.0"
  </source>
  <match mathpix.**>
    @type copy
    <store>
      @type "relabel"
      @label @STDOUT
    </store>
    <store>
      @type "relabel"
      @label @ELASTICSEARCH
    </store>
  </match>
  <label @STDOUT>
    <match mathpix.**>
      @type stdout
    </match>
  </label>
  <label @ELASTICSEARCH>
    <match mathpix.**>
      @type elasticsearch
      host "elasticsearch-484ac42-nico-383f.aivencloud.com"
      user "avnadmin"
      password xxxxxx
      port 12770
      schema https
      ssl_version TLSv1_2
      reconnect_on_error true
      reload_on_failure true
      index_name "fluentd.${tag}.%Y%m%d"
      <buffer>
        @type "memory"
        flush_thread_count 4
        flush_mode interval
        flush_interval 15s
        chunk_limit_size 2m
        queue_limit_length 4096
      </buffer>
    </match>
  </label>

</ROOT>
2020-01-21 09:08:40 +0000 [info]: starting fluentd-1.8.1 pid=7 ruby="2.5.7"
2020-01-21 09:08:40 +0000 [info]: spawn command to main:  cmdline=["/usr/bin/ruby", "-Eascii-8bit:ascii-8bit", "/usr/bin/fluentd", "--use-v1-config", "-c", "/fluentd/etc/fluent.conf", "-p", "/fluentd/plugins", "--under-supervisor"]
2020-01-21 09:08:41 +0000 [info]: adding match in @STDOUT pattern="mathpix.**" type="stdout"
2020-01-21 09:08:41 +0000 [info]: adding match in @ELASTICSEARCH pattern="mathpix.**" type="elasticsearch"
2020-01-21 09:08:42 +0000 [error]: #0 unexpected error error_class=NameError error="uninitialized constant Faraday::Error::ConnectionFailed"
  2020-01-21 09:08:42 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/http/faraday.rb:51:in `host_unreachable_exceptions'
  2020-01-21 09:08:42 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluent-plugin-elasticsearch-3.8.0/lib/fluent/plugin/elasticsearch_index_template.rb:36:in `rescue in retry_operate'
  2020-01-21 09:08:42 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluent-plugin-elasticsearch-3.8.0/lib/fluent/plugin/elasticsearch_index_template.rb:34:in `retry_operate'
  2020-01-21 09:08:42 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluent-plugin-elasticsearch-3.8.0/lib/fluent/plugin/out_elasticsearch.rb:264:in `configure'
  2020-01-21 09:08:42 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.8.1/lib/fluent/plugin.rb:173:in `configure'
  2020-01-21 09:08:42 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.8.1/lib/fluent/agent.rb:132:in `add_match'
  2020-01-21 09:08:42 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.8.1/lib/fluent/agent.rb:74:in `block in configure'
  2020-01-21 09:08:42 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.8.1/lib/fluent/agent.rb:64:in `each'
  2020-01-21 09:08:42 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.8.1/lib/fluent/agent.rb:64:in `configure'
  2020-01-21 09:08:42 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.8.1/lib/fluent/label.rb:31:in `configure'
  2020-01-21 09:08:42 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.8.1/lib/fluent/root_agent.rb:143:in `block in configure'
  2020-01-21 09:08:42 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.8.1/lib/fluent/root_agent.rb:143:in `each'
  2020-01-21 09:08:42 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.8.1/lib/fluent/root_agent.rb:143:in `configure'
  2020-01-21 09:08:42 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.8.1/lib/fluent/engine.rb:104:in `configure'
  2020-01-21 09:08:42 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.8.1/lib/fluent/engine.rb:79:in `run_configure'
  2020-01-21 09:08:42 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.8.1/lib/fluent/supervisor.rb:533:in `block in run_worker'
  2020-01-21 09:08:42 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.8.1/lib/fluent/supervisor.rb:740:in `main_process'
  2020-01-21 09:08:42 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.8.1/lib/fluent/supervisor.rb:528:in `run_worker'
  2020-01-21 09:08:42 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.8.1/lib/fluent/command/fluentd.rb:338:in `<top (required)>'
  2020-01-21 09:08:42 +0000 [error]: #0 /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
  2020-01-21 09:08:42 +0000 [error]: #0 /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
  2020-01-21 09:08:42 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.8.1/bin/fluentd:8:in `<top (required)>'
  2020-01-21 09:08:42 +0000 [error]: #0 /usr/bin/fluentd:23:in `load'
  2020-01-21 09:08:42 +0000 [error]: #0 /usr/bin/fluentd:23:in `<main>'
2020-01-21 09:08:42 +0000 [info]: Worker 0 finished unexpectedly with status 1
```

**Comment by picandocodigo** [comment]
Hi folks,
I'm currently working on releases for  elasticsearch-ruby `6.x` and `7.x` where the Faraday version will be locked to `< 1` as it says on the linked Pull Request. They will be published as soon as possible. 
Thank you for your patience!

**Comment by lucasteles22** [comment]
TY @picandocodigo

**Comment by iShiBin** [comment]
> Wow I just realized this is because I was using `schema` instead of `scheme`.
> 
> I think the logs should point this out but I'll close the issue as it's been resolved.

I encountered the same error without specify the `scheme https` option.

**Comment by gaochundong** [comment]
Not Good.

**Comment by ryangallen** [comment]
This works for now:

```
gem install fluent-plugin-elasticsearch  && sudo gem install elasticsearch -v 7.5.0.pre.pre
```

**Comment by picandocodigo** [comment]
@ryangallen thanks for reporting! The intention is to release 7.5.0 final next week. So thanks for checking it out and if you find any issues, please do report them in the [client's repo](https://github.com/elastic/elasticsearch-ruby/issues). I'll be doing some clean up soon to address the standing issues.

**Comment by ppawel** [comment]
I think this should be reopened, I still see this issue with fluentd 1.10.2, fluent-plugin-elasticsearch 4.0.7.

**Comment by picandocodigo** [comment]
@ppawel Maybe open a new issue either here or in the elasticsearch-ruby repository? If you open a new issue in this repo, please @ me if it's related to the elasticsearch-ruby code. And can you share which version of the client is in your `Gemfile.lock` and also paste the error stack trace please? Thanks!
