### ISSUE TITLE
Plugin Error on Startup

### ISSUE THREAD

**Issue by david-rooke** [uken/fluent-plugin-elasticsearch#712]
(check apply)
- [x] read [the contribution guideline](https://github.com/uken/fluent-plugin-elasticsearch/blob/master/CONTRIBUTING.md)

Am getting startup errors with version 3.5.6 of the plugin:
- Platform: kubernetes
- Image: fluentd-kubernetes-daemonset:v1.8.1-debian-elasticsearch6-1.0
- Plugin Version: 3.5.6
- Log Output:

```
#### Problem
{"time":"2020-02-04T15:28:17.906","level":"info","message":"parsing config file is succeeded path=\"/fluentd/etc/fluent.conf\""}
{"time":"2020-02-04T15:28:17.924","level":"info","message":"gem 'fluent-plugin-concat' version '2.4.0'"}
{"time":"2020-02-04T15:28:17.924","level":"info","message":"gem 'fluent-plugin-dedot_filter' version '1.0.0'"}
{"time":"2020-02-04T15:28:17.924","level":"info","message":"gem 'fluent-plugin-detect-exceptions' version '0.0.13'"}
{"time":"2020-02-04T15:28:17.924","level":"info","message":"gem 'fluent-plugin-elasticsearch' version '3.5.6'"}
{"time":"2020-02-04T15:28:17.924","level":"info","message":"gem 'fluent-plugin-grok-parser' version '2.6.1'"}
{"time":"2020-02-04T15:28:17.925","level":"info","message":"gem 'fluent-plugin-json-in-json-2' version '1.0.2'"}
{"time":"2020-02-04T15:28:17.925","level":"info","message":"gem 'fluent-plugin-kubernetes_metadata_filter' version '2.3.0'"}
{"time":"2020-02-04T15:28:17.925","level":"info","message":"gem 'fluent-plugin-multi-format-parser' version '1.0.0'"}
{"time":"2020-02-04T15:28:17.925","level":"info","message":"gem 'fluent-plugin-prometheus' version '1.6.1'"}
{"time":"2020-02-04T15:28:17.925","level":"info","message":"gem 'fluent-plugin-record-modifier' version '2.0.1'"}
{"time":"2020-02-04T15:28:17.925","level":"info","message":"gem 'fluent-plugin-rewrite-tag-filter' version '2.2.0'"}
{"time":"2020-02-04T15:28:17.925","level":"info","message":"gem 'fluent-plugin-systemd' version '1.0.2'"}
{"time":"2020-02-04T15:28:17.925","level":"info","message":"gem 'fluentd' version '1.8.1'"}
/fluentd/vendor/bundle/ruby/2.6.0/gems/fluent-plugin-elasticsearch-3.5.6/lib/fluent/plugin/out_elasticsearch.rb:190:in `configure': undefined method `dry_run_mode' for #<Fluent::EngineClass:0x00007f7d2a4e4658> (NoMethodError)
	from /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.8.1/lib/fluent/plugin.rb:173:in `configure'
	from /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.8.1/lib/fluent/agent.rb:132:in `add_match'
	from /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.8.1/lib/fluent/agent.rb:74:in `block in configure'
	from /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.8.1/lib/fluent/agent.rb:64:in `each'
	from /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.8.1/lib/fluent/agent.rb:64:in `configure'
	from /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.8.1/lib/fluent/root_agent.rb:146:in `configure'
	from /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.8.1/lib/fluent/engine.rb:104:in `configure'
	from /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.8.1/lib/fluent/engine.rb:79:in `run_configure'
	from /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.8.1/lib/fluent/supervisor.rb:485:in `run_supervisor'
	from /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.8.1/lib/fluent/command/fluentd.rb:330:in `<top (required)>'
	from /usr/local/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/local/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.8.1/bin/fluentd:8:in `<top (required)>'
	from /fluentd/vendor/bundle/ruby/2.6.0/bin/fluentd:23:in `load'
	from /fluentd/vendor/bundle/ruby/2.6.0/bin/fluentd:23:in `<main>'
```

- Config:
```
    <match **>
      @type elasticsearch
      verify_es_version_at_startup true
      hosts "#{ENV['ELASTICSEARCH_HOSTS']}"
      port "#{ENV['ELASTICSEARCH_PORT']}"
      id_key _hash
      remove_keys _hash
      logstash_format true
      logstash_prefix kubernetes-logs
      bulk_message_request_threshold 10mb
      request_timeout 10s
      log_es_400_reason true
      <buffer tag>
        @type file
        # Limit bulk size at the request of the Data Platform team
        chunk_limit_size 48m
        disable_chunk_backup true
        flush_interval 30s
        flush_thread_count 4
        overflow_action drop_oldest_chunk
        path /var/lib/fluentd/buffer/
        queued_chunks_limit_size 100
        total_limit_size 1g
      </buffer>
      slow_flush_log_threshold 60
      reload_connections false
      reconnect_on_error true
      reload_on_failure true
      resurrect_after 10s
      write_operation create
      with_transporter_log true
      @log_level info
    </match>
```

**Comment by cosmo0920** [comment]
Thanks for opening your issue.
I'd reported this issue in https://github.com/fluent/fluentd-kubernetes-daemonset/pull/399.

**Comment by cosmo0920** [comment]
Try v1.8.1-debian-elasticsearch6-1.1 image. Closing.
