### ISSUE TITLE
failed to flush the buffer(connect_write timeout reached)

### ISSUE THREAD

**Issue by mingyuejishi** [uken/fluent-plugin-elasticsearch#746]
(check apply)
- [ ] read [the contribution guideline](https://github.com/uken/fluent-plugin-elasticsearch/blob/master/CONTRIBUTING.md)

#### Problem
`2020-04-20 06:32:13 +0000 [warn]: [elasticsearch_dynamic] failed to flush the buffer. retry_time=0 next_retry_seconds=2020-04-20 06:32:14.370847601 +0000
chunk="5a3b3074953fdfe378ae80e4933ff273" error_class=Fluent::Plugin::ElasticsearchOutput::RecoverableRequestFailure error="could not push logs to Elastics
earch cluster ({:host=>\"elasticsearch\", :port=>9200, :scheme=>\"http\", :user=>\"elastic\", :password=>\"obfuscated\"}): Connection timed ou
t - connect(2) for 172.17.0.1:9201 (Errno::ETIMEDOUT)"
2020-04-20 06:32:13.370866353 +0000 fluent.warn: {"retry_time":0,"next_retry_seconds":"2020-04-20 06:32:14.370847601 +0000","chunk":"5a3b3074953fdfe378ae8
0e4933ff273","error":"#<Fluent::Plugin::ElasticsearchOutput::RecoverableRequestFailure: could not push logs to Elasticsearch cluster ({:host=>\"user-cente
r-elasticsearch\", :port=>9200, :scheme=>\"http\", :user=>\"elastic\", :password=>\"obfuscated\"}): Connection timed out - connect(2) for 172.17.0.1:9201
(Errno::ETIMEDOUT)>","message":"[elasticsearch_dynamic] failed to flush the buffer. retry_time=0 next_retry_seconds=2020-04-20 06:32:14.370847601 +0000 ch
unk=\"5a3b3074953fdfe378ae80e4933ff273\" error_class=Fluent::Plugin::ElasticsearchOutput::RecoverableRequestFailure error=\"could not push logs to Elastic
search cluster ({:host=>\\\"elasticsearch\\\", :port=>9200, :scheme=>\\\"http\\\", :user=>\\\"elastic\\\", :password=>\\\"obfuscated\\\"}): Co
nnection timed out - connect(2) for 172.17.0.1:9201 (Errno::ETIMEDOUT)\""}
  2020-04-20 06:32:13 +0000 [warn]: /usr/local/bundle/gems/fluent-plugin-elasticsearch-4.0.7/lib/fluent/plugin/out_elasticsearch_dynamic.rb:238:in `rescue
 in send_bulk'
  2020-04-20 06:32:13 +0000 [warn]: /usr/local/bundle/gems/fluent-plugin-elasticsearch-4.0.7/lib/fluent/plugin/out_elasticsearch_dynamic.rb:224:in `send_b
ulk'
  2020-04-20 06:32:13 +0000 [warn]: /usr/local/bundle/gems/fluent-plugin-elasticsearch-4.0.7/lib/fluent/plugin/out_elasticsearch_dynamic.rb:219:in `block
in write'
  2020-04-20 06:32:13 +0000 [warn]: /usr/local/bundle/gems/fluent-plugin-elasticsearch-4.0.7/lib/fluent/plugin/out_elasticsearch_dynamic.rb:218:in `each'
  2020-04-20 06:32:13 +0000 [warn]: /usr/local/bundle/gems/fluent-plugin-elasticsearch-4.0.7/lib/fluent/plugin/out_elasticsearch_dynamic.rb:218:in `write'

  2020-04-20 06:32:13 +0000 [warn]: /usr/local/bundle/gems/fluentd-1.9.3/lib/fluent/plugin/output.rb:1133:in `try_flush'
  2020-04-20 06:32:13 +0000 [warn]: /usr/local/bundle/gems/fluentd-1.9.3/lib/fluent/plugin/output.rb:1439:in `flush_thread_run'
  2020-04-20 06:32:13 +0000 [warn]: /usr/local/bundle/gems/fluentd-1.9.3/lib/fluent/plugin/output.rb:461:in `block (2 levels) in start'
  2020-04-20 06:32:13 +0000 [warn]: /usr/local/bundle/gems/fluentd-1.9.3/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
2020-04-20 06:32:20 +0000 [warn]: [elasticsearch_dynamic] failed to flush the buffer. retry_time=1 next_retry_seconds=2020-04-20 06:32:21 1871101776259621
13557/879609302220800000000 +0000 chunk="5a3b307b3b4be337ee7076a4c05b3bdd" error_class=Fluent::Plugin::ElasticsearchOutput::RecoverableRequestFailure erro
r="could not push logs to Elasticsearch cluster ({:host=>\"elasticsearch\", :port=>9200, :scheme=>\"http\", :user=>\"elastic\", :password=>\"o
bfuscated\"}): Connection timed out - connect(2) for 172.17.0.1:9201 (Errno::ETIMEDOUT)"
2020-04-20 06:32:20.278660184 +0000 fluent.warn: {"retry_time":1,"next_retry_seconds":"2020-04-20 06:32:21 187110177625962113557/879609302220800000000 +00
00","chunk":"5a3b307b3b4be337ee7076a4c05b3bdd","error":"#<Fluent::Plugin::ElasticsearchOutput::RecoverableRequestFailure: could not push logs to Elasticse
arch cluster ({:host=>\"elasticsearch\", :port=>9200, :scheme=>\"http\", :user=>\"elastic\", :password=>\"obfuscated\"}): Connection timed out
 - connect(2) for 172.17.0.1:9201 (Errno::ETIMEDOUT)>","message":"[elasticsearch_dynamic] failed to flush the buffer. retry_time=1 next_retry_seconds=2020
-04-20 06:32:21 187110177625962113557/879609302220800000000 +0000 chunk=\"5a3b307b3b4be337ee7076a4c05b3bdd\" error_class=Fluent::Plugin::ElasticsearchOutp
ut::RecoverableRequestFailure error=\"could not push logs to Elasticsearch cluster ({:host=>\\\"elasticsearch\\\", :port=>9200, :scheme=>\\\"h
ttp\\\", :user=>\\\"elastic\\\", :password=>\\\"obfuscated\\\"}): Connection timed out - connect(2) for 172.17.0.1:9201 (Errno::ETIMEDOUT)\""}
  2020-04-20 06:32:20 +0000 [warn]: /usr/local/bundle/gems/fluent-plugin-elasticsearch-4.0.7/lib/fluent/plugin/out_elasticsearch_dynamic.rb:238:in `rescue
 in send_bulk'
  2020-04-20 06:32:20 +0000 [warn]: /usr/local/bundle/gems/fluent-plugin-elasticsearch-4.0.7/lib/fluent/plugin/out_elasticsearch_dynamic.rb:224:in `send_b
ulk'
  2020-04-20 06:32:20 +0000 [warn]: /usr/local/bundle/gems/fluent-plugin-elasticsearch-4.0.7/lib/fluent/plugin/out_elasticsearch_dynamic.rb:219:in `block
in write'
  2020-04-20 06:32:20 +0000 [warn]: /usr/local/bundle/gems/fluent-plugin-elasticsearch-4.0.7/lib/fluent/plugin/out_elasticsearch_dynamic.rb:218:in `each'
  2020-04-20 06:32:20 +0000 [warn]: /usr/local/bundle/gems/fluent-plugin-elasticsearch-4.0.7/lib/fluent/plugin/out_elasticsearch_dynamic.rb:218:in `write'

  2020-04-20 06:32:20 +0000 [warn]: /usr/local/bundle/gems/fluentd-1.9.3/lib/fluent/plugin/output.rb:1133:in `try_flush'
  2020-04-20 06:32:20 +0000 [warn]: /usr/local/bundle/gems/fluentd-1.9.3/lib/fluent/plugin/output.rb:1439:in `flush_thread_run'
  2020-04-20 06:32:20 +0000 [warn]: /usr/local/bundle/gems/fluentd-1.9.3/lib/fluent/plugin/output.rb:461:in `block (2 levels) in start'
  2020-04-20 06:32:20 +0000 [warn]: /usr/local/bundle/gems/fluentd-1.9.3/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
`
...

config:
```aconf
    # Detect exceptions in the log output and forward them as one log entry.
    <match raw.kubernetes.**>
      @id raw.kubernetes
      @type detect_exceptions
      remove_tag_prefix raw
      message log
      stream stream
      multiline_flush_interval 5
      max_bytes 500000
      max_lines 1000
    </match>

    # Concatenate multi-line logs
    <filter **>
      @id filter_concat
      @type concat
      key message
      multiline_end_regexp /\n$/
      separator ""
    </filter>

    
    <match kubernetes.var.log.containers.**fluentd-es**.log>
      @type null
    </match>
    
    

    # Enriches records with Kubernetes metadata
    <filter kubernetes.**>
      @id filter_kubernetes_metadata
      @type kubernetes_metadata
    </filter>

    # Fixes json fields in Elasticsearch
    <filter kubernetes.**>
      @id filter_parser
      @type parser
      key_name log
      reserve_data true
      remove_key_name_field true
      <parse>
        @type multi_format
        <pattern>
          format json
        </pattern>
        <pattern>
          format none
        </pattern>
      </parse>
    </filter>
```
 
```
output.conf: |-
    <match **>
      @id elasticsearch_dynamic
      @type elasticsearch_dynamic
      @log_level info
      type_name _doc
      include_tag_key true
      host user-center-elasticsearch
      port 9200
      request_timeout 3600000
      user "#{ENV['FLUENT_ELASTICSEARCH_USER']}"
      password "#{ENV['FLUENT_ELASTICSEARCH_PASSWORD']}"
      scheme "#{ENV['FLUENT_ELASTICSEARCH_SCHEME'] || 'http'}"
      ssl_verify "#{ENV['FLUENT_ELASTICSEARCH_SSL_VERIFY'] || 'true'}"
      logstash_format true
      logstash_prefix fluentd-${record['kubernetes']['container_name']}
      <buffer>
        @type file
        path /var/log/fluentd-buffers/kubernetes.system.buffer
        flush_mode interval
        retry_type exponential_backoff
        flush_thread_count 2
        flush_interval 5s
        retry_forever 
        retry_max_interval 30
        chunk_limit_size 2M
        total_limit_size 500M
        overflow_action block
      </buffer>
    </match>
```

#### Expected Behavior or What you need to ask
how to solve the problem?when it occurs ,there are always two  chunks that are failed to flush the buffer.and it occurs many times after the pod run several hours later.
...

#### Using Fluentd and ES plugin versions
fluentd:fluentd-1.9.3
esplugin:fluent-plugin-elasticsearch-4.0.7
image:quay.io/fluentd_elasticsearch/fluentd:v3.0.1

**Comment by mingyuejishi** [comment]
i change the version of the image and make fluentd not to collect its own log any longer. the problem hasn't occurred so far.

**Comment by mingyuejishi** [comment]
i change the version ,but it still occurs two days later.
2020-04-20 06:32:13 +0000 [warn]: [elasticsearch_dynamic] failed to flush the buffer. retry_time=0 next_retry_seconds=2020-04-20 06:32:14.370847601 +0000
chunk="5a3b3074953fdfe378ae80e4933ff273" error_class=Fluent::Plugin::ElasticsearchOutput::RecoverableRequestFailure error="could not push logs to Elastics
earch cluster ({:host=>\"elasticsearch\", :port=>9200, :scheme=>\"http\", :user=>\"elastic\", :password=>\"obfuscated\"}): Connection timed ou
t - connect(2) for 172.17.0.1:9201 (Errno::ETIMEDOUT)"
2020-04-20 06:32:13.370866353 +0000 fluent.warn: {"retry_time":0,"next_retry_seconds":"2020-04-20 06:32:14.370847601 +0000","chunk":"5a3b3074953fdfe378ae8
0e4933ff273","error":"#<Fluent::Plugin::ElasticsearchOutput::RecoverableRequestFailure: could not push logs to Elasticsearch cluster ({:host=>\"user-cente
r-elasticsearch\", :port=>9200, :scheme=>\"http\", :user=>\"elastic\", :password=>\"obfuscated\"}): Connection timed out - connect(2) for 172.17.0.1:9201
(Errno::ETIMEDOUT)>","message":"[elasticsearch_dynamic] failed to flush the buffer. retry_time=0 next_retry_seconds=2020-04-20 06:32:14.370847601 +0000 ch
unk=\"5a3b3074953fdfe378ae80e4933ff273\" error_class=Fluent::Plugin::ElasticsearchOutput::RecoverableRequestFailure error=\"could not push logs to Elastic
search cluster ({:host=>\\\"elasticsearch\\\", :port=>9200, :scheme=>\\\"http\\\", :user=>\\\"elastic\\\", :password=>\\\"obfuscated\\\"}): Co
nnection timed out - connect(2) for 172.17.0.1:9201 (Errno::ETIMEDOUT)\""}
  2020-04-20 06:32:13 +0000 [warn]: /usr/local/bundle/gems/fluent-plugin-elasticsearch-4.0.7/lib/fluent/plugin/out_elasticsearch_dynamic.rb:238:in `rescue
 in send_bulk'
  2020-04-20 06:32:13 +0000 [warn]: /usr/local/bundle/gems/fluent-plugin-elasticsearch-4.0.7/lib/fluent/plugin/out_elasticsearch_dynamic.rb:224:in `send_b
ulk'
  2020-04-20 06:32:13 +0000 [warn]: /usr/local/bundle/gems/fluent-plugin-elasticsearch-4.0.7/lib/fluent/plugin/out_elasticsearch_dynamic.rb:219:in `block
in write'
  2020-04-20 06:32:13 +0000 [warn]: /usr/local/bundle/gems/fluent-plugin-elasticsearch-4.0.7/lib/fluent/plugin/out_elasticsearch_dynamic.rb:218:in `each'
  2020-04-20 06:32:13 +0000 [warn]: /usr/local/bundle/gems/fluent-plugin-elasticsearch-4.0.7/lib/fluent/plugin/out_elasticsearch_dynamic.rb:218:in `write'

  2020-04-20 06:32:13 +0000 [warn]: /usr/local/bundle/gems/fluentd-1.9.3/lib/fluent/plugin/output.rb:1133:in `try_flush'
  2020-04-20 06:32:13 +0000 [warn]: /usr/local/bundle/gems/fluentd-1.9.3/lib/fluent/plugin/output.rb:1439:in `flush_thread_run'
  2020-04-20 06:32:13 +0000 [warn]: /usr/local/bundle/gems/fluentd-1.9.3/lib/fluent/plugin/output.rb:461:in `block (2 levels) in start'
  2020-04-20 06:32:13 +0000 [warn]: /usr/local/bundle/gems/fluentd-1.9.3/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
2020-04-20 06:32:20 +0000 [warn]: [elasticsearch_dynamic] failed to flush the buffer. retry_time=1 next_retry_seconds=2020-04-20 06:32:21 1871101776259621
13557/879609302220800000000 +0000 chunk="5a3b307b3b4be337ee7076a4c05b3bdd" error_class=Fluent::Plugin::ElasticsearchOutput::RecoverableRequestFailure erro
r="could not push logs to Elasticsearch cluster ({:host=>\"elasticsearch\", :port=>9200, :scheme=>\"http\", :user=>\"elastic\", :password=>\"o
bfuscated\"}): Connection timed out - connect(2) for 172.17.0.1:9201 (Errno::ETIMEDOUT)"
2020-04-20 06:32:20.278660184 +0000 fluent.warn: {"retry_time":1,"next_retry_seconds":"2020-04-20 06:32:21 187110177625962113557/879609302220800000000 +00
00","chunk":"5a3b307b3b4be337ee7076a4c05b3bdd","error":"#<Fluent::Plugin::ElasticsearchOutput::RecoverableRequestFailure: could not push logs to Elasticse
arch cluster ({:host=>\"elasticsearch\", :port=>9200, :scheme=>\"http\", :user=>\"elastic\", :password=>\"obfuscated\"}): Connection timed out
 - connect(2) for 172.17.0.1:9201 (Errno::ETIMEDOUT)>","message":"[elasticsearch_dynamic] failed to flush the buffer. retry_time=1 next_retry_seconds=2020
-04-20 06:32:21 187110177625962113557/879609302220800000000 +0000 chunk=\"5a3b307b3b4be337ee7076a4c05b3bdd\" error_class=Fluent::Plugin::ElasticsearchOutp
ut::RecoverableRequestFailure error=\"could not push logs to Elasticsearch cluster ({:host=>\\\"elasticsearch\\\", :port=>9200, :scheme=>\\\"h
ttp\\\", :user=>\\\"elastic\\\", :password=>\\\"obfuscated\\\"}): Connection timed out - connect(2) for 172.17.0.1:9201 (Errno::ETIMEDOUT)\""}
  2020-04-20 06:32:20 +0000 [warn]: /usr/local/bundle/gems/fluent-plugin-elasticsearch-4.0.7/lib/fluent/plugin/out_elasticsearch_dynamic.rb:238:in `rescue
 in send_bulk'
  2020-04-20 06:32:20 +0000 [warn]: /usr/local/bundle/gems/fluent-plugin-elasticsearch-4.0.7/lib/fluent/plugin/out_elasticsearch_dynamic.rb:224:in `send_b
ulk'
  2020-04-20 06:32:20 +0000 [warn]: /usr/local/bundle/gems/fluent-plugin-elasticsearch-4.0.7/lib/fluent/plugin/out_elasticsearch_dynamic.rb:219:in `block
in write'
  2020-04-20 06:32:20 +0000 [warn]: /usr/local/bundle/gems/fluent-plugin-elasticsearch-4.0.7/lib/fluent/plugin/out_elasticsearch_dynamic.rb:218:in `each'
  2020-04-20 06:32:20 +0000 [warn]: /usr/local/bundle/gems/fluent-plugin-elasticsearch-4.0.7/lib/fluent/plugin/out_elasticsearch_dynamic.rb:218:in `write'

  2020-04-20 06:32:20 +0000 [warn]: /usr/local/bundle/gems/fluentd-1.9.3/lib/fluent/plugin/output.rb:1133:in `try_flush'
  2020-04-20 06:32:20 +0000 [warn]: /usr/local/bundle/gems/fluentd-1.9.3/lib/fluent/plugin/output.rb:1439:in `flush_thread_run'
  2020-04-20 06:32:20 +0000 [warn]: /usr/local/bundle/gems/fluentd-1.9.3/lib/fluent/plugin/output.rb:461:in `block (2 levels) in start'
  2020-04-20 06:32:20 +0000 [warn]: /usr/local/bundle/gems/fluentd-1.9.3/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'

**Comment by cosmo0920** [comment]
Could you specify the following configurations in output.conf config map?

```aconf
    reload_connections false
    reconnect_on_error true
    reload_on_failure false
```

**Comment by mingyuejishi** [comment]
i specify it in the Daemonset file:
` - name: FLUENT_ELASTICSEARCH_RELOAD_CONNECTION
              value: "false"
            - name: FLUENT_ELASTICSEARCH_RECONNECT_ON_ERROR
              value: "true"
            - name: FLUENT_ELASTICSEARCH_RELOAD_ON_FAILURE
              value: "true"`

**Comment by cosmo0920** [comment]
> when the problem occurs, fluentd doesn't connect to the service,instaed it connet to a ip(172.17.0.1),i don't know why . i change the es address from the service name to its real ip in the configmap.so far the problem does't occur again.

This is because elasticsearch-ruby sniffer feature. 
This should stop with `SimpleSniffer` class:
https://github.com/uken/fluent-plugin-elasticsearch#sniffer-class-name

But I don't know how to specify `sniffer_class_name Fluent::Plugin::ElasticsearchSimpleSniffer` and to add elasticsearch_simple_sniffer.rb for Fluentd load path.

**Comment by mingyuejishi** [comment]
so as long as i user the real ip address of es instead of service name,the problem will be solved?

**Comment by cosmo0920** [comment]
> so as long as i use the real ip address of es(make a direct connection to es) instead of service name,the problem will be solved?

Yes. But, it adds fragility for changing service IP address.

**Comment by mingyuejishi** [comment]
ok, thank you! @cosmo0920

**Comment by linbingdouzhe** [comment]
@mingyuejishi  hi , i am using es https , i can not setup real ip address, is there some way can i aviod this problem ? thanks

**Comment by cosmo0920** [comment]
Please don't use closed issue and w/o issue template comment such as help me ASAP. Thanks!!!
