### ISSUE TITLE
ILM and template feature error

### ISSUE THREAD

**Issue by vDMG** [uken/fluent-plugin-elasticsearch#747]
- [x] read [the contribution guideline](https://github.com/uken/fluent-plugin-elasticsearch/blob/master/CONTRIBUTING.md)

#### Problem
Hello,

fluent-plugin-elasticsearch **4.0.4** works like a charm when I don't try enabling ILM feature but he's raising the following exception when I try to use index template and ILM feature :
```
2020-04-16 14:02:27 +0000 [error]: #0 unexpected error error_class=NameError error="uninitialized constant Faraday::Error::ConnectionFailed"
  2020-04-16 14:02:27 +0000 [error]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/http/faraday.rb:51:in `host_unreachable_exceptions'
  2020-04-16 14:02:27 +0000 [error]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluent-plugin-elasticsearch-4.0.4/lib/fluent/plugin/elasticsearch_index_template.rb:36:in `rescue in retry_operate'
  2020-04-16 14:02:27 +0000 [error]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluent-plugin-elasticsearch-4.0.4/lib/fluent/plugin/elasticsearch_index_template.rb:34:in `retry_operate'
  2020-04-16 14:02:27 +0000 [error]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluent-plugin-elasticsearch-4.0.4/lib/fluent/plugin/out_elasticsearch.rb:900:in `template_installation_actual'
  2020-04-16 14:02:27 +0000 [error]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluent-plugin-elasticsearch-4.0.4/lib/fluent/plugin/out_elasticsearch.rb:235:in `configure'
  2020-04-16 14:02:27 +0000 [error]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.8.1/lib/fluent/plugin.rb:173:in `configure'
  2020-04-16 14:02:27 +0000 [error]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.8.1/lib/fluent/agent.rb:132:in `add_match'
  2020-04-16 14:02:27 +0000 [error]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.8.1/lib/fluent/agent.rb:74:in `block in configure'
  2020-04-16 14:02:27 +0000 [error]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.8.1/lib/fluent/agent.rb:64:in `each'
  2020-04-16 14:02:27 +0000 [error]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.8.1/lib/fluent/agent.rb:64:in `configure'
  2020-04-16 14:02:27 +0000 [error]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.8.1/lib/fluent/root_agent.rb:146:in `configure'
  2020-04-16 14:02:27 +0000 [error]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.8.1/lib/fluent/engine.rb:104:in `configure'
  2020-04-16 14:02:27 +0000 [error]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.8.1/lib/fluent/engine.rb:79:in `run_configure'
  2020-04-16 14:02:27 +0000 [error]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.8.1/lib/fluent/supervisor.rb:533:in `block in run_worker'
  2020-04-16 14:02:27 +0000 [error]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.8.1/lib/fluent/supervisor.rb:740:in `main_process'
  2020-04-16 14:02:27 +0000 [error]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.8.1/lib/fluent/supervisor.rb:528:in `run_worker'
  2020-04-16 14:02:27 +0000 [error]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.8.1/lib/fluent/command/fluentd.rb:338:in `<top (required)>'
  2020-04-16 14:02:27 +0000 [error]: #0 /usr/local/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
  2020-04-16 14:02:27 +0000 [error]: #0 /usr/local/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
  2020-04-16 14:02:27 +0000 [error]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.8.1/bin/fluentd:8:in `<top (required)>'
  2020-04-16 14:02:27 +0000 [error]: #0 /fluentd/vendor/bundle/ruby/2.6.0/bin/fluentd:23:in `load'
  2020-04-16 14:02:27 +0000 [error]: #0 /fluentd/vendor/bundle/ruby/2.6.0/bin/fluentd:23:in `<main>'
2020-04-16 14:02:27 +0000 [info]: Worker 0 finished unexpectedly with status 1
```
#### Steps to replicate

Index template :
```
{
      "index_patterns": [
        "data-logs-*"
      ],
      "aliases" : {
        "data-logs" : { }
      },
      "mappings": {
        "_default_": {
          "_all": { "enabled": false }, 
          "_source": { "compress": true },
          "properties" : {
            "event_data": { "type": "object", "store": "no" },
            "@fields": { "type": "object", "dynamic": true, "path": "full" }, 
            "@message": { "type": "string", "index": "analyzed" },
            "@source": { "type": "string", "index": "not_analyzed" },
            "@source_host": { "type": "string", "index": "not_analyzed" },
            "@source_path": { "type": "string", "index": "not_analyzed" },
            "@tags": { "type": "string", "index": "not_analyzed" },
            "@timestamp": { "type": "date", "index": "not_analyzed" },
            "@type": { "type": "string", "index": "not_analyzed" }    
          }   
        }
      },
      "settings": {
        "index.cache.field.type" : "soft",
        "index.refresh_interval": "5s",
        "index.store.compress.stored": true,
        "index.number_of_shards": "3", 
        "index.number_of_replicas": "2",
        "index.query.default_field": "querystring", 
        "index.routing.allocation.total_shards_per_node": "2"
        "index.lifecycle.name": "fluentd-policy"
      }, 
      "template": "data-logs-*"
    }
```

Working configuration:
``` 
<match kubernetes.**>
    @type elasticsearch
    @id out_es
    @log_level "info"
    include_tag_key true
    host "elastic-logs-es-http.elastic-system.svc.cluster.local"
    port 9200
    path ""
    scheme https
    ssl_verify false
    ssl_version TLSv1_2
    user "elastic"
    password xxxxxx
    reload_connections false
    reconnect_on_error true
    reload_on_failure true
    log_es_400_reason true
    logstash_prefix "data-logs"
    logstash_format false
    type_name "fluentd"
    index_name "data-logs"
    prefer_oj_serializer true
    <buffer>
      flush_thread_count 8
      flush_interval 5s
      chunk_limit_size 2M
      queue_limit_length 32
      retry_max_interval 30
      retry_forever true
    </buffer>
  </match>
```

Failing configuration:
```
<match kubernetes.**>
    @type elasticsearch
    @id out_es
    @log_level "info"
    include_tag_key true
    host "elastic-logs-es-http.elastic-system.svc.cluster.local"
    port 9200
    path ""
    scheme https
    ssl_verify false
    ssl_version TLSv1_2
    user "elastic"
    password xxxxxx
    reload_connections false
    reconnect_on_error true
    reload_on_failure true
    log_es_400_reason true
    logstash_prefix "data-logs"
    logstash_format false
    type_name "fluentd"
    customize_template {"<<index_prefix>>":"test"}
    index_name "data-logs"
    template_name "template"
    template_file "/fluentd/etc/template.json"
    rollover_index "true"
    deflector_alias "data-logs"
    enable_ilm true
    ilm_policy_id "fluentd-policy"
    ilm_policy {"policy":{"phases":{"delete":{"min_age":"30d","actions":{"delete":{}}}}}}
    prefer_oj_serializer true
    <buffer>
      flush_thread_count 8
      flush_interval 5s
      chunk_limit_size 2M
      queue_limit_length 32
      retry_max_interval 30
      retry_forever true
    </buffer>
  </match>
``` 
#### Expected Behavior or What you need to ask

Fluentd creating index template and ILM policy

#### Using Fluentd and ES plugin versions

* Kubernetes
* Docker image : fluent/fluentd-kubernetes-daemonset:v1.8-debian-elasticsearch7-1
* Fluentd v0.12 or v0.14/v1.0
  * `fluentd 1.8.1`
* ES plugin 4.0.4
* ES version (optional) **7.5.1**

**Comment by cosmo0920** [comment]
Could you use v0.17.3 faraday gem? This error indicates that elasticsearch-ruby gem does not follow faraday's error constant breaking changes on v1.

**Comment by cosmo0920** [comment]
No response and this issue seems to be Faraday's error definitions glitches.
Closing.
