### ISSUE TITLE
Plugin retries even when `retry_max_times 0`

### ISSUE THREAD

**Issue by willemveerman** [uken/fluent-plugin-elasticsearch#829]
- [x] read [the contribution guideline](https://github.com/uken/fluent-plugin-elasticsearch/blob/master/CONTRIBUTING.md)

#### Problem

Plugin will retry chunks even when configured with `retry_max_times 0`

The buffer config below will cause retries, as per logs pasted below
```          
          retry_max_times 0
          retry_wait 3s
          retry_timeout 100s
          retry_max_interval 30s
          retry_forever false
```
See below that certain chunk IDs are repeated, with a delay of 3 seconds as per config.

So `retry_max_times` is not being obeyed, but `retry_wait` parameter is being obeyed.

```
2020-10-26 12:15:39 +0000 [debug]: #0 taking back chunk for errors. chunk="5b291e18e2edb64d253b478e2b5e20d7"
2020-10-26 12:15:39 +0000 [warn]: #0 failed to flush the buffer. retry_time=0 next_retry_seconds=2020-10-26 12:15:42 +0000 chunk="5b291e18e2edb64d253b478e2b5e20d7" error_class=Fluent::Plugin::ElasticsearchOutput::RecoverableRequestFailure error="could not push logs to Elasticsearch cluster ({:host=>\"elasticsearch.default.svc.cluster.local\", :port=>9200, :scheme=>\"http\", :user=>\"\", :password=>\"obfuscated\"}): getaddrinfo: Name or service not known (SocketError)"
  2020-10-26 12:15:39 +0000 [warn]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluent-plugin-elasticsearch-4.0.11/lib/fluent/plugin/out_elasticsearch.rb:1005:in `rescue in send_bulk'
  2020-10-26 12:15:39 +0000 [warn]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluent-plugin-elasticsearch-4.0.11/lib/fluent/plugin/out_elasticsearch.rb:967:in `send_bulk'
  2020-10-26 12:15:39 +0000 [warn]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluent-plugin-elasticsearch-4.0.11/lib/fluent/plugin/out_elasticsearch.rb:794:in `block in write'
  2020-10-26 12:15:39 +0000 [warn]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluent-plugin-elasticsearch-4.0.11/lib/fluent/plugin/out_elasticsearch.rb:793:in `each'
  2020-10-26 12:15:39 +0000 [warn]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluent-plugin-elasticsearch-4.0.11/lib/fluent/plugin/out_elasticsearch.rb:793:in `write'
  2020-10-26 12:15:39 +0000 [warn]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.11.4/lib/fluent/plugin/output.rb:1136:in `try_flush'
  2020-10-26 12:15:39 +0000 [warn]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.11.4/lib/fluent/plugin/output.rb:1442:in `flush_thread_run'
  2020-10-26 12:15:39 +0000 [warn]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.11.4/lib/fluent/plugin/output.rb:462:in `block (2 levels) in start'
  2020-10-26 12:15:39 +0000 [warn]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.11.4/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
2020-10-26 12:15:42 +0000 [debug]: #0 taking back chunk for errors. chunk="5b291e18e2edb64d253b478e2b5e20d7"
2020-10-26 12:15:42 +0000 [error]: #0 failed to flush the buffer, and hit limit for retries. dropping all chunks in the buffer queue. retry_times=0 records=2 error_class=Fluent::Plugin::ElasticsearchOutput::RecoverableRequestFailure error="could not push logs to Elasticsearch cluster ({:host=>\"elasticsearch.default.svc.cluster.local\", :port=>9200, :scheme=>\"http\", :user=>\"\", :password=>\"obfuscated\"}): getaddrinfo: Name or service not known (SocketError)"
  2020-10-26 12:15:42 +0000 [error]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluent-plugin-elasticsearch-4.0.11/lib/fluent/plugin/out_elasticsearch.rb:1005:in `rescue in send_bulk'
  2020-10-26 12:15:42 +0000 [error]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluent-plugin-elasticsearch-4.0.11/lib/fluent/plugin/out_elasticsearch.rb:967:in `send_bulk'
  2020-10-26 12:15:42 +0000 [error]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluent-plugin-elasticsearch-4.0.11/lib/fluent/plugin/out_elasticsearch.rb:794:in `block in write'
  2020-10-26 12:15:42 +0000 [error]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluent-plugin-elasticsearch-4.0.11/lib/fluent/plugin/out_elasticsearch.rb:793:in `each'
  2020-10-26 12:15:42 +0000 [error]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluent-plugin-elasticsearch-4.0.11/lib/fluent/plugin/out_elasticsearch.rb:793:in `write'
  2020-10-26 12:15:42 +0000 [error]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.11.4/lib/fluent/plugin/output.rb:1136:in `try_flush'
  2020-10-26 12:15:42 +0000 [error]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.11.4/lib/fluent/plugin/output.rb:1442:in `flush_thread_run'
  2020-10-26 12:15:42 +0000 [error]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.11.4/lib/fluent/plugin/output.rb:462:in `block (2 levels) in start'
  2020-10-26 12:15:42 +0000 [error]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.11.4/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
2020-10-26 12:15:42 +0000 [debug]: #0 buffer queue cleared
2020-10-26 12:15:55 +0000 [debug]: #0 taking back chunk for errors. chunk="5b291e2a0fd2981e73850bb311ed7cb1"
2020-10-26 12:15:55 +0000 [warn]: #0 failed to flush the buffer. retry_time=0 next_retry_seconds=2020-10-26 12:15:58 +0000 chunk="5b291e2a0fd2981e73850bb311ed7cb1" error_class=Fluent::Plugin::ElasticsearchOutput::RecoverableRequestFailure error="could not push logs to Elasticsearch cluster ({:host=>\"elasticsearch.default.svc.cluster.local\", :port=>9200, :scheme=>\"http\", :user=>\"\", :password=>\"obfuscated\"}): getaddrinfo: Name or service not known (SocketError)"
  2020-10-26 12:15:55 +0000 [warn]: #0 suppressed same stacktrace
2020-10-26 12:15:58 +0000 [debug]: #0 taking back chunk for errors. chunk="5b291e2a0fd2981e73850bb311ed7cb1"
2020-10-26 12:15:58 +0000 [error]: #0 failed to flush the buffer, and hit limit for retries. dropping all chunks in the buffer queue. retry_times=0 records=69 error_class=Fluent::Plugin::ElasticsearchOutput::RecoverableRequestFailure error="could not push logs to Elasticsearch cluster ({:host=>\"elasticsearch.default.svc.cluster.local\", :port=>9200, :scheme=>\"http\", :user=>\"\", :password=>\"obfuscated\"}): getaddrinfo: Name or service not known (SocketError)"
  2020-10-26 12:15:58 +0000 [error]: #0 suppressed same stacktrace
2020-10-26 12:15:58 +0000 [debug]: #0 buffer queue cleared

```

#### Steps to replicate

1. Apply this yaml to k8s cluster - https://gist.github.com/willemveerman/b8c37d766b3cb625fc4669dff4c03b14 - e.g.:
    - `minikube start`
    - `kubectl apply -f retry_issue.yaml`
2. Wait until fluentd and ES pods are in `Running` status
3. Delete ES service: `kubectl delete svc elasticsearch`
4. View fluentd logs - `kubectl logs fluentd-7sw4h` - you will observe chunks being retried, even though configuration is `retry_max_times 0`

#### Expected Behavior or What you need to ask

When configured is `retry_max_times 0` chunk are sent once and not retried.

#### Using Fluentd and ES plugin versions

* OS version:
   😄  minikube v1.12.1 on Darwin 10.15.7
   ✨  Automatically selected the docker driver. Other choices: hyperkit, virtualbox
   🔥  Creating docker container (CPUs=2, Memory=4000MB) ...
   🐳  Preparing Kubernetes v1.18.3 on Docker 19.03.2 ...
* Fluentd `v1.11.4`
  - image `fluent/fluentd-kubernetes-daemonset:v1.11.4-debian-elasticsearch6-1.0`
* ES plugin `4.0.11`
  ```
  2020-10-26 12:19:51 +0000 [info]: gem 'fluent-plugin-concat' version '2.4.0'
  2020-10-26 12:19:51 +0000 [info]: gem 'fluent-plugin-detect-exceptions' version '0.0.13'
  2020-10-26 12:19:51 +0000 [info]: gem 'fluent-plugin-elasticsearch' version '4.0.11'
  2020-10-26 12:19:51 +0000 [info]: gem 'fluent-plugin-grok-parser' version '2.6.2'
  2020-10-26 12:19:51 +0000 [info]: gem 'fluent-plugin-json-in-json-2' version '1.0.2'
  2020-10-26 12:19:51 +0000 [info]: gem 'fluent-plugin-kubernetes_metadata_filter' version '2.3.0'
  2020-10-26 12:19:51 +0000 [info]: gem 'fluent-plugin-multi-format-parser' version '1.0.0'
  2020-10-26 12:19:51 +0000 [info]: gem 'fluent-plugin-prometheus' version '1.6.1'
  2020-10-26 12:19:51 +0000 [info]: gem 'fluent-plugin-record-modifier' version '2.0.1'
  2020-10-26 12:19:51 +0000 [info]: gem 'fluent-plugin-rewrite-tag-filter' version '2.2.0'
  2020-10-26 12:19:51 +0000 [info]: gem 'fluent-plugin-systemd' version '1.0.2'
  2020-10-26 12:19:51 +0000 [info]: gem 'fluentd' version '1.11.4'
  ```
* ES version `6.8.12`

**Comment by cosmo0920** [comment]
Unfortunately, `<buffer>` section is not handled in fluent-plugin-elasticsearch.
ES plugin just handles `<match>` section w/o `<buffer>` section.
Fluentd core's buffer plugin base class and buffer plugins handle `<buffer>` section.
Could you report this issue in [Fluentd itself bug tracker](https://github.com/fluent/fluentd/issues)?

**Comment by cosmo0920** [comment]
BTW, your configuration uses `overflow_action throw_exception`
It is correct usage even if Fluentd running on k8s. :100:
 
> * `overflow_action` [enum: `throw_exception`/`block`/`drop_oldest_chunk`]
>   * Default: throw_exception
>   * How does output plugin behave when its buffer queue is full?
>     * `throw_exception`: raises an exception to show the error in log
>     * `block`: wait until buffer can store more data.
> After buffer is ready for storing more data, writing buffer is retried.
> Because of such behavior, `block` is suitable for processing batch execution,
> so do not use for improving processing throughput or performance.
>     * `drop_oldest_chunk`: drops/purges the oldest chunk to accept newly
incoming chunk
ref: https://docs.fluentd.org/configuration/buffer-section#flushing-parameters

**Comment by willemveerman** [comment]
Thank you Cosmo - I will submit this issue on the fluentd portal. Sorry for taking so long to reply.

I noticed that in the openshift repo they set [`request_timeout`](https://github.com/uken/fluent-plugin-elasticsearch#request_timeout) to `2^31`; essentially, they never want the plugin to resend a pending request, which is understandable. See discussion here: https://bugzilla.redhat.com/show_bug.cgi?id=1559404

The question I have, is how does the plugin retry behaviour interact with the buffer retry behaviour?

The plugin retry behaviour - determined by [`request_timeout`](https://github.com/uken/fluent-plugin-elasticsearch#request_timeout) - must apply to the application level, i.e. HTTP requests. So if the plugin sends a bulk POST request it will wait for a HTTP response until [`request_timeout`](https://github.com/uken/fluent-plugin-elasticsearch#request_timeout) and then retry.

But what about the `<buffer>` section retry section? Does this pertain to
1. The network level, i.e. TCP?
1. The application level, i.e. HTTP?

If it's option 1., then if the buffer finds that the TCP endoint (`http://elasticsearch-IP:elasticsearch-port/_bulk`) is unreachable (i.e. there is nothing listening on `elasticsearch-port` so endpoint is 'closed') it will then retry. Is that right?

However, each chunk in the buffer is sent as a separate HTTP request to the ES Bulk API (I think), so if the buffer behaviour corresponds to option 2., it will retry if it hasn't received an HTTP response. So, in this case, it will override the plugin [`request_timeout`](https://github.com/uken/fluent-plugin-elasticsearch#request_timeout) parameter.

**Comment by cosmo0920** [comment]
> But what about the `<buffer>` section retry parameters? Does this pertain to
> 
>     1. The network level, i.e. TCP?
> 
>     2. The application level, i.e. HTTP?

It depends on Fluentd plugin. 
`<buffer>` section retrying requests to redo `#write` or `#try_write` or `#process`.

In ES plugin, `<buffer>` section retrying requests to redo `#write`. (This is because ES plugin just implements `#write`.)

So, in ES plugin, `<buffer>` section retrying does application level retry via HTTP.

**Comment by willemveerman** [comment]
I see, so the buffer section will simply re-send the chunk back to the output plugin to be re-processed.

So then presumably, if the buffer detects either a closed TCP endpoint or no HTTP response it will cause the chunk to be re-sent.

So then that means that the buffer retry paramters can completely over-ride the plugin `request_timeout` parameter

**Comment by willemveerman** [comment]
Thanks for confirming Cosmo. I will close this issue as I have logged it on the fluentd core issue tracker

**Comment by willemveerman** [comment]
> BTW, your configuration uses `overflow_action throw_exception`.
> It is correct usage even if Fluentd is running on k8s. 💯
> 

Hi Cosmo, we're still experiencing problems with our ES cluster which we assume are caused by excessive retry attempts from fluentd

We were thinking of using the configuration below:
```
<buffer>
  @type file
  path /var/log/fluent/buffers/es/kubernetes
  total_limit_size 1GB
  chunk_limit_size 30MB
  flush_mode interval
  flush_thread_burst_interval 5s
  flush_interval 60s
  flush_thread_count 8 
  retry_wait 300s
  retry_forever true
  overflow_action block
</buffer>
```
With the plugin `request_timeout` set to `2^31` just like in openshift

With this configuration, if fluentd is unable to send logs to ES, once the buffer reaches 1GB in size, it will simply stop reading input until it is able to transmit the chunks to ES, right?

**Comment by cosmo0920** [comment]
> With this configuration, if fluentd is unable to send logs to ES, once the buffer reaches 1GB in size, it will simply stop reading input until it is able to transmit the chunks to ES, right?

Pertially, yes.

> , if fluentd is unable to send logs to ES, once the buffer reaches 1GB in size, it will simply stop reading input until it is able to transmit the chunks to ES, right?

But, this hypothesis is wrong.
Once Fluentd gets to unable to send logs into ES, and stuck with `overflow_action block`, it will not to be able to resume operation. Just Fluentd stucks forever. Nobody knows how to resume stucked Fluentd with `overflow_action block`.

**Comment by willemveerman** [comment]
Thank you for providing some insight on this.

> But, this hypothesis is wrong.
> Once Fluentd gets to unable to send logs into ES, and stuck with `overflow_action block`, it will not to be able to resume operation. Just Fluentd stucks forever. Nobody knows how to resume stucked Fluentd with `overflow_action block`.

I thought you fixed that problem in PR https://github.com/uken/fluent-plugin-elasticsearch/pull/688?

**Comment by cosmo0920** [comment]
> > But, this hypothesis is wrong.
> > Once Fluentd gets to unable to send logs into ES, and stuck with `overflow_action block`, it will not to be able to resume operation. Just Fluentd stucks forever. Nobody knows how to resume stucked Fluentd with `overflow_action block`.
> 
> I thought you fixed that problem in PR #688?

No. This is not correct fix. Just workaround to prevent blocking in some circumstances.

**Comment by willemveerman** [comment]
OK so does this code mean that when the buffer is full and `overflow_action block` it will raise an exception and therefore exit the fluentd process?

In that situation the pod would restart, then the new process would find the same buffer file and restart, etc

**Comment by cosmo0920** [comment]
> OK so does this code mean that when the buffer is full and `overflow_action block` it will raise an exception and therefore exit the fluentd process?

No, just stuck without no error messages/

**Comment by willemveerman** [comment]
> (Preventing to fill buffer space is only solution for this case.)

Oh I see - so when buffer reaches 90% for example, stop input plugin from reading input

**Comment by willemveerman** [comment]
OK, that's disappointing because using this feature in the way I expected would have been a good solution for us (and many other users I think)

**Comment by cosmo0920** [comment]
> > (Preventing to fill buffer space is only solution for this case.)
> 
> Oh I see - so when buffer reaches 90% for example, stop input plugin from reading input

Yeah. This feature is filed for future task in comment:
https://github.com/fluent/fluentd/blob/master/lib/fluent/plugin/buffer.rb#L239

**Comment by willemveerman** [comment]
OK.... that TODO was committed four years ago! I guess there's little chance of it being completed soon... that's a shame

**Comment by cosmo0920** [comment]
> OK, that's disappointing because using this feature in the way I expected would have been a good solution for us (and many other users I think)

Sorry for inconvenience. We'd already add a note for this misunderstanding on the document:
https://docs.fluentd.org/configuration/buffer-section#flushing-parameters

> `block`: wait until buffer can store more data.
 After buffer is ready for storing more data, writing buffer is retried.
 Because of such behavior, block is suitable for processing batch execution,
 so do not use for improving processing throughput or performance.

**Comment by cosmo0920** [comment]
> OK.... that TODO was committed four years ago! I guess there's little chance of it being completed soon... that's a shame

Send a feature request is reasonable for me! :muscle:

**Comment by willemveerman** [comment]
> Sorry for inconvenience. We'd already add a note for this common misunderstanding on the document:

No problem - you've been really helpful.

I think that comments in the docs doesn't fully convey the behaviour. Even with batch processing the buffer could fill up and then fluentd will hang forever. I will submit a PR for the docs I think

**Comment by willemveerman** [comment]
> BTW, your configuration uses `overflow_action throw_exception`.
> It is correct usage even if Fluentd is running on k8s. 💯

So if we set `overflow_action throw_exception`, what happens when the buffer is full?

It continues writing to the buffer, but the buffer exceeds the limit, or does it drop the chunks, or does it stop writing to the buffer?

**Comment by cosmo0920** [comment]
> > BTW, your configuration uses `overflow_action throw_exception`.
> > It is correct usage even if Fluentd is running on k8s. 💯
> 
> So if we set `overflow_action throw_exception`, what happens when the buffer is full?
> 
> It continues writing to the buffer, but the buffer exceeds the limit, or does it drop the chunks, or does it stop writing to the buffer?

Fluentd raise exception and stop processing logs.

**Comment by willemveerman** [comment]
> Fluentd raises exception and stop processing logs.

Oh interesting... so essentially it carries out the same action that I thought `block` would do - it keeps trying to send buffered logs to ES but stops reading source log files - yes that's exaxctly what we need
