### ISSUE TITLE
Retry exponential backoff does not work when using invalid/expired credentials

### ISSUE THREAD

**Issue by ventsislav-georgiev** [uken/fluent-plugin-elasticsearch#844]
#### Problem
When the authentication credentials fail the plugins logs the following error:
```
2020-11-30 16:41:53 +0000 [error]: #0 unexpected error error_class=Elasticsearch::Transport::Transport::Errors::Unauthorized error="[401] {\"error\":{\"root_cause\":[{\"type\":\"security_exception\",\"reason\":\"unable to authenticate user [test] for REST request [/]\",\"header\":{\"WWW-Authenticate\":\"Basic realm=\\\"security\\\" charset=\\\"UTF-8\\\"\"}}],\"type\":\"security_exception\",\"reason\":\"unable to authenticate user [test] for REST request [/]\",\"header\":{\"WWW-Authenticate\":\"Basic realm=\\\"security\\\" charset=\\\"UTF-8\\\"\"}},\"status\":401}" 
2020-11-30 16:41:53 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/elasticsearch-transport-7.9.0/lib/elasticsearch/transport/transport/base.rb:218:in `__raise_transport_error'
2020-11-30 16:41:53 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/elasticsearch-transport-7.9.0/lib/elasticsearch/transport/transport/base.rb:347:in `perform_request'
2020-11-30 16:41:53 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/elasticsearch-transport-7.9.0/lib/elasticsearch/transport/transport/http/faraday.rb:37:in `perform_request'
2020-11-30 16:41:53 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/elasticsearch-transport-7.9.0/lib/elasticsearch/transport/client.rb:176:in `perform_request'
2020-11-30 16:41:53 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/elasticsearch-api-7.9.0/lib/elasticsearch/api/actions/info.rb:37:in `info'
2020-11-30 16:41:53 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluent-plugin-elasticsearch-4.2.2/lib/fluent/plugin/out_elasticsearch.rb:482:in `detect_es_major_version'
2020-11-30 16:41:53 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluent-plugin-elasticsearch-4.2.2/lib/fluent/plugin/out_elasticsearch.rb:474:in `block in handle_last_seen_es_major_version'
2020-11-30 16:41:53 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluent-plugin-elasticsearch-4.2.2/lib/fluent/plugin/elasticsearch_index_template.rb:39:in `retry_operate'
2020-11-30 16:41:53 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluent-plugin-elasticsearch-4.2.2/lib/fluent/plugin/out_elasticsearch.rb:473:in `handle_last_seen_es_major_version'
2020-11-30 16:41:53 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluent-plugin-elasticsearch-4.2.2/lib/fluent/plugin/out_elasticsearch.rb:325:in `configure'
2020-11-30 16:41:53 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.11.2/lib/fluent/plugin.rb:173:in `configure'
2020-11-30 16:41:53 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.11.2/lib/fluent/plugin/multi_output.rb:74:in `block in configure'
2020-11-30 16:41:53 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.11.2/lib/fluent/plugin/multi_output.rb:63:in `each'
2020-11-30 16:41:53 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.11.2/lib/fluent/plugin/multi_output.rb:63:in `configure'
2020-11-30 16:41:53 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.11.2/lib/fluent/plugin/out_copy.rb:38:in `configure'
2020-11-30 16:41:53 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.11.2/lib/fluent/plugin.rb:173:in `configure'
2020-11-30 16:41:53 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.11.2/lib/fluent/agent.rb:132:in `add_match'
2020-11-30 16:41:53 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.11.2/lib/fluent/agent.rb:74:in `block in configure'
2020-11-30 16:41:53 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.11.2/lib/fluent/agent.rb:64:in `each'
2020-11-30 16:41:53 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.11.2/lib/fluent/agent.rb:64:in `configure'
2020-11-30 16:41:53 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.11.2/lib/fluent/root_agent.rb:146:in `configure'
2020-11-30 16:41:53 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.11.2/lib/fluent/engine.rb:105:in `configure'
2020-11-30 16:41:53 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.11.2/lib/fluent/engine.rb:80:in `run_configure'
2020-11-30 16:41:53 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.11.2/lib/fluent/supervisor.rb:602:in `block in run_worker'
2020-11-30 16:41:53 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.11.2/lib/fluent/supervisor.rb:840:in `main_process'
2020-11-30 16:41:53 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.11.2/lib/fluent/supervisor.rb:594:in `run_worker'
2020-11-30 16:41:53 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.11.2/lib/fluent/command/fluentd.rb:361:in `<top (required)>' 
2020-11-30 16:41:53 +0000 [error]: #0 /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
2020-11-30 16:41:53 +0000 [error]: #0 /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
2020-11-30 16:41:53 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.11.2/bin/fluentd:8:in `<top (required)>' 
2020-11-30 16:41:53 +0000 [error]: #0 /usr/bin/fluentd:23:in `load'
2020-11-30 16:41:53 +0000 [error]: #0 /usr/bin/fluentd:23:in `<main>'
```

<br/>
<br/>

This error repeats every 6-12 seconds (may depend on the flush interval) and the process is constantly working instead of properly applying the configured retry exponential backoff.

Buffer configuration:
```
<buffer>
  @type file
  path /fluentd/tmp/buffers
  flush_mode interval
  flush_interval 5s
  overflow_action block
  retry_type exponential_backoff
  retry_forever true
  retry_max_interval 5m
</buffer>
```
...

#### Steps to replicate
Any elasticsearch server with basic auth setup. No SSL setup required.
Just use invalid user/password so that the authentication fails.

Example fluentd config:
```
<match *>
  @type elasticsearch
  hosts 'localhost:9200'
  scheme 'http'
  user 'test'
  password 'test'
  <buffer>
    @type file
    path /fluentd/tmp/buffers
    flush_mode interval
    flush_interval 5s
    overflow_action block
    retry_type exponential_backoff
    retry_forever true
    retry_max_interval 5m
  </buffer>
</match>
```

#### Expected Behavior or What you need to ask
Plugin catches the above error the same way it does when the host is invalid. Logs a simple message and retries with exponential backoff.

...

#### Using Fluentd and ES plugin versions

* OS version macOS Catalina
* Bare Metal/Docker/Kubernetes all the same
* fluentd 1.11.2
* fluent-plugin-elasticsearch (4.2.2)
* ES version 7.3.1

**Comment by cosmo0920** [comment]
Unauthorized exceptions are not unreachable exception:
https://github.com/elastic/elasticsearch-ruby/blob/ee83caf8ea090775b19190341eeee2cd627fdcd0/elasticsearch-transport/lib/elasticsearch/transport/transport/http/faraday.rb#L63

Then, Fluentd workers just exit and resume on every a few seconds due to uncaught exception.

Could you send a patch to rescue Unauthorized exception here?
https://github.com/uken/fluent-plugin-elasticsearch/blob/66d12b06e9118649ece5a4d07db633a24de12ce0/lib/fluent/plugin/elasticsearch_index_template.rb#L40

**Comment by ventsislav-georgiev** [comment]
@cosmo0920 We are actually having the same issue in [fluent-plugin-s3](https://github.com/fluent/fluent-plugin-s3/issues/359) and kind of the same but worst in [fluent-plugin-splunk-hec](https://github.com/splunk/fluent-plugin-splunk-hec/issues/153). Is there a way for me to handle this in a higher level so that it works in all plugins? Isn't the retry buffer settings suppose to work for all plugins?

**Comment by cosmo0920** [comment]
>  Is there a way for me to handle this in a higher level so that it works in all plugins?

AFAIK, there is no way for handling this.



> Isn't the retry buffer settings suppose to work for all plugins?

Buffered output plugin will use buffer plugin settings. Ideally, buffer plugin settings will be used for all buffered plugin such as fluent-plugin-elasticsearch, fluent-plugin-s3, and fluent-plugin-splunk-hec, and so on.

**Comment by cosmo0920** [comment]
IMO, invalid/expired credentials should be failure immediately. But retrying loop is not user-friendly....

**Comment by ventsislav-georgiev** [comment]
> Ideally, buffer plugin settings will be used for all buffered plugin

So these settings are just for the plugins and each plugin may or may not implement them?
I was expecting the core Fluentd code to use them and have some common interface for the plugins to implement which would comply with those settings...

> IMO, invalid/expired credentials should be failed/stopped immediately.

This type of implementation will also work for us well. Crashing Fluentd with error when the creds expire.
