### ISSUE TITLE
SSL_read: sslv3 alert certificate unknown

### ISSUE THREAD

**Issue by dhurng** [uken/fluent-plugin-elasticsearch#864]
(check apply)
- [ x ] read [the contribution guideline](https://github.com/uken/fluent-plugin-elasticsearch/blob/master/CONTRIBUTING.md)
- [ ] (optional) already reported 3rd party upstream repository or mailing list if you use k8s addon or helm charts.

#### Problem
I am seeing a `SSL_read: sslv3 alert certificate unknown`

when attempting to reach my elasticsearch cluster.

On the fluentd instance I can curl the elasticsearch cluster with proper certs/keys/cacert but not via the plugin.
...

#### Steps to replicate

Either clone and modify https://gist.github.com/pitr/9a518e840db58f435911

**OR**

Provide example config and message

Here is my config:

      @type elasticsearch
      include_tag_key true
      scheme https
      host elasticsearch...
      user "test"
      password "Temp4now"
      ssl_version TLSv1_2
      ca_file /etc/pki_service/ca/cacerts.pem
      client_cert /etc/identity/client/certificates/client.pem
      client_key /etc/identity/client/keys/client-key.pem
      ssl_verify true
      logstash_format true

the user test was created ad hoc on the cluster as well.

Here is the error log:

```
2021-02-04 03:26:12 +0000 [info]: Worker 0 finished unexpectedly with status 1
2021-02-04 03:26:13 +0000 [info]: adding match pattern="**" type="elasticsearch"
2021-02-04 03:26:14 +0000 [error]: #0 unexpected error error_class=Faraday::SSLError error="SSL_read: sslv3 alert certificate unknown (OpenSSL::SSL::SSLError)"
  2021-02-04 03:26:14 +0000 [error]: #0 /usr/lib/ruby/2.7.0/openssl/buffering.rb:182:in `sysread_nonblock'
  2021-02-04 03:26:14 +0000 [error]: #0 /usr/lib/ruby/2.7.0/openssl/buffering.rb:182:in `read_nonblock'
  2021-02-04 03:26:14 +0000 [error]: #0 /usr/lib/ruby/gems/2.7.0/gems/excon-0.79.0/lib/excon/socket.rb:179:in `read_nonblock'
  2021-02-04 03:26:14 +0000 [error]: #0 /usr/lib/ruby/gems/2.7.0/gems/excon-0.79.0/lib/excon/socket.rb:63:in `readline'
  2021-02-04 03:26:14 +0000 [error]: #0 /usr/lib/ruby/gems/2.7.0/gems/excon-0.79.0/lib/excon/response.rb:64:in `block in parse'
  2021-02-04 03:26:14 +0000 [error]: #0 /usr/lib/ruby/gems/2.7.0/gems/excon-0.79.0/lib/excon/response.rb:63:in `loop'
  2021-02-04 03:26:14 +0000 [error]: #0 /usr/lib/ruby/gems/2.7.0/gems/excon-0.79.0/lib/excon/response.rb:63:in `parse'
  2021-02-04 03:26:14 +0000 [error]: #0 /usr/lib/ruby/gems/2.7.0/gems/excon-0.79.0/lib/excon/middlewares/response_parser.rb:7:in `response_call'
  2021-02-04 03:26:14 +0000 [error]: #0 /usr/lib/ruby/gems/2.7.0/gems/excon-0.79.0/lib/excon/connection.rb:456:in `response'
  2021-02-04 03:26:14 +0000 [error]: #0 /usr/lib/ruby/gems/2.7.0/gems/excon-0.79.0/lib/excon/connection.rb:287:in `request'
  2021-02-04 03:26:14 +0000 [error]: #0 /usr/lib/ruby/gems/2.7.0/gems/faraday-1.3.0/lib/faraday/adapter/excon.rb:31:in `block in call'
  2021-02-04 03:26:14 +0000 [error]: #0 /usr/lib/ruby/gems/2.7.0/gems/faraday-1.3.0/lib/faraday/adapter.rb:60:in `connection'
  2021-02-04 03:26:14 +0000 [error]: #0 /usr/lib/ruby/gems/2.7.0/gems/faraday-1.3.0/lib/faraday/adapter/excon.rb:31:in `call'
  2021-02-04 03:26:14 +0000 [error]: #0 /usr/lib/ruby/gems/2.7.0/gems/faraday-1.3.0/lib/faraday/rack_builder.rb:154:in `build_response'
  2021-02-04 03:26:14 +0000 [error]: #0 /usr/lib/ruby/gems/2.7.0/gems/faraday-1.3.0/lib/faraday/connection.rb:492:in `run_request'
  2021-02-04 03:26:14 +0000 [error]: #0 /usr/lib/ruby/gems/2.7.0/gems/elasticsearch-transport-7.10.1/lib/elasticsearch/transport/transport/http/faraday.rb:40:in `block in perform_request'
  2021-02-04 03:26:14 +0000 [error]: #0 /usr/lib/ruby/gems/2.7.0/gems/elasticsearch-transport-7.10.1/lib/elasticsearch/transport/transport/base.rb:288:in `perform_request'
  2021-02-04 03:26:14 +0000 [error]: #0 /usr/lib/ruby/gems/2.7.0/gems/elasticsearch-transport-7.10.1/lib/elasticsearch/transport/transport/http/faraday.rb:37:in `perform_request'
  2021-02-04 03:26:14 +0000 [error]: #0 /usr/lib/ruby/gems/2.7.0/gems/elasticsearch-transport-7.10.1/lib/elasticsearch/transport/client.rb:182:in `perform_request'
  2021-02-04 03:26:14 +0000 [error]: #0 /usr/lib/ruby/gems/2.7.0/gems/elasticsearch-api-7.10.1/lib/elasticsearch/api/actions/info.rb:37:in `info'
  2021-02-04 03:26:14 +0000 [error]: #0 /usr/lib/ruby/gems/2.7.0/gems/fluent-plugin-elasticsearch-5.0.0/lib/fluent/plugin/out_elasticsearch.rb:495:in `detect_es_major_version'
  2021-02-04 03:26:14 +0000 [error]: #0 /usr/lib/ruby/gems/2.7.0/gems/fluent-plugin-elasticsearch-5.0.0/lib/fluent/plugin/out_elasticsearch.rb:487:in `block in handle_last_seen_es_major_version'
  2021-02-04 03:26:14 +0000 [error]: #0 /usr/lib/ruby/gems/2.7.0/gems/fluent-plugin-elasticsearch-5.0.0/lib/fluent/plugin/elasticsearch_index_template.rb:40:in `retry_operate'
  2021-02-04 03:26:14 +0000 [error]: #0 /usr/lib/ruby/gems/2.7.0/gems/fluent-plugin-elasticsearch-5.0.0/lib/fluent/plugin/out_elasticsearch.rb:484:in `handle_last_seen_es_major_version'
  2021-02-04 03:26:14 +0000 [error]: #0 /usr/lib/ruby/gems/2.7.0/gems/fluent-plugin-elasticsearch-5.0.0/lib/fluent/plugin/out_elasticsearch.rb:336:in `configure'
  2021-02-04 03:26:14 +0000 [error]: #0 /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.12.0/lib/fluent/plugin.rb:178:in `configure'
  2021-02-04 03:26:14 +0000 [error]: #0 /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.12.0/lib/fluent/agent.rb:132:in `add_match'
  2021-02-04 03:26:14 +0000 [error]: #0 /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.12.0/lib/fluent/agent.rb:74:in `block in configure'
  2021-02-04 03:26:14 +0000 [error]: #0 /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.12.0/lib/fluent/agent.rb:64:in `each'
  2021-02-04 03:26:14 +0000 [error]: #0 /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.12.0/lib/fluent/agent.rb:64:in `configure'
  2021-02-04 03:26:14 +0000 [error]: #0 /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.12.0/lib/fluent/root_agent.rb:146:in `configure'
  2021-02-04 03:26:14 +0000 [error]: #0 /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.12.0/lib/fluent/engine.rb:105:in `configure'
  2021-02-04 03:26:14 +0000 [error]: #0 /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.12.0/lib/fluent/engine.rb:80:in `run_configure'
  2021-02-04 03:26:14 +0000 [error]: #0 /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.12.0/lib/fluent/supervisor.rb:692:in `block in run_worker'
  2021-02-04 03:26:14 +0000 [error]: #0 /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.12.0/lib/fluent/supervisor.rb:943:in `main_process'
  2021-02-04 03:26:14 +0000 [error]: #0 /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.12.0/lib/fluent/supervisor.rb:684:in `run_worker'
  2021-02-04 03:26:14 +0000 [error]: #0 /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.12.0/lib/fluent/command/fluentd.rb:361:in `<top (required)>'
  2021-02-04 03:26:14 +0000 [error]: #0 /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
  2021-02-04 03:26:14 +0000 [error]: #0 /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
  2021-02-04 03:26:14 +0000 [error]: #0 /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.12.0/bin/fluentd:8:in `<top (required)>'
  2021-02-04 03:26:14 +0000 [error]: #0 /usr/bin/fluentd:23:in `load'
  2021-02-04 03:26:14 +0000 [error]: #0 /usr/bin/fluentd:23:in `<main>'
```

#### Expected Behavior or What you need to ask

With verify_ssl to true or false I would expect a connection to the elasticsearch cluster. 
...

#### Using Fluentd and ES plugin versions

* OS version

* Bare Metal or within Docker or Kubernetes or others? 
Kubernetes

* Fluentd v0.12 or v0.14/v1.0
  * paste result of ``fluentd --version`` or ``td-agent --version``
fluentd 1.12.0

* ES plugin 3.x.y/2.x.y or 1.x.y
  * paste boot log of fluentd or td-agent
  * paste result of ``fluent-gem list``, ``td-agent-gem list`` or your Gemfile.lock
fluent-plugin-elasticsearch (5.0.0)

* ES version 
7.10.2 

* ES template(s) (optional)

**Comment by cosmo0920** [comment]
@kenhys Could you take a glance in this issue?

**Comment by kenhys** [comment]
I'm not sure yet but there is a mismatch of cipher suites. The concern is:

* How ca file and client cert is generated
* What version of OpenSSL and cipher is used on Elasticsearch side (curl -v -o /dev/null https://ELASTIC_SERACH_SERVER/_license/basic_status)
* What version of OpenSSL and cipher is used on forwarder (fluentd) side?

**Comment by dhurng** [comment]
Hey @kenhys , thank you for taking a look.

1. the ca file and client cert is actually generated by our intenal cert manager service, it will inject peer/server/client certs for both elastic and fluentd. Ideally for mtls
2. OpenSSL Version is: OpenSSL 1.1.1g FIPS
Cipher output: 

* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: ...
  CApath: none
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, [no content] (0):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Request CERT (13):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, [no content] (0):
* TLSv1.3 (OUT), TLS handshake, Certificate (11):
* TLSv1.3 (OUT), TLS handshake, [no content] (0):
* TLSv1.3 (OUT), TLS handshake, CERT verify (15):
* TLSv1.3 (OUT), TLS handshake, [no content] (0):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: ...
*  start date: ...
*  expire date: ...
*  subjectAltName: ...
* ...
*  SSL certificate verify ok.
* Server auth using Basic with user 'test'
* TLSv1.3 (OUT), TLS app data, [no content] (0):
> GET /_license/basic_status HTTP/1.1
> Host: elasticsearch-master-external.hawking-elastic-search.hawking-elastic-search.einstein.dev1-uswest2.aws.sfdc.is:9200
> Authorization: Basic dGVzdDpUZW1wNG5vdw==
> User-Agent: curl/7.61.1
> Accept: */*
>
* TLSv1.3 (IN), TLS handshake, [no content] (0):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS app data, [no content] (0):
< HTTP/1.1 200 OK
< content-type: application/json; charset=UTF-8
< content-length: 33
<
* Connection #0 to host elasticsearch-master-external.hawking-elastic-search.hawking-elastic-search.einstein.dev1-uswest2.aws.sfdc.is left intact
{"eligible_to_start_basic":false}

3. Fluentd configuration: I am using the plugin which interesting enough the container doesnt seem to be using openssl. maybe there is another way to confirm this?

**Comment by kenhys** [comment]
Thanks, @dhurng 

> SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384

Then, `ssl_version TLSv1_3` will work for you?

**Comment by dhurng** [comment]
Hey @kenhys so interesting enough I actually tried to use the attributes for max/min version off SSL as well which I believe is this:

ssl_max_version TLSv1_3
ssl_min_version TLSv1_2

But it actually shows the same error. Same also goes for specifically using TLSv1_3 :/

Here is my error again: 

`2021-02-09 19:15:33 +0000 [error]: #0 unexpected error error_class=Faraday::SSLError error="SSL_read: sslv3 alert certificate unknown (OpenSSL::SSL::SSLError)"
  2021-02-09 19:15:33 +0000 [error]: #0 /usr/lib/ruby/2.7.0/openssl/buffering.rb:182:in `sysread_nonblock'
  2021-02-09 19:15:33 +0000 [error]: #0 /usr/lib/ruby/2.7.0/openssl/buffering.rb:182:in `read_nonblock'
  2021-02-09 19:15:33 +0000 [error]: #0 /usr/lib/ruby/gems/2.7.0/gems/excon-0.79.0/lib/excon/socket.rb:179:in `read_nonblock'
  2021-02-09 19:15:33 +0000 [error]: #0 /usr/lib/ruby/gems/2.7.0/gems/excon-0.79.0/lib/excon/socket.rb:63:in `readline'
  2021-02-09 19:15:33 +0000 [error]: #0 /usr/lib/ruby/gems/2.7.0/gems/excon-0.79.0/lib/excon/response.rb:64:in `block in parse'
  2021-02-09 19:15:33 +0000 [error]: #0 /usr/lib/ruby/gems/2.7.0/gems/excon-0.79.0/lib/excon/response.rb:63:in `loop'
  2021-02-09 19:15:33 +0000 [error]: #0 /usr/lib/ruby/gems/2.7.0/gems/excon-0.79.0/lib/excon/response.rb:63:in `parse'
  2021-02-09 19:15:33 +0000 [error]: #0 /usr/lib/ruby/gems/2.7.0/gems/excon-0.79.0/lib/excon/middlewares/response_parser.rb:7:in `response_call'
  2021-02-09 19:15:33 +0000 [error]: #0 /usr/lib/ruby/gems/2.7.0/gems/excon-0.79.0/lib/excon/connection.rb:456:in `response'
  2021-02-09 19:15:33 +0000 [error]: #0 /usr/lib/ruby/gems/2.7.0/gems/excon-0.79.0/lib/excon/connection.rb:287:in `request'
  2021-02-09 19:15:33 +0000 [error]: #0 /usr/lib/ruby/gems/2.7.0/gems/faraday-1.3.0/lib/faraday/adapter/excon.rb:31:in `block in call'
  2021-02-09 19:15:33 +0000 [error]: #0 /usr/lib/ruby/gems/2.7.0/gems/faraday-1.3.0/lib/faraday/adapter.rb:60:in `connection'
  2021-02-09 19:15:33 +0000 [error]: #0 /usr/lib/ruby/gems/2.7.0/gems/faraday-1.3.0/lib/faraday/adapter/excon.rb:31:in `call'
  2021-02-09 19:15:33 +0000 [error]: #0 /usr/lib/ruby/gems/2.7.0/gems/faraday-1.3.0/lib/faraday/rack_builder.rb:154:in `build_response'
  2021-02-09 19:15:33 +0000 [error]: #0 /usr/lib/ruby/gems/2.7.0/gems/faraday-1.3.0/lib/faraday/connection.rb:492:in `run_request'
  2021-02-09 19:15:33 +0000 [error]: #0 /usr/lib/ruby/gems/2.7.0/gems/elasticsearch-transport-7.10.1/lib/elasticsearch/transport/transport/http/faraday.rb:40:in `block in perform_request'
  2021-02-09 19:15:33 +0000 [error]: #0 /usr/lib/ruby/gems/2.7.0/gems/elasticsearch-transport-7.10.1/lib/elasticsearch/transport/transport/base.rb:288:in `perform_request'
  2021-02-09 19:15:33 +0000 [error]: #0 /usr/lib/ruby/gems/2.7.0/gems/elasticsearch-transport-7.10.1/lib/elasticsearch/transport/transport/http/faraday.rb:37:in `perform_request'
  2021-02-09 19:15:33 +0000 [error]: #0 /usr/lib/ruby/gems/2.7.0/gems/elasticsearch-transport-7.10.1/lib/elasticsearch/transport/client.rb:182:in `perform_request'
  2021-02-09 19:15:33 +0000 [error]: #0 /usr/lib/ruby/gems/2.7.0/gems/elasticsearch-api-7.10.1/lib/elasticsearch/api/actions/info.rb:37:in `info'
  2021-02-09 19:15:33 +0000 [error]: #0 /usr/lib/ruby/gems/2.7.0/gems/fluent-plugin-elasticsearch-5.0.0/lib/fluent/plugin/out_elasticsearch.rb:495:in `detect_es_major_version'
  2021-02-09 19:15:33 +0000 [error]: #0 /usr/lib/ruby/gems/2.7.0/gems/fluent-plugin-elasticsearch-5.0.0/lib/fluent/plugin/out_elasticsearch.rb:487:in `block in handle_last_seen_es_major_version'
  2021-02-09 19:15:33 +0000 [error]: #0 /usr/lib/ruby/gems/2.7.0/gems/fluent-plugin-elasticsearch-5.0.0/lib/fluent/plugin/elasticsearch_index_template.rb:40:in `retry_operate'
  2021-02-09 19:15:33 +0000 [error]: #0 /usr/lib/ruby/gems/2.7.0/gems/fluent-plugin-elasticsearch-5.0.0/lib/fluent/plugin/out_elasticsearch.rb:484:in `handle_last_seen_es_major_version'
  2021-02-09 19:15:33 +0000 [error]: #0 /usr/lib/ruby/gems/2.7.0/gems/fluent-plugin-elasticsearch-5.0.0/lib/fluent/plugin/out_elasticsearch.rb:336:in `configure'
  2021-02-09 19:15:33 +0000 [error]: #0 /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.12.0/lib/fluent/plugin.rb:178:in `configure'
  2021-02-09 19:15:33 +0000 [error]: #0 /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.12.0/lib/fluent/agent.rb:132:in `add_match'
  2021-02-09 19:15:33 +0000 [error]: #0 /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.12.0/lib/fluent/agent.rb:74:in `block in configure'
  2021-02-09 19:15:33 +0000 [error]: #0 /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.12.0/lib/fluent/agent.rb:64:in `each'
  2021-02-09 19:15:33 +0000 [error]: #0 /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.12.0/lib/fluent/agent.rb:64:in `configure'
  2021-02-09 19:15:33 +0000 [error]: #0 /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.12.0/lib/fluent/root_agent.rb:146:in `configure'
  2021-02-09 19:15:33 +0000 [error]: #0 /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.12.0/lib/fluent/engine.rb:105:in `configure'
  2021-02-09 19:15:33 +0000 [error]: #0 /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.12.0/lib/fluent/engine.rb:80:in `run_configure'
  2021-02-09 19:15:33 +0000 [error]: #0 /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.12.0/lib/fluent/supervisor.rb:692:in `block in run_worker'
  2021-02-09 19:15:33 +0000 [error]: #0 /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.12.0/lib/fluent/supervisor.rb:943:in `main_process'
  2021-02-09 19:15:33 +0000 [error]: #0 /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.12.0/lib/fluent/supervisor.rb:684:in `run_worker'
  2021-02-09 19:15:33 +0000 [error]: #0 /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.12.0/lib/fluent/command/fluentd.rb:361:in `<top (required)>'
  2021-02-09 19:15:33 +0000 [error]: #0 /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
  2021-02-09 19:15:33 +0000 [error]: #0 /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
  2021-02-09 19:15:33 +0000 [error]: #0 /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.12.0/bin/fluentd:8:in `<top (required)>'
  2021-02-09 19:15:33 +0000 [error]: #0 /usr/bin/fluentd:23:in `load'
  2021-02-09 19:15:33 +0000 [error]: #0 /usr/bin/fluentd:23:in `<main>'`

I went ahead and also tried with ssl_verify false but still same thing. 

<match **>
  @type elasticsearch
  include_tag_key true
  scheme https
  host ...
  user "test"
  password "Temp4now"
  ssl_version TLSv1_3
  ca_file /etc/.../cacerts.pem
  client_cert /etc/.../client.pem
  client_key /etc/.../client-key.pem
  ssl_verify false
  logstash_format true
</match>

**Comment by kenhys** [comment]
I've tried to reproduce this issue on some distributions, but there is no luck.
If fluentd forwarder is reproducible, it may help.

* debian/unstable (not reproducible)
* debian/buster (not reproducible)
* ubuntu/bionic (not reproducible)
* ubuntu/xenial (not reproducible)

For the record:

Setup one node es01 with certs create-certs.yml. ref. https://www.elastic.co/guide/en/elasticsearch/reference/current/configuring-tls-docker.html

Run elasticsearch like this.

```
% cat runes.sh
export CERTS_DIR=/usr/share/elasticsearch/config/certificates
docker run \
       --name es \
       --network es_default \
       -p 9200:9200 \
       -p 9300:9300 \
       -v $PWD/certs:/usr/share/elasticsearch/config/certificates \
       -e ELASTIC_PASSWORD=changeme \
       -e xpack.security.enabled=true \
       -e xpack.monitoring.collection.enabled=true \
       -e xpack.security.transport.ssl.enabled=true \
       -e xpack.security.transport.ssl.key=$CERTS_DIR/es01/es01.key \
       -e xpack.security.transport.ssl.certificate=$CERTS_DIR/es01/es01.crt \
       -e xpack.security.transport.ssl.certificate_authorities=$CERTS_DIR/ca/ca.crt \
       -e xpack.security.http.ssl.enabled=true \
       -e xpack.security.http.ssl.key=$CERTS_DIR/es01/es01.key \
       -e xpack.security.http.ssl.certificate=$CERTS_DIR/es01/es01.crt \
       -e xpack.security.http.ssl.certificate_authorities=$CERTS_DIR/ca/ca.crt \
       -e "discovery.type=single-node" docker.elastic.co/elasticsearch/elasticsearch:7.10.2
```

In this situation, access from host: `curl -k -v https://localhost:9200` 

```
% LANG=C curl -k -v -u elastic:changeme https://localhost:9200
*   Trying ::1:9200...
* connect to ::1 port 9200 failed: Connection refused
*   Trying 127.0.0.1:9200...
* Connected to localhost (127.0.0.1) port 9200 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: CN=es01
*  start date: Feb 10 02:05:11 2021 GMT
*  expire date: Feb 10 02:05:11 2024 GMT
*  issuer: CN=Elastic Certificate Tool Autogenerated CA
*  SSL certificate verify result: unable to get local issuer certificate (20), continuing anyway.
* Server auth using Basic with user 'elastic'
> GET / HTTP/1.1
> Host: localhost:9200
> Authorization: Basic ZWxhc3RpYzpjaGFuZ2VtZQ==
> User-Agent: curl/7.74.0
> Accept: */*
> 
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< content-type: application/json; charset=UTF-8
< content-length: 542
< 
{
  "name" : "fbdc2183dc56",
  "cluster_name" : "docker-cluster",
  "cluster_uuid" : "ZdP6f2RBSpeloYe3mLY59g",
  "version" : {
    "number" : "7.10.2",
    "build_flavor" : "default",
    "build_type" : "docker",
    "build_hash" : "747e1cc71def077253878a59143c1f785afa92b9",
    "build_date" : "2021-01-13T00:42:12.435326Z",
    "build_snapshot" : false,
    "lucene_version" : "8.7.0",
    "minimum_wire_compatibility_version" : "6.8.0",
    "minimum_index_compatibility_version" : "6.0.0-beta1"
  },
  "tagline" : "You Know, for Search"
}
* Connection #0 to host localhost left intact
```

TLSv1.3 is used.

```
% curl --key ./certs/es01/es01.key --cert ./certs/es01/es01.crt --cacert ./certs/ca/ca.crt  -u elastic:changeme ./certs/ca/ca.crt https://localhost:9200
curl: (6) Could not resolve host: .
{
  "name" : "fbdc2183dc56",
  "cluster_name" : "docker-cluster",
  "cluster_uuid" : "ZdP6f2RBSpeloYe3mLY59g",
  "version" : {
    "number" : "7.10.2",
    "build_flavor" : "default",
    "build_type" : "docker",
    "build_hash" : "747e1cc71def077253878a59143c1f785afa92b9",
    "build_date" : "2021-01-13T00:42:12.435326Z",
    "build_snapshot" : false,
    "lucene_version" : "8.7.0",
    "minimum_wire_compatibility_version" : "6.8.0",
    "minimum_index_compatibility_version" : "6.0.0-beta1"
  },
  "tagline" : "You Know, for Search"
}
```

certs pair is also works.

Then, launch fluentd (1.12.0) with fluent-plugin-elasticsearch(5.0.0). 

```
<source>
  @type sample
  sample {"hello":"world"}
  tag sample
</source>

<match **>
  @type elasticsearch
  include_tag_key true
  scheme https
  host localhost
  port 9200
  user "elastic"
  password "changeme"
  ssl_version TLSv1_2
  ca_file ./certs/ca/ca.crt
  client_cert ./certs/es01/es01.crt
  client_key ./certs/es01/es01.key
  ssl_verify true
  logstash_format true
  index_name fluentd
  type_name fluentd
</match>
```

It has no problem.

I've tried some other distributions.

# Case 2. fluentd on buster

Not reproducible on buster docker container.

docker run -v $PWD:/debian --network es_default -it debian:buster

```
apt update -y
apt upgrade -y
apt install -y gcc make ruby-dev libmsgpack-dev inetutils-ping curl vim-tiny
gem install -N fluentd fluent-plugin-elasticsearch
```

Set /etc/hosts for es01 (172.22.0.3) (curl -k -u elastic:changeme https://es01:9200/ works for testing)

```
<source>
  @type sample
  sample {"hello":"world"}
  tag sample
</source>

<match **>
  @type elasticsearch
  include_tag_key true
  scheme https
  host es01
  port 9200
  user "elastic"
  password "changeme"
  ssl_version TLSv1_2
  ssl_verify true
  ca_file /debian/certs/ca/ca.crt
  client_cert /debian/certs/es01/es01.crt
  client_key /debian/certs/es01/es01.key
  logstash_format true
  index_name fluentd
  type_name fluentd
</match>
```

# Case 3. fluentd on bionic

Same as on buster

docker run -v $PWD:/debian --network es_default -it ubuntu:bionic


# Case 4. fluentd on xenial

docker run -v $PWD:/debian --network es_default -it ubuntu:xenial

Same as on buster
Ruby is too old, so I've used rvm instead.

**Comment by dhurng** [comment]
Hey @kenhys Thank you for the detailed breakdown, I will go ahead and go through this and provide updates when I get around to it. 

thank you!
