### ISSUE TITLE
"no implicit conversion of nil into String" error

### ISSUE THREAD

**Issue by tbragin** [uken/fluent-plugin-elasticsearch#88]
I keep getting these errors in the log file. 

```
2015-01-22 15:27:35 -0800 [warn]: temporarily failed to flush the buffer. next_retry=2015-01-22 15:27:32 -0800 error_class="TypeError" error="no implicit conversion of nil into String" instance=70364703686720
  2015-01-22 15:27:35 -0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/patron-0.4.18/lib/patron/session.rb:223:in `handle_request'
  2015-01-22 15:27:35 -0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/patron-0.4.18/lib/patron/session.rb:223:in `request'
  2015-01-22 15:27:35 -0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/faraday-0.9.1/lib/faraday/adapter/patron.rb:33:in `call'
  2015-01-22 15:27:35 -0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/faraday-0.9.1/lib/faraday/rack_builder.rb:139:in `build_response'
  2015-01-22 15:27:35 -0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/faraday-0.9.1/lib/faraday/connection.rb:377:in `run_request'
  2015-01-22 15:27:35 -0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/elasticsearch-transport-1.0.6/lib/elasticsearch/transport/transport/http/faraday.rb:21:in `block in perform_request'
  2015-01-22 15:27:35 -0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/elasticsearch-transport-1.0.6/lib/elasticsearch/transport/transport/base.rb:187:in `call'
  2015-01-22 15:27:35 -0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/elasticsearch-transport-1.0.6/lib/elasticsearch/transport/transport/base.rb:187:in `perform_request'
  2015-01-22 15:27:35 -0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/elasticsearch-transport-1.0.6/lib/elasticsearch/transport/transport/http/faraday.rb:20:in `perform_request'
  2015-01-22 15:27:35 -0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/elasticsearch-transport-1.0.6/lib/elasticsearch/transport/client.rb:111:in `perform_request'
  2015-01-22 15:27:35 -0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/elasticsearch-api-1.0.6/lib/elasticsearch/api/actions/ping.rb:19:in `ping'
  2015-01-22 15:27:35 -0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-elasticsearch-0.7.0/lib/fluent/plugin/out_elasticsearch.rb:62:in `client'
  2015-01-22 15:27:35 -0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-elasticsearch-0.7.0/lib/fluent/plugin/out_elasticsearch.rb:168:in `send'
  2015-01-22 15:27:35 -0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-elasticsearch-0.7.0/lib/fluent/plugin/out_elasticsearch.rb:161:in `write'
  2015-01-22 15:27:35 -0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.10.55/lib/fluent/buffer.rb:296:in `write_chunk'
  2015-01-22 15:27:35 -0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.10.55/lib/fluent/buffer.rb:276:in `pop'
  2015-01-22 15:27:35 -0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.10.55/lib/fluent/output.rb:311:in `try_flush'
  2015-01-22 15:27:35 -0800 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.10.55/lib/fluent/output.rb:132:in `run'
```

environment:
* Mac OSX 10.9.5
* fluentd version 0.10.55
* fluent-plugin-elasticsearch verson 0.7.0
* elasticsearch version 1.4.1
* running on localhost, port 9200
* a local Logstash instance has no trouble connecting and writing to it over HTTP
* debug output seems to suggest that file input gets parsed without issues

config
```
####
## Output descriptions:
##
<match tb.logs>
  type elasticsearch
  host localhost
  port 9200
  logstash_format true
  logstash_prefix fluentd
</match>
...
## File input
## read apache logs continuously and tags td.apache.access
<source>
  type tail
  format apache
  path /Users/tanya/logs
  tag tb.logs
  read_from_head true
</source>
```

**Comment by pitr** [comment]
Is this still a problem? Is there a chance this sends nil to fluentd-plugin-elasticsearch?

**Comment by pitr** [comment]
Oh, this is on `es.ping`! The exception is thrown from patron's C code. Please update to v0.8.0 to see if this is still an issue. We switched to use excon gem.

**Comment by gtmtech** [comment]
I am also getting this, using excon gem

2015-10-24 16:08:06 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2015-10-24 16:08:07 +0000 error_class="TypeError" error="no implicit conversion of nil into String" plugin_id="output_from_docker"
  2015-10-24 16:08:06 +0000 [warn]: /home/ubuntu/ruby/lib/ruby/gems/2.2.0/gems/excon-0.45.4/lib/excon/connection.rb:89:in `initialize'
  2015-10-24 16:08:06 +0000 [warn]: /home/ubuntu/ruby/lib/ruby/gems/2.2.0/gems/excon-0.45.4/lib/excon.rb:126:in `new'
  2015-10-24 16:08:06 +0000 [warn]: /home/ubuntu/ruby/lib/ruby/gems/2.2.0/gems/excon-0.45.4/lib/excon.rb:126:in `new'
  2015-10-24 16:08:06 +0000 [warn]: /home/ubuntu/ruby/lib/ruby/gems/2.2.0/gems/faraday-0.9.2/lib/faraday/adapter/excon.rb:53:in `call'
  2015-10-24 16:08:06 +0000 [warn]: /home/ubuntu/ruby/lib/ruby/gems/2.2.0/gems/faraday-0.9.2/lib/faraday/rack_builder.rb:139:in `build_response'
  2015-10-24 16:08:06 +0000 [warn]: /home/ubuntu/ruby/lib/ruby/gems/2.2.0/gems/faraday-0.9.2/lib/faraday/connection.rb:377:in `run_request'
  2015-10-24 16:08:06 +0000 [warn]: /home/ubuntu/ruby/lib/ruby/gems/2.2.0/gems/elasticsearch-transport-1.0.14/lib/elasticsearch/transport/transport/http/faraday.rb:21:in `block in perform_request'
  2015-10-24 16:08:06 +0000 [warn]: /home/ubuntu/ruby/lib/ruby/gems/2.2.0/gems/elasticsearch-transport-1.0.14/lib/elasticsearch/transport/transport/base.rb:191:in `call'
  2015-10-24 16:08:06 +0000 [warn]: /home/ubuntu/ruby/lib/ruby/gems/2.2.0/gems/elasticsearch-transport-1.0.14/lib/elasticsearch/transport/transport/base.rb:191:in `perform_request'
  2015-10-24 16:08:06 +0000 [warn]: /home/ubuntu/ruby/lib/ruby/gems/2.2.0/gems/elasticsearch-transport-1.0.14/lib/elasticsearch/transport/transport/http/faraday.rb:20:in `perform_request'
  2015-10-24 16:08:06 +0000 [warn]: /home/ubuntu/ruby/lib/ruby/gems/2.2.0/gems/elasticsearch-transport-1.0.14/lib/elasticsearch/transport/client.rb:119:in `perform_request'
  2015-10-24 16:08:06 +0000 [warn]: /home/ubuntu/ruby/lib/ruby/gems/2.2.0/gems/elasticsearch-api-1.0.14/lib/elasticsearch/api/actions/ping.rb:20:in `block in ping'
  2015-10-24 16:08:06 +0000 [warn]: /home/ubuntu/ruby/lib/ruby/gems/2.2.0/gems/elasticsearch-api-1.0.14/lib/elasticsearch/api/utils.rb:191:in `__rescue_from_not_found'
  2015-10-24 16:08:06 +0000 [warn]: /home/ubuntu/ruby/lib/ruby/gems/2.2.0/gems/elasticsearch-api-1.0.14/lib/elasticsearch/api/actions/ping.rb:19:in `ping'
  2015-10-24 16:08:06 +0000 [warn]: /home/ubuntu/ruby/lib/ruby/gems/2.2.0/gems/fluent-plugin-elasticsearch-1.0.0/lib/fluent/plugin/out_elasticsearch.rb:64:in `client'
  2015-10-24 16:08:06 +0000 [warn]: /home/ubuntu/ruby/lib/ruby/gems/2.2.0/gems/fluent-plugin-elasticsearch-1.0.0/lib/fluent/plugin/out_elasticsearch.rb:171:in `rescue in send'
  2015-10-24 16:08:06 +0000 [warn]: /home/ubuntu/ruby/lib/ruby/gems/2.2.0/gems/fluent-plugin-elasticsearch-1.0.0/lib/fluent/plugin/out_elasticsearch.rb:169:in `send'
  2015-10-24 16:08:06 +0000 [warn]: /home/ubuntu/ruby/lib/ruby/gems/2.2.0/gems/fluent-plugin-elasticsearch-1.0.0/lib/fluent/plugin/out_elasticsearch.rb:163:in `write'
  2015-10-24 16:08:06 +0000 [warn]: /home/ubuntu/ruby/lib/ruby/gems/2.2.0/gems/fluentd-0.12.15/lib/fluent/buffer.rb:325:in `write_chunk'
  2015-10-24 16:08:06 +0000 [warn]: /home/ubuntu/ruby/lib/ruby/gems/2.2.0/gems/fluentd-0.12.15/lib/fluent/buffer.rb:304:in `pop'
  2015-10-24 16:08:06 +0000 [warn]: /home/ubuntu/ruby/lib/ruby/gems/2.2.0/gems/fluentd-0.12.15/lib/fluent/output.rb:321:in `try_flush'
  2015-10-24 16:08:06 +0000 [warn]: /home/ubuntu/ruby/lib/ruby/gems/2.2.0/gems/fluentd-0.12.15/lib/fluent/output.rb:140:in `run'

**Comment by pitr** [comment]
@gtmtech can you share your config?

**Comment by goller** [comment]
I think I understand @gtmtech 's issue.
If you don't have excon installed then you get his error.

` excon_options = { client_key: @client_key, client_cert: @client_cert, client_key_pass: @client_key_pass }`

**Comment by yehosef** [comment]
installed `sudo gem install excon` and it works now - thanks!
