### ISSUE TITLE
Unable to store logs to Amazon Elasticsearch. Forbidden error="[403] Authorization header requires 'Credential' parameter. Authorization header requires 'Signature' parameter. Authorization header requires 'SignedHeaders' parameter. Authorization header requires existence of either a 'X-Amz-Date' or a 'Date' header.

### ISSUE THREAD

**Issue by prashantcsutar** [uken/fluent-plugin-elasticsearch#893]
#### Problem
We are getting below error while connecting to Amazon Elasticsearch. As our application is hosted in AWS we are using Amazon Elasticsearch to store logs but we are getting below error:

```
2021-06-11 11:29:12 +0000 [error]: #0 unexpected error error_class=Elasticsearch::Transport::Transport::Errors::Forbidden error="[403] {\"message\":\"Authorization header requires 'Credential' parameter. Authorization header requires 'Signature' parameter. Authorization header requires 'SignedHeaders' parameter. Authorization header requires existence of either a 'X-Amz-Date' or a 'Date' header. Authorization=Basic Og==\"}"
2021-06-11 11:29:12 +0000 [error]: #0 /fluentd/vendor/bundle/ruby/2.7.0/gems/elasticsearch-transport-6.8.2/lib/elasticsearch/transport/transport/base.rb:208:in `__raise_transport_error'
2021-06-11 11:29:12 +0000 [error]: #0 /fluentd/vendor/bundle/ruby/2.7.0/gems/elasticsearch-transport-6.8.2/lib/elasticsearch/transport/transport/base.rb:333:in `perform_request'
```

#### Steps to replicate

We have created custom Fluentd image as per our requirements. I have uploaded that image to docker hub: `prashantcsutar/fluentd-deamonset-elasticsearch:v1.11-alpine-elasticsearch6`

Our configurations are:

```
<store>
  @type              elasticsearch
  @id                out_mosaic_es
  @log_level         info
  include_tag_key    true
  host               "hostname"
  port               "443"
  path               "#{ENV['FLUENT_ELASTICSEARCH_PATH']}"
  scheme             "443"
  ssl_verify         "#{ENV['FLUENT_ELASTICSEARCH_SSL_VERIFY'] || 'true'}"
  ssl_version        "#{ENV['FLUENT_ELASTICSEARCH_SSL_VERSION'] || 'TLSv1'}"
  user               ""
  password           ""
  reload_connections "#{ENV['FLUENT_ELASTICSEARCH_RELOAD_CONNECTIONS'] || 'false'}"
  reconnect_on_error "#{ENV['FLUENT_ELASTICSEARCH_RECONNECT_ON_ERROR'] || 'true'}"
  reload_on_failure  "#{ENV['FLUENT_ELASTICSEARCH_RELOAD_ON_FAILURE'] || 'true'}"
  log_es_400_reason  "#{ENV['FLUENT_ELASTICSEARCH_LOG_ES_400_REASON'] || 'false'}"
  logstash_prefix    "#{ENV['FLUENT_ELASTICSEARCH_LOGSTASH_PREFIX'] || 'logstash'}"
  logstash_format    "#{ENV['FLUENT_ELASTICSEARCH_LOGSTASH_FORMAT'] || 'false'}"
  index_name         "#{ENV['FLUENT_ELASTICSEARCH_LOGSTASH_INDEX_NAME'] || 'logstash'}"
  type_name          "#{ENV['FLUENT_ELASTICSEARCH_LOGSTASH_TYPE_NAME'] || 'fluentd'}"
  <buffer>
    flush_thread_count   "#{ENV['FLUENT_ELASTICSEARCH_BUFFER_FLUSH_THREAD_COUNT'] || '8'}"
    flush_interval       "#{ENV['FLUENT_ELASTICSEARCH_BUFFER_FLUSH_INTERVAL'] || '5s'}"
    chunk_limit_size     "#{ENV['FLUENT_ELASTICSEARCH_BUFFER_CHUNK_LIMIT_SIZE'] || '2M'}"
    total_limit_size     "#{ENV['FLUENT_ELASTICSEARCH_BUFFER_TOTAL_LIMIT_SIZE'] || '512MB'}"
    chunk_full_threshold 0.95
    flush_mode           interval
    overflow_action      throw_exception
    retry_max_interval   "#{ENV['FLUENT_ELASTICSEARCH_BUFFER_RETRY_MAX_INTERVAL'] || '30'}"
    retry_forever        true
  </buffer>
</store>
```

Our Elasticsearch do not have any user name and password. Also we are able to access Elasticsearch inside the pod using `curl`. As we are getting this issue we are not able to use Amazon Elasticsearch in our project.

#### Expected Behavior or What you need to ask
There is problem due to `Authorization` header. Our Elasticsearch doesn't have any user name or password. Is there any way by which we should restrict `Authorization` header from getting added while connecting to Elasticsearch?

We have tested amazon Elasticsearch with `curl` without user name and password its working. But when we added empty user name & password in `curl` we faced similar error.

#### Using Fluentd and ES plugin versions

* OS version- Alpine 3.12
* Docker and Kubernetes
* Fluentd v1.11.5
  * ``fluentd 1.11.5``
* ES plugin 4.2.2
* Gem List
 ```
addressable (2.7.0)
async (1.27.0)
async-http (0.50.7)
async-io (1.27.7)
async-pool (0.3.3)
benchmark (default: 0.1.0)
bigdecimal (1.4.4)
bundler (2.1.4)
cgi (default: 0.1.0)
concurrent-ruby (1.1.7)
console (1.10.1)
cool.io (1.7.0)
csv (default: 3.1.2)
date (default: 3.0.0)
delegate (default: 0.1.0)
did_you_mean (default: 1.4.0)
domain_name (0.5.20190701)
elasticsearch (6.8.2)
elasticsearch-api (6.8.2)
elasticsearch-transport (6.8.2)
etc (default: 1.1.0)
excon (0.78.0)
ext_monitor (0.1.2)
faraday (1.1.0)
fcntl (default: 1.0.0)
ffi (1.13.1)
ffi-compiler (1.0.1)
fiber-local (1.0.0)
fileutils (default: 1.4.1)
fluent-config-regexp-type (1.0.0)
fluent-plugin-concat (2.4.0)
fluent-plugin-detect-exceptions (0.0.13)
fluent-plugin-elasticsearch (4.2.2)
fluent-plugin-grok-parser (2.6.2)
fluent-plugin-json-in-json-2 (1.0.2)
fluent-plugin-kubernetes_metadata_filter (2.5.2)
fluent-plugin-multi-format-parser (1.0.0)
fluent-plugin-out-http (1.3.3)
fluent-plugin-prometheus (1.6.1)
fluent-plugin-record-modifier (2.0.1)
fluent-plugin-rewrite-tag-filter (2.2.0)
fluent-plugin-systemd (1.0.2)
fluentd (1.11.5)
forwardable (default: 1.3.1)
getoptlong (default: 0.1.0)
http (4.4.1)
http-accept (1.7.0)
http-cookie (1.0.3)
http-form_data (2.3.0)
http-parser (1.2.2)
http_parser.rb (0.6.0)
ipaddr (default: 1.2.2)
irb (default: 1.2.3)
json (2.3.0)
jsonpath (1.0.6)
kubeclient (4.9.1)
logger (default: 1.4.2)
lru_redux (1.1.0)
matrix (default: 0.2.0)
mime-types (3.3.1)
mime-types-data (3.2020.1104)
msgpack (1.3.3)
multi_json (1.15.0)
multipart-post (2.1.1)
mutex_m (default: 0.1.0)
net-pop (default: 0.1.0)
net-smtp (default: 0.1.0)
netrc (0.11.0)
nio4r (2.5.4)
observer (default: 0.1.0)
oj (3.8.1)
open3 (default: 0.1.0)
openssl (default: 2.1.2)
ostruct (default: 0.2.0)
prime (default: 0.1.1)
prometheus-client (0.9.0)
protocol-hpack (1.4.2)
protocol-http (0.15.1)
protocol-http1 (0.10.3)
protocol-http2 (0.11.6)
pstore (default: 0.1.0)
psych (default: 3.1.0)
public_suffix (4.0.6)
quantile (0.2.1)
racc (default: 1.4.16)
rake (13.0.1)
readline (default: 0.0.2)
readline-ext (default: 0.1.0)
recursive-open-struct (1.1.3)
reline (default: 0.1.3)
rest-client (2.1.0)
rexml (default: 3.2.3)
rss (default: 0.2.8)
ruby2_keywords (0.0.2)
serverengine (2.2.2)
sigdump (0.2.4)
singleton (default: 0.1.0)
stringio (default: 0.1.0)
strptime (0.2.5)
strscan (default: 1.0.3)
systemd-journal (1.3.3)
timeout (default: 0.1.0)
timers (4.3.2)
tracer (default: 0.1.0)
tzinfo (2.0.3)
tzinfo-data (1.2020.4)
unf (0.1.4)
unf_ext (0.0.7.7)
uri (default: 0.10.0)
webrick (default: 1.6.0)
yajl-ruby (1.4.1)
yaml (default: 0.1.0)
zlib (default: 1.1.0)
```
* ES version - `6.8.0`

**Comment by cosmo0920** [comment]
This is because this plugin does not sign request with SigV4.
Try https://github.com/atomita/fluent-plugin-aws-elasticsearch-service.
