### ISSUE TITLE
Elasticsearch 8.0 release breaks plugin (cannot load such file -- elasticsearch/transport/transport/connections/selector)

### ISSUE THREAD

**Issue by nnul** [uken/fluent-plugin-elasticsearch#944]
(check apply)
- [x] read [the contribution guideline](https://github.com/uken/fluent-plugin-elasticsearch/blob/master/CONTRIBUTING.md)
- [ ] (optional) already reported 3rd party upstream repository or mailing list if you use k8s addon or helm charts.

#### Problem

The release of the Elasticsearch 8.0 ruby package has broken this plugin. The Gemspec does not version the elasticsearch dependency and v8.0 has breaking changes related to the transport code. The easy fix is to version the elasticsearch gem dependency to v7.x until v8.x support is added.

Callstack:
```x
 /usr/local/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:85:in `require': cannot load such file -- elasticsearch/transport/transport/connections/selector (LoadError)
      from /usr/local/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:85:in `require'
      from /usr/local/bundle/gems/fluent-plugin-elasticsearch-5.1.5/lib/fluent/plugin/elasticsearch_fallback_selector.rb:1:in `<top (required)>'
      from /usr/local/bundle/gems/fluent-plugin-elasticsearch-5.1.5/lib/fluent/plugin/out_elasticsearch.rb:32:in `require_relative'
      from /usr/local/bundle/gems/fluent-plugin-elasticsearch-5.1.5/lib/fluent/plugin/out_elasticsearch.rb:32:in `<top (required)>'
      from /usr/local/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:85:in `require'
      from /usr/local/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:85:in `require'
      from /usr/local/bundle/gems/fluentd-1.14.0/lib/fluent/registry.rb:102:in `block in search'
      from /usr/local/bundle/gems/fluentd-1.14.0/lib/fluent/registry.rb:99:in `each'
      from /usr/local/bundle/gems/fluentd-1.14.0/lib/fluent/registry.rb:99:in `search'
      from /usr/local/bundle/gems/fluentd-1.14.0/lib/fluent/registry.rb:44:in `lookup'
      from /usr/local/bundle/gems/fluentd-1.14.0/lib/fluent/plugin.rb:169:in `new_impl'
      from /usr/local/bundle/gems/fluentd-1.14.0/lib/fluent/plugin.rb:114:in `new_output'
      from /usr/local/bundle/gems/fluentd-1.14.0/lib/fluent/plugin/multi_output.rb:108:in `block in configure'
      from /usr/local/bundle/gems/fluentd-1.14.0/lib/fluent/plugin/multi_output.rb:99:in `each'
      from /usr/local/bundle/gems/fluentd-1.14.0/lib/fluent/plugin/multi_output.rb:99:in `configure'
      from /usr/local/bundle/gems/fluentd-1.14.0/lib/fluent/plugin/out_copy.rb:39:in `configure'
      from /usr/local/bundle/gems/fluentd-1.14.0/lib/fluent/plugin.rb:187:in `configure'
      from /usr/local/bundle/gems/fluentd-1.14.0/lib/fluent/agent.rb:132:in `add_match'
      from /usr/local/bundle/gems/fluentd-1.14.0/lib/fluent/agent.rb:74:in `block in configure'
      from /usr/local/bundle/gems/fluentd-1.14.0/lib/fluent/agent.rb:64:in `each'
      from /usr/local/bundle/gems/fluentd-1.14.0/lib/fluent/agent.rb:64:in `configure'
      from /usr/local/bundle/gems/fluentd-1.14.0/lib/fluent/root_agent.rb:149:in `configure'
      from /usr/local/bundle/gems/fluentd-1.14.0/lib/fluent/engine.rb:105:in `configure'
      from /usr/local/bundle/gems/fluentd-1.14.0/lib/fluent/engine.rb:80:in `run_configure'
      from /usr/local/bundle/gems/fluentd-1.14.0/lib/fluent/supervisor.rb:665:in `run_supervisor'
      from /usr/local/bundle/gems/fluentd-1.14.0/lib/fluent/command/fluentd.rb:352:in `<top (required)>'
      from /usr/local/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:85:in `require'
      from /usr/local/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:85:in `require'
      from /usr/local/bundle/gems/fluentd-1.14.0/bin/fluentd:15:in `<top (required)>'
      from /usr/local/bundle/bin/fluentd:23:in `load'
      from /usr/local/bundle/bin/fluentd:23:in `<main>'
```

#### Steps to replicate

Run the fluentd plugin from a new install.

#### Expected Behavior or What you need to ask

The plugin runs as expected.

#### Using Fluentd and ES plugin versions

Affects all versions and all platforms

**Comment by nnul** [comment]
As a work around you can force uninstall the elasticsearch gem and install v7.17.0 as a work around.

```x
gem uninstall -I elasticsearch
gem install elasticsearch -v 7.17.0
```

**Comment by nnul** [comment]
I believe this is the root cause and should instead be versioned:
https://github.com/uken/fluent-plugin-elasticsearch/blob/9cafce0c01fa9e21b36784ac82e9526d2f4767e4/fluent-plugin-elasticsearch.gemspec#L27

**Comment by nnul** [comment]
Additional information on the release that triggered this: https://github.com/elastic/elasticsearch-ruby/releases/tag/v8.0.0

**Comment by PhotoTeeborChoka** [comment]
Hi @nnul can you prepare a PR?

**Comment by kvokka** [comment]
Pls, keep in mind that gem CI is falsely green on master, cos elasticsearch-ruby gem was released after the latest CI execution.

**Comment by pershin-artem-gene** [comment]
Recently, workaround, mentioned here broke unexpectedly:
``` 
sudo gem install fluent-plugin-elasticsearch fluent-plugin-grok-parser \
                             fluent-plugin-rewrite-tag-filter fluent-plugin-concat \
                             fluent-plugin-multi-format-parser \
 && sudo gem uninstall -I elasticsearch \
 && sudo gem install elasticsearch:7.17.0 elasticsearch-xpack
 ```
 
 Now, it fails with the following error on the docker (`fluentd`) startup:
 ```
 {"time":"2022-02-24T14:39:37.192Z","level":"error","message":"unexpected error error_class=RuntimeError error=\"elasticsearch-xpack gem is not installed.\"","worker_id":0}
{"time":"2022-02-24T14:39:37.192Z","level":"error","worker_id":0,"message":"/usr/local/lib/ruby/gems/2.7.0/gems/fluent-plugin-elasticsearch-5.1.4/lib/fluent/plugin/elasticsearch_index_lifecycle_management.rb:39:in `rescue in xpack_info'\n/usr/local/lib/ruby/gems/2.7.0/gems/fluent-plugin-elasticsearch-5.1.4/lib/fluent/plugin/elasticsearch_index_lifecycle_management.rb:35:in `xpack_info'\n/usr/local/lib/ruby/gems/2.7.0/gems/fluent-plugin-elasticsearch-5.1.4/lib/fluent/plugin/elasticsearch_index_lifecycle_management.rb:14:in `verify_ilm_working'\n/usr/local/lib/ruby/gems/2.7.0/gems/fluent-plugin-elasticsearch-5.1.4/lib/fluent/plugin/out_elasticsearch.rb:267:in `configure'\n/usr/local/lib/ruby/gems/2.7.0/gems/fluentd-1.14.5/lib/fluent/plugin.rb:187:in `configure'\n/usr/local/lib/ruby/gems/2.7.0/gems/fluentd-1.14.5/lib/fluent/plugin/multi_output.rb:110:in `block in configure'\n/usr/local/lib/ruby/gems/2.7.0/gems/fluentd-1.14.5/lib/fluent/plugin/multi_output.rb:99:in `each'\n/usr/local/lib/ruby/gems/2.7.0/gems/fluentd-1.14.5/lib/fluent/plugin/multi_output.rb:99:in `configure'\n/usr/local/lib/ruby/gems/2.7.0/gems/fluentd-1.14.5/lib/fluent/plugin/out_copy.rb:39:in `configure'\n/usr/local/lib/ruby/gems/2.7.0/gems/fluentd-1.14.5/lib/fluent/plugin.rb:187:in `configure'\n/usr/local/lib/ruby/gems/2.7.0/gems/fluentd-1.14.5/lib/fluent/agent.rb:132:in `add_match'\n/usr/local/lib/ruby/gems/2.7.0/gems/fluentd-1.14.5/lib/fluent/agent.rb:74:in `block in configure'\n/usr/local/lib/ruby/gems/2.7.0/gems/fluentd-1.14.5/lib/fluent/agent.rb:64:in `each'\n/usr/local/lib/ruby/gems/2.7.0/gems/fluentd-1.14.5/lib/fluent/agent.rb:64:in `configure'\n/usr/local/lib/ruby/gems/2.7.0/gems/fluentd-1.14.5/lib/fluent/label.rb:31:in `configure'\n/usr/local/lib/ruby/gems/2.7.0/gems/fluentd-1.14.5/lib/fluent/root_agent.rb:146:in `block in configure'\n/usr/local/lib/ruby/gems/2.7.0/gems/fluentd-1.14.5/lib/fluent/root_agent.rb:146:in `each'\n/usr/local/lib/ruby/gems/2.7.0/gems/fluentd-1.14.5/lib/fluent/root_agent.rb:146:in `configure'\n/usr/local/lib/ruby/gems/2.7.0/gems/fluentd-1.14.5/lib/fluent/engine.rb:105:in `configure'\n/usr/local/lib/ruby/gems/2.7.0/gems/fluentd-1.14.5/lib/fluent/engine.rb:80:in `run_configure'\n/usr/local/lib/ruby/gems/2.7.0/gems/fluentd-1.14.5/lib/fluent/supervisor.rb:716:in `block in run_worker'\n/usr/local/lib/ruby/gems/2.7.0/gems/fluentd-1.14.5/lib/fluent/supervisor.rb:968:in `main_process'\n/usr/local/lib/ruby/gems/2.7.0/gems/fluentd-1.14.5/lib/fluent/supervisor.rb:708:in `run_worker'\n/usr/local/lib/ruby/gems/2.7.0/gems/fluentd-1.14.5/lib/fluent/command/fluentd.rb:372:in `<top (required)>'\n/usr/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'\n/usr/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'\n/usr/local/lib/ruby/gems/2.7.0/gems/fluentd-1.14.5/bin/fluentd:15:in `<top (required)>'\n/usr/local/bundle/bin/fluentd:23:in `load'\n/usr/local/bundle/bin/fluentd:23:in `<main>'"}
{"time":"2022-02-24T14:39:37.199Z","level":"info","message":"Worker 0 finished with status 1"}
 ```
 
 List of installed gems:
 ```
 #4 25.42 Successfully installed multi_json-1.15.0
#4 25.42 Successfully installed faraday-em_http-1.0.0
#4 25.42 Successfully installed faraday-em_synchrony-1.0.0
#4 25.42 Successfully installed faraday-excon-1.1.0
#4 25.42 Successfully installed faraday-httpclient-1.0.1
#4 25.42 Successfully installed multipart-post-2.1.1
#4 25.42 Successfully installed faraday-multipart-1.0.3
#4 25.42 Successfully installed faraday-net_http-1.0.1
#4 25.42 Successfully installed faraday-net_http_persistent-1.2.0
#4 25.42 Successfully installed faraday-patron-1.0.0
#4 25.42 Successfully installed faraday-rack-1.0.0
#4 25.42 Successfully installed faraday-retry-1.0.3
#4 25.42 Successfully installed ruby2_keywords-0.0.5
#4 25.42 Successfully installed faraday-1.10.0
#4 25.42 Successfully installed elastic-transport-8.0.0
#4 25.42 Successfully installed elasticsearch-api-8.0.0
#4 25.42 Successfully installed elasticsearch-8.0.0
#4 25.42 Successfully installed excon-0.91.0
#4 25.42 Building native extensions. This could take a while...
#4 28.17 Successfully installed msgpack-1.4.5
#4 28.17 Building native extensions. This could take a while...
#4 29.57 Successfully installed yajl-ruby-1.4.1
#4 29.57 Building native extensions. This could take a while...
#4 33.29 Successfully installed cool.io-1.7.1
#4 33.29 Successfully installed sigdump-0.2.4
#4 33.29 Successfully installed serverengine-2.2.5
#4 33.29 Building native extensions. This could take a while...
#4 34.53 Successfully installed http_parser.rb-0.8.0
#4 34.53 Successfully installed concurrent-ruby-1.1.9
#4 34.53 Successfully installed tzinfo-2.0.4
#4 34.53 Successfully installed tzinfo-data-1.2021.5
#4 34.53 Building native extensions. This could take a while...
#4 39.47 Successfully installed strptime-0.2.5
#4 39.47 Successfully installed fluentd-1.14.5
#4 39.47 Successfully installed fluent-plugin-elasticsearch-5.1.4
#4 39.47 Successfully installed fluent-plugin-grok-parser-2.6.2
#4 39.47 Successfully installed fluent-config-regexp-type-1.0.0
#4 39.47 Successfully installed fluent-plugin-rewrite-tag-filter-2.4.0
#4 39.47 Successfully installed fluent-plugin-concat-2.5.0
#4 39.47 Successfully installed fluent-plugin-multi-format-parser-1.0.0
#4 39.47 35 gems installed
#4 39.65 Removing elastic_ruby_console
#4 39.65 Successfully uninstalled elasticsearch-8.0.0
#4 42.17 Successfully installed elasticsearch-transport-7.17.0
#4 42.17 Successfully installed elasticsearch-api-7.17.0
#4 42.17 Successfully installed elasticsearch-7.17.0
#4 42.17 WARNING: This library is deprecated
#4 42.17 
#4 42.17 The API endpoints currently living in elasticsearch-xpack will be moved into elasticsearch-api in version 8.0.0 and forward. You should be able to keep using elasticsearch-xpack and the xpack namespace in 7.x. We're running the same tests in elasticsearch-xpack, but if you encounter any problems, please let us know in this issue: https://github.com/elastic/elasticsearch-ruby/issues/1274 
#4 42.17 
#4 42.17 Successfully installed elasticsearch-xpack-7.17.0
#4 42.17 4 gems installed
#4 42.97 Building native extensions. This could take a while...
#4 43.90 Successfully installed strptime-0.2.5

 ```
