### ISSUE TITLE
`require': cannot load such file -- elasticsearch/transport/transport/connections/selector (LoadError)

### ISSUE THREAD

**Issue by imsoul** [uken/fluent-plugin-elasticsearch#945]
```
2022-02-12 05:52:17 +0000 [info]: gem 'fluentd' version '1.14.3'
/usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require': cannot load such file -- elasticsearch/transport/transport/connections/selector (LoadError)
	from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	from /usr/lib/ruby/gems/2.7.0/gems/fluent-plugin-elasticsearch-5.0.3/lib/fluent/plugin/elasticsearch_fallback_selector.rb:1:in `<top (required)>'
	from /usr/lib/ruby/gems/2.7.0/gems/fluent-plugin-elasticsearch-5.0.3/lib/fluent/plugin/out_elasticsearch.rb:31:in `require_relative'
	from /usr/lib/ruby/gems/2.7.0/gems/fluent-plugin-elasticsearch-5.0.3/lib/fluent/plugin/out_elasticsearch.rb:31:in `<top (required)>'
	from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	from /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.14.3/lib/fluent/registry.rb:102:in `block in search'
	from /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.14.3/lib/fluent/registry.rb:99:in `each'
	from /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.14.3/lib/fluent/registry.rb:99:in `search'
	from /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.14.3/lib/fluent/registry.rb:44:in `lookup'
	from /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.14.3/lib/fluent/plugin.rb:169:in `new_impl'
	from /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.14.3/lib/fluent/plugin.rb:114:in `new_output'
	from /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.14.3/lib/fluent/agent.rb:130:in `add_match'
	from /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.14.3/lib/fluent/agent.rb:74:in `block in configure'
	from /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.14.3/lib/fluent/agent.rb:64:in `each'
	from /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.14.3/lib/fluent/agent.rb:64:in `configure'
	from /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.14.3/lib/fluent/root_agent.rb:149:in `configure'
	from /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.14.3/lib/fluent/engine.rb:105:in `configure'
	from /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.14.3/lib/fluent/engine.rb:80:in `run_configure'
	from /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.14.3/lib/fluent/supervisor.rb:665:in `run_supervisor'
	from /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.14.3/lib/fluent/command/fluentd.rb:352:in `<top (required)>'
	from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	from /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.14.3/bin/fluentd:15:in `<top (required)>'
	from /usr/bin/fluentd:23:in `load'
	from /usr/bin/fluentd:23:in `<main>'
```

**Comment by nnul** [comment]
Duplicate of #944
