### ISSUE TITLE
Crush with elasticsearch server 7.2

### ISSUE THREAD

**Issue by kvokka** [uken/fluent-plugin-elasticsearch#951]
(check apply)
- [x] read [the contribution guideline](https://github.com/uken/fluent-plugin-elasticsearch/blob/master/CONTRIBUTING.md)
- [ ] (optional) already reported 3rd party upstream repository or mailing list if you use k8s addon or helm charts.

#### Problem

Elasticrearch 7.2 support vanished after the update to 5.2.0 from 5.1.5. Fluentd config was unchanged

logs
```
2022-02-23 04:21:59 +0000 [info]: adding match in @FLUENT_LOG pattern="**" type="stdout"
2022-02-23 04:21:59 +0000 [info]: adding match in @NORMAL pattern="**" type="elasticsearch"
The client is unable to verify that the server is Elasticsearch. Some functionality may not be compatible if the server is running an unsupported product.
2022-02-23 04:22:00 +0000 [error]: unexpected error error_class=Elasticsearch::UnsupportedProductError error="The client noticed that the server is not Elasticsearch and we do not support this unknown product."
  2022-02-23 04:22:00 +0000 [error]: /opt/bitnami/fluentd/gems/elasticsearch-8.0.0/lib/elasticsearch.rb:115:in `verify_with_version_or_header'
  2022-02-23 04:22:00 +0000 [error]: /opt/bitnami/fluentd/gems/elasticsearch-8.0.0/lib/elasticsearch.rb:104:in `verify_elasticsearch'
  2022-02-23 04:22:00 +0000 [error]: /opt/bitnami/fluentd/gems/elasticsearch-8.0.0/lib/elasticsearch.rb:70:in `method_missing'
  2022-02-23 04:22:00 +0000 [error]: /opt/bitnami/fluentd/gems/elasticsearch-api-8.0.0/lib/elasticsearch/api/actions/info.rb:39:in `info'
  2022-02-23 04:22:00 +0000 [error]: /opt/bitnami/fluentd/gems/fluent-plugin-elasticsearch-5.2.0/lib/fluent/plugin/out_elasticsearch.rb:495:in `detect_es_major_version'
  2022-02-23 04:22:00 +0000 [error]: /opt/bitnami/fluentd/gems/fluent-plugin-elasticsearch-5.2.0/lib/fluent/plugin/out_elasticsearch.rb:487:in `block in handle_last_seen_es_major_version'
  2022-02-23 04:22:00 +0000 [error]: /opt/bitnami/fluentd/gems/fluent-plugin-elasticsearch-5.2.0/lib/fluent/plugin/elasticsearch_index_template.rb:56:in `retry_operate'
  2022-02-23 04:22:00 +0000 [error]: /opt/bitnami/fluentd/gems/fluent-plugin-elasticsearch-5.2.0/lib/fluent/plugin/out_elasticsearch.rb:484:in `handle_last_seen_es_major_version'
  2022-02-23 04:22:00 +0000 [error]: /opt/bitnami/fluentd/gems/fluent-plugin-elasticsearch-5.2.0/lib/fluent/plugin/out_elasticsearch.rb:336:in `configure'
  2022-02-23 04:22:00 +0000 [error]: /opt/bitnami/fluentd/gems/fluentd-1.14.5/lib/fluent/plugin.rb:187:in `configure'
  2022-02-23 04:22:00 +0000 [error]: /opt/bitnami/fluentd/gems/fluentd-1.14.5/lib/fluent/agent.rb:132:in `add_match'
  2022-02-23 04:22:00 +0000 [error]: /opt/bitnami/fluentd/gems/fluentd-1.14.5/lib/fluent/agent.rb:74:in `block in configure'
  2022-02-23 04:22:00 +0000 [error]: /opt/bitnami/fluentd/gems/fluentd-1.14.5/lib/fluent/agent.rb:64:in `each'
  2022-02-23 04:22:00 +0000 [error]: /opt/bitnami/fluentd/gems/fluentd-1.14.5/lib/fluent/agent.rb:64:in `configure'
  2022-02-23 04:22:00 +0000 [error]: /opt/bitnami/fluentd/gems/fluentd-1.14.5/lib/fluent/label.rb:31:in `configure'
  2022-02-23 04:22:00 +0000 [error]: /opt/bitnami/fluentd/gems/fluentd-1.14.5/lib/fluent/root_agent.rb:146:in `block in configure'
  2022-02-23 04:22:00 +0000 [error]: /opt/bitnami/fluentd/gems/fluentd-1.14.5/lib/fluent/root_agent.rb:146:in `each'
  2022-02-23 04:22:00 +0000 [error]: /opt/bitnami/fluentd/gems/fluentd-1.14.5/lib/fluent/root_agent.rb:146:in `configure'
  2022-02-23 04:22:00 +0000 [error]: /opt/bitnami/fluentd/gems/fluentd-1.14.5/lib/fluent/engine.rb:105:in `configure'
  2022-02-23 04:22:00 +0000 [error]: /opt/bitnami/fluentd/gems/fluentd-1.14.5/lib/fluent/engine.rb:80:in `run_configure'
  2022-02-23 04:22:00 +0000 [error]: /opt/bitnami/fluentd/gems/fluentd-1.14.5/lib/fluent/supervisor.rb:716:in `block in run_worker'
  2022-02-23 04:22:00 +0000 [error]: /opt/bitnami/fluentd/gems/fluentd-1.14.5/lib/fluent/supervisor.rb:968:in `main_process'
  2022-02-23 04:22:00 +0000 [error]: /opt/bitnami/fluentd/gems/fluentd-1.14.5/lib/fluent/supervisor.rb:708:in `run_worker'
  2022-02-23 04:22:00 +0000 [error]: /opt/bitnami/fluentd/gems/fluentd-1.14.5/lib/fluent/command/fluentd.rb:372:in `<top (required)>'
  2022-02-23 04:22:00 +0000 [error]: /opt/bitnami/ruby/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:85:in `require'
  2022-02-23 04:22:00 +0000 [error]: /opt/bitnami/ruby/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:85:in `require'
  2022-02-23 04:22:00 +0000 [error]: /opt/bitnami/fluentd/gems/fluentd-1.14.5/bin/fluentd:15:in `<top (required)>'
  2022-02-23 04:22:00 +0000 [error]: /opt/bitnami/fluentd/bin/fluentd:23:in `load'
  2022-02-23 04:22:00 +0000 [error]: /opt/bitnami/fluentd/bin/fluentd:23:in `<main>'
```

**CONFIG**

```
          <match **>
            @id elasticsearch
            @type elasticsearch
            @log_level info
            include_tag_key true
            host "{{ .Values.global.chart_name }}-es.{{ .Values.global.es_service.domain }}"
            port {{ .Values.global.es_service.httpPort }}
            type_name _doc
            logstash_format true
            reconnect_on_error true
            reload_on_failure true
            reload_connections false
            compression_level default_compression
            prefer_oj_serializer true
            http_backend typhoeus
            <buffer>
              @type file
              path /opt/bitnami/fluentd/logs/buffers/elasticsearch
              flush_mode interval
              retry_type exponential_backoff
              flush_thread_count 2
              flush_interval 5s
              retry_max_interval 10
              chunk_limit_size 32M
              queue_limit_length 8
              overflow_action drop_oldest_chunk
            </buffer>
          </match>
```

#### Using Fluentd and ES plugin versions

* OS Ubuntu
* Kubernetes
* Fluentd v1.14.5
* ES plugin 5.2.0
```
activesupport-7.0.2.2
addressable-2.8.0
aws-eventstream-1.2.0
aws-partitions-1.556.0
aws-sdk-core-3.126.2
aws-sdk-kms-1.54.0
aws-sdk-s3-1.112.0
aws-sdk-sqs-1.50.0
aws-sigv4-1.4.0
bundler-2.3.7
concurrent-ruby-1.1.9
cool.io-1.7.1
digest-crc-0.6.4
domain_name-0.5.20190701
elastic-transport-8.0.0
elasticsearch-8.0.0
elasticsearch-api-8.0.0
elasticsearch-xpack-7.17.0
excon-0.91.0
faraday-1.10.0
faraday-em_http-1.0.0
faraday-em_synchrony-1.0.0
faraday-excon-1.1.0
faraday-httpclient-1.0.1
faraday-multipart-1.0.3
faraday-net_http-1.0.1
faraday-net_http_persistent-1.2.0
faraday-patron-1.0.0
faraday-rack-1.0.0
faraday-retry-1.0.3
ffi-1.15.5
ffi-compiler-1.0.1
fluent-config-regexp-type-1.0.0
fluent-plugin-concat-2.5.0
fluent-plugin-detect-exceptions-0.0.14
fluent-plugin-elasticsearch-5.2.0
fluent-plugin-grafana-loki-1.2.18
fluent-plugin-kafka-0.17.4
fluent-plugin-kubernetes_metadata_filter-2.9.4
fluent-plugin-multi-format-parser-1.0.0
fluent-plugin-prometheus-2.0.2
fluent-plugin-record-modifier-2.1.0
fluent-plugin-rewrite-tag-filter-2.4.0
fluent-plugin-s3-1.6.1
fluent-plugin-systemd-1.0.5
fluentd-1.14.5
http-4.4.1
http-accept-1.7.0
http-cookie-1.0.4
http-form_data-2.3.0
http-parser-1.2.3
http_parser.rb-0.8.0
i18n-1.10.0
jmespath-1.6.0
json-2.1.0
jsonpath-1.1.0
kubeclient-4.9.2
lru_redux-1.1.0
ltsv-0.1.2
mime-types-3.4.1
mime-types-data-3.2022.0105
minitest-5.15.0
msgpack-1.4.5
multi_json-1.15.0
multipart-post-2.1.1
netrc-0.11.0
oj-3.3.10
prometheus-client-3.0.0
public_suffix-4.0.6
rake-13.0.6
recursive-open-struct-1.1.3
rest-client-2.1.0
ruby-kafka-1.4.0
ruby2_keywords-0.0.5
serverengine-2.2.5
sigdump-0.2.4
strptime-0.2.5
systemd-journal-1.4.2
tzinfo-2.0.4
tzinfo-data-1.2021.5
unf-0.1.4
unf_ext-0.0.8
webrick-1.7.0
yajl-ruby-1.4.1
```
* ES version 7.2

**Comment by ppadron** [comment]
Are you using OSS Elasticsearch? If so, downgrade the elasticsearch gem to 7.14:

```sh
gem install elasticsearch --version '< 7.14'
```

> With the 7.11 the release of Elasticsearch, we will no longer be releasing oss-only distributions, as stated in the [FAQ on license change](https://www.elastic.co/pricing/faq/licensing). The recommendation is to upgrade to the latest default distribution of Elasticsearch, which is free to use under [Elastic License v2](https://www.elastic.co/licensing/elastic-license). Otherwise, you can pin the client version to <7.14.

Reference:
https://github.com/elastic/elasticsearch-py/issues/1639#issuecomment-883319286

**Comment by kvokka** [comment]
Thank you for the advice. With the image https://github.com/bitnami/bitnami-docker-fluentd version `1.14.5-debian-10-r11` I can only rollback to  `elasticsearch:7.14.1` to make this run. But this hack is not supposed to be a default solution IMO.

Gemspec does not lock dependency versions. 

Hope this issue will save a day for someone and will be happy if the maintainers of this gem either drop support of older versions or fix the gem or update the readme at least.

**Comment by cosmo0920** [comment]
> Gemspec does not lock dependency versions.
> 
> Hope this issue will save a day for someone and will be happy if the maintainers of this gem either drop support of older versions or fix the gem or update the readme at least.

 We don't plan to lock gemspec versions for elasticsearch related gems. It is compatibility issue. Maybe ES plugin should catch Unsupported exceptions and report appropriate errors.
