### ISSUE TITLE
NameError error="uninitialized constant Fluent::Plugin::ElasticsearchOutput::Elasticsearch::UnsupportedProductError"

### ISSUE THREAD

**Issue by anand3493** [uken/fluent-plugin-elasticsearch#958]
(check apply)
- [x] read [the contribution guideline](https://github.com/uken/fluent-plugin-elasticsearch/blob/master/CONTRIBUTING.md)
- [ ] (optional) already reported 3rd party upstream repository or mailing list if you use k8s addon or helm charts.

#### Problem
Getting error with fluentd - aws elasticsearch setup 
[error]: #0 unexpected error error_class=NameError error="uninitialized constant Fluent::Plugin::ElasticsearchOutput::Elasticsearch::UnsupportedProductError"

Fluentd Pods are running. But logs are not flowing. 
FLuentd Logs reported error with stack trace: 
```
2022-03-29 09:55:46 +0000 [error]: #0 unexpected error error_class=NameError error="uninitialized constant Fluent::Plugin::ElasticsearchOutput::Elasticsearch::UnsupportedProductError"
  2022-03-29 09:55:46 +0000 [error]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluent-plugin-elasticsearch-5.2.1/lib/fluent/plugin/out_elasticsearch.rb:497:in `rescue in detect_es_major_version'
  2022-03-29 09:55:46 +0000 [error]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluent-plugin-elasticsearch-5.2.1/lib/fluent/plugin/out_elasticsearch.rb:495:in `detect_es_major_version'
  2022-03-29 09:55:46 +0000 [error]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluent-plugin-elasticsearch-5.2.1/lib/fluent/plugin/out_elasticsearch.rb:487:in `block in handle_last_seen_es_major_version'
  2022-03-29 09:55:46 +0000 [error]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluent-plugin-elasticsearch-5.2.1/lib/fluent/plugin/elasticsearch_index_template.rb:56:in `retry_operate'
  2022-03-29 09:55:46 +0000 [error]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluent-plugin-elasticsearch-5.2.1/lib/fluent/plugin/out_elasticsearch.rb:484:in `handle_last_seen_es_major_version'
  2022-03-29 09:55:46 +0000 [error]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluent-plugin-elasticsearch-5.2.1/lib/fluent/plugin/out_elasticsearch.rb:336:in `configure'
  2022-03-29 09:55:46 +0000 [error]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.14.1/lib/fluent/plugin.rb:187:in `configure'
  2022-03-29 09:55:46 +0000 [error]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.14.1/lib/fluent/agent.rb:132:in `add_match'
  2022-03-29 09:55:46 +0000 [error]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.14.1/lib/fluent/agent.rb:74:in `block in configure'
  2022-03-29 09:55:46 +0000 [error]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.14.1/lib/fluent/agent.rb:64:in `each'
  2022-03-29 09:55:46 +0000 [error]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.14.1/lib/fluent/agent.rb:64:in `configure'
  2022-03-29 09:55:46 +0000 [error]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.14.1/lib/fluent/root_agent.rb:149:in `configure'
  2022-03-29 09:55:46 +0000 [error]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.14.1/lib/fluent/engine.rb:105:in `configure'
  2022-03-29 09:55:46 +0000 [error]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.14.1/lib/fluent/engine.rb:80:in `run_configure'
  2022-03-29 09:55:46 +0000 [error]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.14.1/lib/fluent/supervisor.rb:716:in `block in run_worker'
  2022-03-29 09:55:46 +0000 [error]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.14.1/lib/fluent/supervisor.rb:968:in `main_process'
  2022-03-29 09:55:46 +0000 [error]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.14.1/lib/fluent/supervisor.rb:708:in `run_worker'
  2022-03-29 09:55:46 +0000 [error]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.14.1/lib/fluent/command/fluentd.rb:372:in `<top (required)>'
  2022-03-29 09:55:46 +0000 [error]: #0 /usr/local/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
  2022-03-29 09:55:46 +0000 [error]: #0 /usr/local/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
  2022-03-29 09:55:46 +0000 [error]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.14.1/bin/fluentd:15:in `<top (required)>'
  2022-03-29 09:55:46 +0000 [error]: #0 /fluentd/vendor/bundle/ruby/2.6.0/bin/fluentd:23:in `load'
  2022-03-29 09:55:46 +0000 [error]: #0 /fluentd/vendor/bundle/ruby/2.6.0/bin/fluentd:23:in `<main>'
```
...

#### Steps to replicate

Fluentd daemonset with aws elasticsearch plugin is configured to push logs

#### Expected Behavior or What you need to ask

Fluentd to push logs to ES
...

#### Using Fluentd and ES plugin versions

* Kubernetes
* Fluentd v.14.1
* fluent-plugin-elasticsearch 5.2.1
* fluent-plugin-aws-elasticsearch-service 2.4.1
* ES version 7.10

**Comment by anand3493** [comment]
Verified the fix in 5.2.2 release. working fine. Thank you for fixing the issue @cosmo0920

**Comment by cosmo0920** [comment]
Wow, thanks for the conformation.

**Comment by anand3493** [comment]
@cosmo0920  In one of the environment am getting the below error for the same packages: 
![image](https://user-images.githubusercontent.com/90377358/167615147-b3c2ef42-79e4-40d1-9d4f-b8afb3dc4b7d.png)

Can u please check on this and let me know. 
As the stack trace suggests, it starting from fluent-plugin-elasticsearch only

**Comment by cosmo0920** [comment]
This could be caused from `[default]` profile on `~/.aws/credentials` or `/root/.aws/config`.

**Comment by cosmo0920** [comment]
I'm not sure why you are using almost obsoleted plugin that is fluent-plugin-aws-elasticsearch-service.
We recommend to use [fluent-plugin-opensearch](https://github.com/fluent/fluent-plugin-opensearch).
That plugin can handle Fluentd logs ingestion into the recent AWS OpenSearch service.
