### ISSUE TITLE
undefined method `+' for nil:NilClass

### ISSUE THREAD

**Issue by mokhos** [uken/fluent-plugin-elasticsearch#959]
(check apply)
- [x] read [the contribution guideline](https://github.com/uken/fluent-plugin-elasticsearch/blob/master/CONTRIBUTING.md)
- [x] (optional) already reported 3rd party upstream repository or mailing list if you use k8s addon or helm charts.

#### Problem

I'm using `bitnami/fluentd:v1.14.5-debian-10-r1` which contains `fluent-plugin-elasticsearch-5.1.5`, but still getting this undefined method like so:

```

2022-03-30 10:30:48 +0000 [info]: adding match pattern="**" type="elasticsearch"
2022-03-30 10:30:48 +0000 [error]: #0 unexpected error error_class=NoMethodError error="undefined method `+' for nil:NilClass"
  2022-03-30 10:30:48 +0000 [error]: #0 /opt/bitnami/fluentd/gems/excon-0.91.0/lib/excon/connection.rb:247:in `request'
  2022-03-30 10:30:48 +0000 [error]: #0 /opt/bitnami/fluentd/gems/faraday-excon-1.1.0/lib/faraday/adapter/excon.rb:31:in `block in call'
  2022-03-30 10:30:48 +0000 [error]: #0 /opt/bitnami/fluentd/gems/faraday-1.9.3/lib/faraday/adapter.rb:50:in `connection'
  2022-03-30 10:30:48 +0000 [error]: #0 /opt/bitnami/fluentd/gems/faraday-excon-1.1.0/lib/faraday/adapter/excon.rb:31:in `call'
  2022-03-30 10:30:48 +0000 [error]: #0 /opt/bitnami/fluentd/gems/faraday-1.9.3/lib/faraday/rack_builder.rb:154:in `build_response'
  2022-03-30 10:30:48 +0000 [error]: #0 /opt/bitnami/fluentd/gems/faraday-1.9.3/lib/faraday/connection.rb:516:in `run_request'
  2022-03-30 10:30:48 +0000 [error]: #0 /opt/bitnami/fluentd/gems/elasticsearch-transport-7.17.0/lib/elasticsearch/transport/transport/http/faraday.rb:50:in `block in perform_request'
  2022-03-30 10:30:48 +0000 [error]: #0 /opt/bitnami/fluentd/gems/elasticsearch-transport-7.17.0/lib/elasticsearch/transport/transport/base.rb:289:in `perform_request'
  2022-03-30 10:30:48 +0000 [error]: #0 /opt/bitnami/fluentd/gems/elasticsearch-transport-7.17.0/lib/elasticsearch/transport/transport/http/faraday.rb:36:in `perform_request'
  2022-03-30 10:30:48 +0000 [error]: #0 /opt/bitnami/fluentd/gems/elasticsearch-transport-7.17.0/lib/elasticsearch/transport/client.rb:197:in `perform_request'
  2022-03-30 10:30:48 +0000 [error]: #0 /opt/bitnami/fluentd/gems/elasticsearch-7.17.0/lib/elasticsearch.rb:93:in `elasticsearch_validation_request'
  2022-03-30 10:30:48 +0000 [error]: #0 /opt/bitnami/fluentd/gems/elasticsearch-7.17.0/lib/elasticsearch.rb:51:in `verify_elasticsearch'
  2022-03-30 10:30:48 +0000 [error]: #0 /opt/bitnami/fluentd/gems/elasticsearch-7.17.0/lib/elasticsearch.rb:40:in `method_missing'
  2022-03-30 10:30:48 +0000 [error]: #0 /opt/bitnami/fluentd/gems/elasticsearch-api-7.17.0/lib/elasticsearch/api/actions/info.rb:37:in `info'
  2022-03-30 10:30:48 +0000 [error]: #0 /opt/bitnami/fluentd/gems/fluent-plugin-elasticsearch-5.1.5/lib/fluent/plugin/out_elasticsearch.rb:498:in `detect_es_major_version'
  2022-03-30 10:30:48 +0000 [error]: #0 /opt/bitnami/fluentd/gems/fluent-plugin-elasticsearch-5.1.5/lib/fluent/plugin/out_elasticsearch.rb:490:in `block in handle_last_seen_es_major_version'
  2022-03-30 10:30:48 +0000 [error]: #0 /opt/bitnami/fluentd/gems/fluent-plugin-elasticsearch-5.1.5/lib/fluent/plugin/elasticsearch_index_template.rb:52:in `retry_operate'
  2022-03-30 10:30:48 +0000 [error]: #0 /opt/bitnami/fluentd/gems/fluent-plugin-elasticsearch-5.1.5/lib/fluent/plugin/out_elasticsearch.rb:487:in `handle_last_seen_es_major_version'
  2022-03-30 10:30:48 +0000 [error]: #0 /opt/bitnami/fluentd/gems/fluent-plugin-elasticsearch-5.1.5/lib/fluent/plugin/out_elasticsearch.rb:339:in `configure'
  2022-03-30 10:30:48 +0000 [error]: #0 /opt/bitnami/fluentd/gems/fluentd-1.14.5/lib/fluent/plugin.rb:187:in `configure'
  2022-03-30 10:30:48 +0000 [error]: #0 /opt/bitnami/fluentd/gems/fluentd-1.14.5/lib/fluent/agent.rb:132:in `add_match'
  2022-03-30 10:30:48 +0000 [error]: #0 /opt/bitnami/fluentd/gems/fluentd-1.14.5/lib/fluent/agent.rb:74:in `block in configure'
  2022-03-30 10:30:48 +0000 [error]: #0 /opt/bitnami/fluentd/gems/fluentd-1.14.5/lib/fluent/agent.rb:64:in `each'
  2022-03-30 10:30:48 +0000 [error]: #0 /opt/bitnami/fluentd/gems/fluentd-1.14.5/lib/fluent/agent.rb:64:in `configure'
  2022-03-30 10:30:48 +0000 [error]: #0 /opt/bitnami/fluentd/gems/fluentd-1.14.5/lib/fluent/root_agent.rb:149:in `configure'
  2022-03-30 10:30:48 +0000 [error]: #0 /opt/bitnami/fluentd/gems/fluentd-1.14.5/lib/fluent/engine.rb:105:in `configure'
  2022-03-30 10:30:48 +0000 [error]: #0 /opt/bitnami/fluentd/gems/fluentd-1.14.5/lib/fluent/engine.rb:80:in `run_configure'
  2022-03-30 10:30:48 +0000 [error]: #0 /opt/bitnami/fluentd/gems/fluentd-1.14.5/lib/fluent/supervisor.rb:716:in `block in run_worker'
  2022-03-30 10:30:48 +0000 [error]: #0 /opt/bitnami/fluentd/gems/fluentd-1.14.5/lib/fluent/supervisor.rb:968:in `main_process'
  2022-03-30 10:30:48 +0000 [error]: #0 /opt/bitnami/fluentd/gems/fluentd-1.14.5/lib/fluent/supervisor.rb:708:in `run_worker'
  2022-03-30 10:30:48 +0000 [error]: #0 /opt/bitnami/fluentd/gems/fluentd-1.14.5/lib/fluent/command/fluentd.rb:372:in `<top (required)>'
  2022-03-30 10:30:48 +0000 [error]: #0 /opt/bitnami/ruby/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:85:in `require'
  2022-03-30 10:30:48 +0000 [error]: #0 /opt/bitnami/ruby/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:85:in `require'
  2022-03-30 10:30:48 +0000 [error]: #0 /opt/bitnami/fluentd/gems/fluentd-1.14.5/bin/fluentd:15:in `<top (required)>'
  2022-03-30 10:30:48 +0000 [error]: #0 /opt/bitnami/fluentd/bin/fluentd:23:in `load'
  2022-03-30 10:30:48 +0000 [error]: #0 /opt/bitnami/fluentd/bin/fluentd:23:in `<main>'
2022-03-30 10:30:48 +0000 [error]: Worker 0 finished unexpectedly with status 1
```

#### Steps to replicate

1. ES 7.17.1 is installed.
2. `bitnami/fluentd:v1.14.5-debian-10-r1` is installed. 

#### Expected Behavior or What you need to ask

Fluentd daemonset to be running properly.

#### Using Fluentd and ES plugin versions

* OS version Ubuntu 20.04
* Bare Metal or within Docker or Kubernetes or others? Kubernetes
* Fluentd 
```
2022-03-30 11:56:59 +0000 [info]: gem 'fluentd' version '1.14.5' 
```
* ES plugin 

```
2022-03-30 11:56:59 +0000 [info]: gem 'fluent-plugin-elasticsearch' version '5.1.5'
``` 
* ES version (optional) 7.17.1
* ES template(s) (optional)

**Comment by mokhos** [comment]
I found the solution and described it [here](https://github.com/uken/fluent-plugin-elasticsearch/issues/561#issuecomment-1084298476)
